// 사자소학 (Sajasohak) — generated from sajasohak.csv. Original + readings are
// public/standard; meanings are plain renderings. 39 four-character couplets.
import type { ClassicVerse } from './cheonjamun'
export const SAJASOHAK: ClassicVerse[] = [
  { no: 1, topic: "효행", hanja: "父生我身 母鞠吾身", reading: "부생아신 모국오신", meaning: "아버지는 내 몸을 낳으시고, 어머니는 내 몸을 기르셨다." },
  { no: 2, topic: "효행", hanja: "腹以懷我 乳以哺我", reading: "복이회아 유이포아", meaning: "배로써 나를 품어 주시고, 젖으로써 나를 먹여 주셨다." },
  { no: 3, topic: "효행", hanja: "以衣溫我 以食飽我", reading: "이의온아 이식포아", meaning: "옷으로써 나를 따뜻하게 하시고, 밥으로써 나를 배부르게 하셨다." },
  { no: 4, topic: "효행", hanja: "恩高如天 德厚似地", reading: "은고여천 덕후사지", meaning: "은혜는 높기가 하늘과 같고, 덕은 두텁기가 땅과 같다." },
  { no: 5, topic: "효행", hanja: "爲人子者 曷不爲孝", reading: "위인자자 갈불위효", meaning: "사람의 자식 된 자가, 어찌 효도하지 않으리오." },
  { no: 6, topic: "효행", hanja: "欲報其德 昊天罔極", reading: "욕보기덕 호천망극", meaning: "그 은덕을 갚고자 하나, 하늘처럼 끝이 없다." },
  { no: 7, topic: "효행", hanja: "晨必先起 必盥必漱", reading: "신필선기 필관필수", meaning: "새벽에는 반드시 먼저 일어나, 반드시 세수하고 양치질하라." },
  { no: 8, topic: "효행", hanja: "父母呼我 唯而趨進", reading: "부모호아 유이추진", meaning: "부모님께서 나를 부르시면, 대답하고 달려 나아가라." },
  { no: 9, topic: "효행", hanja: "父母使我 勿逆勿怠", reading: "부모사아 물역물태", meaning: "부모님께서 나를 시키시면, 거스르지 말고 게을리하지 말라." },
  { no: 10, topic: "효행", hanja: "父母有命 俯首敬聽", reading: "부모유명 부수경청", meaning: "부모님께서 명하심이 있으면, 머리를 숙여 공경히 들어라." },
  { no: 11, topic: "효행", hanja: "坐命坐聽 立命立聽", reading: "좌명좌청 입명입청", meaning: "앉아서 들으라 하시면 앉아 듣고, 서서 들으라 하시면 서서 들어라." },
  { no: 12, topic: "효행", hanja: "父母出入 每必起立", reading: "부모출입 매필기립", meaning: "부모님께서 드나드시면, 매번 반드시 일어서라." },
  { no: 13, topic: "효행", hanja: "父母衣服 勿踰勿踐", reading: "부모의복 물유물천", meaning: "부모님의 의복을, 넘어다니지 말고 밟지 말라." },
  { no: 14, topic: "효행", hanja: "父母有疾 憂而謀瘳", reading: "부모유질 우이모추", meaning: "부모님께서 병이 있으시면, 근심하며 낫게 하기를 꾀하라." },
  { no: 15, topic: "효행", hanja: "出必告之 反必面之", reading: "출필고지 반필면지", meaning: "나갈 때는 반드시 아뢰고, 돌아오면 반드시 얼굴을 뵈어라." },
  { no: 16, topic: "효행", hanja: "愼勿遠遊 遊必有方", reading: "신물원유 유필유방", meaning: "삼가 멀리 나가 놀지 말고, 놀더라도 반드시 일정한 곳이 있게 하라." },
  { no: 17, topic: "효행", hanja: "出入門戶 開閉必恭", reading: "출입문호 개폐필공", meaning: "문을 드나들 때는, 열고 닫기를 반드시 공손히 하라." },
  { no: 18, topic: "효행", hanja: "行勿慢步 坐勿倚身", reading: "행물만보 좌물의신", meaning: "다닐 때 거만하게 걷지 말고, 앉을 때 몸을 기대지 말라." },
  { no: 19, topic: "효행", hanja: "口勿雜談 手勿雜戱", reading: "구물잡담 수물잡희", meaning: "입으로 잡담하지 말고, 손으로 장난하지 말라." },
  { no: 20, topic: "효행", hanja: "膝前勿坐 親面勿仰", reading: "슬전물좌 친면물앙", meaning: "무릎 앞에 앉지 말고, 부모님 얼굴을 똑바로 올려다보지 말라." },
  { no: 21, topic: "효행", hanja: "侍坐父母 勿怒責人", reading: "시좌부모 물노책인", meaning: "부모님을 모시고 앉아서는, 성내어 남을 꾸짖지 말라." },
  { no: 22, topic: "효행", hanja: "獻物父母 跪而進之", reading: "헌물부모 궤이진지", meaning: "부모님께 물건을 드릴 때는, 꿇어앉아 올려라." },
  { no: 23, topic: "효행", hanja: "與我飮食 跪而受之", reading: "여아음식 궤이수지", meaning: "나에게 음식을 주시면, 꿇어앉아 받아라." },
  { no: 24, topic: "효행", hanja: "器有飮食 不與勿食", reading: "기유음식 불여물식", meaning: "그릇에 음식이 있어도, 주시지 않으면 먹지 말라." },
  { no: 25, topic: "효행", hanja: "若得美味 歸獻父母", reading: "약득미미 귀헌부모", meaning: "만약 맛있는 것을 얻으면, 돌아가 부모님께 드려라." },
  { no: 26, topic: "효행", hanja: "衣服雖惡 與之必著", reading: "의복수악 여지필착", meaning: "의복이 비록 나쁘더라도, 주시면 반드시 입어라." },
  { no: 27, topic: "효행", hanja: "飮食雖厭 與之必食", reading: "음식수염 여지필식", meaning: "음식이 비록 싫더라도, 주시면 반드시 먹어라." },
  { no: 28, topic: "효행", hanja: "身體髮膚 勿毁勿傷", reading: "신체발부 물훼물상", meaning: "신체와 머리털과 살갗을, 헐지 말고 상하게 하지 말라." },
  { no: 29, topic: "효행", hanja: "一欺父母 其罪如山", reading: "일기부모 기죄여산", meaning: "한 번 부모님을 속이면, 그 죄가 산과 같다." },
  { no: 30, topic: "효행", hanja: "我身能賢 譽及父母", reading: "아신능현 예급부모", meaning: "내 몸이 능히 어질면, 명예가 부모님께 미친다." },
  { no: 31, topic: "형제", hanja: "兄弟姊妹 同氣而生", reading: "형제자매 동기이생", meaning: "형제와 자매는, 한 기운을 받고 태어났다." },
  { no: 32, topic: "형제", hanja: "兄友弟恭 不敢怨怒", reading: "형우제공 불감원노", meaning: "형은 우애하고 아우는 공손하여, 감히 원망하거나 성내지 말라." },
  { no: 33, topic: "형제", hanja: "骨肉雖分 本生一氣", reading: "골육수분 본생일기", meaning: "뼈와 살은 비록 나뉘었으나, 본래 한 기운에서 났다." },
  { no: 34, topic: "형제", hanja: "兄弟怡怡 行則雁行", reading: "형제이이 행즉안행", meaning: "형제는 화목하여, 길을 갈 때는 기러기처럼 줄지어 가라." },
  { no: 35, topic: "사제", hanja: "事師如親 必恭必敬", reading: "사사여친 필공필경", meaning: "스승 섬기기를 어버이같이 하여, 반드시 공손하고 공경하라." },
  { no: 36, topic: "사제", hanja: "先生施敎 弟子是則", reading: "선생시교 제자시칙", meaning: "선생님이 가르침을 베푸시면, 제자는 이를 본받아라." },
  { no: 37, topic: "붕우", hanja: "人之在世 不可無友", reading: "인지재세 불가무우", meaning: "사람이 세상을 살면서, 벗이 없을 수 없다." },
  { no: 38, topic: "붕우", hanja: "以文會友 以友輔仁", reading: "이문회우 이우보인", meaning: "글로써 벗을 모으고, 벗으로써 인(仁)을 돕는다." },
  { no: 39, topic: "붕우", hanja: "友其正人 我亦自正", reading: "우기정인 아역자정", meaning: "바른 사람을 벗하면, 나도 또한 절로 바르게 된다." },
]
