export interface EnWord { en: string; ko: string }

/**
 * Elementary essential English words (~800) with a concise Korean meaning,
 * for the elementary English flashcard trainer. Source: Korea MOE elementary
 * word list (chodeung pilsu yeongdaneo 800).
 */
export const ELEMENTARY_EN: EnWord[] = [
  { en: 'a', ko: '하나의' }, { en: 'about', ko: '~에관하여' }, { en: 'across', ko: '~을 가로질러' }, { en: 'act', ko: '행동' }, { en: 'address', ko: '주소' }, { en: 'afraid', ko: '두려워하여' },
  { en: 'after', ko: '~후에' }, { en: 'afternoon', ko: '오후' }, { en: 'again', ko: '다시' }, { en: 'age', ko: '나이' }, { en: 'ago', ko: '~전에' }, { en: 'air', ko: '공기' },
  { en: 'airport', ko: '공항' }, { en: 'album', ko: '사진첩' }, { en: 'all', ko: '모두' }, { en: 'along', ko: '~을 따라서' }, { en: 'always', ko: '항상' }, { en: 'among', ko: '~사이에서' },
  { en: 'and', ko: '그리고' }, { en: 'angry', ko: '성난' }, { en: 'animal', ko: '동물' }, { en: 'answer', ko: '대답' }, { en: 'any', ko: '어떤' }, { en: 'apartment', ko: '아파트' },
  { en: 'apple', ko: '사과' }, { en: 'arm', ko: '팔' }, { en: 'around', ko: '~주위에' }, { en: 'arrive', ko: '도착하다' }, { en: 'as', ko: '~같은/~로서' }, { en: 'ask', ko: '묻다' },
  { en: 'at', ko: '~에' }, { en: 'aunt', ko: '이모,고모' }, { en: 'autumn', ko: '가을' }, { en: 'away', ko: '떨어져' }, { en: 'baby', ko: '아기' }, { en: 'back', ko: '뒤에' },
  { en: 'bad', ko: '나쁜' }, { en: 'bag', ko: '가방' }, { en: 'ball', ko: '공' }, { en: 'balloon', ko: '풍선' }, { en: 'banana', ko: '바나나' }, { en: 'band', ko: '끈/악단' },
  { en: 'bank', ko: '은행' }, { en: 'base', ko: '기초' }, { en: 'basket', ko: '바구니' }, { en: 'bath', ko: '목욕' }, { en: 'be', ko: '~이다' }, { en: 'beach', ko: '해변' },
  { en: 'bear', ko: '곰' }, { en: 'beautiful', ko: '아름다움' }, { en: 'because', ko: '~때문에' }, { en: 'become', ko: '~이되다' }, { en: 'bed', ko: '침대' }, { en: 'before', ko: '~전에' },
  { en: 'begin', ko: '시작하다' }, { en: 'behind', ko: '~뒤에' }, { en: 'bell', ko: '종' }, { en: 'below', ko: '~아래' }, { en: 'bench', ko: '긴의자' }, { en: 'beside', ko: '~곁에' },
  { en: 'between', ko: '~사이에' }, { en: 'bicycle', ko: '자전거' }, { en: 'big', ko: '큰' }, { en: 'bird', ko: '새' }, { en: 'birthday', ko: '생일' }, { en: 'black', ko: '검정색' },
  { en: 'blow', ko: '불다' }, { en: 'blue', ko: '푸른' }, { en: 'board', ko: '판자' }, { en: 'boat', ko: '배' }, { en: 'body', ko: '몸' }, { en: 'book', ko: '책' },
  { en: 'bottle', ko: '병' }, { en: 'bowl', ko: '사발' }, { en: 'box', ko: '상자' }, { en: 'boy', ko: '소년' }, { en: 'bread', ko: '빵' }, { en: 'break', ko: '깨뜨리다' },
  { en: 'breakfast', ko: '아침' }, { en: 'bridge', ko: '다리' }, { en: 'bright', ko: '밝은' }, { en: 'bring', ko: '가져오다' }, { en: 'brother', ko: '형제' }, { en: 'brown', ko: '갈색' },
  { en: 'brush', ko: '솔' }, { en: 'build', ko: '건설하다' }, { en: 'burn', ko: '불타다' }, { en: 'bus', ko: '버스' }, { en: 'busy', ko: '바쁜' }, { en: 'but', ko: '그러나' },
  { en: 'butter', ko: '버터' }, { en: 'button', ko: '단추' }, { en: 'buy', ko: '사다' }, { en: 'by', ko: '~옆에' }, { en: 'bye', ko: '안녕' }, { en: 'calendar', ko: '달력' },
  { en: 'cake', ko: '케이크' }, { en: 'call', ko: '부르다' }, { en: 'camera', ko: '사진기' }, { en: 'camp', ko: '야영지' }, { en: 'can', ko: '할수있다' }, { en: 'candle', ko: '양초' },
  { en: 'candy', ko: '사탕' }, { en: 'cap', ko: '모자' }, { en: 'capital', ko: '수도/대문자' }, { en: 'captain', ko: '우두머리' }, { en: 'car', ko: '자동차' }, { en: 'card', ko: '카드' },
  { en: 'care', ko: '걱정/돌보다' }, { en: 'carry', ko: '나르다' }, { en: 'case', ko: '경우' }, { en: 'cassette', ko: '카셋트' }, { en: 'cat', ko: '고양이' }, { en: 'catch', ko: '붙잡다' },
  { en: 'ceiling', ko: '천장' }, { en: 'center', ko: '중앙' }, { en: 'chair', ko: '의자' }, { en: 'chalk', ko: '분필' }, { en: 'chance', ko: '기회' }, { en: 'change', ko: '바꾸다' },
  { en: 'cheap', ko: '값싼' }, { en: 'cheese', ko: '치즈' }, { en: 'chicken', ko: '닭' }, { en: 'child', ko: '어린이' }, { en: 'chopstick', ko: '젓가락' }, { en: 'church', ko: '교회' },
  { en: 'circle', ko: '원' }, { en: 'city', ko: '도시' }, { en: 'class', ko: '학급' }, { en: 'classmate', ko: '동급생' }, { en: 'clean', ko: '깨끗한' }, { en: 'climb', ko: '오르다' },
  { en: 'clock', ko: '시계' }, { en: 'close', ko: '닫다' }, { en: 'clothes', ko: '옷' }, { en: 'cloud', ko: '구름' }, { en: 'club', ko: '클럽' }, { en: 'coat', ko: '코트' },
  { en: 'coffee', ko: '커피' }, { en: 'coin', ko: '동전' }, { en: 'cold', ko: '추운' }, { en: 'color', ko: '색깔' }, { en: 'come', ko: '오다' }, { en: 'computer', ko: '컴퓨터' },
  { en: 'cook', ko: '요리하다' }, { en: 'cool', ko: '시원한' }, { en: 'copy', ko: '사본/베끼다' }, { en: 'corner', ko: '모퉁이' }, { en: 'count', ko: '세다' }, { en: 'country', ko: '지역' },
  { en: 'course', ko: '과정' }, { en: 'cousin', ko: '사촌' }, { en: 'cover', ko: '덮다' }, { en: 'cow', ko: '암소' }, { en: 'crayon', ko: '크레옹' }, { en: 'cream', ko: '크림' },
  { en: 'cross', ko: '가로지르다' }, { en: 'cry', ko: '울다' }, { en: 'cup', ko: '컵' }, { en: 'curtain', ko: '커튼' }, { en: 'cut', ko: '자르다' }, { en: 'dad', ko: 'dy' },
  { en: 'dance', ko: '춤추다' }, { en: 'danger', ko: '위험한' }, { en: 'dark', ko: '어두운' }, { en: 'date', ko: '날짜' }, { en: 'daughter', ko: '딸' }, { en: 'day', ko: '낮/하루' },
  { en: 'dead', ko: '죽은' }, { en: 'deep', ko: '깊은' }, { en: 'dear', ko: '존경하는' }, { en: 'desk', ko: '책상' }, { en: 'dial', ko: '다이얼' }, { en: 'diary', ko: '일기' },
  { en: 'dictionary', ko: '사전' }, { en: 'die', ko: '죽다' }, { en: 'dinner', ko: '저녁' }, { en: 'dirty', ko: '더러운' }, { en: 'dish', ko: '큰접시' }, { en: 'do', ko: '하다' },
  { en: 'doctor', ko: '의사' }, { en: 'dog', ko: '개' }, { en: 'doll', ko: '인형' }, { en: 'dollar', ko: '달러' }, { en: 'dolphin', ko: '돌고래' }, { en: 'door', ko: '문' },
  { en: 'down', ko: '아래에' }, { en: 'draw', ko: '그리다' }, { en: 'dream', ko: '꿈' }, { en: 'dress', ko: '드레스' }, { en: 'drink', ko: '마시다' }, { en: 'drive', ko: '운전하다' },
  { en: 'drop', ko: '떨어지다/방울' }, { en: 'drum', ko: '북' }, { en: 'dry', ko: '마른' }, { en: 'duck', ko: '오리' }, { en: 'ear', ko: '귀' }, { en: 'early', ko: '일찍' },
  { en: 'earth', ko: '지구' }, { en: 'east', ko: '동쪽' }, { en: 'easy', ko: '쉬운' }, { en: 'eat', ko: '먹다' }, { en: 'egg', ko: '계란' }, { en: 'empty', ko: '텅빈' },
  { en: 'end', ko: '끝' }, { en: 'engine', ko: '엔진' }, { en: 'enjoy', ko: '즐기다' }, { en: 'enough', ko: '충분한' }, { en: 'eraser', ko: '지우개' }, { en: 'evening', ko: '저녁' },
  { en: 'every', ko: '모든/모두의' }, { en: 'example', ko: '예/보기' }, { en: 'exellent', ko: '뛰어난' }, { en: 'excite', ko: '흥분시키다' }, { en: 'excuse', ko: '용서하다' }, { en: 'exercise', ko: '연습' },
  { en: 'eye', ko: '눈' }, { en: 'face', ko: '얼굴' }, { en: 'fact', ko: '사실' }, { en: 'fair', ko: '공정한' }, { en: 'fall', ko: '가을/떨어지다' }, { en: 'family', ko: '가족' },
  { en: 'far', ko: '멀리떨어진' }, { en: 'farm', ko: '농장' }, { en: 'fast', ko: '빠른' }, { en: 'fat', ko: '쌀찐' }, { en: 'famous', ko: '유명한' }, { en: 'father', ko: '아버지' },
  { en: 'feel', ko: '느끼다' }, { en: 'few', ko: '다소양이적은' }, { en: 'field', ko: '들판/경기장' }, { en: 'fight', ko: '싸움' }, { en: 'fill', ko: '채우다' }, { en: 'film', ko: '필름' },
  { en: 'find', ko: '찾다' }, { en: 'fine', ko: '좋은/맑은' }, { en: 'finger', ko: '손가락' }, { en: 'finish', ko: '끝내다' }, { en: 'fire', ko: '불' }, { en: 'fish', ko: '고기/낚시하다' },
  { en: 'flag', ko: '깃발' }, { en: 'floor', ko: '마루' }, { en: 'flower', ko: '꽃' }, { en: 'fly', ko: '날다' }, { en: 'follow', ko: '뒤를따르다' }, { en: 'food', ko: '음식' },
  { en: 'fool', ko: '바보' }, { en: 'foot', ko: '발' }, { en: 'for', ko: '~을 위하여/~동안' }, { en: 'forget', ko: '잊다' }, { en: 'fork', ko: '포크' }, { en: 'free', ko: '자유로운' },
  { en: 'fresh', ko: '시선한' }, { en: 'friend', ko: '친구' }, { en: 'from', ko: '~로부터' }, { en: 'front', ko: '앞/정면' }, { en: 'fruit', ko: '과일' }, { en: 'full', ko: '가득찬' },
  { en: 'fun', ko: '즐거움' }, { en: 'game', ko: '놀이' }, { en: 'garden', ko: '정원' }, { en: 'gas', ko: '가스/휘발유' }, { en: 'gate', ko: '문' }, { en: 'gentle', ko: '온화한' },
  { en: 'get', ko: '얻다' }, { en: 'girl', ko: '소녀' }, { en: 'give', ko: '주다' }, { en: 'glad', ko: '기쁜' }, { en: 'glass', ko: '유리/컵' }, { en: 'glove', ko: '장갑' },
  { en: 'go', ko: '가다' }, { en: 'god', ko: 'GOD' }, { en: 'gold', ko: '금' }, { en: 'good', ko: '좋은' }, { en: 'grandmother', ko: '할머니' }, { en: 'grass', ko: '풀/잔디' },
  { en: 'gray', ko: '회색' }, { en: 'great', ko: '큰' }, { en: 'green', ko: '녹색' }, { en: 'ground', ko: '땅/기초' }, { en: 'group', ko: '단체' }, { en: 'grow', ko: '성장하다' },
  { en: 'guitar', ko: '기타(악기' }, { en: 'hair', ko: '머리카락' }, { en: 'half', ko: '절반' }, { en: 'hall', ko: '회관/넓은방' }, { en: 'hamburger', ko: '햄버거' }, { en: 'hand', ko: '손' },
  { en: 'handle', ko: '손잡이' }, { en: 'happen', ko: '발생하다' }, { en: 'happy', ko: '행복한' }, { en: 'hard', ko: '단단한/열심히' }, { en: 'hat', ko: '모자' }, { en: 'hate', ko: '미워하다' },
  { en: 'have', ko: '가지고있다' }, { en: 'he', ko: '그/남자' }, { en: 'head', ko: '머리' }, { en: 'hear', ko: '듣다' }, { en: 'heart', ko: '마음/상징' }, { en: 'heavy', ko: '무거운' },
  { en: 'hello', ko: '여보세요' }, { en: 'help', ko: '돕다' }, { en: 'hen', ko: '암닭' }, { en: 'here', ko: '여기에서' }, { en: 'hi', ko: '안녕하세요!' }, { en: 'hide', ko: '숨기다' },
  { en: 'high', ko: '높은' }, { en: 'hiking', ko: '하이킹/도보여행' }, { en: 'hill', ko: '언덕' }, { en: 'hit', ko: '때리다' }, { en: 'hold', ko: '잡다' }, { en: 'hole', ko: '구멍' },
  { en: 'holiday', ko: '휴일' }, { en: 'home', ko: '집' }, { en: 'hope', ko: '희망' }, { en: 'hose', ko: '호스' }, { en: 'horse', ko: '말' }, { en: 'hospital', ko: '병원' },
  { en: 'hot', ko: '뜨거운' }, { en: 'hotel', ko: '호텔' }, { en: 'hour', ko: '시간' }, { en: 'house', ko: '집' }, { en: 'how', ko: '어떻게' }, { en: 'hundred', ko: '백(100' },
  { en: 'hungry', ko: '배고픈' }, { en: 'hurry', ko: '서두르다' }, { en: 'hurt', ko: '다치게하다' }, { en: 'i', ko: '나' }, { en: 'ice', ko: '얼음' }, { en: 'idea', ko: '생각' },
  { en: 'if', ko: '만약' }, { en: 'ill', ko: '병든' }, { en: 'in', ko: '~속' }, { en: 'ink', ko: '잉크' }, { en: 'interest', ko: '흥미' }, { en: 'into', ko: '~속으로' },
  { en: 'introduce', ko: '소개하다' }, { en: 'island', ko: '섬' }, { en: 'it', ko: '그것' }, { en: 'job', ko: '직업' }, { en: 'join', ko: '가입하다' }, { en: 'juice', ko: '주스' },
  { en: 'jump', ko: '뛰어오르다' }, { en: 'jungle', ko: '밀림지대' }, { en: 'just', ko: '오직/겨우' }, { en: 'keep', ko: '지키다/유지하다' }, { en: 'key', ko: '열쇠' }, { en: 'kick', ko: '차다' },
  { en: 'kid', ko: '아이' }, { en: 'kill', ko: '죽이다' }, { en: 'kind', ko: '친절한/종류' }, { en: 'king', ko: '왕' }, { en: 'kitchen', ko: '부엌' }, { en: 'knee', ko: '무릎' },
  { en: 'knife', ko: '칼' }, { en: 'knock', ko: '두드리다' }, { en: 'know', ko: '알다' }, { en: 'lady', ko: '숙녀' }, { en: 'lake', ko: '호수' }, { en: 'lamp', ko: '등불' },
  { en: 'land', ko: '땅' }, { en: 'large', ko: '큰/넓은' }, { en: 'last', ko: '마지막/최근' }, { en: 'late', ko: '늦은' }, { en: 'laugh', ko: '웃다' }, { en: 'lead', ko: '인도하다' },
  { en: 'leaf', ko: '잎' }, { en: 'learn', ko: '배우다' }, { en: 'leave', ko: '떠나다' }, { en: 'left', ko: '왼쪽' }, { en: 'leg', ko: '다리' }, { en: 'lesson', ko: '학과' },
  { en: 'let', ko: '허락하다' }, { en: 'letter', ko: '편지' }, { en: 'library', ko: '도서관' }, { en: 'lie', ko: '눕다/거짓말하다' }, { en: 'light', ko: '빛' }, { en: 'like', ko: '좋아하다' },
  { en: 'line', ko: '선/줄' }, { en: 'lion', ko: '사자' }, { en: 'lip', ko: '입술' }, { en: 'list', ko: '목록' }, { en: 'listen', ko: '듣다' }, { en: 'little', ko: '작은' },
  { en: 'live', ko: '살다/생생한' }, { en: 'long', ko: '긴' }, { en: 'look', ko: '바라보다' }, { en: 'lose', ko: '잃다' }, { en: 'lot', ko: '많음' }, { en: 'loud', ko: '소리가 큰' },
  { en: 'love', ko: '사랑하다' }, { en: 'low', ko: '낮은' }, { en: 'luck', ko: '행운' }, { en: 'lunch', ko: '점심식사' }, { en: 'ma\'am', ko: '아주머니' }, { en: 'mad', ko: '미친' },
  { en: 'mail', ko: '우편' }, { en: 'make', ko: '만들다' }, { en: 'man', ko: '사람/남자' }, { en: 'many', ko: '많은' }, { en: 'map', ko: '지도' }, { en: 'march', ko: '행진/3월' },
  { en: 'market', ko: '상점' }, { en: 'marry', ko: '결혼하다' }, { en: 'matter', ko: '문제' }, { en: 'may', ko: '~해도좋다/5월' }, { en: 'meat', ko: '고기' }, { en: 'medal', ko: '메달' },
  { en: 'meet', ko: '만나다' }, { en: 'melon', ko: '멜론' }, { en: 'meter', ko: '미터' }, { en: 'middle', ko: '한가운데' }, { en: 'milk', ko: '우유' }, { en: 'million', ko: '100만' },
  { en: 'minute', ko: '분/순간' }, { en: 'mirror', ko: '거울' }, { en: 'miss', ko: '~양/호칭' }, { en: 'model', ko: '모형' }, { en: 'mom', ko: 'my' }, { en: 'money', ko: '돈' },
  { en: 'monkey', ko: '원숭이' }, { en: 'month', ko: '달/개월' }, { en: 'moon', ko: '달' }, { en: 'morning', ko: '아침' }, { en: 'mother', ko: '어머니' }, { en: 'mountain', ko: '산' },
  { en: 'mouth', ko: '입' }, { en: 'move', ko: '움직이다' }, { en: 'movie', ko: '영화' }, { en: 'mr', ko: '~씨' }, { en: 'mrs', ko: '~여사' }, { en: 'much', ko: '많은' },
  { en: 'music', ko: '음악' }, { en: 'must', ko: '~해야한다' }, { en: 'name', ko: '이름' }, { en: 'narrow', ko: '좁은' }, { en: 'near', ko: '가까운' }, { en: 'neck', ko: '목' },
  { en: 'need', ko: '필요하다' }, { en: 'never', ko: '결코~않다' }, { en: 'new', ko: '새로운' }, { en: 'news', ko: '뉴스' }, { en: 'next', ko: '다음의' }, { en: 'nice', ko: '좋은' },
  { en: 'night', ko: '밤' }, { en: 'no', ko: '아니다/없다' }, { en: 'noise', ko: '소음' }, { en: 'north', ko: '북쪽' }, { en: 'nose', ko: '코' }, { en: 'not', ko: '아니다' },
  { en: 'note', ko: '공책' }, { en: 'now', ko: '지금' }, { en: 'number', ko: '숫자' }, { en: 'nurse', ko: '간호원' }, { en: 'o\'clock', ko: '~시 정각' }, { en: 'of', ko: '~의' },
  { en: 'off', ko: '떨어진/끄다' }, { en: 'office', ko: '사무실' }, { en: 'often', ko: '흔히/종종' }, { en: 'oh', ko: '오!' }, { en: 'oil', ko: '기름' }, { en: 'okay', ko: 'ok' },
  { en: 'old', ko: '늙은' }, { en: 'on', ko: '~위에' }, { en: 'once', ko: '한번' }, { en: 'only', ko: '오직' }, { en: 'open', ko: '열린' }, { en: 'or', ko: '또는' },
  { en: 'orange', ko: '오렌지' }, { en: 'other', ko: '그밖의' }, { en: 'out', ko: '밖에' }, { en: 'over', ko: '~위쪽에' }, { en: 'page', ko: '쪽' }, { en: 'paint', ko: '칠하다' },
  { en: 'pair', ko: '짝' }, { en: 'pants', ko: '바지' }, { en: 'paper', ko: '종이' }, { en: 'pardon', ko: '용서하다' }, { en: 'parent', ko: '부모' }, { en: 'park', ko: '공원' },
  { en: 'party', ko: '파티' }, { en: 'pass', ko: '통과하다' }, { en: 'pay', ko: '지불하다' }, { en: 'peace', ko: '평화' }, { en: 'pear', ko: '배' }, { en: 'pen', ko: '펜/만년필' },
  { en: 'pencil', ko: '연필' }, { en: 'people', ko: '사람' }, { en: 'piano', ko: '피아노' }, { en: 'pick', ko: '따다/골라내다' }, { en: 'picnic', ko: '소풍' }, { en: 'picture', ko: '그림' },
  { en: 'piece', ko: '조각' }, { en: 'pig', ko: '돼지' }, { en: 'pilot', ko: '조종사' }, { en: 'pin', ko: '핀' }, { en: 'pine', ko: '소나무' }, { en: 'pink', ko: '분홍' },
  { en: 'pipe', ko: '파이프/판' }, { en: 'place', ko: '장소' }, { en: 'plan', ko: '계획' }, { en: 'plane', ko: '비행기' }, { en: 'plant', ko: '식물' }, { en: 'play', ko: '놀다' },
  { en: 'please', ko: '기쁘게하다/제발' }, { en: 'pocket', ko: '주머니' }, { en: 'point', ko: '점수/요점' }, { en: 'police', ko: '경찰' }, { en: 'pool', ko: '웅덩이' }, { en: 'poor', ko: '가난한' },
  { en: 'post', ko: '기둥/우편' }, { en: 'poster', ko: '포스터' }, { en: 'postato', ko: '감자' }, { en: 'practice', ko: '연습/습관' }, { en: 'present', ko: '현재/선물' }, { en: 'pretty', ko: '예쁜' },
  { en: 'print', ko: '인쇄하다' }, { en: 'problem', ko: '문제' }, { en: 'pull', ko: '끌다' }, { en: 'push', ko: '밀다' }, { en: 'put', ko: '놓다' }, { en: 'queen', ko: '여왕' },
  { en: 'question', ko: '질문' }, { en: 'quick', ko: '빠른' }, { en: 'quiet', ko: '조용한' }, { en: 'radio', ko: '라디오' }, { en: 'rain', ko: '비' }, { en: 'rainbow', ko: '무지개' },
  { en: 'read', ko: '읽다' }, { en: 'ready', ko: '준비가 된' }, { en: 'real', ko: '실제하는' }, { en: 'record', ko: '기록하다' }, { en: 'red', ko: '빨강' }, { en: 'remember', ko: '기억하다' },
  { en: 'repeat', ko: '반복하다' }, { en: 'rest', ko: '휴식' }, { en: 'restaurant', ko: '식당' }, { en: 'return', ko: '되돌아가다' }, { en: 'ribbon', ko: '리본' }, { en: 'rice', ko: '쌀' },
  { en: 'rich', ko: '부유한' }, { en: 'ride', ko: '타다' }, { en: 'right', ko: '오른쪽/옳은' }, { en: 'ring', ko: '반지/고리' }, { en: 'river', ko: '강' }, { en: 'road', ko: '길' },
  { en: 'robot', ko: '로보트' }, { en: 'rock', ko: '바위' }, { en: 'rocket', ko: '로켓' }, { en: 'roll', ko: '구르다' }, { en: 'roof', ko: '지붕' }, { en: 'room', ko: '방' },
  { en: 'rose', ko: '장미' }, { en: 'round', ko: '둥근' }, { en: 'ruler', ko: '자' }, { en: 'run', ko: '달리다' }, { en: 'sad', ko: '슬픈' }, { en: 'safe', ko: '안전한' },
  { en: 'salt', ko: '소금' }, { en: 'salad', ko: '샐러드' }, { en: 'same', ko: '같은' }, { en: 'sand', ko: '모래' }, { en: 'say', ko: '말하다' }, { en: 'school', ko: '학교' },
  { en: 'score', ko: '점수' }, { en: 'sea', ko: '바다' }, { en: 'season', ko: '계절' }, { en: 'seat', ko: '의자/좌석' }, { en: 'see', ko: '보다' }, { en: 'sell', ko: '팔다' },
  { en: 'send', ko: '보내다' }, { en: 'service', ko: '봉사하다' }, { en: 'set', ko: '놓다' }, { en: 'shall', ko: '~일것이다' }, { en: 'shape', ko: '모양' }, { en: 'she', ko: '그녀' },
  { en: 'sheep', ko: '양' }, { en: 'sheet', ko: '시트/한장' }, { en: 'ship', ko: '배' }, { en: 'shirt', ko: '셔츠' }, { en: 'shoe', ko: '구두' }, { en: 'shoot', ko: '쏘다' },
  { en: 'shop', ko: '가게' }, { en: 'short', ko: '짧은' }, { en: 'shoulder', ko: '어깨' }, { en: 'shout', ko: '외치다' }, { en: 'show', ko: '보이다' }, { en: 'shower', ko: '소나기/샤워' },
  { en: 'shut', ko: '닫다' }, { en: 'sick', ko: '아픈' }, { en: 'side', ko: '옆/측면' }, { en: 'sign', ko: '기호/신호' }, { en: 'silver', ko: '은' }, { en: 'sing', ko: '노래하다' },
  { en: 'sir', ko: '~님/~씨' }, { en: 'sister', ko: '자매' }, { en: 'sit', ko: '앉다' }, { en: 'size', ko: '크기' }, { en: 'skate', ko: '스케이트' }, { en: 'skirt', ko: '치마' },
  { en: 'sky', ko: '하늘' }, { en: 'sleep', ko: '잠자다' }, { en: 'slide', ko: '미끄러지다' }, { en: 'slow', ko: '느린' }, { en: 'small', ko: '작은' }, { en: 'smell', ko: '냄새나다' },
  { en: 'smile', ko: '웃다' }, { en: 'smoke', ko: '연기' }, { en: 'snow', ko: '눈' }, { en: 'so', ko: '그와같은' }, { en: 'soap', ko: '비누' }, { en: 'soccer', ko: '축구' },
  { en: 'sock', ko: '양말' }, { en: 'soft', ko: '부드러운' }, { en: 'some', ko: '약간의' }, { en: 'son', ko: '아들' }, { en: 'song', ko: '노래' }, { en: 'soon', ko: '곧' },
  { en: 'sorry', ko: '슬픈/유감의' }, { en: 'sound', ko: '소리' }, { en: 'soup', ko: '스프' }, { en: 'south', ko: '남쪽' }, { en: 'space', ko: '공간/우주' }, { en: 'speak', ko: '이야기하다' },
  { en: 'speed', ko: '속력' }, { en: 'spell', ko: '철자' }, { en: 'spend', ko: '낭비하다' }, { en: 'spoon', ko: '숟가락' }, { en: 'sport', ko: '운동경기' }, { en: 'spring', ko: '봄/용수철' },
  { en: 'square', ko: '정사각형' }, { en: 'stairs', ko: '계단/사닥다리' }, { en: 'stamp', ko: '우편' }, { en: 'stand', ko: '서다' }, { en: 'star', ko: '별' }, { en: 'start', ko: '출발하다' },
  { en: 'station', ko: '정거장' }, { en: 'stay', ko: '머물다' }, { en: 'steam', ko: '증기' }, { en: 'step', ko: '한걸음' }, { en: 'stick', ko: '막대기' }, { en: 'stone', ko: '돌멩이' },
  { en: 'stop', ko: '멈추다' }, { en: 'store', ko: '가게' }, { en: 'storm', ko: '폭풍우' }, { en: 'story', ko: '이야기' }, { en: 'stove', ko: '스토브/난로' }, { en: 'straight', ko: '곧은' },
  { en: 'strange', ko: '이상한/낯선' }, { en: 'strawberry', ko: '딸기' }, { en: 'street', ko: '거리' }, { en: 'strike', ko: '치다' }, { en: 'strong', ko: '강한' }, { en: 'student', ko: '학생' },
  { en: 'study', ko: '공부하다' }, { en: 'stupid', ko: '어리석은' }, { en: 'subway', ko: '지하철' }, { en: 'sugar', ko: '설탕' }, { en: 'summer', ko: '여름' }, { en: 'sun', ko: '태양' },
  { en: 'supermarket', ko: '슈퍼마켓' }, { en: 'supper', ko: '저녁식사' }, { en: 'sure', ko: '확실한' }, { en: 'surprise', ko: '놀라운' }, { en: 'sweater', ko: '스웨터' }, { en: 'sweet', ko: '달콤한' },
  { en: 'swim', ko: '수영' }, { en: 'swing', ko: '흔들리다' }, { en: 'switch', ko: '스위치' }, { en: 'table', ko: '식탁/탁자' }, { en: 'take', ko: '잡다/가져가다' }, { en: 'talk', ko: '말하다' },
  { en: 'tall', ko: '키가 큰' }, { en: 'tape', ko: '테이프' }, { en: 'taste', ko: '맛보다' }, { en: 'taxi', ko: '택시' }, { en: 'tea', ko: '차' }, { en: 'teach', ko: '가르치다' },
  { en: 'team', ko: '팀' }, { en: 'telephone', ko: '전화기' }, { en: 'television', ko: '텔레비전' }, { en: 'tell', ko: '이야기하다' }, { en: 'temple', ko: '절' }, { en: 'tennis', ko: '테니스' },
  { en: 'test', ko: '시험' }, { en: 'than', ko: '~보다(도' }, { en: 'thank', ko: '감사하다' }, { en: 'that', ko: '그것' }, { en: 'the', ko: '그(정관사' }, { en: 'then', ko: '그때' },
  { en: 'there', ko: '그곳에' }, { en: 'they', ko: '그들' }, { en: 'thick', ko: '두꺼운' }, { en: 'thin', ko: '얇은' }, { en: 'thing', ko: '사물' }, { en: 'think', ko: '생각하다' },
  { en: 'thirsty', ko: '목마른/갈망' }, { en: 'this', ko: '이것' }, { en: 'thousand', ko: '천(1000' }, { en: 'through', ko: '통해서' }, { en: 'throw', ko: '던지다' }, { en: 'ticket', ko: '표' },
  { en: 'tie', ko: '매다' }, { en: 'tiger', ko: '호랑이' }, { en: 'till', ko: '~까지' }, { en: 'time', ko: '시간' }, { en: 'tired', ko: '피곤한' }, { en: 'to', ko: '~으로/~까지' },
  { en: 'today', ko: '오늘/현재' }, { en: 'together', ko: '함께' }, { en: 'tomato', ko: '토마토' }, { en: 'tomorrow', ko: '내일' }, { en: 'tonight', ko: '오늘밤' }, { en: 'too', ko: '또한/많은' },
  { en: 'tooth', ko: '이' }, { en: 'top', ko: '꼭대기' }, { en: 'touch', ko: '만지다' }, { en: 'town', ko: '도시' }, { en: 'toy', ko: '인형' }, { en: 'train', ko: '훈련' },
  { en: 'travel', ko: '여행하다' }, { en: 'tree', ko: '나무' }, { en: 'trip', ko: '여행' }, { en: 'truck', ko: '화물차' }, { en: 'true', ko: '참된/진짜의' }, { en: 'try', ko: '노력/시도하다' },
  { en: 'tulip', ko: '튤립' }, { en: 'turn', ko: '돌다' }, { en: 'twice', ko: '두번' }, { en: 'umbrella', ko: '우산' }, { en: 'uncle', ko: '삼촌' }, { en: 'under', ko: '~아래에서' },
  { en: 'understand', ko: '이해하다' }, { en: 'until', ko: '~까지' }, { en: 'up', ko: '위에' }, { en: 'use', ko: '사용하다' }, { en: 'usual', ko: '보통의' }, { en: 'vacation', ko: '휴가' },
  { en: 'vegetable', ko: '야채' }, { en: 'very', ko: '대단히/몹시' }, { en: 'video', ko: '비디오' }, { en: 'village', ko: '마을' }, { en: 'visit', ko: '방문하다' }, { en: 'violin', ko: '바이올린' },
  { en: 'wait', ko: '기다리다' }, { en: 'wake', ko: '잠이깨다' }, { en: 'walk', ko: '걷다' }, { en: 'wall', ko: '벽' }, { en: 'want', ko: '원하다' }, { en: 'war', ko: '전쟁' },
  { en: 'warm', ko: '따뜻한' }, { en: 'wash', ko: '씻다' }, { en: 'waste', ko: '낭비하다' }, { en: 'watch', ko: '보다' }, { en: 'water', ko: '물' }, { en: 'way', ko: '길' },
  { en: 'we', ko: '우리' }, { en: 'weak', ko: '약한' }, { en: 'wear', ko: '옷을입다' }, { en: 'weather', ko: '계절' }, { en: 'week', ko: '한 주' }, { en: 'welcome', ko: '환영하다' },
  { en: 'well', ko: '상당히' }, { en: 'west', ko: '서쪽' }, { en: 'wet', ko: '젖은' }, { en: 'what', ko: '무엇(의문사' }, { en: 'when', ko: '언제' }, { en: 'where', ko: '어디(의문사' },
  { en: 'which', ko: '어느쪽(의문사' }, { en: 'white', ko: '하얀색' }, { en: 'who', ko: '누구(의문사' }, { en: 'why', ko: '왜(의문사' }, { en: 'wide', ko: '넓은' }, { en: 'will', ko: '~할것이다' },
  { en: 'win', ko: '이기다' }, { en: 'wind', ko: '바람' }, { en: 'window', ko: '창문' }, { en: 'wing', ko: '날개' }, { en: 'winter', ko: '겨울' }, { en: 'with', ko: '~와함께' },
  { en: 'woman', ko: '여자' }, { en: 'wonder', ko: '놀라다' }, { en: 'wood', ko: '나무' }, { en: 'word', ko: '낱말/말' }, { en: 'work', ko: '일' }, { en: 'world', ko: '세상' },
  { en: 'write', ko: '쓰다' }, { en: 'wrong', ko: '나쁜' }, { en: 'yeah', ko: '예(찬성/긍정' }, { en: 'year', ko: '해/1년' }, { en: 'yellow', ko: '노랑색' }, { en: 'yes', ko: '네(대답' },
  { en: 'yesterday', ko: '어제' }, { en: 'yet', ko: '아직' }, { en: 'you', ko: '당신' }, { en: 'young', ko: '젊은' }, { en: 'zero', ko: '0, 영' }, { en: 'zoo', ko: '동물원' },
]
