// 118 chemical elements with trilingual names (en/ko/ja), standard atomic
// weights, category, group and period. Public-domain facts. Powers the
// periodic table, molar-mass calculator and element quiz.

export interface Element { n: number; sym: string; en: string; ko: string; ja: string; mass: number; cat: string; group: number; period: number }

/** URL slug for an element's own page: /tools/periodic-table/<slug> (English name, lowercase). */
export const elementSlug = (e: Element): string => e.en.toLowerCase()

export const ELEMENTS: Element[] = [
  { n: 1, sym: 'H', en: 'Hydrogen', ko: '수소', ja: '水素', mass: 1.008, cat: 'nonmetal', group: 1, period: 1 },
  { n: 2, sym: 'He', en: 'Helium', ko: '헬륨', ja: 'ヘリウム', mass: 4.0026, cat: 'noble', group: 18, period: 1 },
  { n: 3, sym: 'Li', en: 'Lithium', ko: '리튬', ja: 'リチウム', mass: 6.94, cat: 'alkali', group: 1, period: 2 },
  { n: 4, sym: 'Be', en: 'Beryllium', ko: '베릴륨', ja: 'ベリリウム', mass: 9.0122, cat: 'alkaline', group: 2, period: 2 },
  { n: 5, sym: 'B', en: 'Boron', ko: '붕소', ja: 'ホウ素', mass: 10.81, cat: 'metalloid', group: 13, period: 2 },
  { n: 6, sym: 'C', en: 'Carbon', ko: '탄소', ja: '炭素', mass: 12.011, cat: 'nonmetal', group: 14, period: 2 },
  { n: 7, sym: 'N', en: 'Nitrogen', ko: '질소', ja: '窒素', mass: 14.007, cat: 'nonmetal', group: 15, period: 2 },
  { n: 8, sym: 'O', en: 'Oxygen', ko: '산소', ja: '酸素', mass: 15.999, cat: 'nonmetal', group: 16, period: 2 },
  { n: 9, sym: 'F', en: 'Fluorine', ko: '플루오린', ja: 'フッ素', mass: 18.998, cat: 'halogen', group: 17, period: 2 },
  { n: 10, sym: 'Ne', en: 'Neon', ko: '네온', ja: 'ネオン', mass: 20.18, cat: 'noble', group: 18, period: 2 },
  { n: 11, sym: 'Na', en: 'Sodium', ko: '나트륨', ja: 'ナトリウム', mass: 22.99, cat: 'alkali', group: 1, period: 3 },
  { n: 12, sym: 'Mg', en: 'Magnesium', ko: '마그네슘', ja: 'マグネシウム', mass: 24.305, cat: 'alkaline', group: 2, period: 3 },
  { n: 13, sym: 'Al', en: 'Aluminium', ko: '알루미늄', ja: 'アルミニウム', mass: 26.982, cat: 'post-transition', group: 13, period: 3 },
  { n: 14, sym: 'Si', en: 'Silicon', ko: '규소', ja: 'ケイ素', mass: 28.085, cat: 'metalloid', group: 14, period: 3 },
  { n: 15, sym: 'P', en: 'Phosphorus', ko: '인', ja: 'リン', mass: 30.974, cat: 'nonmetal', group: 15, period: 3 },
  { n: 16, sym: 'S', en: 'Sulfur', ko: '황', ja: '硫黄', mass: 32.06, cat: 'nonmetal', group: 16, period: 3 },
  { n: 17, sym: 'Cl', en: 'Chlorine', ko: '염소', ja: '塩素', mass: 35.45, cat: 'halogen', group: 17, period: 3 },
  { n: 18, sym: 'Ar', en: 'Argon', ko: '아르곤', ja: 'アルゴン', mass: 39.95, cat: 'noble', group: 18, period: 3 },
  { n: 19, sym: 'K', en: 'Potassium', ko: '칼륨', ja: 'カリウム', mass: 39.098, cat: 'alkali', group: 1, period: 4 },
  { n: 20, sym: 'Ca', en: 'Calcium', ko: '칼슘', ja: 'カルシウム', mass: 40.078, cat: 'alkaline', group: 2, period: 4 },
  { n: 21, sym: 'Sc', en: 'Scandium', ko: '스칸듐', ja: 'スカンジウム', mass: 44.956, cat: 'transition', group: 3, period: 4 },
  { n: 22, sym: 'Ti', en: 'Titanium', ko: '타이타늄', ja: 'チタン', mass: 47.867, cat: 'transition', group: 4, period: 4 },
  { n: 23, sym: 'V', en: 'Vanadium', ko: '바나듐', ja: 'バナジウム', mass: 50.942, cat: 'transition', group: 5, period: 4 },
  { n: 24, sym: 'Cr', en: 'Chromium', ko: '크로뮴', ja: 'クロム', mass: 51.996, cat: 'transition', group: 6, period: 4 },
  { n: 25, sym: 'Mn', en: 'Manganese', ko: '망가니즈', ja: 'マンガン', mass: 54.938, cat: 'transition', group: 7, period: 4 },
  { n: 26, sym: 'Fe', en: 'Iron', ko: '철', ja: '鉄', mass: 55.845, cat: 'transition', group: 8, period: 4 },
  { n: 27, sym: 'Co', en: 'Cobalt', ko: '코발트', ja: 'コバルト', mass: 58.933, cat: 'transition', group: 9, period: 4 },
  { n: 28, sym: 'Ni', en: 'Nickel', ko: '니켈', ja: 'ニッケル', mass: 58.693, cat: 'transition', group: 10, period: 4 },
  { n: 29, sym: 'Cu', en: 'Copper', ko: '구리', ja: '銅', mass: 63.546, cat: 'transition', group: 11, period: 4 },
  { n: 30, sym: 'Zn', en: 'Zinc', ko: '아연', ja: '亜鉛', mass: 65.38, cat: 'transition', group: 12, period: 4 },
  { n: 31, sym: 'Ga', en: 'Gallium', ko: '갈륨', ja: 'ガリウム', mass: 69.723, cat: 'post-transition', group: 13, period: 4 },
  { n: 32, sym: 'Ge', en: 'Germanium', ko: '저마늄', ja: 'ゲルマニウム', mass: 72.63, cat: 'metalloid', group: 14, period: 4 },
  { n: 33, sym: 'As', en: 'Arsenic', ko: '비소', ja: 'ヒ素', mass: 74.922, cat: 'metalloid', group: 15, period: 4 },
  { n: 34, sym: 'Se', en: 'Selenium', ko: '셀레늄', ja: 'セレン', mass: 78.971, cat: 'nonmetal', group: 16, period: 4 },
  { n: 35, sym: 'Br', en: 'Bromine', ko: '브로민', ja: '臭素', mass: 79.904, cat: 'halogen', group: 17, period: 4 },
  { n: 36, sym: 'Kr', en: 'Krypton', ko: '크립톤', ja: 'クリプトン', mass: 83.798, cat: 'noble', group: 18, period: 4 },
  { n: 37, sym: 'Rb', en: 'Rubidium', ko: '루비듐', ja: 'ルビジウム', mass: 85.468, cat: 'alkali', group: 1, period: 5 },
  { n: 38, sym: 'Sr', en: 'Strontium', ko: '스트론튬', ja: 'ストロンチウム', mass: 87.62, cat: 'alkaline', group: 2, period: 5 },
  { n: 39, sym: 'Y', en: 'Yttrium', ko: '이트륨', ja: 'イットリウム', mass: 88.906, cat: 'transition', group: 3, period: 5 },
  { n: 40, sym: 'Zr', en: 'Zirconium', ko: '지르코늄', ja: 'ジルコニウム', mass: 91.224, cat: 'transition', group: 4, period: 5 },
  { n: 41, sym: 'Nb', en: 'Niobium', ko: '나이오븀', ja: 'ニオブ', mass: 92.906, cat: 'transition', group: 5, period: 5 },
  { n: 42, sym: 'Mo', en: 'Molybdenum', ko: '몰리브데넘', ja: 'モリブデン', mass: 95.95, cat: 'transition', group: 6, period: 5 },
  { n: 43, sym: 'Tc', en: 'Technetium', ko: '테크네튬', ja: 'テクネチウム', mass: 98, cat: 'transition', group: 7, period: 5 },
  { n: 44, sym: 'Ru', en: 'Ruthenium', ko: '루테늄', ja: 'ルテニウム', mass: 101.07, cat: 'transition', group: 8, period: 5 },
  { n: 45, sym: 'Rh', en: 'Rhodium', ko: '로듐', ja: 'ロジウム', mass: 102.91, cat: 'transition', group: 9, period: 5 },
  { n: 46, sym: 'Pd', en: 'Palladium', ko: '팔라듐', ja: 'パラジウム', mass: 106.42, cat: 'transition', group: 10, period: 5 },
  { n: 47, sym: 'Ag', en: 'Silver', ko: '은', ja: '銀', mass: 107.87, cat: 'transition', group: 11, period: 5 },
  { n: 48, sym: 'Cd', en: 'Cadmium', ko: '카드뮴', ja: 'カドミウム', mass: 112.41, cat: 'transition', group: 12, period: 5 },
  { n: 49, sym: 'In', en: 'Indium', ko: '인듐', ja: 'インジウム', mass: 114.82, cat: 'post-transition', group: 13, period: 5 },
  { n: 50, sym: 'Sn', en: 'Tin', ko: '주석', ja: 'スズ', mass: 118.71, cat: 'post-transition', group: 14, period: 5 },
  { n: 51, sym: 'Sb', en: 'Antimony', ko: '안티모니', ja: 'アンチモン', mass: 121.76, cat: 'metalloid', group: 15, period: 5 },
  { n: 52, sym: 'Te', en: 'Tellurium', ko: '텔루륨', ja: 'テルル', mass: 127.6, cat: 'metalloid', group: 16, period: 5 },
  { n: 53, sym: 'I', en: 'Iodine', ko: '아이오딘', ja: 'ヨウ素', mass: 126.9, cat: 'halogen', group: 17, period: 5 },
  { n: 54, sym: 'Xe', en: 'Xenon', ko: '제논', ja: 'キセノン', mass: 131.29, cat: 'noble', group: 18, period: 5 },
  { n: 55, sym: 'Cs', en: 'Caesium', ko: '세슘', ja: 'セシウム', mass: 132.91, cat: 'alkali', group: 1, period: 6 },
  { n: 56, sym: 'Ba', en: 'Barium', ko: '바륨', ja: 'バリウム', mass: 137.33, cat: 'alkaline', group: 2, period: 6 },
  { n: 57, sym: 'La', en: 'Lanthanum', ko: '란타넘', ja: 'ランタン', mass: 138.91, cat: 'lanthanide', group: 3, period: 6 },
  { n: 58, sym: 'Ce', en: 'Cerium', ko: '세륨', ja: 'セリウム', mass: 140.12, cat: 'lanthanide', group: 3, period: 6 },
  { n: 59, sym: 'Pr', en: 'Praseodymium', ko: '프라세오디뮴', ja: 'プラセオジム', mass: 140.91, cat: 'lanthanide', group: 3, period: 6 },
  { n: 60, sym: 'Nd', en: 'Neodymium', ko: '네오디뮴', ja: 'ネオジム', mass: 144.24, cat: 'lanthanide', group: 3, period: 6 },
  { n: 61, sym: 'Pm', en: 'Promethium', ko: '프로메튬', ja: 'プロメチウム', mass: 145, cat: 'lanthanide', group: 3, period: 6 },
  { n: 62, sym: 'Sm', en: 'Samarium', ko: '사마륨', ja: 'サマリウム', mass: 150.36, cat: 'lanthanide', group: 3, period: 6 },
  { n: 63, sym: 'Eu', en: 'Europium', ko: '유로퓸', ja: 'ユウロピウム', mass: 151.96, cat: 'lanthanide', group: 3, period: 6 },
  { n: 64, sym: 'Gd', en: 'Gadolinium', ko: '가돌리늄', ja: 'ガドリニウム', mass: 157.25, cat: 'lanthanide', group: 3, period: 6 },
  { n: 65, sym: 'Tb', en: 'Terbium', ko: '터븀', ja: 'テルビウム', mass: 158.93, cat: 'lanthanide', group: 3, period: 6 },
  { n: 66, sym: 'Dy', en: 'Dysprosium', ko: '디스프로슘', ja: 'ジスプロシウム', mass: 162.5, cat: 'lanthanide', group: 3, period: 6 },
  { n: 67, sym: 'Ho', en: 'Holmium', ko: '홀뮴', ja: 'ホルミウム', mass: 164.93, cat: 'lanthanide', group: 3, period: 6 },
  { n: 68, sym: 'Er', en: 'Erbium', ko: '어븀', ja: 'エルビウム', mass: 167.26, cat: 'lanthanide', group: 3, period: 6 },
  { n: 69, sym: 'Tm', en: 'Thulium', ko: '툴륨', ja: 'ツリウム', mass: 168.93, cat: 'lanthanide', group: 3, period: 6 },
  { n: 70, sym: 'Yb', en: 'Ytterbium', ko: '이터븀', ja: 'イッテルビウム', mass: 173.05, cat: 'lanthanide', group: 3, period: 6 },
  { n: 71, sym: 'Lu', en: 'Lutetium', ko: '루테튬', ja: 'ルテチウム', mass: 174.97, cat: 'lanthanide', group: 3, period: 6 },
  { n: 72, sym: 'Hf', en: 'Hafnium', ko: '하프늄', ja: 'ハフニウム', mass: 178.49, cat: 'transition', group: 4, period: 6 },
  { n: 73, sym: 'Ta', en: 'Tantalum', ko: '탄탈럼', ja: 'タンタル', mass: 180.95, cat: 'transition', group: 5, period: 6 },
  { n: 74, sym: 'W', en: 'Tungsten', ko: '텅스텐', ja: 'タングステン', mass: 183.84, cat: 'transition', group: 6, period: 6 },
  { n: 75, sym: 'Re', en: 'Rhenium', ko: '레늄', ja: 'レニウム', mass: 186.21, cat: 'transition', group: 7, period: 6 },
  { n: 76, sym: 'Os', en: 'Osmium', ko: '오스뮴', ja: 'オスミウム', mass: 190.23, cat: 'transition', group: 8, period: 6 },
  { n: 77, sym: 'Ir', en: 'Iridium', ko: '이리듐', ja: 'イリジウム', mass: 192.22, cat: 'transition', group: 9, period: 6 },
  { n: 78, sym: 'Pt', en: 'Platinum', ko: '백금', ja: '白金', mass: 195.08, cat: 'transition', group: 10, period: 6 },
  { n: 79, sym: 'Au', en: 'Gold', ko: '금', ja: '金', mass: 196.97, cat: 'transition', group: 11, period: 6 },
  { n: 80, sym: 'Hg', en: 'Mercury', ko: '수은', ja: '水銀', mass: 200.59, cat: 'transition', group: 12, period: 6 },
  { n: 81, sym: 'Tl', en: 'Thallium', ko: '탈륨', ja: 'タリウム', mass: 204.38, cat: 'post-transition', group: 13, period: 6 },
  { n: 82, sym: 'Pb', en: 'Lead', ko: '납', ja: '鉛', mass: 207.2, cat: 'post-transition', group: 14, period: 6 },
  { n: 83, sym: 'Bi', en: 'Bismuth', ko: '비스무트', ja: 'ビスマス', mass: 208.98, cat: 'post-transition', group: 15, period: 6 },
  { n: 84, sym: 'Po', en: 'Polonium', ko: '폴로늄', ja: 'ポロニウム', mass: 209, cat: 'post-transition', group: 16, period: 6 },
  { n: 85, sym: 'At', en: 'Astatine', ko: '아스타틴', ja: 'アスタチン', mass: 210, cat: 'halogen', group: 17, period: 6 },
  { n: 86, sym: 'Rn', en: 'Radon', ko: '라돈', ja: 'ラドン', mass: 222, cat: 'noble', group: 18, period: 6 },
  { n: 87, sym: 'Fr', en: 'Francium', ko: '프랑슘', ja: 'フランシウム', mass: 223, cat: 'alkali', group: 1, period: 7 },
  { n: 88, sym: 'Ra', en: 'Radium', ko: '라듐', ja: 'ラジウム', mass: 226, cat: 'alkaline', group: 2, period: 7 },
  { n: 89, sym: 'Ac', en: 'Actinium', ko: '악티늄', ja: 'アクチニウム', mass: 227, cat: 'actinide', group: 3, period: 7 },
  { n: 90, sym: 'Th', en: 'Thorium', ko: '토륨', ja: 'トリウム', mass: 232.04, cat: 'actinide', group: 3, period: 7 },
  { n: 91, sym: 'Pa', en: 'Protactinium', ko: '프로트악티늄', ja: 'プロトアクチニウム', mass: 231.04, cat: 'actinide', group: 3, period: 7 },
  { n: 92, sym: 'U', en: 'Uranium', ko: '우라늄', ja: 'ウラン', mass: 238.03, cat: 'actinide', group: 3, period: 7 },
  { n: 93, sym: 'Np', en: 'Neptunium', ko: '넵투늄', ja: 'ネプツニウム', mass: 237, cat: 'actinide', group: 3, period: 7 },
  { n: 94, sym: 'Pu', en: 'Plutonium', ko: '플루토늄', ja: 'プルトニウム', mass: 244, cat: 'actinide', group: 3, period: 7 },
  { n: 95, sym: 'Am', en: 'Americium', ko: '아메리슘', ja: 'アメリシウム', mass: 243, cat: 'actinide', group: 3, period: 7 },
  { n: 96, sym: 'Cm', en: 'Curium', ko: '퀴륨', ja: 'キュリウム', mass: 247, cat: 'actinide', group: 3, period: 7 },
  { n: 97, sym: 'Bk', en: 'Berkelium', ko: '버클륨', ja: 'バークリウム', mass: 247, cat: 'actinide', group: 3, period: 7 },
  { n: 98, sym: 'Cf', en: 'Californium', ko: '캘리포늄', ja: 'カリホルニウム', mass: 251, cat: 'actinide', group: 3, period: 7 },
  { n: 99, sym: 'Es', en: 'Einsteinium', ko: '아인슈타이늄', ja: 'アインスタイニウム', mass: 252, cat: 'actinide', group: 3, period: 7 },
  { n: 100, sym: 'Fm', en: 'Fermium', ko: '페르뮴', ja: 'フェルミウム', mass: 257, cat: 'actinide', group: 3, period: 7 },
  { n: 101, sym: 'Md', en: 'Mendelevium', ko: '멘델레븀', ja: 'メンデレビウム', mass: 258, cat: 'actinide', group: 3, period: 7 },
  { n: 102, sym: 'No', en: 'Nobelium', ko: '노벨륨', ja: 'ノーベリウム', mass: 259, cat: 'actinide', group: 3, period: 7 },
  { n: 103, sym: 'Lr', en: 'Lawrencium', ko: '로렌슘', ja: 'ローレンシウム', mass: 266, cat: 'actinide', group: 3, period: 7 },
  { n: 104, sym: 'Rf', en: 'Rutherfordium', ko: '러더포듐', ja: 'ラザホージウム', mass: 267, cat: 'transition', group: 4, period: 7 },
  { n: 105, sym: 'Db', en: 'Dubnium', ko: '더브늄', ja: 'ドブニウム', mass: 268, cat: 'transition', group: 5, period: 7 },
  { n: 106, sym: 'Sg', en: 'Seaborgium', ko: '시보귬', ja: 'シーボーギウム', mass: 269, cat: 'transition', group: 6, period: 7 },
  { n: 107, sym: 'Bh', en: 'Bohrium', ko: '보륨', ja: 'ボーリウム', mass: 270, cat: 'transition', group: 7, period: 7 },
  { n: 108, sym: 'Hs', en: 'Hassium', ko: '하슘', ja: 'ハッシウム', mass: 269, cat: 'transition', group: 8, period: 7 },
  { n: 109, sym: 'Mt', en: 'Meitnerium', ko: '마이트너륨', ja: 'マイトネリウム', mass: 278, cat: 'transition', group: 9, period: 7 },
  { n: 110, sym: 'Ds', en: 'Darmstadtium', ko: '다름슈타튬', ja: 'ダームスタチウム', mass: 281, cat: 'transition', group: 10, period: 7 },
  { n: 111, sym: 'Rg', en: 'Roentgenium', ko: '뢴트게늄', ja: 'レントゲニウム', mass: 282, cat: 'transition', group: 11, period: 7 },
  { n: 112, sym: 'Cn', en: 'Copernicium', ko: '코페르니슘', ja: 'コペルニシウム', mass: 285, cat: 'transition', group: 12, period: 7 },
  { n: 113, sym: 'Nh', en: 'Nihonium', ko: '니호늄', ja: 'ニホニウム', mass: 286, cat: 'post-transition', group: 13, period: 7 },
  { n: 114, sym: 'Fl', en: 'Flerovium', ko: '플레로븀', ja: 'フレロビウム', mass: 289, cat: 'post-transition', group: 14, period: 7 },
  { n: 115, sym: 'Mc', en: 'Moscovium', ko: '모스코븀', ja: 'モスコビウム', mass: 290, cat: 'post-transition', group: 15, period: 7 },
  { n: 116, sym: 'Lv', en: 'Livermorium', ko: '리버모륨', ja: 'リバモリウム', mass: 293, cat: 'post-transition', group: 16, period: 7 },
  { n: 117, sym: 'Ts', en: 'Tennessine', ko: '테네신', ja: 'テネシン', mass: 294, cat: 'halogen', group: 17, period: 7 },
  { n: 118, sym: 'Og', en: 'Oganesson', ko: '오가네손', ja: 'オガネソン', mass: 294, cat: 'noble', group: 18, period: 7 },
]

export const BY_SYMBOL: Record<string, Element> = Object.fromEntries(ELEMENTS.map((e) => [e.sym, e]))
export const ELEMENT_BY_SLUG: Record<string, Element> = Object.fromEntries(ELEMENTS.map((e) => [elementSlug(e), e]))
