// 고사성어 사전 — generated from gosaseongeo_master.csv (seed 300).
// 성어·뜻은 공유 지식, 유래·예문은 자체 작성(저작권 클린). 확장은 gosaseongeo_확장_지시문.md 참고.
export interface Idiom { id: string; hanja: string; reading: string; len: number; lit: string; fig: string; origin: string; source: string; example: string; syn: string[]; reviewed: boolean }
export const IDIOMS: Idiom[] = [
  {"id":"gs0001","hanja":"刻舟求劍","reading":"각주구검","len":4,"lit":"배에 표시해 칼을 찾음","fig":"융통성 없이 낡은 방식만 고집함","origin":"칼을 강에 빠뜨린 사람이 뱃전에 표시해 두고 나중에 그 자리에서 찾으려 했다는 이야기","source":"여씨춘추","example":"시대가 바뀌었는데 옛 방식만 고집하는 건 각주구검이나 다름없다.","syn":["守株待兎"],"reviewed":true},
  {"id":"gs0002","hanja":"結草報恩","reading":"결초보은","len":4,"lit":"풀을 묶어 은혜를 갚음","fig":"죽어서도 잊지 않고 은혜를 갚음","origin":"은혜 입은 이의 혼령이 풀을 묶어 적장을 넘어뜨려 보답했다는 고사","source":"춘추좌씨전","example":"그때 도와주신 은혜는 결초보은하겠습니다.","syn":["白骨難忘"],"reviewed":true},
  {"id":"gs0003","hanja":"鷄肋","reading":"계륵","len":2,"lit":"닭의 갈비","fig":"버리기는 아깝지만 그다지 쓸모는 없는 것","origin":"조조가 한중 철군을 두고 '계륵'이라 한 데서 유래","source":"후한서","example":"쓰자니 애매하고 버리자니 아까운, 계륵 같은 물건이다.","syn":[],"reviewed":true},
  {"id":"gs0004","hanja":"苦盡甘來","reading":"고진감래","len":4,"lit":"쓴 것이 다하면 단 것이 옴","fig":"고생 끝에 즐거움이 옴","origin":"","source":"","example":"오랜 노력 끝에 합격했으니 그야말로 고진감래다.","syn":["興盡悲來"],"reviewed":true},
  {"id":"gs0005","hanja":"過猶不及","reading":"과유불급","len":4,"lit":"지나침은 미치지 못함과 같음","fig":"정도를 지나침은 모자람과 같다","origin":"","source":"논어","example":"운동도 과유불급이라 지나치면 몸을 해친다.","syn":[],"reviewed":true},
  {"id":"gs0006","hanja":"群鷄一鶴","reading":"군계일학","len":4,"lit":"닭 무리 속의 한 마리 학","fig":"평범한 사람들 가운데 뛰어난 한 사람","origin":"","source":"진서","example":"수많은 지원자 중에서 그녀는 단연 군계일학이었다.","syn":["囊中之錐"],"reviewed":true},
  {"id":"gs0007","hanja":"錦上添花","reading":"금상첨화","len":4,"lit":"비단 위에 꽃을 더함","fig":"좋은 일에 또 좋은 일이 더해짐","origin":"","source":"","example":"경치도 좋은데 음식까지 훌륭하니 금상첨화다.","syn":["雪上加霜"],"reviewed":true},
  {"id":"gs0008","hanja":"杞憂","reading":"기우","len":2,"lit":"기나라 사람의 걱정","fig":"쓸데없는 걱정","origin":"하늘이 무너질까 걱정한 기나라 사람의 이야기","source":"열자","example":"걱정했던 일은 일어나지 않았으니 한낱 기우였다.","syn":[],"reviewed":true},
  {"id":"gs0009","hanja":"囊中之錐","reading":"낭중지추","len":4,"lit":"주머니 속의 송곳","fig":"뛰어난 재능은 저절로 드러남","origin":"","source":"사기","example":"실력이 있으면 낭중지추처럼 언젠가 드러나기 마련이다.","syn":["群鷄一鶴"],"reviewed":true},
  {"id":"gs0010","hanja":"累卵之危","reading":"누란지위","len":4,"lit":"알을 쌓아 놓은 듯한 위태로움","fig":"몹시 위태로운 형세","origin":"","source":"","example":"회사는 부도 직전의 누란지위에 처했다.","syn":["風前燈火"],"reviewed":true},
  {"id":"gs0011","hanja":"多多益善","reading":"다다익선","len":4,"lit":"많으면 많을수록 좋음","fig":"많을수록 더 좋다","origin":"한신이 군사는 많을수록 좋다고 한 데서 유래","source":"사기","example":"자료는 다다익선이니 많이 모아 두자.","syn":[],"reviewed":true},
  {"id":"gs0012","hanja":"大器晩成","reading":"대기만성","len":4,"lit":"큰 그릇은 늦게 이루어짐","fig":"큰 인물은 늦게 성공함","origin":"","source":"노자","example":"그는 마흔에 빛을 본 대기만성형 배우다.","syn":[],"reviewed":true},
  {"id":"gs0013","hanja":"同病相憐","reading":"동병상련","len":4,"lit":"같은 병을 앓는 이끼리 가엾게 여김","fig":"처지가 비슷한 사람끼리 서로 동정함","origin":"","source":"오월춘추","example":"같은 처지라 동병상련의 마음으로 그를 도왔다.","syn":[],"reviewed":true},
  {"id":"gs0014","hanja":"登龍門","reading":"등용문","len":3,"lit":"용문에 오름","fig":"어려운 관문을 넘어 크게 출세함","origin":"황하 상류 용문을 오른 잉어가 용이 된다는 전설","source":"후한서","example":"그 대회는 신인 배우의 등용문으로 통한다.","syn":[],"reviewed":true},
  {"id":"gs0015","hanja":"燈火可親","reading":"등화가친","len":4,"lit":"등불을 가까이할 만함","fig":"가을은 독서하기 좋은 계절","origin":"","source":"","example":"등화가친의 계절, 책 한 권 읽어 보자.","syn":[],"reviewed":true},
  {"id":"gs0016","hanja":"馬耳東風","reading":"마이동풍","len":4,"lit":"말 귀에 봄바람","fig":"남의 말을 흘려듣고 새겨듣지 않음","origin":"","source":"","example":"아무리 조언해도 마이동풍이니 답답하다.","syn":["牛耳讀經"],"reviewed":true},
  {"id":"gs0017","hanja":"孟母三遷","reading":"맹모삼천","len":4,"lit":"맹자 어머니가 세 번 이사함","fig":"교육에는 주변 환경이 중요함","origin":"맹자 어머니가 자식 교육을 위해 세 번 이사했다는 고사","source":"열녀전","example":"맹모삼천이라더니, 좋은 학군을 찾아 이사했다.","syn":[],"reviewed":true},
  {"id":"gs0018","hanja":"明鏡止水","reading":"명경지수","len":4,"lit":"맑은 거울과 고요한 물","fig":"잡념 없이 맑고 고요한 마음","origin":"","source":"장자","example":"그는 명경지수 같은 마음으로 결정을 내렸다.","syn":[],"reviewed":true},
  {"id":"gs0019","hanja":"矛盾","reading":"모순","len":2,"lit":"창과 방패","fig":"말이나 행동의 앞뒤가 맞지 않음","origin":"무엇이든 뚫는 창과 무엇도 막는 방패를 함께 판 장사꾼 이야기","source":"한비자","example":"그의 주장에는 명백한 모순이 있다.","syn":["自家撞着"],"reviewed":true},
  {"id":"gs0020","hanja":"刎頸之交","reading":"문경지교","len":4,"lit":"목을 베어 줄 수 있는 사귐","fig":"생사를 함께할 만큼 깊은 우정","origin":"염파와 인상여의 우정에서 유래","source":"사기","example":"두 사람은 문경지교를 맺은 둘도 없는 벗이다.","syn":["竹馬故友"],"reviewed":true},
  {"id":"gs0021","hanja":"拔本塞源","reading":"발본색원","len":4,"lit":"뿌리를 뽑고 근원을 막음","fig":"폐단의 근원을 완전히 없앰","origin":"","source":"","example":"부패를 발본색원하겠다고 선언했다.","syn":[],"reviewed":true},
  {"id":"gs0022","hanja":"背水陣","reading":"배수진","len":3,"lit":"물을 등지고 친 진","fig":"물러설 곳 없이 죽을 각오로 맞섬","origin":"한신이 강을 등지고 진을 쳐 승리한 고사","source":"사기","example":"마지막 시험에 배수진을 치고 공부에 매달렸다.","syn":[],"reviewed":true},
  {"id":"gs0023","hanja":"百年河淸","reading":"백년하청","len":4,"lit":"백 년을 기다려도 황하는 맑아지지 않음","fig":"아무리 기다려도 가망이 없음","origin":"","source":"","example":"그 약속만 믿는 건 백년하청이다.","syn":[],"reviewed":true},
  {"id":"gs0024","hanja":"白眉","reading":"백미","len":2,"lit":"흰 눈썹","fig":"여럿 가운데 가장 뛰어난 것","origin":"마씨 오형제 중 흰 눈썹의 마량이 가장 뛰어났다는 데서 유래","source":"삼국지","example":"이 작품이 그의 대표작 중 백미로 꼽힌다.","syn":[],"reviewed":true},
  {"id":"gs0025","hanja":"不恥下問","reading":"불치하문","len":4,"lit":"아랫사람에게 묻기를 부끄러워하지 않음","fig":"모르는 것을 묻는 것을 부끄러워하지 않음","origin":"","source":"논어","example":"불치하문의 자세로 후배에게도 배운다.","syn":[],"reviewed":true},
  {"id":"gs0026","hanja":"四面楚歌","reading":"사면초가","len":4,"lit":"사방에서 들리는 초나라 노래","fig":"사방이 적으로 둘러싸여 고립된 처지","origin":"항우가 한나라 군에 포위돼 사방에서 초나라 노래를 들은 고사","source":"사기","example":"여론도 등을 돌려 그는 사면초가에 빠졌다.","syn":["孤立無援"],"reviewed":true},
  {"id":"gs0027","hanja":"沙上樓閣","reading":"사상누각","len":4,"lit":"모래 위의 누각","fig":"기초가 부실해 오래가지 못하는 것","origin":"","source":"","example":"계획 없는 사업은 사상누각에 불과하다.","syn":[],"reviewed":true},
  {"id":"gs0028","hanja":"塞翁之馬","reading":"새옹지마","len":4,"lit":"변방 노인의 말","fig":"인생의 길흉화복은 미리 알 수 없음","origin":"변방 노인의 말이 화가 되고 복이 되기를 거듭한 이야기","source":"회남자","example":"인생은 새옹지마라 지금의 실패가 약이 될 수 있다.","syn":["轉禍爲福"],"reviewed":true},
  {"id":"gs0029","hanja":"桑田碧海","reading":"상전벽해","len":4,"lit":"뽕밭이 푸른 바다가 됨","fig":"세상이 몰라보게 크게 변함","origin":"","source":"","example":"십 년 만에 온 고향은 상전벽해였다.","syn":["隔世之感"],"reviewed":true},
  {"id":"gs0030","hanja":"雪上加霜","reading":"설상가상","len":4,"lit":"눈 위에 서리가 더해짐","fig":"어려운 일이 잇따라 겹침","origin":"","source":"","example":"늦은 데다 비까지 오니 설상가상이다.","syn":["錦上添花"],"reviewed":true},
  {"id":"gs0031","hanja":"首丘初心","reading":"수구초심","len":4,"lit":"여우가 죽을 때 머리를 고향 언덕으로 둠","fig":"고향을 그리워하는 마음","origin":"","source":"예기","example":"나이 들수록 수구초심으로 고향이 그립다.","syn":[],"reviewed":true},
  {"id":"gs0032","hanja":"守株待兎","reading":"수주대토","len":4,"lit":"그루터기를 지키며 토끼를 기다림","fig":"낡은 방식만 고집하며 헛되이 요행을 바람","origin":"우연히 토끼를 잡은 농부가 그루터기만 지켰다는 이야기","source":"한비자","example":"노력 없이 행운만 바라는 건 수주대토다.","syn":["刻舟求劍"],"reviewed":true},
  {"id":"gs0033","hanja":"脣亡齒寒","reading":"순망치한","len":4,"lit":"입술이 없으면 이가 시림","fig":"서로 의지하던 한쪽이 망하면 다른 쪽도 위태로움","origin":"","source":"춘추좌씨전","example":"협력사가 무너지면 우리도 위태로우니 순망치한이다.","syn":[],"reviewed":true},
  {"id":"gs0034","hanja":"識字憂患","reading":"식자우환","len":4,"lit":"글자를 아는 것이 근심","fig":"어설픈 지식이 도리어 걱정을 부름","origin":"","source":"","example":"어설프게 아는 게 식자우환이 될 때가 있다.","syn":[],"reviewed":true},
  {"id":"gs0035","hanja":"我田引水","reading":"아전인수","len":4,"lit":"제 논에 물 대기","fig":"자기에게만 이롭게 생각하거나 행동함","origin":"","source":"","example":"규정을 아전인수 격으로 해석하지 마라.","syn":[],"reviewed":true},
  {"id":"gs0036","hanja":"漁夫之利","reading":"어부지리","len":4,"lit":"어부의 이익","fig":"둘이 다투는 사이 제삼자가 이익을 봄","origin":"조개와 도요새가 다투다 어부에게 둘 다 잡힌 이야기","source":"전국책","example":"두 후보가 다투는 사이 제3 후보가 어부지리로 당선됐다.","syn":["犬兎之爭"],"reviewed":true},
  {"id":"gs0037","hanja":"緣木求魚","reading":"연목구어","len":4,"lit":"나무에 올라 물고기를 구함","fig":"불가능한 일을 무리하게 하려 함","origin":"","source":"맹자","example":"준비 없이 성공을 바라는 건 연목구어다.","syn":[],"reviewed":true},
  {"id":"gs0038","hanja":"五里霧中","reading":"오리무중","len":4,"lit":"오 리에 걸친 안개 속","fig":"일의 갈피를 전혀 잡을 수 없음","origin":"","source":"후한서","example":"사건은 단서조차 없이 오리무중이다.","syn":[],"reviewed":true},
  {"id":"gs0039","hanja":"吳越同舟","reading":"오월동주","len":4,"lit":"오나라와 월나라가 한 배를 탐","fig":"원수 사이라도 위급할 땐 서로 협력함","origin":"","source":"손자","example":"경쟁사지만 위기 앞에선 오월동주로 손잡았다.","syn":[],"reviewed":true},
  {"id":"gs0040","hanja":"烏合之卒","reading":"오합지졸","len":4,"lit":"까마귀 떼처럼 모인 군사","fig":"규율도 통일도 없는 무리","origin":"","source":"","example":"훈련 없는 오합지졸로는 이길 수 없다.","syn":[],"reviewed":true},
  {"id":"gs0041","hanja":"溫故知新","reading":"온고지신","len":4,"lit":"옛것을 익혀 새것을 앎","fig":"옛것을 바탕으로 새 지식을 얻음","origin":"","source":"논어","example":"고전을 읽으며 온고지신의 지혜를 얻는다.","syn":[],"reviewed":true},
  {"id":"gs0042","hanja":"臥薪嘗膽","reading":"와신상담","len":4,"lit":"섶에 눕고 쓸개를 맛봄","fig":"원수를 갚으려 온갖 괴로움을 참고 견딤","origin":"월왕 구천이 패배 후 복수를 위해 고생을 참은 고사","source":"사기","example":"그는 와신상담 끝에 재기에 성공했다.","syn":["切齒腐心"],"reviewed":true},
  {"id":"gs0043","hanja":"完璧","reading":"완벽","len":2,"lit":"흠 없는 옥","fig":"결함 없이 완전함","origin":"인상여가 화씨벽을 온전히 지켜 돌아온 고사","source":"사기","example":"그의 발표는 빈틈없이 완벽했다.","syn":[],"reviewed":true},
  {"id":"gs0044","hanja":"龍頭蛇尾","reading":"용두사미","len":4,"lit":"용의 머리에 뱀의 꼬리","fig":"시작은 거창하나 끝이 흐지부지함","origin":"","source":"","example":"요란하게 시작했지만 결국 용두사미로 끝났다.","syn":[],"reviewed":true},
  {"id":"gs0045","hanja":"牛耳讀經","reading":"우이독경","len":4,"lit":"쇠귀에 경 읽기","fig":"아무리 일러도 알아듣지 못함","origin":"","source":"","example":"몇 번을 설명해도 우이독경이다.","syn":["馬耳東風"],"reviewed":true},
  {"id":"gs0046","hanja":"有備無患","reading":"유비무환","len":4,"lit":"준비가 있으면 근심이 없음","fig":"미리 대비하면 걱정할 것이 없다","origin":"","source":"서경","example":"유비무환이라고, 미리 대비해 두자.","syn":[],"reviewed":true},
  {"id":"gs0047","hanja":"以心傳心","reading":"이심전심","len":4,"lit":"마음에서 마음으로 전함","fig":"말 없이도 서로 뜻이 통함","origin":"부처가 가섭에게 말 없이 뜻을 전했다는 데서 유래","source":"불교","example":"오랜 친구라 이심전심으로 통한다.","syn":["拈華微笑"],"reviewed":true},
  {"id":"gs0048","hanja":"一擧兩得","reading":"일거양득","len":4,"lit":"한 번에 두 가지를 얻음","fig":"한 가지 일로 두 이익을 봄","origin":"","source":"","example":"운동하며 출근하니 일거양득이다.","syn":["一石二鳥"],"reviewed":true},
  {"id":"gs0049","hanja":"一網打盡","reading":"일망타진","len":4,"lit":"한 그물로 다 잡음","fig":"한꺼번에 모조리 잡아들임","origin":"","source":"","example":"경찰이 조직을 일망타진했다.","syn":[],"reviewed":true},
  {"id":"gs0050","hanja":"自家撞着","reading":"자가당착","len":4,"lit":"자기끼리 부딪침","fig":"자기 말과 행동이 앞뒤가 맞지 않음","origin":"","source":"","example":"그의 변명은 자가당착에 빠졌다.","syn":["矛盾"],"reviewed":true},
  {"id":"gs0051","hanja":"自繩自縛","reading":"자승자박","len":4,"lit":"제 줄로 제 몸을 묶음","fig":"자기 말·행동으로 스스로 곤란해짐","origin":"","source":"","example":"거짓말이 늘어 결국 자승자박이 됐다.","syn":[],"reviewed":true},
  {"id":"gs0052","hanja":"賊反荷杖","reading":"적반하장","len":4,"lit":"도둑이 도리어 매를 듦","fig":"잘못한 자가 도리어 큰소리침","origin":"","source":"","example":"잘못은 자기가 해 놓고 적반하장으로 화를 낸다.","syn":[],"reviewed":true},
  {"id":"gs0053","hanja":"戰戰兢兢","reading":"전전긍긍","len":4,"lit":"몹시 두려워 조심함","fig":"잘못될까 봐 매우 두려워하고 조심함","origin":"","source":"시경","example":"들킬까 봐 전전긍긍하며 지냈다.","syn":[],"reviewed":true},
  {"id":"gs0054","hanja":"轉禍爲福","reading":"전화위복","len":4,"lit":"화가 바뀌어 복이 됨","fig":"나쁜 일이 도리어 좋은 일이 됨","origin":"","source":"","example":"이번 실패가 전화위복의 계기가 됐다.","syn":["塞翁之馬"],"reviewed":true},
  {"id":"gs0055","hanja":"切磋琢磨","reading":"절차탁마","len":4,"lit":"옥돌을 자르고 갈고 쪼고 닦음","fig":"학문과 덕을 끊임없이 갈고닦음","origin":"","source":"시경","example":"동료들과 절차탁마하며 실력을 키웠다.","syn":[],"reviewed":true},
  {"id":"gs0056","hanja":"井底之蛙","reading":"정저지와","len":4,"lit":"우물 안 개구리","fig":"견문이 좁아 넓은 세상을 모름","origin":"","source":"장자","example":"넓은 세상을 보니 그동안 정저지와였음을 깨달았다.","syn":[],"reviewed":true},
  {"id":"gs0057","hanja":"朝三暮四","reading":"조삼모사","len":4,"lit":"아침에 셋 저녁에 넷","fig":"눈앞 차이만 알고 결과가 같음을 모름; 잔꾀로 속임","origin":"원숭이에게 도토리를 아침 셋 저녁 넷이라 하자 화내다, 아침 넷 저녁 셋이라 하자 좋아한 이야기","source":"열자","example":"할인처럼 보여도 조삼모사인 경우가 많다.","syn":[],"reviewed":true},
  {"id":"gs0058","hanja":"主客顚倒","reading":"주객전도","len":4,"lit":"주인과 손님이 뒤바뀜","fig":"사물의 경중·선후가 뒤바뀜","origin":"","source":"","example":"수단이 목적이 되니 주객전도다.","syn":[],"reviewed":true},
  {"id":"gs0059","hanja":"走馬看山","reading":"주마간산","len":4,"lit":"말을 달리며 산을 봄","fig":"자세히 살피지 못하고 대충 보고 지나침","origin":"","source":"","example":"시간이 없어 전시를 주마간산으로 봤다.","syn":[],"reviewed":true},
  {"id":"gs0060","hanja":"竹馬故友","reading":"죽마고우","len":4,"lit":"대말을 타고 놀던 옛 벗","fig":"어릴 때부터 함께 자란 오랜 친구","origin":"","source":"진서","example":"그와는 삼십 년 지기 죽마고우다.","syn":["刎頸之交"],"reviewed":true},
  {"id":"gs0061","hanja":"衆寡不敵","reading":"중과부적","len":4,"lit":"적은 수로 많은 수를 대적하지 못함","fig":"수가 적으면 많은 쪽을 이길 수 없다","origin":"","source":"맹자","example":"용감히 맞섰으나 중과부적이었다.","syn":[],"reviewed":true},
  {"id":"gs0062","hanja":"指鹿爲馬","reading":"지록위마","len":4,"lit":"사슴을 가리켜 말이라 함","fig":"윗사람을 농락하고 권세를 함부로 휘두름","origin":"조고가 사슴을 말이라 우기며 신하들을 시험한 고사","source":"사기","example":"권력자가 지록위마로 진실을 뒤집었다.","syn":[],"reviewed":true},
  {"id":"gs0063","hanja":"千載一遇","reading":"천재일우","len":4,"lit":"천 년에 한 번 만남","fig":"좀처럼 오지 않는 더없이 좋은 기회","origin":"","source":"","example":"이건 천재일우의 기회이니 놓치지 마라.","syn":[],"reviewed":true},
  {"id":"gs0064","hanja":"靑出於藍","reading":"청출어람","len":4,"lit":"쪽에서 나온 푸른빛이 쪽보다 더 푸름","fig":"제자나 후배가 스승·선배보다 나음","origin":"","source":"순자","example":"제자가 스승을 뛰어넘었으니 청출어람이다.","syn":[],"reviewed":true},
  {"id":"gs0065","hanja":"草綠同色","reading":"초록동색","len":4,"lit":"풀빛과 녹색은 같은 색","fig":"처지나 부류가 같은 사람끼리 어울림","origin":"","source":"","example":"끼리끼리 뭉치는 걸 보니 초록동색이다.","syn":["類類相從"],"reviewed":true},
  {"id":"gs0066","hanja":"寸鐵殺人","reading":"촌철살인","len":4,"lit":"한 치의 쇠로 사람을 죽임","fig":"짧은 한마디로 핵심을 찔러 감동·교훈을 줌","origin":"","source":"","example":"그의 한마디는 촌철살인이었다.","syn":[],"reviewed":true},
  {"id":"gs0067","hanja":"七顚八起","reading":"칠전팔기","len":4,"lit":"일곱 번 넘어져도 여덟 번 일어남","fig":"실패를 거듭해도 굴하지 않고 다시 일어남","origin":"","source":"","example":"칠전팔기 끝에 마침내 창업에 성공했다.","syn":["百折不屈"],"reviewed":true},
  {"id":"gs0068","hanja":"兎死狗烹","reading":"토사구팽","len":4,"lit":"토끼가 죽으면 사냥개를 삶음","fig":"쓸모가 다하면 가차 없이 버려짐","origin":"한신이 공을 세운 뒤 토사구팽을 탄식한 고사","source":"사기","example":"쓸모가 없어지자 토사구팽 당했다.","syn":["甘呑苦吐"],"reviewed":true},
  {"id":"gs0069","hanja":"破竹之勢","reading":"파죽지세","len":4,"lit":"대나무를 쪼개는 기세","fig":"막을 수 없을 만큼 거침없이 나아가는 기세","origin":"","source":"진서","example":"우리 팀은 파죽지세로 결승에 올랐다.","syn":[],"reviewed":true},
  {"id":"gs0070","hanja":"風前燈火","reading":"풍전등화","len":4,"lit":"바람 앞의 등불","fig":"매우 위태로워 곧 사라질 듯한 처지","origin":"","source":"","example":"회사의 운명은 풍전등화 같았다.","syn":["累卵之危"],"reviewed":true},
  {"id":"gs0071","hanja":"鶴首苦待","reading":"학수고대","len":4,"lit":"학처럼 목을 빼고 기다림","fig":"몹시 애타게 기다림","origin":"","source":"","example":"합격 발표를 학수고대하고 있다.","syn":["一日如三秋"],"reviewed":true},
  {"id":"gs0072","hanja":"螢雪之功","reading":"형설지공","len":4,"lit":"반딧불과 눈빛으로 이룬 공","fig":"온갖 고생을 하며 부지런히 공부한 보람","origin":"차윤은 반딧불로, 손강은 눈빛으로 글을 읽었다는 고사","source":"진서","example":"형설지공으로 어려운 시험을 통과했다.","syn":[],"reviewed":true},
  {"id":"gs0073","hanja":"浩然之氣","reading":"호연지기","len":4,"lit":"넓고 큰 기운","fig":"거침없이 떳떳하고 도덕적인 기상","origin":"","source":"맹자","example":"산에 올라 호연지기를 길렀다.","syn":[],"reviewed":true},
  {"id":"gs0074","hanja":"畵龍點睛","reading":"화룡점정","len":4,"lit":"용을 그리고 마지막에 눈동자를 찍음","fig":"가장 중요한 부분을 마무리해 일을 완성함","origin":"장승요가 용의 눈동자를 찍자 용이 날아올랐다는 고사","source":"역대명화기","example":"마지막 연설이 행사의 화룡점정이었다.","syn":[],"reviewed":true},
  {"id":"gs0075","hanja":"換骨奪胎","reading":"환골탈태","len":4,"lit":"뼈를 바꾸고 태를 빼앗음","fig":"사람이나 사물이 완전히 새롭게 변함","origin":"","source":"","example":"리모델링 후 가게가 환골탈태했다.","syn":[],"reviewed":true},
  {"id":"gs0076","hanja":"興盡悲來","reading":"흥진비래","len":4,"lit":"즐거움이 다하면 슬픔이 옴","fig":"세상일은 돌고 돌아 기쁨과 슬픔이 갈마듦","origin":"","source":"","example":"흥진비래라더니 좋은 일 뒤에 시련이 왔다.","syn":["苦盡甘來"],"reviewed":true},
  {"id":"gs0077","hanja":"愚公移山","reading":"우공이산","len":4,"lit":"우공이 산을 옮김","fig":"어떤 일이든 끊임없이 노력하면 결국 이룸","origin":"우공이라는 노인이 집을 가로막은 산을 자손 대대로 파내겠다고 하자 하늘이 감복해 산을 옮겨 주었다는 이야기","source":"열자","example":"느려도 우공이산이라고, 매일 조금씩 하다 보면 끝이 보인다.","syn":["磨斧作針"],"reviewed":true},
  {"id":"gs0078","hanja":"勸善懲惡","reading":"권선징악","len":4,"lit":"착함을 권하고 악함을 징계함","fig":"선을 권장하고 악을 벌함","origin":"","source":"","example":"옛이야기는 대개 권선징악으로 끝난다.","syn":[],"reviewed":true},
  {"id":"gs0079","hanja":"因果應報","reading":"인과응보","len":4,"lit":"원인과 결과가 서로 응해 갚음","fig":"좋고 나쁜 행동에는 반드시 그에 맞는 결과가 따름","origin":"","source":"","example":"남을 속이더니 결국 자기가 당하는 인과응보였다.","syn":["自業自得","事必歸正"],"reviewed":true},
  {"id":"gs0080","hanja":"自業自得","reading":"자업자득","len":4,"lit":"자기가 한 일의 결과를 자기가 받음","fig":"자신이 저지른 일의 결과를 스스로 떠안음","origin":"","source":"","example":"공부 안 하고 놀더니 낙제한 건 자업자득이다.","syn":["因果應報","自繩自縛"],"reviewed":true},
  {"id":"gs0081","hanja":"易地思之","reading":"역지사지","len":4,"lit":"처지를 바꾸어 생각함","fig":"상대의 입장에서 헤아려 봄","origin":"","source":"맹자","example":"싸우기 전에 역지사지로 한 번 생각해 보자.","syn":[],"reviewed":true},
  {"id":"gs0082","hanja":"類類相從","reading":"유유상종","len":4,"lit":"같은 무리끼리 서로 좇음","fig":"비슷한 사람끼리 어울림","origin":"","source":"","example":"유유상종이라더니 취미 같은 사람끼리 모였다.","syn":["草綠同色"],"reviewed":true},
  {"id":"gs0083","hanja":"結者解之","reading":"결자해지","len":4,"lit":"묶은 자가 풀어야 함","fig":"일을 저지른 사람이 그 일을 해결해야 함","origin":"","source":"","example":"네가 시작한 일이니 결자해지로 마무리해라.","syn":[],"reviewed":true},
  {"id":"gs0084","hanja":"見物生心","reading":"견물생심","len":4,"lit":"물건을 보면 마음이 생김","fig":"좋은 것을 보면 가지고 싶은 욕심이 생김","origin":"","source":"","example":"견물생심이라고, 진열장을 보니 자꾸 사고 싶어진다.","syn":[],"reviewed":true},
  {"id":"gs0085","hanja":"事必歸正","reading":"사필귀정","len":4,"lit":"일은 반드시 바른 데로 돌아감","fig":"모든 일은 결국 옳은 이치대로 풀림","origin":"","source":"","example":"억울했지만 사필귀정으로 진실이 밝혀졌다.","syn":["因果應報"],"reviewed":true},
  {"id":"gs0086","hanja":"作心三日","reading":"작심삼일","len":4,"lit":"먹은 마음이 사흘을 감","fig":"결심이 오래가지 못함","origin":"","source":"","example":"새해 운동 결심은 늘 작심삼일로 끝난다.","syn":[],"reviewed":true},
  {"id":"gs0087","hanja":"天高馬肥","reading":"천고마비","len":4,"lit":"하늘은 높고 말은 살찜","fig":"가을이 좋은 계절임을 이르는 말","origin":"옛 중국에서 가을이면 북방 말이 살쪄 침입을 경계한 데서 비롯했다고 전함","source":"","example":"천고마비의 계절, 독서하기 딱 좋다.","syn":[],"reviewed":true},
  {"id":"gs0088","hanja":"改過遷善","reading":"개과천선","len":4,"lit":"잘못을 고치고 착함으로 옮김","fig":"지난 잘못을 뉘우치고 바르게 됨","origin":"젊은 날 방탕하던 진나라 주처가 잘못을 깨닫고 학문에 힘써 훌륭한 사람이 되었다는 이야기에서 비롯","source":"진서","example":"그는 개과천선해서 봉사하며 산다.","syn":[],"reviewed":true},
  {"id":"gs0089","hanja":"殺身成仁","reading":"살신성인","len":4,"lit":"몸을 죽여 인을 이룸","fig":"옳은 일을 위해 자기 목숨을 바침","origin":"공자가 뜻있는 선비는 살기를 구해 인을 해치지 않고 몸을 바쳐 인을 이룬다고 한 말에서 비롯","source":"논어","example":"그 소방관은 살신성인의 정신으로 사람을 구했다.","syn":[],"reviewed":true},
  {"id":"gs0090","hanja":"三顧草廬","reading":"삼고초려","len":4,"lit":"초가집을 세 번 찾아감","fig":"인재를 맞으려고 정성껏 거듭 찾아감","origin":"유비가 제갈량을 모시려고 그의 초가를 세 번이나 찾아갔다는 이야기","source":"출사표","example":"회사는 삼고초려 끝에 그 전문가를 영입했다.","syn":[],"reviewed":true},
  {"id":"gs0091","hanja":"一石二鳥","reading":"일석이조","len":4,"lit":"돌 하나로 새 두 마리를 잡음","fig":"한 가지 일로 두 가지 이익을 얻음","origin":"","source":"","example":"걸어서 출근하니 운동도 되고 돈도 아껴 일석이조다.","syn":["一擧兩得"],"reviewed":true},
  {"id":"gs0092","hanja":"十匙一飯","reading":"십시일반","len":4,"lit":"열 술이 한 그릇 밥이 됨","fig":"여럿이 조금씩 도우면 한 사람을 돕기 쉬움","origin":"","source":"","example":"십시일반으로 모은 성금이 큰 힘이 되었다.","syn":[],"reviewed":true},
  {"id":"gs0093","hanja":"十中八九","reading":"십중팔구","len":4,"lit":"열 가운데 여덟이나 아홉","fig":"거의 대부분, 거의 틀림없이","origin":"","source":"","example":"이렇게 흐리면 십중팔구 비가 온다.","syn":[],"reviewed":true},
  {"id":"gs0094","hanja":"錦衣還鄕","reading":"금의환향","len":4,"lit":"비단옷 입고 고향에 돌아옴","fig":"성공하여 고향에 떳떳이 돌아옴","origin":"출세하면 고향으로 돌아가야 한다며 항우가 한 말에서 비롯했다고 전함","source":"사기","example":"그는 금의환향해서 고향에 학교를 지었다.","syn":[],"reviewed":true},
  {"id":"gs0095","hanja":"糟糠之妻","reading":"조강지처","len":4,"lit":"지게미와 쌀겨를 함께 먹은 아내","fig":"가난할 때 고생을 함께한 본처","origin":"후한의 송홍이 가난할 때 함께 고생한 아내는 버릴 수 없다고 한 말에서 비롯","source":"후한서","example":"성공해도 조강지처를 잊으면 안 된다.","syn":[],"reviewed":true},
  {"id":"gs0096","hanja":"同床異夢","reading":"동상이몽","len":4,"lit":"같은 자리에서 다른 꿈을 꿈","fig":"겉으로 함께하나 속으로는 서로 다른 생각을 함","origin":"","source":"","example":"협력하는 척했지만 둘은 동상이몽이었다.","syn":[],"reviewed":true},
  {"id":"gs0097","hanja":"山戰水戰","reading":"산전수전","len":4,"lit":"산에서 싸우고 물에서 싸움","fig":"세상의 온갖 고생과 어려움을 다 겪음","origin":"","source":"","example":"산전수전 다 겪은 사장님이라 위기에도 침착했다.","syn":[],"reviewed":true},
  {"id":"gs0098","hanja":"靑天霹靂","reading":"청천벽력","len":4,"lit":"맑은 하늘에 날벼락","fig":"뜻밖에 갑자기 일어난 큰 변고","origin":"","source":"","example":"시험 취소 소식은 그야말로 청천벽력이었다.","syn":[],"reviewed":true},
  {"id":"gs0099","hanja":"一片丹心","reading":"일편단심","len":4,"lit":"한 조각 붉은 마음","fig":"변치 않는 한결같은 마음","origin":"","source":"","example":"그는 첫사랑을 일편단심으로 기다렸다.","syn":[],"reviewed":true},
  {"id":"gs0100","hanja":"臨機應變","reading":"임기응변","len":4,"lit":"그때그때 형편에 맞게 대응함","fig":"상황에 따라 알맞게 그 자리에서 대처함","origin":"","source":"","example":"돌발 질문에도 임기응변으로 잘 넘겼다.","syn":[],"reviewed":true},
  {"id":"gs0101","hanja":"漸入佳境","reading":"점입가경","len":4,"lit":"점점 아름다운 경지로 들어감","fig":"갈수록 흥미롭거나, 반어적으로 꼴이 더해 감","origin":"화가 고개지가 사탕수수를 끝에서부터 먹으며 점점 단맛이 나는 경지로 들어간다고 한 데서 비롯","source":"진서","example":"이야기가 점입가경이라 눈을 뗄 수 없었다.","syn":[],"reviewed":true},
  {"id":"gs0102","hanja":"莫上莫下","reading":"막상막하","len":4,"lit":"위도 없고 아래도 없음","fig":"실력 차이가 거의 없어 우열을 가리기 어려움","origin":"","source":"","example":"두 팀의 실력이 막상막하여서 끝까지 손에 땀을 쥐었다.","syn":["難兄難弟"],"reviewed":true},
  {"id":"gs0103","hanja":"大同小異","reading":"대동소이","len":4,"lit":"크게는 같고 작게만 다름","fig":"거의 비슷하고 큰 차이가 없음","origin":"","source":"장자","example":"후보들 공약이 대동소이해서 고르기 어렵다.","syn":[],"reviewed":true},
  {"id":"gs0104","hanja":"東奔西走","reading":"동분서주","len":4,"lit":"동으로 뛰고 서로 달림","fig":"이리저리 매우 바쁘게 돌아다님","origin":"","source":"","example":"행사 준비로 하루 종일 동분서주했다.","syn":[],"reviewed":true},
  {"id":"gs0105","hanja":"日就月將","reading":"일취월장","len":4,"lit":"날로 나아가고 달로 발전함","fig":"실력이 빠르게 늘어 감","origin":"","source":"시경","example":"꾸준히 연습하더니 실력이 일취월장했다.","syn":[],"reviewed":true},
  {"id":"gs0106","hanja":"眼下無人","reading":"안하무인","len":4,"lit":"눈 아래에 사람이 없음","fig":"잘난 체하며 남을 업신여김","origin":"","source":"","example":"상을 받더니 안하무인으로 굴어 친구들이 떠났다.","syn":["傍若無人"],"reviewed":true},
  {"id":"gs0107","hanja":"厚顔無恥","reading":"후안무치","len":4,"lit":"낯이 두껍고 부끄러움이 없음","fig":"뻔뻔스러워 부끄러운 줄 모름","origin":"","source":"","example":"잘못을 해 놓고도 큰소리치다니 후안무치하다.","syn":[],"reviewed":true},
  {"id":"gs0108","hanja":"狐假虎威","reading":"호가호위","len":4,"lit":"여우가 호랑이의 위세를 빌림","fig":"남의 권세를 빌려 위세를 부림","origin":"여우가 호랑이를 앞세워 걸으며 짐승들이 자기를 보고 달아난다고 속인 이야기에서 비롯","source":"전국책","example":"사장 친척이라며 호가호위하는 그가 얄밉다.","syn":[],"reviewed":true},
  {"id":"gs0109","hanja":"羊頭狗肉","reading":"양두구육","len":4,"lit":"양 머리를 걸고 개고기를 팖","fig":"겉은 그럴듯하나 속은 변변치 못함","origin":"가게 앞엔 양 머리를 걸어 두고 실제로는 개고기를 판다는 데서 비롯","source":"","example":"광고와 딴판인 양두구육 상품에 속았다.","syn":["表裏不同"],"reviewed":true},
  {"id":"gs0110","hanja":"他山之石","reading":"타산지석","len":4,"lit":"다른 산의 돌","fig":"남의 허물이나 실수도 자기를 갈고닦는 데 도움이 됨","origin":"다른 산의 거친 돌이라도 자기 옥을 가는 데 쓸 수 있다는 데서 비롯","source":"시경","example":"그의 실패를 타산지석으로 삼아 같은 실수를 피하자.","syn":[],"reviewed":true},
  {"id":"gs0111","hanja":"犬猿之間","reading":"견원지간","len":4,"lit":"개와 원숭이 사이","fig":"서로 사이가 매우 나쁜 관계","origin":"","source":"","example":"두 사람은 견원지간이라 한자리에 두면 안 된다.","syn":[],"reviewed":true},
  {"id":"gs0112","hanja":"難兄難弟","reading":"난형난제","len":4,"lit":"형이라 하기도 아우라 하기도 어려움","fig":"둘이 비슷해 우열을 가리기 어려움","origin":"","source":"세설신어","example":"두 작품 모두 뛰어나 난형난제다.","syn":["莫上莫下"],"reviewed":true},
  {"id":"gs0113","hanja":"甘言利說","reading":"감언이설","len":4,"lit":"달콤한 말과 이로운 말","fig":"남을 꾀려고 비위를 맞추는 달콤한 말","origin":"","source":"","example":"감언이설에 속아 큰돈을 잃었다.","syn":["巧言令色"],"reviewed":true},
  {"id":"gs0114","hanja":"巧言令色","reading":"교언영색","len":4,"lit":"교묘한 말과 꾸민 얼굴빛","fig":"남의 환심을 사려고 말을 꾸미고 표정을 지음","origin":"공자가 교언영색하는 자 중에 어진 이가 드물다고 한 말에서 비롯","source":"논어","example":"교언영색하는 사람보다 묵묵한 사람이 믿음직하다.","syn":["甘言利說"],"reviewed":true},
  {"id":"gs0115","hanja":"語不成說","reading":"어불성설","len":4,"lit":"말이 말을 이루지 못함","fig":"말이 조금도 사리에 맞지 않음","origin":"","source":"","example":"준비도 안 하고 일등 하겠다니 어불성설이다.","syn":[],"reviewed":true},
  {"id":"gs0116","hanja":"橫說竪說","reading":"횡설수설","len":4,"lit":"가로로 말하고 세로로 말함","fig":"조리 없이 이러쿵저러쿵 마구 지껄임","origin":"","source":"","example":"긴장했는지 횡설수설하다 발표를 망쳤다.","syn":[],"reviewed":true},
  {"id":"gs0117","hanja":"自暴自棄","reading":"자포자기","len":4,"lit":"스스로 해치고 스스로 버림","fig":"절망에 빠져 자신을 돌보지 않고 마구 행동함","origin":"","source":"맹자","example":"한 번 실패했다고 자포자기하면 안 된다.","syn":[],"reviewed":true},
  {"id":"gs0118","hanja":"適材適所","reading":"적재적소","len":4,"lit":"알맞은 인재를 알맞은 자리에","fig":"능력에 맞는 자리에 알맞게 씀","origin":"","source":"","example":"적재적소에 사람을 배치하니 일이 잘 돌아간다.","syn":[],"reviewed":true},
  {"id":"gs0119","hanja":"九死一生","reading":"구사일생","len":4,"lit":"아홉 번 죽을 뻔하다 한 번 살아남","fig":"여러 차례 죽을 고비를 넘기고 겨우 살아남","origin":"","source":"","example":"사고에서 구사일생으로 살아났다.","syn":["起死回生"],"reviewed":true},
  {"id":"gs0120","hanja":"起死回生","reading":"기사회생","len":4,"lit":"죽을 사람을 살려 일으킴","fig":"거의 죽을 지경에서 다시 살아남","origin":"","source":"","example":"역전골로 팀이 기사회생했다.","syn":["九死一生"],"reviewed":true},
  {"id":"gs0121","hanja":"九牛一毛","reading":"구우일모","len":4,"lit":"아홉 마리 소 가운데 털 하나","fig":"매우 많은 것 가운데 극히 적은 부분","origin":"사마천이 자신의 처지를 아홉 마리 소 가운데 털 한 올에 빗댄 데서 비롯","source":"","example":"그 돈은 회사 예산에선 구우일모에 불과하다.","syn":[],"reviewed":true},
  {"id":"gs0122","hanja":"氣高萬丈","reading":"기고만장","len":4,"lit":"기세가 만 길이나 높음","fig":"일이 뜻대로 되어 기세가 대단하거나 잔뜩 우쭐함","origin":"","source":"","example":"한 번 이기더니 기고만장해서 큰소리친다.","syn":[],"reviewed":true},
  {"id":"gs0123","hanja":"勞心焦思","reading":"노심초사","len":4,"lit":"마음을 수고롭게 하고 애를 태움","fig":"몹시 마음을 쓰며 애를 태움","origin":"","source":"","example":"합격자 발표를 기다리며 노심초사했다.","syn":[],"reviewed":true},
  {"id":"gs0124","hanja":"切齒腐心","reading":"절치부심","len":4,"lit":"이를 갈고 마음을 썩임","fig":"몹시 분하여 이를 갈며 속을 썩임","origin":"","source":"","example":"그는 패배를 절치부심하며 다음을 준비했다.","syn":[],"reviewed":true},
  {"id":"gs0125","hanja":"捲土重來","reading":"권토중래","len":4,"lit":"흙먼지를 일으키며 다시 옴","fig":"한 번 실패한 사람이 힘을 길러 다시 도전함","origin":"싸움에 진 항우가 강동으로 돌아가 힘을 길렀다면 다시 일어설 수 있었으리라 읊은 시구에서 비롯","source":"","example":"이번엔 졌지만 권토중래를 노린다.","syn":[],"reviewed":true},
  {"id":"gs0126","hanja":"晩時之歎","reading":"만시지탄","len":4,"lit":"때늦은 한탄","fig":"기회를 놓치고 뒤늦게 한탄함","origin":"","source":"","example":"미리 준비할걸, 만시지탄이 따로 없다.","syn":[],"reviewed":true},
  {"id":"gs0127","hanja":"苦肉之策","reading":"고육지책","len":4,"lit":"제 몸을 상해 가며 꾸민 계책","fig":"어려운 처지를 벗어나려고 어쩔 수 없이 쓰는 방책","origin":"자기 몸을 상하게 해서까지 적을 속이는 계책에서 비롯","source":"","example":"빚을 갚으려 집을 판 건 고육지책이었다.","syn":[],"reviewed":true},
  {"id":"gs0128","hanja":"孤立無援","reading":"고립무원","len":4,"lit":"외따로 떨어져 도움이 없음","fig":"홀로 떨어져 도움받을 데가 없음","origin":"","source":"","example":"지원이 끊겨 고립무원에 빠졌다.","syn":["四面楚歌"],"reviewed":true},
  {"id":"gs0129","hanja":"孤軍奮鬪","reading":"고군분투","len":4,"lit":"외로운 군대가 힘껏 싸움","fig":"적은 힘으로 도움 없이 힘껏 노력함","origin":"","source":"","example":"혼자 고군분투해서 프로젝트를 끝냈다.","syn":[],"reviewed":true},
  {"id":"gs0130","hanja":"刻骨難忘","reading":"각골난망","len":4,"lit":"뼈에 새겨 잊기 어려움","fig":"입은 은혜가 뼈에 사무쳐 잊히지 않음","origin":"","source":"","example":"베풀어 주신 은혜 각골난망입니다.","syn":["白骨難忘","結草報恩"],"reviewed":true},
  {"id":"gs0131","hanja":"白骨難忘","reading":"백골난망","len":4,"lit":"백골이 되어도 잊기 어려움","fig":"죽어서도 잊지 못할 큰 은혜","origin":"","source":"","example":"도와주신 은혜는 백골난망이에요.","syn":["刻骨難忘","結草報恩"],"reviewed":true},
  {"id":"gs0132","hanja":"百戰百勝","reading":"백전백승","len":4,"lit":"백 번 싸워 백 번 이김","fig":"싸울 때마다 모두 이김","origin":"적을 알고 나를 알면 백 번 싸워도 위태롭지 않다고 한 병법의 가르침과 통함","source":"손자병법","example":"준비를 철저히 하면 백전백승이다.","syn":[],"reviewed":true},
  {"id":"gs0133","hanja":"百折不屈","reading":"백절불굴","len":4,"lit":"백 번 꺾여도 굽히지 않음","fig":"어떤 어려움에도 굽히지 않음","origin":"","source":"","example":"백절불굴의 의지로 끝내 성공했다.","syn":["七顚八起"],"reviewed":true},
  {"id":"gs0134","hanja":"父傳子傳","reading":"부전자전","len":4,"lit":"아버지가 전하고 아들이 전함","fig":"대대로 아버지에서 아들로 이어짐","origin":"","source":"","example":"음악 재능은 부전자전인가 보다.","syn":[],"reviewed":true},
  {"id":"gs0135","hanja":"粉骨碎身","reading":"분골쇄신","len":4,"lit":"뼈가 가루가 되고 몸이 부서짐","fig":"있는 힘을 다해 노력함","origin":"","source":"","example":"분골쇄신 노력해 회사를 일으켰다.","syn":[],"reviewed":true},
  {"id":"gs0136","hanja":"非一非再","reading":"비일비재","len":4,"lit":"한 번도 두 번도 아님","fig":"같은 일이 한두 번이 아니고 매우 잦음","origin":"","source":"","example":"이런 실수가 비일비재해 신뢰를 잃었다.","syn":[],"reviewed":true},
  {"id":"gs0137","hanja":"名實相符","reading":"명실상부","len":4,"lit":"이름과 실상이 서로 맞음","fig":"알려진 것과 실제가 일치함","origin":"","source":"","example":"그는 명실상부한 이 분야 일인자다.","syn":[],"reviewed":true},
  {"id":"gs0138","hanja":"有名無實","reading":"유명무실","len":4,"lit":"이름만 있고 실속이 없음","fig":"겉으로는 그럴듯하나 실제 내용이 없음","origin":"","source":"","example":"규정이 유명무실해 아무도 지키지 않는다.","syn":[],"reviewed":true},
  {"id":"gs0139","hanja":"有口無言","reading":"유구무언","len":4,"lit":"입은 있어도 할 말이 없음","fig":"잘못이 분명해 변명할 말이 없음","origin":"","source":"","example":"내 실수가 맞으니 유구무언입니다.","syn":[],"reviewed":true},
  {"id":"gs0140","hanja":"異口同聲","reading":"이구동성","len":4,"lit":"다른 입에서 같은 소리","fig":"여러 사람의 말이 한결같음","origin":"","source":"","example":"모두 이구동성으로 그를 칭찬했다.","syn":[],"reviewed":true},
  {"id":"gs0141","hanja":"人山人海","reading":"인산인해","len":4,"lit":"사람이 산을 이루고 바다를 이룸","fig":"헤아릴 수 없이 많은 사람이 모임","origin":"","source":"","example":"축제장은 인산인해를 이루었다.","syn":[],"reviewed":true},
  {"id":"gs0142","hanja":"一瀉千里","reading":"일사천리","len":4,"lit":"물이 쏟아져 천 리를 흐름","fig":"일이 거침없이 빨리 진행됨","origin":"","source":"","example":"회의가 일사천리로 끝났다.","syn":[],"reviewed":true},
  {"id":"gs0143","hanja":"一言之下","reading":"일언지하","len":4,"lit":"한마디 말 아래","fig":"두말할 것 없이 한마디로 잘라","origin":"","source":"","example":"제안은 일언지하에 거절당했다.","syn":[],"reviewed":true},
  {"id":"gs0144","hanja":"一絲不亂","reading":"일사불란","len":4,"lit":"한 올 실도 흐트러지지 않음","fig":"질서가 정연해 조금도 어지럽지 않음","origin":"","source":"","example":"선수들이 일사불란하게 움직였다.","syn":[],"reviewed":true},
  {"id":"gs0145","hanja":"一目瞭然","reading":"일목요연","len":4,"lit":"한 번 보아 환히 밝음","fig":"한눈에 환히 알 수 있을 만큼 분명함","origin":"","source":"","example":"표로 정리하니 일목요연하다.","syn":[],"reviewed":true},
  {"id":"gs0146","hanja":"一脈相通","reading":"일맥상통","len":4,"lit":"한 줄기로 서로 통함","fig":"생각이나 상태가 서로 통하는 데가 있음","origin":"","source":"","example":"두 이론은 일맥상통하는 면이 있다.","syn":[],"reviewed":true},
  {"id":"gs0147","hanja":"自初至終","reading":"자초지종","len":4,"lit":"처음부터 끝까지","fig":"일의 처음부터 끝까지의 모든 과정","origin":"","source":"","example":"자초지종을 차근차근 설명했다.","syn":[],"reviewed":true},
  {"id":"gs0148","hanja":"去頭截尾","reading":"거두절미","len":4,"lit":"머리를 떼고 꼬리를 자름","fig":"군더더기를 빼고 핵심만 말함","origin":"","source":"","example":"거두절미하고 본론부터 말하겠다.","syn":[],"reviewed":true},
  {"id":"gs0149","hanja":"單刀直入","reading":"단도직입","len":4,"lit":"한 자루 칼로 곧장 쳐들어감","fig":"여러 말 없이 곧바로 핵심을 말함","origin":"","source":"","example":"단도직입으로 묻겠다, 할 거냐 말 거냐.","syn":[],"reviewed":true},
  {"id":"gs0150","hanja":"牽強附會","reading":"견강부회","len":4,"lit":"억지로 끌어다 갖다 붙임","fig":"말을 억지로 자기에게 유리하게 끌어 맞춤","origin":"","source":"","example":"근거도 없이 견강부회로 우긴다.","syn":[],"reviewed":true},
  {"id":"gs0151","hanja":"甲論乙駁","reading":"갑론을박","len":4,"lit":"갑이 논하면 을이 반박함","fig":"서로 자기 주장을 내세우며 논박함","origin":"","source":"","example":"안건을 두고 갑론을박이 벌어졌다.","syn":[],"reviewed":true},
  {"id":"gs0152","hanja":"輕擧妄動","reading":"경거망동","len":4,"lit":"가볍게 행동하고 망령되이 움직임","fig":"깊이 생각 없이 경솔하게 행동함","origin":"","source":"","example":"흥분해서 경거망동하지 말고 침착해라.","syn":[],"reviewed":true},
  {"id":"gs0153","hanja":"誇大妄想","reading":"과대망상","len":4,"lit":"사실보다 부풀려 망령되이 생각함","fig":"자신을 실제보다 크게 평가하는 헛된 생각","origin":"","source":"","example":"근거 없는 자신감은 과대망상일 뿐이다.","syn":[],"reviewed":true},
  {"id":"gs0154","hanja":"權謀術數","reading":"권모술수","len":4,"lit":"권세를 위한 꾀와 술수","fig":"목적을 위해 수단을 가리지 않는 온갖 꾀","origin":"","source":"","example":"그는 권모술수에 능한 사람이다.","syn":[],"reviewed":true},
  {"id":"gs0155","hanja":"群雄割據","reading":"군웅할거","len":4,"lit":"여러 영웅이 땅을 나눠 차지함","fig":"여러 세력이 각지에서 맞서 세력을 떨침","origin":"","source":"","example":"초창기 시장은 군웅할거의 양상이었다.","syn":[],"reviewed":true},
  {"id":"gs0156","hanja":"今時初聞","reading":"금시초문","len":4,"lit":"지금 처음 들음","fig":"이제야 비로소 처음 들음","origin":"","source":"","example":"그 소식은 금시초문인데?","syn":[],"reviewed":true},
  {"id":"gs0157","hanja":"美辭麗句","reading":"미사여구","len":4,"lit":"아름다운 말과 고운 글귀","fig":"듣기 좋게 꾸민 말과 글귀","origin":"","source":"","example":"미사여구만 늘어놓지 말고 핵심을 말해라.","syn":[],"reviewed":true},
  {"id":"gs0158","hanja":"博學多識","reading":"박학다식","len":4,"lit":"널리 배우고 아는 것이 많음","fig":"학식이 넓고 아는 것이 많음","origin":"","source":"","example":"그는 박학다식해서 모르는 게 없다.","syn":[],"reviewed":true},
  {"id":"gs0159","hanja":"半信半疑","reading":"반신반의","len":4,"lit":"반은 믿고 반은 의심함","fig":"믿으면서도 한편으로는 의심함","origin":"","source":"","example":"그 소문을 반신반의하며 들었다.","syn":[],"reviewed":true},
  {"id":"gs0160","hanja":"無用之物","reading":"무용지물","len":4,"lit":"쓸데없는 물건","fig":"아무 쓸모가 없는 물건이나 사람","origin":"","source":"","example":"고장 나서 무용지물이 된 기계.","syn":[],"reviewed":true},
  {"id":"gs0161","hanja":"無爲徒食","reading":"무위도식","len":4,"lit":"하는 일 없이 헛되이 먹기만 함","fig":"일하지 않고 놀고먹음","origin":"","source":"","example":"젊어서 무위도식하면 늙어 고생한다.","syn":[],"reviewed":true},
  {"id":"gs0162","hanja":"門前成市","reading":"문전성시","len":4,"lit":"문 앞이 저자를 이룸","fig":"찾아오는 사람이 많아 문 앞이 붐빔","origin":"","source":"","example":"맛집으로 소문나 문전성시를 이룬다.","syn":[],"reviewed":true},
  {"id":"gs0163","hanja":"小貪大失","reading":"소탐대실","len":4,"lit":"작은 것을 탐하다 큰 것을 잃음","fig":"작은 이익을 욕심내다 큰 손해를 봄","origin":"","source":"","example":"할인에 혹해 충동구매하면 소탐대실이다.","syn":[],"reviewed":true},
  {"id":"gs0164","hanja":"束手無策","reading":"속수무책","len":4,"lit":"손이 묶인 듯 방책이 없음","fig":"어찌할 도리가 없어 꼼짝 못함","origin":"","source":"","example":"갑작스러운 정전에 속수무책이었다.","syn":[],"reviewed":true},
  {"id":"gs0165","hanja":"袖手傍觀","reading":"수수방관","len":4,"lit":"소매에 손을 넣고 곁에서 봄","fig":"직접 나서지 않고 그저 지켜보기만 함","origin":"","source":"","example":"위험에 빠진 사람을 수수방관할 수 없다.","syn":[],"reviewed":true},
  {"id":"gs0166","hanja":"信賞必罰","reading":"신상필벌","len":4,"lit":"상은 믿음 있게, 벌은 반드시","fig":"공이 있으면 반드시 상을 주고 죄가 있으면 반드시 벌함","origin":"","source":"한비자","example":"신상필벌이 분명해야 조직이 산다.","syn":[],"reviewed":true},
  {"id":"gs0167","hanja":"進退兩難","reading":"진퇴양난","len":4,"lit":"나아가기도 물러서기도 어려움","fig":"이러지도 저러지도 못하는 난처한 처지","origin":"","source":"","example":"양쪽 다 거절할 수 없어 진퇴양난이다.","syn":["四面楚歌"],"reviewed":true},
  {"id":"gs0168","hanja":"千辛萬苦","reading":"천신만고","len":4,"lit":"천 가지 매움과 만 가지 쓴 것","fig":"온갖 어려움과 고생","origin":"","source":"","example":"천신만고 끝에 정상에 올랐다.","syn":[],"reviewed":true},
  {"id":"gs0169","hanja":"千差萬別","reading":"천차만별","len":4,"lit":"천 가지 차이와 만 가지 구별","fig":"여러 가지가 서로 차이와 구별이 많음","origin":"","source":"","example":"사람마다 취향이 천차만별이다.","syn":[],"reviewed":true},
  {"id":"gs0170","hanja":"針小棒大","reading":"침소봉대","len":4,"lit":"바늘만 한 것을 몽둥이만 하다고 함","fig":"작은 일을 크게 부풀려 떠벌림","origin":"","source":"","example":"소문이 침소봉대되어 퍼졌다.","syn":[],"reviewed":true},
  {"id":"gs0171","hanja":"波瀾萬丈","reading":"파란만장","len":4,"lit":"물결이 만 길이나 높음","fig":"일의 진행에 변화와 곡절이 매우 심함","origin":"","source":"","example":"그의 삶은 파란만장한 한 편의 드라마 같았다.","syn":[],"reviewed":true},
  {"id":"gs0172","hanja":"表裏不同","reading":"표리부동","len":4,"lit":"겉과 속이 같지 않음","fig":"마음이 음흉해 겉과 속이 다름","origin":"","source":"","example":"표리부동한 사람은 믿기 어렵다.","syn":["羊頭狗肉"],"reviewed":true},
  {"id":"gs0173","hanja":"好事多魔","reading":"호사다마","len":4,"lit":"좋은 일에는 마가 많음","fig":"좋은 일에는 흔히 방해되는 일이 많음","origin":"","source":"","example":"호사다마라더니 잔치 날 비가 쏟아졌다.","syn":[],"reviewed":true},
  {"id":"gs0174","hanja":"畵中之餠","reading":"화중지병","len":4,"lit":"그림 속의 떡","fig":"보기만 좋을 뿐 차지할 수 없는 것","origin":"","source":"","example":"비싼 차는 내겐 화중지병일 뿐이다.","syn":[],"reviewed":true},
  {"id":"gs0175","hanja":"蛇足","reading":"사족","len":2,"lit":"뱀의 발","fig":"쓸데없이 덧붙인 군더더기","origin":"뱀을 먼저 그린 사람이 발까지 그려 넣다가 도리어 내기에서 졌다는 이야기에서 비롯","source":"전국책","example":"설명이 충분하니 사족은 빼자.","syn":[],"reviewed":true},
  {"id":"gs0176","hanja":"咸興差使","reading":"함흥차사","len":4,"lit":"함흥으로 보낸 심부름꾼","fig":"심부름을 가서 소식이 없거나 돌아오지 않는 사람","origin":"태조 이성계가 함흥에 머물 때 보낸 사신들이 돌아오지 못한 데서 비롯했다고 전함","source":"","example":"심부름 보냈더니 함흥차사다.","syn":[],"reviewed":true},
  {"id":"gs0177","hanja":"安貧樂道","reading":"안빈낙도","len":4,"lit":"가난을 편안히 여기며 도를 즐김","fig":"가난한 가운데서도 편안한 마음으로 분수를 지킴","origin":"","source":"","example":"그는 안빈낙도하며 글을 벗 삼아 산다.","syn":[],"reviewed":true},
  {"id":"gs0178","hanja":"靑雲之志","reading":"청운지지","len":4,"lit":"푸른 구름의 뜻","fig":"높은 이상이나 큰 포부","origin":"","source":"","example":"청운지지를 품고 도시로 올라왔다.","syn":[],"reviewed":true},
  {"id":"gs0179","hanja":"初志一貫","reading":"초지일관","len":4,"lit":"처음 뜻을 끝까지 밀고 감","fig":"처음 먹은 마음을 한결같이 지킴","origin":"","source":"","example":"초지일관 한 우물을 판 끝에 성공했다.","syn":[],"reviewed":true},
  {"id":"gs0180","hanja":"水魚之交","reading":"수어지교","len":4,"lit":"물과 물고기의 사귐","fig":"떼려야 뗄 수 없는 매우 친밀한 사이","origin":"유비가 제갈량과의 사이를 물과 물고기에 빗댄 데서 비롯","source":"삼국지","example":"두 사람은 수어지교처럼 가까웠다.","syn":["莫逆之友"],"reviewed":true},
  {"id":"gs0181","hanja":"百年偕老","reading":"백년해로","len":4,"lit":"백 년을 함께 늙음","fig":"부부가 화목하게 평생을 함께함","origin":"","source":"","example":"두 분 백년해로하시길 빕니다.","syn":[],"reviewed":true},
  {"id":"gs0182","hanja":"說往說來","reading":"설왕설래","len":4,"lit":"말이 오가고 옴","fig":"옳고 그름을 따지며 말을 주고받음","origin":"","source":"","example":"결론 없이 설왕설래만 길어졌다.","syn":["甲論乙駁"],"reviewed":true},
  {"id":"gs0183","hanja":"一刀兩斷","reading":"일도양단","len":4,"lit":"한 칼에 두 도막을 냄","fig":"머뭇거리지 않고 단번에 결단함","origin":"","source":"","example":"고민을 일도양단으로 끊고 결정했다.","syn":[],"reviewed":true},
  {"id":"gs0184","hanja":"天衣無縫","reading":"천의무봉","len":4,"lit":"하늘 옷에 꿰맨 자국이 없음","fig":"꾸밈없이 자연스럽고 완전무결함","origin":"선녀의 옷에는 바느질 자국이 없다는 이야기에서 비롯","source":"","example":"그의 문장은 천의무봉처럼 자연스럽다.","syn":[],"reviewed":true},
  {"id":"gs0185","hanja":"胡蝶之夢","reading":"호접지몽","len":4,"lit":"나비의 꿈","fig":"인생의 덧없음, 또는 나와 사물의 경계가 모호함","origin":"장자가 나비가 된 꿈을 꾸고 깨어 내가 나비인지 나비가 나인지 모르겠다고 한 데서 비롯","source":"장자","example":"지난 일이 호접지몽처럼 아득하다.","syn":[],"reviewed":true},
  {"id":"gs0186","hanja":"亡羊補牢","reading":"망양보뢰","len":4,"lit":"양을 잃고 우리를 고침","fig":"일이 잘못된 뒤에 늦게라도 대비함","origin":"","source":"전국책","example":"사고 후에야 점검하니 망양보뢰인 셈이다.","syn":[],"reviewed":true},
  {"id":"gs0187","hanja":"良藥苦口","reading":"양약고구","len":4,"lit":"좋은 약은 입에 씀","fig":"바른 충고는 듣기 거북하지만 이로움","origin":"","source":"","example":"양약고구라니 쓴소리도 새겨듣자.","syn":[],"reviewed":true},
  {"id":"gs0188","hanja":"右往左往","reading":"우왕좌왕","len":4,"lit":"오른쪽으로 갔다 왼쪽으로 갔다 함","fig":"갈팡질팡하며 이리저리 헤맴","origin":"","source":"","example":"안내가 없어 사람들이 우왕좌왕했다.","syn":[],"reviewed":true},
  {"id":"gs0189","hanja":"東問西答","reading":"동문서답","len":4,"lit":"동쪽을 묻는데 서쪽을 답함","fig":"묻는 말에 엉뚱하게 대답함","origin":"","source":"","example":"질문과 상관없는 동문서답만 한다.","syn":[],"reviewed":true},
  {"id":"gs0190","hanja":"明若觀火","reading":"명약관화","len":4,"lit":"불을 보듯 분명함","fig":"더 볼 것 없이 매우 명백함","origin":"","source":"","example":"준비 없이 가면 실패할 게 명약관화하다.","syn":[],"reviewed":true},
  {"id":"gs0191","hanja":"武陵桃源","reading":"무릉도원","len":4,"lit":"무릉의 복숭아꽃 핀 곳","fig":"속세를 떠난 별천지, 이상향","origin":"한 어부가 복숭아꽃을 따라 들어간 골짜기에서 평화로운 마을을 만났다는 이야기에서 비롯","source":"","example":"한적한 시골이 무릉도원이 따로 없다.","syn":[],"reviewed":true},
  {"id":"gs0192","hanja":"百尺竿頭","reading":"백척간두","len":4,"lit":"백 자나 되는 장대 끝","fig":"몹시 위태롭고 어려운 지경","origin":"","source":"","example":"회사가 백척간두의 위기에 놓였다.","syn":["風前燈火","累卵之危"],"reviewed":true},
  {"id":"gs0193","hanja":"一攫千金","reading":"일확천금","len":4,"lit":"한 번에 천금을 움켜쥠","fig":"단번에 큰돈을 얻음","origin":"","source":"","example":"일확천금을 노리다 가진 것마저 잃었다.","syn":[],"reviewed":true},
  {"id":"gs0194","hanja":"莫逆之友","reading":"막역지우","len":4,"lit":"거스름이 없는 벗","fig":"허물없이 아주 친한 친구","origin":"","source":"장자","example":"그와는 어릴 적부터 막역지우다.","syn":["竹馬故友","水魚之交"],"reviewed":true},
  {"id":"gs0195","hanja":"見利思義","reading":"견리사의","len":4,"lit":"이익을 보면 의로움을 생각함","fig":"이익 앞에서 옳음을 먼저 헤아림","origin":"","source":"논어","example":"견리사의를 새겨 부정한 돈은 멀리한다.","syn":[],"reviewed":true},
  {"id":"gs0196","hanja":"天佑神助","reading":"천우신조","len":4,"lit":"하늘이 돕고 신이 도움","fig":"뜻밖에 큰 도움을 받아 어려움을 벗어남","origin":"","source":"","example":"천우신조로 사고를 면했다.","syn":[],"reviewed":true},
  {"id":"gs0197","hanja":"靑山流水","reading":"청산유수","len":4,"lit":"푸른 산에 흐르는 물","fig":"막힘없이 썩 잘하는 말을 비유","origin":"","source":"","example":"그는 청산유수로 발표를 이어 갔다.","syn":[],"reviewed":true},
  {"id":"gs0198","hanja":"同苦同樂","reading":"동고동락","len":4,"lit":"괴로움도 즐거움도 함께함","fig":"어려움과 즐거움을 함께 나눔","origin":"","source":"","example":"우리는 십 년을 동고동락한 동료다.","syn":[],"reviewed":true},
  {"id":"gs0199","hanja":"磨斧作針","reading":"마부작침","len":4,"lit":"도끼를 갈아 바늘을 만듦","fig":"아무리 어려운 일도 꾸준히 하면 이룸","origin":"이백이 도끼를 갈아 바늘을 만들겠다는 노파를 보고 학문에 정진했다는 이야기에서 비롯","source":"","example":"마부작침의 마음으로 매일 연습했다.","syn":["愚公移山"],"reviewed":true},
  {"id":"gs0200","hanja":"茫然自失","reading":"망연자실","len":4,"lit":"멍하니 정신을 잃음","fig":"어이없어 정신이 나간 듯 멍함","origin":"","source":"","example":"소식을 듣고 망연자실해 한참을 앉아 있었다.","syn":[],"reviewed":true},
  {"id":"gs0201","hanja":"傍若無人","reading":"방약무인","len":4,"lit":"곁에 사람이 없는 듯이","fig":"남을 의식하지 않고 제멋대로 행동함","origin":"","source":"","example":"방약무인하게 큰 소리로 떠들었다.","syn":["眼下無人"],"reviewed":true},
  {"id":"gs0202","hanja":"外柔內剛","reading":"외유내강","len":4,"lit":"겉은 부드럽고 속은 굳셈","fig":"겉보기에는 순하나 속은 강함","origin":"","source":"","example":"그녀는 외유내강이라 쉽게 흔들리지 않는다.","syn":[],"reviewed":true},
  {"id":"gs0203","hanja":"優柔不斷","reading":"우유부단","len":4,"lit":"부드럽기만 하고 끊지 못함","fig":"망설이기만 하고 결단을 내리지 못함","origin":"","source":"","example":"우유부단해서 메뉴 하나도 못 고른다.","syn":[],"reviewed":true},
  {"id":"gs0204","hanja":"威風堂堂","reading":"위풍당당","len":4,"lit":"위엄찬 기풍이 떳떳함","fig":"풍채나 기세가 위엄 있고 당당함","origin":"","source":"","example":"선수들이 위풍당당하게 입장했다.","syn":[],"reviewed":true},
  {"id":"gs0205","hanja":"悠悠自適","reading":"유유자적","len":4,"lit":"여유롭게 제 마음대로","fig":"속세에 얽매이지 않고 한가로이 지냄","origin":"","source":"","example":"은퇴 후 유유자적 시골 생활을 한다.","syn":["安貧樂道"],"reviewed":true},
  {"id":"gs0206","hanja":"人之常情","reading":"인지상정","len":4,"lit":"사람의 떳떳한 정","fig":"사람이라면 누구나 가지는 보통의 마음","origin":"","source":"","example":"자식 걱정은 인지상정이다.","syn":[],"reviewed":true},
  {"id":"gs0207","hanja":"一場春夢","reading":"일장춘몽","len":4,"lit":"한바탕의 봄꿈","fig":"헛된 영화나 덧없는 일","origin":"","source":"","example":"큰돈도 일장춘몽처럼 사라졌다.","syn":["胡蝶之夢"],"reviewed":true},
  {"id":"gs0208","hanja":"一觸卽發","reading":"일촉즉발","len":4,"lit":"한 번 닿으면 곧 터짐","fig":"조그만 자극에도 곧 터질 듯 위급함","origin":"","source":"","example":"양측이 일촉즉발의 긴장 상태다.","syn":["風前燈火"],"reviewed":true},
  {"id":"gs0209","hanja":"自手成家","reading":"자수성가","len":4,"lit":"제 손으로 집안을 이룸","fig":"물려받은 것 없이 스스로 재산을 모으고 성공함","origin":"","source":"","example":"맨손으로 시작해 자수성가했다.","syn":[],"reviewed":true},
  {"id":"gs0210","hanja":"自畵自讚","reading":"자화자찬","len":4,"lit":"제 그림을 스스로 칭찬함","fig":"자기가 한 일을 스스로 자랑함","origin":"","source":"","example":"자화자찬이지만 이번엔 정말 잘했다.","syn":[],"reviewed":true},
  {"id":"gs0211","hanja":"電光石火","reading":"전광석화","len":4,"lit":"번갯불과 부싯돌 불","fig":"몹시 짧은 순간이나 매우 빠른 동작","origin":"","source":"","example":"전광석화처럼 빠르게 처리했다.","syn":[],"reviewed":true},
  {"id":"gs0212","hanja":"絶體絶命","reading":"절체절명","len":4,"lit":"몸도 목숨도 다한 듯","fig":"빠져나갈 수 없는 절박한 지경","origin":"","source":"","example":"절체절명의 순간에 역전했다.","syn":["進退兩難"],"reviewed":true},
  {"id":"gs0213","hanja":"知彼知己","reading":"지피지기","len":4,"lit":"적을 알고 나를 앎","fig":"상대와 나의 형편을 모두 잘 앎","origin":"적을 알고 나를 알면 백 번 싸워도 위태롭지 않다는 병법에서 비롯","source":"손자병법","example":"지피지기면 백전백승이라 했다.","syn":["百戰百勝"],"reviewed":true},
  {"id":"gs0214","hanja":"八方美人","reading":"팔방미인","len":4,"lit":"여덟 방향에서 봐도 미인","fig":"여러 방면에 두루 능한 사람","origin":"","source":"","example":"그는 공부도 운동도 잘하는 팔방미인이다.","syn":[],"reviewed":true},
  {"id":"gs0215","hanja":"會者定離","reading":"회자정리","len":4,"lit":"만난 자는 반드시 헤어짐","fig":"만남에는 헤어짐이 정해져 있음","origin":"","source":"","example":"회자정리라지만 이별은 늘 아쉽다.","syn":[],"reviewed":true},
  {"id":"gs0216","hanja":"弱肉强食","reading":"약육강식","len":4,"lit":"약한 자의 고기를 강한 자가 먹음","fig":"약한 것이 강한 것에게 먹히는 경쟁 원리","origin":"","source":"","example":"약육강식의 치열한 경쟁 사회.","syn":[],"reviewed":true},
  {"id":"gs0217","hanja":"桃園結義","reading":"도원결의","len":4,"lit":"복숭아밭에서 의를 맺음","fig":"뜻이 맞는 사람끼리 의형제를 맺음","origin":"유비·관우·장비가 복숭아밭에서 의형제를 맺은 이야기에서 비롯","source":"삼국지","example":"셋은 도원결의하듯 의기투합했다.","syn":[],"reviewed":true},
  {"id":"gs0218","hanja":"杜門不出","reading":"두문불출","len":4,"lit":"문을 닫고 나가지 않음","fig":"집 안에만 틀어박혀 세상에 나가지 않음","origin":"","source":"","example":"시험을 앞두고 두문불출 공부만 했다.","syn":[],"reviewed":true},
  {"id":"gs0219","hanja":"名不虛傳","reading":"명불허전","len":4,"lit":"이름은 헛되이 전해지지 않음","fig":"명성이 괜히 난 것이 아님","origin":"","source":"","example":"맛집이라더니 명불허전이다.","syn":["名實相符"],"reviewed":true},
  {"id":"gs0220","hanja":"拍掌大笑","reading":"박장대소","len":4,"lit":"손뼉을 치며 크게 웃음","fig":"손뼉을 치면서 크게 웃음","origin":"","source":"","example":"그의 농담에 모두 박장대소했다.","syn":[],"reviewed":true},
  {"id":"gs0221","hanja":"反哺之孝","reading":"반포지효","len":4,"lit":"되먹이는 효도","fig":"자식이 자라 부모를 봉양하는 효성","origin":"까마귀가 자라서 늙은 어미에게 먹이를 물어다 먹인다는 데서 비롯","source":"","example":"반포지효로 부모님을 모셨다.","syn":["結草報恩"],"reviewed":true},
  {"id":"gs0222","hanja":"山海珍味","reading":"산해진미","len":4,"lit":"산과 바다의 진귀한 맛","fig":"온갖 귀한 재료로 차린 맛있는 음식","origin":"","source":"","example":"잔칫상에 산해진미가 가득했다.","syn":[],"reviewed":true},
  {"id":"gs0223","hanja":"森羅萬象","reading":"삼라만상","len":4,"lit":"늘어선 온갖 모습","fig":"우주에 존재하는 모든 것","origin":"","source":"","example":"삼라만상이 저마다 이치를 지닌다.","syn":[],"reviewed":true},
  {"id":"gs0224","hanja":"相扶相助","reading":"상부상조","len":4,"lit":"서로 붙들고 서로 도움","fig":"서로서로 도움","origin":"","source":"","example":"이웃끼리 상부상조하며 산다.","syn":[],"reviewed":true},
  {"id":"gs0225","hanja":"率先垂範","reading":"솔선수범","len":4,"lit":"앞장서 모범을 보임","fig":"남보다 앞장서서 본보기가 됨","origin":"","source":"","example":"리더가 솔선수범해야 따른다.","syn":[],"reviewed":true},
  {"id":"gs0226","hanja":"安分知足","reading":"안분지족","len":4,"lit":"분수를 지켜 만족할 줄 앎","fig":"제 분수에 만족하며 욕심내지 않음","origin":"","source":"","example":"안분지족하니 마음이 편하다.","syn":["安貧樂道"],"reviewed":true},
  {"id":"gs0227","hanja":"自強不息","reading":"자강불식","len":4,"lit":"스스로 힘써 쉬지 않음","fig":"스스로 강해지려고 끊임없이 노력함","origin":"","source":"주역","example":"자강불식의 자세로 매일 단련했다.","syn":[],"reviewed":true},
  {"id":"gs0228","hanja":"坐不安席","reading":"좌불안석","len":4,"lit":"앉아도 자리가 편치 않음","fig":"불안하거나 걱정되어 한자리에 가만히 못 있음","origin":"","source":"","example":"결과를 기다리며 좌불안석이었다.","syn":[],"reviewed":true},
  {"id":"gs0229","hanja":"晝耕夜讀","reading":"주경야독","len":4,"lit":"낮에는 밭 갈고 밤에는 글 읽음","fig":"어려운 형편에도 부지런히 일하며 공부함","origin":"","source":"","example":"주경야독으로 학업을 이어 갔다.","syn":["螢雪之功"],"reviewed":true},
  {"id":"gs0230","hanja":"衆口難防","reading":"중구난방","len":4,"lit":"여러 입을 막기 어려움","fig":"여럿이 마구 떠들어 막기 어려움","origin":"","source":"","example":"회의가 중구난방으로 흘렀다.","syn":[],"reviewed":true},
  {"id":"gs0231","hanja":"天下泰平","reading":"천하태평","len":4,"lit":"온 세상이 평안함","fig":"세상이 평안하거나 근심 없이 태평함","origin":"","source":"","example":"마감인데 혼자 천하태평이다.","syn":[],"reviewed":true},
  {"id":"gs0232","hanja":"風樹之嘆","reading":"풍수지탄","len":4,"lit":"바람 부는 나무의 한탄","fig":"부모에게 효도하려 하나 이미 돌아가셔서 못 하는 슬픔","origin":"나무는 고요하려 하나 바람이 그치지 않고, 자식이 효도하려 하나 부모가 기다려 주지 않는다는 데서 비롯","source":"","example":"풍수지탄, 살아 계실 때 잘하자.","syn":[],"reviewed":true},
  {"id":"gs0233","hanja":"好衣好食","reading":"호의호식","len":4,"lit":"좋은 옷과 좋은 음식","fig":"잘 입고 잘 먹으며 넉넉히 지냄","origin":"","source":"","example":"호의호식하며 부족함 없이 자랐다.","syn":[],"reviewed":true},
  {"id":"gs0234","hanja":"曲學阿世","reading":"곡학아세","len":4,"lit":"학문을 굽혀 세상에 아첨함","fig":"바른 학문을 굽혀 권력이나 세속에 영합함","origin":"","source":"사기","example":"곡학아세하지 말고 소신을 지켜라.","syn":[],"reviewed":true},
  {"id":"gs0235","hanja":"瓜田李下","reading":"과전이하","len":4,"lit":"오이밭과 자두나무 아래","fig":"의심받기 쉬운 행동은 피해야 함","origin":"오이밭에서 신을 고쳐 신지 말고 자두나무 아래서 갓을 고쳐 쓰지 말라는 데서 비롯","source":"","example":"과전이하라고, 오해 살 자리는 피하자.","syn":[],"reviewed":true},
  {"id":"gs0236","hanja":"矯角殺牛","reading":"교각살우","len":4,"lit":"뿔을 바로잡으려다 소를 죽임","fig":"작은 흠을 고치려다 도리어 일을 그르침","origin":"","source":"","example":"사소한 걸 고치려다 교각살우가 됐다.","syn":["小貪大失"],"reviewed":true},
  {"id":"gs0237","hanja":"肝膽相照","reading":"간담상조","len":4,"lit":"간과 쓸개를 서로 비춤","fig":"서로 마음을 터놓고 친하게 사귐","origin":"","source":"","example":"둘은 간담상조하는 막역한 사이다.","syn":["莫逆之友"],"reviewed":true},
  {"id":"gs0238","hanja":"感慨無量","reading":"감개무량","len":4,"lit":"느낌과 한탄이 헤아릴 수 없음","fig":"마음에 사무치는 느낌이 더없이 큼","origin":"","source":"","example":"졸업식에서 감개무량한 표정을 지었다.","syn":[],"reviewed":true},
  {"id":"gs0239","hanja":"甘呑苦吐","reading":"감탄고토","len":4,"lit":"달면 삼키고 쓰면 뱉음","fig":"제 비위에 맞으면 좋아하고 안 맞으면 싫어하는 이기적 태도","origin":"","source":"","example":"필요할 땐 찾고 아니면 외면하니 감탄고토다.","syn":[],"reviewed":true},
  {"id":"gs0240","hanja":"居安思危","reading":"거안사위","len":4,"lit":"편안할 때 위태로움을 생각함","fig":"평안할 때에도 위기에 대비함","origin":"","source":"춘추좌씨전","example":"거안사위라고, 잘될 때 더 조심해야 한다.","syn":["有備無患"],"reviewed":true},
  {"id":"gs0241","hanja":"見蚊拔劍","reading":"견문발검","len":4,"lit":"모기를 보고 칼을 뺌","fig":"사소한 일에 크게 화내거나 지나치게 대응함","origin":"","source":"","example":"그 정도 일에 견문발검할 필요 없다.","syn":["矯角殺牛"],"reviewed":true},
  {"id":"gs0242","hanja":"傾國之色","reading":"경국지색","len":4,"lit":"나라를 기울게 할 미모","fig":"임금이 빠져 나라가 위태로울 만큼 아름다운 미인","origin":"","source":"","example":"경국지색이라 불릴 만한 미모였다.","syn":[],"reviewed":true},
  {"id":"gs0243","hanja":"鷄鳴狗盜","reading":"계명구도","len":4,"lit":"닭 울음과 개 도둑질","fig":"하찮은 재주도 때로 쓸모가 있음","origin":"맹상군이 닭 울음 흉내와 좀도둑 재주를 지닌 식객 덕에 위기를 벗어났다는 이야기에서 비롯","source":"사기","example":"계명구도라더니 그 재주가 결정적이었다.","syn":[],"reviewed":true},
  {"id":"gs0244","hanja":"孤掌難鳴","reading":"고장난명","len":4,"lit":"외손뼉은 울리지 못함","fig":"혼자서는 일을 이루기 어려움","origin":"","source":"","example":"고장난명이니 함께 힘을 모으자.","syn":[],"reviewed":true},
  {"id":"gs0245","hanja":"骨肉相爭","reading":"골육상쟁","len":4,"lit":"뼈와 살이 서로 다툼","fig":"가까운 혈육끼리 서로 싸움","origin":"","source":"","example":"재산을 두고 골육상쟁이 벌어졌다.","syn":[],"reviewed":true},
  {"id":"gs0246","hanja":"口蜜腹劍","reading":"구밀복검","len":4,"lit":"입에는 꿀, 배에는 칼","fig":"겉으로는 친한 척하나 속으로는 해칠 마음을 품음","origin":"","source":"","example":"구밀복검하는 사람을 조심하라.","syn":["表裏不同"],"reviewed":true},
  {"id":"gs0247","hanja":"口尙乳臭","reading":"구상유취","len":4,"lit":"입에서 아직 젖내가 남","fig":"말과 행동이 어리고 미숙함","origin":"","source":"","example":"구상유취인 신입이 큰소리친다.","syn":[],"reviewed":true},
  {"id":"gs0248","hanja":"權不十年","reading":"권불십년","len":4,"lit":"권세는 십 년을 못 감","fig":"아무리 높은 권세도 오래가지 못함","origin":"","source":"","example":"권불십년이라더니 그도 자리에서 물러났다.","syn":[],"reviewed":true},
  {"id":"gs0249","hanja":"近墨者黑","reading":"근묵자흑","len":4,"lit":"먹을 가까이하면 검어짐","fig":"나쁜 사람과 가까이하면 물들기 쉬움","origin":"","source":"","example":"근묵자흑이니 친구를 잘 사귀어라.","syn":["類類相從","草綠同色"],"reviewed":true},
  {"id":"gs0250","hanja":"金科玉條","reading":"금과옥조","len":4,"lit":"금과 옥 같은 법조문","fig":"더없이 소중히 여기는 규칙이나 교훈","origin":"","source":"","example":"그 가르침을 금과옥조로 삼았다.","syn":[],"reviewed":true},
  {"id":"gs0251","hanja":"氣盡脈盡","reading":"기진맥진","len":4,"lit":"기운과 맥이 다함","fig":"힘이 다 빠져 지칠 대로 지침","origin":"","source":"","example":"마라톤을 완주하고 기진맥진했다.","syn":[],"reviewed":true},
  {"id":"gs0252","hanja":"難攻不落","reading":"난공불락","len":4,"lit":"공격하기 어려워 함락되지 않음","fig":"공격하기 어렵고 좀처럼 무너지지 않음","origin":"","source":"","example":"난공불락의 요새로 알려졌다.","syn":[],"reviewed":true},
  {"id":"gs0253","hanja":"怒發大發","reading":"노발대발","len":4,"lit":"성을 크게 냄","fig":"몹시 화를 냄","origin":"","source":"","example":"사실을 알고 노발대발했다.","syn":[],"reviewed":true},
  {"id":"gs0254","hanja":"多才多能","reading":"다재다능","len":4,"lit":"재주도 능력도 많음","fig":"여러 방면에 재주와 능력이 많음","origin":"","source":"","example":"그림·음악·운동까지 다재다능하다.","syn":["八方美人"],"reviewed":true},
  {"id":"gs0255","hanja":"斷機之戒","reading":"단기지계","len":4,"lit":"베틀의 실을 끊어 보인 경계","fig":"학업을 중도에 그만두면 쓸모없음을 일깨우는 가르침","origin":"맹자의 어머니가 베 짜던 실을 끊어 학업 중단의 잘못을 깨우쳤다는 이야기에서 비롯","source":"","example":"단기지계를 새겨 끝까지 공부했다.","syn":["孟母三遷"],"reviewed":true},
  {"id":"gs0256","hanja":"讀書三昧","reading":"독서삼매","len":4,"lit":"책 읽기에 흠뻑 빠짐","fig":"다른 생각 없이 오로지 책에만 골몰함","origin":"","source":"","example":"주말 내내 독서삼매에 빠졌다.","syn":[],"reviewed":true},
  {"id":"gs0257","hanja":"燈下不明","reading":"등하불명","len":4,"lit":"등잔 밑이 어두움","fig":"가까이 있는 것을 도리어 잘 모름","origin":"","source":"","example":"등하불명이라고, 답이 바로 옆에 있었다.","syn":[],"reviewed":true},
  {"id":"gs0258","hanja":"莫無可奈","reading":"막무가내","len":4,"lit":"도무지 어찌할 수 없음","fig":"고집이 세어 어떻게도 통하지 않음","origin":"","source":"","example":"아무리 말려도 막무가내였다.","syn":[],"reviewed":true},
  {"id":"gs0259","hanja":"目不忍見","reading":"목불인견","len":4,"lit":"차마 눈 뜨고 볼 수 없음","fig":"딱하거나 끔찍해 차마 볼 수 없음","origin":"","source":"","example":"사고 현장은 목불인견이었다.","syn":[],"reviewed":true},
  {"id":"gs0260","hanja":"無所不爲","reading":"무소불위","len":4,"lit":"하지 못하는 일이 없음","fig":"못 하는 것이 없이 다 함, 또는 권세가 대단함","origin":"","source":"","example":"무소불위의 권력을 휘둘렀다.","syn":[],"reviewed":true},
  {"id":"gs0261","hanja":"聞一知十","reading":"문일지십","len":4,"lit":"하나를 들으면 열을 앎","fig":"매우 총명함","origin":"공자가 제자 안회를 두고 하나를 들으면 열을 안다고 평한 데서 비롯","source":"논어","example":"문일지십이라 가르치기 수월하다.","syn":[],"reviewed":true},
  {"id":"gs0262","hanja":"不知其數","reading":"부지기수","len":4,"lit":"그 수를 알지 못함","fig":"헤아릴 수 없을 만큼 많음","origin":"","source":"","example":"비슷한 사례가 부지기수다.","syn":[],"reviewed":true},
  {"id":"gs0263","hanja":"悲憤慷慨","reading":"비분강개","len":4,"lit":"슬프고 분해 의기가 북받침","fig":"옳지 못한 것에 슬퍼하고 분개함","origin":"","source":"","example":"부조리에 비분강개했다.","syn":[],"reviewed":true},
  {"id":"gs0264","hanja":"先公後私","reading":"선공후사","len":4,"lit":"공적인 일을 먼저, 사적인 일을 뒤로","fig":"사사로움보다 공익을 앞세움","origin":"","source":"","example":"선공후사하는 자세가 신뢰를 얻는다.","syn":["見利思義"],"reviewed":true},
  {"id":"gs0265","hanja":"送舊迎新","reading":"송구영신","len":4,"lit":"묵은해를 보내고 새해를 맞음","fig":"지난해를 보내고 새해를 맞이함","origin":"","source":"","example":"송구영신, 새해 복 많이 받으세요.","syn":[],"reviewed":true},
  {"id":"gs0266","hanja":"手不釋卷","reading":"수불석권","len":4,"lit":"손에서 책을 놓지 않음","fig":"늘 부지런히 글을 읽고 공부함","origin":"","source":"","example":"그는 바빠도 수불석권이다.","syn":["晝耕夜讀"],"reviewed":true},
  {"id":"gs0267","hanja":"梁上君子","reading":"양상군자","len":4,"lit":"들보 위의 군자","fig":"도둑을 점잖게 이르는 말","origin":"들보 위에 숨은 도둑을 양상의 군자라 일러 스스로 뉘우치게 했다는 이야기에서 비롯","source":"후한서","example":"밤사이 양상군자가 다녀갔다.","syn":[],"reviewed":true},
  {"id":"gs0268","hanja":"焉敢生心","reading":"언감생심","len":4,"lit":"어찌 감히 그런 마음을","fig":"감히 그런 마음을 품을 수도 없음","origin":"","source":"","example":"언감생심 욕심낼 처지가 아니다.","syn":[],"reviewed":true},
  {"id":"gs0269","hanja":"言語道斷","reading":"언어도단","len":4,"lit":"말로 표현할 길이 끊김","fig":"어이없어 말로 나타낼 수 없음","origin":"","source":"","example":"그 변명은 언어도단이다.","syn":[],"reviewed":true},
  {"id":"gs0270","hanja":"泥田鬪狗","reading":"이전투구","len":4,"lit":"진흙탕에서 싸우는 개","fig":"자기 이익을 위해 볼썽사납게 다툼","origin":"","source":"","example":"양측이 이전투구를 벌였다.","syn":[],"reviewed":true},
  {"id":"gs0271","hanja":"一字無識","reading":"일자무식","len":4,"lit":"글자 한 자도 모름","fig":"아주 무식함","origin":"","source":"","example":"그 분야엔 일자무식이다.","syn":[],"reviewed":true},
  {"id":"gs0272","hanja":"千篇一律","reading":"천편일률","len":4,"lit":"천 편의 글이 한 가락","fig":"여럿이 모두 비슷비슷해 변화가 없음","origin":"","source":"","example":"광고가 천편일률이라 지루하다.","syn":["大同小異"],"reviewed":true},
  {"id":"gs0273","hanja":"快刀亂麻","reading":"쾌도난마","len":4,"lit":"잘 드는 칼로 엉킨 삼을 자름","fig":"복잡한 일을 단번에 시원하게 처리함","origin":"","source":"","example":"쾌도난마로 문제를 해결했다.","syn":["一刀兩斷"],"reviewed":true},
  {"id":"gs0274","hanja":"破顔大笑","reading":"파안대소","len":4,"lit":"얼굴을 활짝 펴고 크게 웃음","fig":"즐겁게 활짝 웃음","origin":"","source":"","example":"오랜만에 만나 파안대소했다.","syn":["拍掌大笑"],"reviewed":true},
  {"id":"gs0275","hanja":"虛心坦懷","reading":"허심탄회","len":4,"lit":"마음을 비우고 생각을 터놓음","fig":"거리낌 없이 솔직하게 마음을 터놓음","origin":"","source":"","example":"허심탄회하게 이야기를 나눴다.","syn":[],"reviewed":true},
  {"id":"gs0276","hanja":"形形色色","reading":"형형색색","len":4,"lit":"모양과 빛깔이 갖가지","fig":"종류와 모양이 가지각색","origin":"","source":"","example":"형형색색의 등불이 거리를 밝혔다.","syn":[],"reviewed":true},
  {"id":"gs0277","hanja":"天生緣分","reading":"천생연분","len":4,"lit":"하늘이 정해 준 인연","fig":"하늘이 맺어 준 것처럼 잘 어울리는 인연","origin":"","source":"","example":"둘은 천생연분처럼 잘 맞는다.","syn":[],"reviewed":true},
  {"id":"gs0278","hanja":"風飛雹散","reading":"풍비박산","len":4,"lit":"바람에 날리고 우박처럼 흩어짐","fig":"사방으로 산산이 흩어짐","origin":"","source":"","example":"사업이 망해 가족이 풍비박산 났다.","syn":[],"reviewed":true},
  {"id":"gs0279","hanja":"百年大計","reading":"백년대계","len":4,"lit":"백 년의 큰 계획","fig":"먼 앞날을 내다본 큰 계획","origin":"","source":"","example":"교육은 나라의 백년대계다.","syn":[],"reviewed":true},
  {"id":"gs0280","hanja":"白面書生","reading":"백면서생","len":4,"lit":"얼굴 흰 선비","fig":"글만 읽어 세상 물정에 어두운 사람","origin":"","source":"","example":"백면서생이라 실무는 서툴다.","syn":[],"reviewed":true},
  {"id":"gs0281","hanja":"夫唱婦隨","reading":"부창부수","len":4,"lit":"남편이 부르면 아내가 따름","fig":"부부가 서로 화합함","origin":"","source":"","example":"부창부수로 금실이 좋다.","syn":["百年偕老"],"reviewed":true},
  {"id":"gs0282","hanja":"正正堂堂","reading":"정정당당","len":4,"lit":"바르고 떳떳함","fig":"태도나 수단이 바르고 떳떳함","origin":"","source":"","example":"정정당당하게 겨루자.","syn":[],"reviewed":true},
  {"id":"gs0283","hanja":"朝變夕改","reading":"조변석개","len":4,"lit":"아침에 바꾸고 저녁에 고침","fig":"계획이나 결정을 자주 뜯어고침","origin":"","source":"","example":"방침이 조변석개라 따르기 어렵다.","syn":[],"reviewed":true},
  {"id":"gs0284","hanja":"前人未踏","reading":"전인미답","len":4,"lit":"앞선 사람이 밟지 않음","fig":"이제까지 아무도 가 보지 못함","origin":"","source":"","example":"전인미답의 기록을 세웠다.","syn":[],"reviewed":true},
  {"id":"gs0285","hanja":"始終一貫","reading":"시종일관","len":4,"lit":"처음부터 끝까지 한결같음","fig":"처음의 자세를 끝까지 지킴","origin":"","source":"","example":"시종일관 침착함을 잃지 않았다.","syn":["初志一貫"],"reviewed":true},
  {"id":"gs0286","hanja":"連戰連勝","reading":"연전연승","len":4,"lit":"싸울 때마다 잇따라 이김","fig":"싸우는 족족 모두 이김","origin":"","source":"","example":"올 시즌 연전연승 중이다.","syn":["百戰百勝"],"reviewed":true},
  {"id":"gs0287","hanja":"四通八達","reading":"사통팔달","len":4,"lit":"사방으로 통하고 팔방으로 닿음","fig":"길이 여러 갈래로 막힘없이 통함","origin":"","source":"","example":"사통팔달의 교통 요지다.","syn":[],"reviewed":true},
  {"id":"gs0288","hanja":"緘口無言","reading":"함구무언","len":4,"lit":"입을 봉하고 말이 없음","fig":"입을 다물고 아무 말도 하지 않음","origin":"","source":"","example":"그 일에 대해선 함구무언이었다.","syn":[],"reviewed":true},
  {"id":"gs0289","hanja":"虛禮虛飾","reading":"허례허식","len":4,"lit":"헛된 예절과 겉치레","fig":"실속 없이 겉만 꾸미는 형식","origin":"","source":"","example":"허례허식을 줄이고 간소하게 치렀다.","syn":[],"reviewed":true},
  {"id":"gs0290","hanja":"風餐露宿","reading":"풍찬노숙","len":4,"lit":"바람에 먹고 이슬에 잠","fig":"떠돌며 온갖 고생을 함","origin":"","source":"","example":"풍찬노숙하며 전국을 누볐다.","syn":[],"reviewed":true},
  {"id":"gs0291","hanja":"糊口之策","reading":"호구지책","len":4,"lit":"입에 풀칠할 방책","fig":"겨우 끼니를 이어 가기 위한 방책","origin":"","source":"","example":"호구지책으로 막일을 시작했다.","syn":[],"reviewed":true},
  {"id":"gs0292","hanja":"犬馬之勞","reading":"견마지로","len":4,"lit":"개와 말의 수고","fig":"윗사람을 위해 바치는 자신의 노력을 낮추어 이르는 말","origin":"","source":"","example":"견마지로를 다하겠습니다.","syn":[],"reviewed":true},
  {"id":"gs0293","hanja":"金蘭之交","reading":"금란지교","len":4,"lit":"쇠처럼 굳고 난초처럼 향기로운 사귐","fig":"매우 두텁고 깊은 우정","origin":"","source":"","example":"두 사람은 금란지교를 맺었다.","syn":["莫逆之友"],"reviewed":true},
  {"id":"gs0294","hanja":"同價紅裳","reading":"동가홍상","len":4,"lit":"같은 값이면 붉은 치마","fig":"같은 값이면 더 좋은 것을 택함","origin":"","source":"","example":"동가홍상이라고, 이왕이면 예쁜 걸 고른다.","syn":[],"reviewed":true},
  {"id":"gs0295","hanja":"甲男乙女","reading":"갑남을녀","len":4,"lit":"갑이라는 남자와 을이라는 여자","fig":"평범한 보통 사람들","origin":"","source":"","example":"갑남을녀의 소박한 일상.","syn":[],"reviewed":true},
  {"id":"gs0296","hanja":"天方地軸","reading":"천방지축","len":4,"lit":"하늘 방향과 땅의 축","fig":"종잡을 수 없이 덤벙대거나 몹시 급해 허둥댐","origin":"","source":"","example":"천방지축으로 뛰어다닌다.","syn":[],"reviewed":true},
  {"id":"gs0297","hanja":"命在頃刻","reading":"명재경각","len":4,"lit":"목숨이 짧은 순간에 달림","fig":"거의 죽게 되어 곧 숨이 끊어질 지경","origin":"","source":"","example":"환자가 명재경각의 위태로운 상태다.","syn":["風前燈火"],"reviewed":true},
  {"id":"gs0298","hanja":"一言半句","reading":"일언반구","len":4,"lit":"한 마디 말과 반 구절","fig":"아주 짧은 말","origin":"","source":"","example":"일언반구 사과도 없었다.","syn":[],"reviewed":true},
  {"id":"gs0299","hanja":"萬古不變","reading":"만고불변","len":4,"lit":"오랜 세월 변하지 않음","fig":"아주 오랜 세월 동안 변함이 없음","origin":"","source":"","example":"우정만은 만고불변이길 바란다.","syn":[],"reviewed":true},
  {"id":"gs0300","hanja":"格物致知","reading":"격물치지","len":4,"lit":"사물을 궁구해 앎에 이름","fig":"사물의 이치를 끝까지 따져 참된 앎에 이름","origin":"","source":"대학","example":"격물치지의 자세로 깊이 파고들었다.","syn":[],"reviewed":true}
]
export const BY_READING: Record<string, Idiom> = Object.fromEntries(IDIOMS.map(i => [i.reading, i]))

const CHO = ['ㄱ','ㄲ','ㄴ','ㄷ','ㄸ','ㄹ','ㅁ','ㅂ','ㅃ','ㅅ','ㅆ','ㅇ','ㅈ','ㅉ','ㅊ','ㅋ','ㅌ','ㅍ','ㅎ']
export function choseong(s: string): string {
  let r = ''
  for (const ch of s) { const c = ch.charCodeAt(0); if (c >= 0xac00 && c <= 0xd7a3) r += CHO[Math.floor((c - 0xac00) / 588)]; else if (ch !== ' ') r += ch }
  return r
}
export function searchIdioms(q: string): Idiom[] {
  const s = q.trim(); if (!s) return IDIOMS
  const low = s.toLowerCase()
  const isCho = /^[ㄱ-ㅎ]+$/.test(s.replace(/\s/g, ''))
  return IDIOMS.filter((i) =>
    i.hanja.includes(s) || i.reading.includes(s) || i.reading.replace(/ /g, '').includes(s) ||
    i.lit.includes(s) || i.fig.includes(s) || i.example.toLowerCase().includes(low) ||
    (isCho && choseong(i.reading).includes(s.replace(/\s/g, '')))
  )
}
