// Korean -> English dictionary (common words). Paired with kr-ja-dict by the
// same Korean keys so all KO/JA/EN directions can be derived. Grows in batches.
export const KR_EN: Record<string, string> = {
  // 인사 / 기본
  '안녕': 'hello', '안녕하세요': 'hello', '안녕히가세요': 'goodbye', '잘가': 'bye', '잘자': 'good night',
  '감사': 'thanks', '감사합니다': 'thank you', '고마워': 'thanks', '고맙습니다': 'thank you',
  '미안': 'sorry', '미안해': 'sorry', '미안합니다': 'sorry', '죄송합니다': 'I apologize', '괜찮아': "it's okay",
  '네': 'yes', '아니요': 'no', '아니': 'no', '예': 'yes', '응': 'yeah',
  '축하': 'congratulations', '환영': 'welcome', '부탁': 'request', '천만에요': "you're welcome",
  // 사람 / 가족
  '사람': 'person', '남자': 'man', '여자': 'woman', '아이': 'child', '어른': 'adult', '아기': 'baby',
  '친구': 'friend', '가족': 'family', '부모': 'parents', '엄마': 'mom', '아빠': 'dad', '어머니': 'mother', '아버지': 'father',
  '형': 'older brother', '누나': 'older sister', '언니': 'older sister', '동생': 'younger sibling',
  '할아버지': 'grandfather', '할머니': 'grandmother', '아들': 'son', '딸': 'daughter', '부부': 'couple',
  '남편': 'husband', '아내': 'wife', '결혼': 'marriage', '선생님': 'teacher', '학생': 'student', '의사': 'doctor',
  '간호사': 'nurse', '경찰': 'police', '손님': 'guest', '이웃': 'neighbor', '연인': 'lover', '애인': 'lover',
  // 신체
  '몸': 'body', '머리': 'head', '얼굴': 'face', '눈': 'eye', '코': 'nose', '입': 'mouth', '귀': 'ear', '이': 'tooth',
  '목': 'neck', '어깨': 'shoulder', '팔': 'arm', '손': 'hand', '손가락': 'finger', '발': 'foot', '무릎': 'knee',
  '배': 'belly', '등': 'back', '가슴': 'chest', '허리': 'waist', '피부': 'skin', '뼈': 'bone', '피': 'blood', '심장': 'heart',
  // 감정 / 성격
  '사랑': 'love', '사랑해': 'I love you', '좋아': 'like', '싫어': 'dislike', '기쁨': 'joy', '슬픔': 'sadness',
  '행복': 'happiness', '슬프다': 'sad', '기쁘다': 'glad', '화나다': 'angry', '무섭다': 'scary', '놀라다': 'surprised',
  '걱정': 'worry', '외롭다': 'lonely', '부끄럽다': 'embarrassed', '긴장': 'nervousness',
  '친절하다': 'kind', '착하다': 'nice', '용감하다': 'brave', '게으르다': 'lazy', '똑똑하다': 'smart', '정직하다': 'honest',
  // 색 / 모양
  '색': 'color', '색깔': 'color', '빨강': 'red', '파랑': 'blue', '노랑': 'yellow', '초록': 'green', '검정': 'black',
  '하양': 'white', '회색': 'gray', '분홍': 'pink', '보라': 'purple', '주황': 'orange', '갈색': 'brown',
  '별': 'star', '동그라미': 'circle', '네모': 'square', '세모': 'triangle',
  // 동물
  '동물': 'animal', '개': 'dog', '강아지': 'puppy', '고양이': 'cat', '새': 'bird', '물고기': 'fish', '말': 'horse',
  '소': 'cow', '돼지': 'pig', '닭': 'chicken', '양': 'sheep', '토끼': 'rabbit', '쥐': 'mouse', '곰': 'bear',
  '호랑이': 'tiger', '사자': 'lion', '코끼리': 'elephant', '원숭이': 'monkey', '뱀': 'snake', '개구리': 'frog',
  '거북이': 'turtle', '나비': 'butterfly', '벌': 'bee', '거미': 'spider', '모기': 'mosquito', '오리': 'duck', '여우': 'fox',
  // 식물 / 자연
  '나무': 'tree', '꽃': 'flower', '풀': 'grass', '잎': 'leaf', '뿌리': 'root', '씨앗': 'seed', '열매': 'fruit',
  '하늘': 'sky', '땅': 'ground', '산': 'mountain', '강': 'river', '바다': 'sea', '호수': 'lake', '섬': 'island',
  '돌': 'stone', '모래': 'sand', '흙': 'soil', '불': 'fire', '물': 'water', '공기': 'air', '바람': 'wind',
  '해': 'sun', '태양': 'sun', '달': 'moon', '지구': 'earth', '우주': 'universe', '구름': 'cloud', '무지개': 'rainbow',
  // 날씨 / 계절
  '날씨': 'weather', '비': 'rain', '맑음': 'sunny', '흐림': 'cloudy', '천둥': 'thunder', '번개': 'lightning',
  '안개': 'fog', '태풍': 'typhoon', '온도': 'temperature', '봄': 'spring', '여름': 'summer', '가을': 'autumn',
  '겨울': 'winter', '계절': 'season',
  // 음식
  '음식': 'food', '밥': 'rice', '국': 'soup', '고기': 'meat', '생선': 'fish', '계란': 'egg', '빵': 'bread',
  '국수': 'noodles', '라면': 'ramen', '김치': 'kimchi', '치즈': 'cheese', '버터': 'butter', '쌀': 'rice',
  '설탕': 'sugar', '소금': 'salt', '기름': 'oil', '과일': 'fruit', '사과': 'apple', '바나나': 'banana', '포도': 'grape',
  '딸기': 'strawberry', '수박': 'watermelon', '오렌지': 'orange', '복숭아': 'peach', '귤': 'tangerine', '레몬': 'lemon',
  '야채': 'vegetable', '채소': 'vegetable', '당근': 'carrot', '감자': 'potato', '양파': 'onion', '마늘': 'garlic',
  '토마토': 'tomato', '오이': 'cucumber', '버섯': 'mushroom', '콩': 'bean', '우유': 'milk', '주스': 'juice',
  '커피': 'coffee', '차': 'tea', '맥주': 'beer', '술': 'alcohol', '와인': 'wine', '과자': 'snack',
  '맛있다': 'delicious', '맛없다': 'tasteless', '달다': 'sweet', '맵다': 'spicy', '짜다': 'salty', '시다': 'sour',
  // 집 / 생활용품
  '집': 'house', '방': 'room', '거실': 'living room', '부엌': 'kitchen', '화장실': 'toilet', '욕실': 'bathroom',
  '문': 'door', '창문': 'window', '벽': 'wall', '바닥': 'floor', '천장': 'ceiling', '계단': 'stairs', '지붕': 'roof',
  '책상': 'desk', '의자': 'chair', '침대': 'bed', '소파': 'sofa', '냉장고': 'fridge', '세탁기': 'washing machine',
  '시계': 'clock', '거울': 'mirror', '그릇': 'bowl', '접시': 'plate', '컵': 'cup', '칼': 'knife', '수건': 'towel',
  '비누': 'soap', '이불': 'blanket', '베개': 'pillow', '우산': 'umbrella', '가방': 'bag', '열쇠': 'key',
  '지갑': 'wallet', '안경': 'glasses',
  // 옷
  '옷': 'clothes', '셔츠': 'shirt', '바지': 'pants', '치마': 'skirt', '모자': 'hat', '신발': 'shoes', '양말': 'socks',
  '장갑': 'gloves', '넥타이': 'necktie', '벨트': 'belt', '반지': 'ring', '목걸이': 'necklace',
  // 장소 / 시설
  '학교': 'school', '회사': 'company', '병원': 'hospital', '은행': 'bank', '우체국': 'post office', '도서관': 'library',
  '식당': 'restaurant', '가게': 'shop', '시장': 'market', '백화점': 'department store', '편의점': 'convenience store',
  '서점': 'bookstore', '약국': 'pharmacy', '카페': 'cafe', '공원': 'park', '동물원': 'zoo', '박물관': 'museum',
  '교회': 'church', '절': 'temple', '호텔': 'hotel', '공장': 'factory', '역': 'station', '공항': 'airport',
  '나라': 'country', '도시': 'city', '시골': 'countryside', '마을': 'village', '거리': 'street', '다리': 'bridge',
  // 교통
  '차': 'car', '자동차': 'car', '버스': 'bus', '택시': 'taxi', '지하철': 'subway', '기차': 'train', '비행기': 'airplane',
  '자전거': 'bicycle', '오토바이': 'motorcycle', '트럭': 'truck', '길': 'road',
  // 학교 / 공부
  '공부': 'study', '숙제': 'homework', '시험': 'exam', '수업': 'class', '교실': 'classroom', '칠판': 'blackboard',
  '책': 'book', '교과서': 'textbook', '공책': 'notebook', '연필': 'pencil', '지우개': 'eraser', '가위': 'scissors',
  '자': 'ruler', '문제': 'problem', '답': 'answer', '점수': 'score', '성적': 'grades', '졸업': 'graduation',
  '입학': 'admission', '방학': 'vacation', '교육': 'education', '국어': 'Korean (subject)', '수학': 'math',
  '과학': 'science', '영어': 'English', '역사': 'history', '지리': 'geography', '음악': 'music', '미술': 'art',
  '체육': 'PE', '단어': 'word', '문장': 'sentence', '글': 'writing',
  // 직업 / 경제
  '일': 'work', '직업': 'job', '월급': 'salary', '회의': 'meeting', '서류': 'document', '사장': 'boss', '직원': 'employee',
  '동료': 'colleague', '면접': 'interview', '돈': 'money', '무료': 'free', '유료': 'paid', '할인': 'discount',
  '가격': 'price', '값': 'price', '세금': 'tax', '현금': 'cash', '카드': 'card', '저금': 'savings', '영수증': 'receipt',
  '경제': 'economy', '계산': 'calculation', '예산': 'budget', '판매': 'sale', '구매': 'purchase',
  // 시간 / 달력
  '시간': 'time', '오늘': 'today', '내일': 'tomorrow', '어제': 'yesterday', '지금': 'now', '나중': 'later',
  '아침': 'morning', '점심': 'noon', '저녁': 'evening', '밤': 'night', '새벽': 'dawn', '낮': 'daytime',
  '주': 'week', '주말': 'weekend', '평일': 'weekday', '년': 'year', '날': 'day', '오전': 'AM', '오후': 'PM',
  '매일': 'every day', '항상': 'always', '가끔': 'sometimes', '월요일': 'Monday', '화요일': 'Tuesday',
  '수요일': 'Wednesday', '목요일': 'Thursday', '금요일': 'Friday', '토요일': 'Saturday', '일요일': 'Sunday',
  '생일': 'birthday', '휴일': 'holiday',
  // 형용사
  '크다': 'big', '작다': 'small', '많다': 'many', '적다': 'few', '높다': 'high', '낮다': 'low', '길다': 'long',
  '짧다': 'short', '넓다': 'wide', '좁다': 'narrow', '무겁다': 'heavy', '가볍다': 'light', '빠르다': 'fast',
  '느리다': 'slow', '강하다': 'strong', '약하다': 'weak', '좋다': 'good', '나쁘다': 'bad', '새롭다': 'new',
  '깨끗하다': 'clean', '더럽다': 'dirty', '예쁘다': 'pretty', '귀엽다': 'cute', '멋지다': 'cool', '아름답다': 'beautiful',
  '쉽다': 'easy', '어렵다': 'difficult', '재미있다': 'fun', '재미없다': 'boring', '중요하다': 'important',
  '덥다': 'hot (weather)', '춥다': 'cold (weather)', '뜨겁다': 'hot', '차갑다': 'cold', '따뜻하다': 'warm',
  '시원하다': 'cool', '밝다': 'bright', '어둡다': 'dark', '조용하다': 'quiet', '시끄럽다': 'noisy', '바쁘다': 'busy',
  '피곤하다': 'tired', '아프다': 'sick', '같다': 'same', '다르다': 'different', '비슷하다': 'similar', '특별하다': 'special',
  // 동사
  '가다': 'go', '오다': 'come', '먹다': 'eat', '마시다': 'drink', '자다': 'sleep', '일어나다': 'wake up',
  '걷다': 'walk', '뛰다': 'run', '서다': 'stand', '앉다': 'sit', '보다': 'see', '듣다': 'listen', '말하다': 'speak',
  '읽다': 'read', '쓰다': 'write', '사다': 'buy', '팔다': 'sell', '주다': 'give', '받다': 'receive', '만나다': 'meet',
  '웃다': 'laugh', '울다': 'cry', '놀다': 'play', '쉬다': 'rest', '열다': 'open', '닫다': 'close', '찾다': 'find',
  '만들다': 'make', '고치다': 'fix', '씻다': 'wash', '배우다': 'learn', '가르치다': 'teach', '생각하다': 'think',
  '알다': 'know', '모르다': "don't know", '기억하다': 'remember', '잊다': 'forget', '믿다': 'believe', '돕다': 'help',
  '기다리다': 'wait', '시작하다': 'start', '끝나다': 'end', '살다': 'live', '죽다': 'die', '되다': 'become',
  '있다': 'exist', '없다': 'not exist', '하다': 'do', '필요하다': 'need', '원하다': 'want',
  // 부사 / 의문사 / 대명사
  '아주': 'very', '너무': 'too', '조금': 'a little', '많이': 'a lot', '빨리': 'quickly', '천천히': 'slowly',
  '함께': 'together', '같이': 'together', '혼자': 'alone', '다시': 'again', '정말': 'really', '그리고': 'and',
  '하지만': 'but', '그래서': 'so', '또': 'also',
  '나': 'I', '너': 'you', '우리': 'we', '여기': 'here', '거기': 'there', '어디': 'where', '누구': 'who',
  '무엇': 'what', '뭐': 'what', '왜': 'why', '어떻게': 'how', '언제': 'when', '얼마': 'how much',
  // 동사 (격식/한자어)
  '발생하다': 'occur', '존재하다': 'exist', '포함하다': 'include', '제공하다': 'provide', '제외하다': 'exclude',
  '구성하다': 'compose', '표현하다': 'express', '분석하다': 'analyze', '판단하다': 'judge', '평가하다': 'evaluate',
  '측정하다': 'measure', '증가하다': 'increase', '감소하다': 'decrease', '유지하다': 'maintain', '개발하다': 'develop',
  '생산하다': 'produce', '소비하다': 'consume', '제작하다': 'produce', '건설하다': 'construct', '파괴하다': 'destroy',
  '보호하다': 'protect', '공격하다': 'attack', '방어하다': 'defend', '지원하다': 'support', '협력하다': 'cooperate',
  '참여하다': 'participate', '신청하다': 'apply', '등록하다': 'register', '제출하다': 'submit', '거절하다': 'refuse',
  '승인하다': 'approve', '허락하다': 'permit', '금지하다': 'forbid', '명령하다': 'command', '요청하다': 'request',
  '요구하다': 'demand', '주장하다': 'insist', '반대하다': 'oppose', '동의하다': 'agree', '찬성하다': 'approve',
  '인정하다': 'admit', '거부하다': 'reject', '검사하다': 'inspect', '조사하다': 'investigate', '연구하다': 'research',
  '발표하다': 'announce', '보고하다': 'report', '기록하다': 'record', '저장하다': 'save', '삭제하다': 'delete',
  '수정하다': 'edit', '복사하다': 'copy', '인쇄하다': 'print', '연결하다': 'connect', '분리하다': 'separate',
  '교환하다': 'exchange', '변경하다': 'change', '처리하다': 'process', '관리하다': 'manage', '운영하다': 'operate',
  '진행하다': 'proceed', '완성하다': 'complete', '달성하다': 'achieve', '해결하다': 'solve', '극복하다': 'overcome',
  '적용하다': 'apply', '활용하다': 'utilize', '제한하다': 'limit', '예방하다': 'prevent', '치료하다': 'treat',
  '회복하다': 'recover', '발달하다': 'develop', '모방하다': 'imitate', '창조하다': 'create', '의미하다': 'mean',
  '시도하다': 'try', '도전하다': 'challenge', '경험하다': 'experience', '체험하다': 'experience', '익히다': 'master',
  // 동사 (생활)
  '보내다': 'send', '던지다': 'throw', '잡다': 'catch', '밀다': 'push', '당기다': 'pull', '들다': 'hold',
  '떨어지다': 'fall', '넘어지다': 'fall over', '날다': 'fly', '수영하다': 'swim', '흔들다': 'shake', '두드리다': 'knock',
  '때리다': 'hit', '차다': 'kick', '자르다': 'cut', '붙이다': 'attach', '묶다': 'tie', '풀다': 'untie', '접다': 'fold',
  '펴다': 'spread', '싸다': 'wrap', '붓다': 'pour', '섞다': 'mix', '끓이다': 'boil', '굽다': 'grill', '튀기다': 'fry',
  '삶다': 'boil', '볶다': 'stir-fry', '자라다': 'grow', '키우다': 'raise', '심다': 'plant', '짓다': 'build',
  '부수다': 'break', '움직이다': 'move', '멈추다': 'stop', '돌다': 'turn', '오르다': 'climb', '건너다': 'cross',
  '지나가다': 'pass', '도착하다': 'arrive', '출발하다': 'depart', '떠나다': 'leave', '머물다': 'stay', '돌아오다': 'return',
  '보이다': 'be seen', '들리다': 'be heard', '대답하다': 'answer', '설명하다': 'explain', '소개하다': 'introduce',
  '약속하다': 'promise', '싸우다': 'fight', '도와주다': 'help', '사과하다': 'apologize', '칭찬하다': 'praise',
  '혼내다': 'scold', '결정하다': 'decide', '선택하다': 'choose', '계획하다': 'plan', '바꾸다': 'change', '참다': 'endure',
  '포기하다': 'give up', '노력하다': 'make an effort', '성공하다': 'succeed', '실패하다': 'fail', '이기다': 'win',
  '지다': 'lose', '연습하다': 'practice', '외우다': 'memorize', '이해하다': 'understand', '상상하다': 'imagine',
  '나누다': 'divide', '모으다': 'collect', '버리다': 'throw away', '줍다': 'pick up', '빌리다': 'borrow', '갚다': 'repay',
  '넣다': 'put in', '꺼내다': 'take out', '돕다(추가)': 'help', '구하다': 'save', '얻다': 'obtain', '벌다': 'earn',
  '다니다': 'attend', '향하다': 'head toward', '마주치다': 'run into', '들르다': 'drop by', '줄서다': 'line up',
  '양보하다': 'yield', '미루다': 'postpone', '서두르다': 'hurry', '중단하다': 'interrupt', '취소하다': 'cancel',
  '예약하다': 'reserve', '주문하다': 'order', '배달하다': 'deliver', '지불하다': 'pay', '저축하다': 'save up',
  '투자하다': 'invest', '청소하다': 'clean', '빨래하다': 'do laundry', '정리하다': 'organize', '고르다': 'choose',
  '비교하다': 'compare', '반복하다': 'repeat', '계속하다': 'continue', '그만두다': 'quit', '용서하다': 'forgive',
  '배신하다': 'betray', '떠오르다': 'come to mind', '가라앉다': 'sink', '빠지다': 'drown', '시들다': 'wither',
  '설레다': 'flutter', '깨닫다': 'realize', '무시하다': 'ignore', '존중하다': 'respect', '돌보다': 'care for',
  '기르다': 'raise', '낳다': 'give birth', '견디다': 'endure', '맞서다': 'confront', '구조하다': 'rescue',
  // 형용사
  '멀다': 'far', '가깝다': 'near', '깊다': 'deep', '얕다': 'shallow', '굵다': 'thick', '가늘다': 'thin',
  '단단하다': 'hard', '부드럽다': 'soft', '거칠다': 'rough', '둥글다': 'round', '곧다': 'straight', '젖다': 'wet',
  '위험하다': 'dangerous', '안전하다': 'safe', '건강하다': 'healthy', '편하다': 'comfortable', '불편하다': 'inconvenient',
  '졸리다': 'sleepy', '부지런하다': 'diligent', '솔직하다': 'frank', '겸손하다': 'humble', '어리다': 'young',
  '젊다': 'young', '늙다': 'old', '그립다': 'nostalgic', '부럽다': 'envious', '귀찮다': 'bothersome', '심심하다': 'bored',
  '비싸다': 'expensive', '흔하다': 'common', '드물다': 'rare', '가난하다': 'poor', '부유하다': 'rich', '신기하다': 'amazing',
  '가능하다': 'possible', '소중하다': 'precious', '평범하다': 'ordinary', '이상하다': 'strange', '확실하다': 'certain',
  '분명하다': 'clear', '복잡하다': 'complex', '단순하다': 'simple', '정확하다': 'accurate', '자세하다': 'detailed',
  '대단하다': 'amazing', '훌륭하다': 'excellent', '완벽하다': 'perfect', '충분하다': 'enough', '부족하다': 'insufficient',
  '풍부하다': 'abundant', '다양하다': 'diverse', '자유롭다': 'free', '즐겁다': 'enjoyable', '놀랍다': 'surprising',
  '딱딱하다': 'stiff', '적당하다': 'moderate', '간단하다': 'simple', '거대하다': 'huge', '날씬하다': 'slim',
  '당연하다': 'natural', '엄격하다': 'strict', '관대하다': 'generous', '침착하다': 'calm', '대담하다': 'bold',
  '익숙하다': 'familiar', '낯설다': 'unfamiliar',
  // 명사 (자주 쓰는)
  '관심': 'interest', '흥미': 'interest', '실력': 'ability', '효과': 'effect', '영향': 'influence', '변화': 'change',
  '발전': 'development', '성장': 'growth', '과정': 'process', '단계': 'stage', '순서': 'order', '수준': 'level',
  '정도': 'degree', '양': 'amount', '비율': 'ratio', '평균': 'average', '일부': 'part', '나머지': 'rest',
  '중간': 'middle', '끝': 'end', '기억': 'memory', '추억': 'memories', '기분': 'mood', '느낌': 'feeling',
  '성격': 'personality', '태도': 'attitude', '행동': 'behavior', '분위기': 'atmosphere', '표정': 'expression',
  '목소리': 'voice', '웃음': 'laughter', '눈물': 'tears', '일상': 'daily life', '생활': 'life', '인생': 'life',
  '죽음': 'death', '의미': 'meaning', '가치': 'value', '목적': 'purpose', '장점': 'strength', '단점': 'weakness',
  '특징': 'feature', '조건': 'condition', '결심': 'resolution', '실수': 'mistake', '잘못': 'fault', '자세': 'posture',
  '이유': 'reason', '원인': 'cause', '결과': 'result', '결론': 'conclusion', '핵심': 'core', '주제': 'topic',
  '경향': 'tendency', '유행': 'trend', '인기': 'popularity', '평판': 'reputation', '분야': 'field', '항목': 'item',
  '목록': 'list', '순위': 'ranking', '등급': 'grade', '단위': 'unit', '기준': 'standard',
  // 명사 (사회/학문/기술)
  '세계': 'world', '사회': 'society', '문화': 'culture', '정치': 'politics', '법': 'law', '자유': 'freedom',
  '평화': 'peace', '전쟁': 'war', '환경': 'environment', '자연': 'nature', '미래': 'future', '과거': 'past',
  '현재': 'present', '꿈': 'dream', '희망': 'hope', '목표': 'goal', '약속': 'promise', '비밀': 'secret',
  '진실': 'truth', '거짓말': 'lie', '방법': 'method', '능력': 'ability', '경험': 'experience', '기회': 'chance',
  '습관': 'habit', '취미': 'hobby', '여행': 'travel', '선물': 'gift', '뉴스': 'news', '정보': 'information',
  '소식': 'news', '내용': 'content', '종류': 'kind', '문학': 'literature', '철학': 'philosophy', '역사': 'history',
  '과학자': 'scientist', '실험': 'experiment', '관찰': 'observation', '발견': 'discovery', '에너지': 'energy',
  '전기': 'electricity', '기계': 'machine', '도구': 'tool', '컴퓨터': 'computer', '인터넷': 'internet',
  '전화': 'phone', '휴대폰': 'cellphone', '검색': 'search', '계정': 'account', '비밀번호': 'password',
  '게임': 'game', '사진': 'photo', '영화': 'movie', '음악': 'music', '노래': 'song', '운동': 'exercise', '건강': 'health',
  '병': 'illness', '감기': 'cold', '약': 'medicine', '치료': 'treatment', '수술': 'surgery',
}
