// Korean -> English dictionary (common words). Paired with kr-ja-dict by the
// same Korean keys so all KO/JA/EN directions can be derived. Grows in batches.
export const KR_EN: Record<string, string> = {
  // 인사 / 기본
  '안녕': 'hello', '안녕하세요': 'hello', '안녕히가세요': 'goodbye', '잘가': 'bye', '잘자': 'good night',
  '감사': 'thanks', '감사합니다': 'thank you', '고마워': 'thanks', '고맙습니다': 'thank you',
  '미안': 'sorry', '미안해': 'sorry', '미안합니다': 'sorry', '죄송합니다': 'I apologize', '괜찮아': "it's okay",
  '네': 'yes', '아니요': 'no', '아니': 'no', '예': 'yes', '응': 'yeah',
  '축하': 'congratulations', '환영': 'welcome', '부탁': 'request', '천만에요': "you're welcome",
  // 사람 / 가족
  '사람': 'person', '남자': 'man', '여자': 'woman', '아이': 'child', '어른': 'adult', '아기': 'baby',
  '친구': 'friend', '가족': 'family', '부모': 'parents', '엄마': 'mom', '아빠': 'dad', '어머니': 'mother', '아버지': 'father',
  '형': 'older brother', '누나': 'older sister', '언니': 'older sister', '동생': 'younger sibling',
  '할아버지': 'grandfather', '할머니': 'grandmother', '아들': 'son', '딸': 'daughter', '부부': 'couple',
  '남편': 'husband', '아내': 'wife', '결혼': 'marriage', '선생님': 'teacher', '학생': 'student', '의사': 'doctor',
  '간호사': 'nurse', '경찰': 'police', '손님': 'guest', '이웃': 'neighbor', '연인': 'lover', '애인': 'lover',
  // 신체
  '몸': 'body', '머리': 'head', '얼굴': 'face', '눈': 'eye', '코': 'nose', '입': 'mouth', '귀': 'ear', '이': 'tooth',
  '목': 'neck', '어깨': 'shoulder', '팔': 'arm', '손': 'hand', '손가락': 'finger', '발': 'foot', '무릎': 'knee',
  '배': 'belly', '등': 'back', '가슴': 'chest', '허리': 'waist', '피부': 'skin', '뼈': 'bone', '피': 'blood', '심장': 'heart',
  // 감정 / 성격
  '사랑': 'love', '사랑해': 'I love you', '좋아': 'like', '싫어': 'dislike', '기쁨': 'joy', '슬픔': 'sadness',
  '행복': 'happiness', '슬프다': 'sad', '기쁘다': 'glad', '화나다': 'angry', '무섭다': 'scary', '놀라다': 'surprised',
  '걱정': 'worry', '외롭다': 'lonely', '부끄럽다': 'embarrassed', '긴장': 'nervousness',
  '친절하다': 'kind', '착하다': 'nice', '용감하다': 'brave', '게으르다': 'lazy', '똑똑하다': 'smart', '정직하다': 'honest',
  // 색 / 모양
  '색': 'color', '색깔': 'color', '빨강': 'red', '파랑': 'blue', '노랑': 'yellow', '초록': 'green', '검정': 'black',
  '하양': 'white', '회색': 'gray', '분홍': 'pink', '보라': 'purple', '주황': 'orange', '갈색': 'brown',
  '별': 'star', '동그라미': 'circle', '네모': 'square', '세모': 'triangle',
  // 동물
  '동물': 'animal', '개': 'dog', '강아지': 'puppy', '고양이': 'cat', '새': 'bird', '물고기': 'fish', '말': 'horse',
  '소': 'cow', '돼지': 'pig', '닭': 'chicken', '양': 'sheep', '토끼': 'rabbit', '쥐': 'mouse', '곰': 'bear',
  '호랑이': 'tiger', '사자': 'lion', '코끼리': 'elephant', '원숭이': 'monkey', '뱀': 'snake', '개구리': 'frog',
  '거북이': 'turtle', '나비': 'butterfly', '벌': 'bee', '거미': 'spider', '모기': 'mosquito', '오리': 'duck', '여우': 'fox',
  // 식물 / 자연
  '나무': 'tree', '꽃': 'flower', '풀': 'grass', '잎': 'leaf', '뿌리': 'root', '씨앗': 'seed', '열매': 'fruit',
  '하늘': 'sky', '땅': 'ground', '산': 'mountain', '강': 'river', '바다': 'sea', '호수': 'lake', '섬': 'island',
  '돌': 'stone', '모래': 'sand', '흙': 'soil', '불': 'fire', '물': 'water', '공기': 'air', '바람': 'wind',
  '해': 'sun', '태양': 'sun', '달': 'moon', '지구': 'earth', '우주': 'universe', '구름': 'cloud', '무지개': 'rainbow',
  // 날씨 / 계절
  '날씨': 'weather', '비': 'rain', '맑음': 'sunny', '흐림': 'cloudy', '천둥': 'thunder', '번개': 'lightning',
  '안개': 'fog', '태풍': 'typhoon', '온도': 'temperature', '봄': 'spring', '여름': 'summer', '가을': 'autumn',
  '겨울': 'winter', '계절': 'season',
  // 음식
  '음식': 'food', '밥': 'rice', '국': 'soup', '고기': 'meat', '생선': 'fish', '계란': 'egg', '빵': 'bread',
  '국수': 'noodles', '라면': 'ramen', '김치': 'kimchi', '치즈': 'cheese', '버터': 'butter', '쌀': 'rice',
  '설탕': 'sugar', '소금': 'salt', '기름': 'oil', '과일': 'fruit', '사과': 'apple', '바나나': 'banana', '포도': 'grape',
  '딸기': 'strawberry', '수박': 'watermelon', '오렌지': 'orange', '복숭아': 'peach', '귤': 'tangerine', '레몬': 'lemon',
  '야채': 'vegetable', '채소': 'vegetable', '당근': 'carrot', '감자': 'potato', '양파': 'onion', '마늘': 'garlic',
  '토마토': 'tomato', '오이': 'cucumber', '버섯': 'mushroom', '콩': 'bean', '우유': 'milk', '주스': 'juice',
  '커피': 'coffee', '차': 'tea', '맥주': 'beer', '술': 'alcohol', '와인': 'wine', '과자': 'snack',
  '맛있다': 'delicious', '맛없다': 'tasteless', '달다': 'sweet', '맵다': 'spicy', '짜다': 'salty', '시다': 'sour',
  // 집 / 생활용품
  '집': 'house', '방': 'room', '거실': 'living room', '부엌': 'kitchen', '화장실': 'toilet', '욕실': 'bathroom',
  '문': 'door', '창문': 'window', '벽': 'wall', '바닥': 'floor', '천장': 'ceiling', '계단': 'stairs', '지붕': 'roof',
  '책상': 'desk', '의자': 'chair', '침대': 'bed', '소파': 'sofa', '냉장고': 'fridge', '세탁기': 'washing machine',
  '시계': 'clock', '거울': 'mirror', '그릇': 'bowl', '접시': 'plate', '컵': 'cup', '칼': 'knife', '수건': 'towel',
  '비누': 'soap', '이불': 'blanket', '베개': 'pillow', '우산': 'umbrella', '가방': 'bag', '열쇠': 'key',
  '지갑': 'wallet', '안경': 'glasses',
  // 옷
  '옷': 'clothes', '셔츠': 'shirt', '바지': 'pants', '치마': 'skirt', '모자': 'hat', '신발': 'shoes', '양말': 'socks',
  '장갑': 'gloves', '넥타이': 'necktie', '벨트': 'belt', '반지': 'ring', '목걸이': 'necklace',
  // 장소 / 시설
  '학교': 'school', '회사': 'company', '병원': 'hospital', '은행': 'bank', '우체국': 'post office', '도서관': 'library',
  '식당': 'restaurant', '가게': 'shop', '시장': 'market', '백화점': 'department store', '편의점': 'convenience store',
  '서점': 'bookstore', '약국': 'pharmacy', '카페': 'cafe', '공원': 'park', '동물원': 'zoo', '박물관': 'museum',
  '교회': 'church', '절': 'temple', '호텔': 'hotel', '공장': 'factory', '역': 'station', '공항': 'airport',
  '나라': 'country', '도시': 'city', '시골': 'countryside', '마을': 'village', '거리': 'street', '다리': 'bridge',
  // 교통
  '차': 'car', '자동차': 'car', '버스': 'bus', '택시': 'taxi', '지하철': 'subway', '기차': 'train', '비행기': 'airplane',
  '자전거': 'bicycle', '오토바이': 'motorcycle', '트럭': 'truck', '길': 'road',
  // 학교 / 공부
  '공부': 'study', '숙제': 'homework', '시험': 'exam', '수업': 'class', '교실': 'classroom', '칠판': 'blackboard',
  '책': 'book', '교과서': 'textbook', '공책': 'notebook', '연필': 'pencil', '지우개': 'eraser', '가위': 'scissors',
  '자': 'ruler', '문제': 'problem', '답': 'answer', '점수': 'score', '성적': 'grades', '졸업': 'graduation',
  '입학': 'admission', '방학': 'vacation', '교육': 'education', '국어': 'Korean (subject)', '수학': 'math',
  '과학': 'science', '영어': 'English', '역사': 'history', '지리': 'geography', '음악': 'music', '미술': 'art',
  '체육': 'PE', '단어': 'word', '문장': 'sentence', '글': 'writing',
  // 직업 / 경제
  '일': 'work', '직업': 'job', '월급': 'salary', '회의': 'meeting', '서류': 'document', '사장': 'boss', '직원': 'employee',
  '동료': 'colleague', '면접': 'interview', '돈': 'money', '무료': 'free', '유료': 'paid', '할인': 'discount',
  '가격': 'price', '값': 'price', '세금': 'tax', '현금': 'cash', '카드': 'card', '저금': 'savings', '영수증': 'receipt',
  '경제': 'economy', '계산': 'calculation', '예산': 'budget', '판매': 'sale', '구매': 'purchase',
  // 시간 / 달력
  '시간': 'time', '오늘': 'today', '내일': 'tomorrow', '어제': 'yesterday', '지금': 'now', '나중': 'later',
  '아침': 'morning', '점심': 'noon', '저녁': 'evening', '밤': 'night', '새벽': 'dawn', '낮': 'daytime',
  '주': 'week', '주말': 'weekend', '평일': 'weekday', '년': 'year', '날': 'day', '오전': 'AM', '오후': 'PM',
  '매일': 'every day', '항상': 'always', '가끔': 'sometimes', '월요일': 'Monday', '화요일': 'Tuesday',
  '수요일': 'Wednesday', '목요일': 'Thursday', '금요일': 'Friday', '토요일': 'Saturday', '일요일': 'Sunday',
  '생일': 'birthday', '휴일': 'holiday',
  // 형용사
  '크다': 'big', '작다': 'small', '많다': 'many', '적다': 'few', '높다': 'high', '낮다': 'low', '길다': 'long',
  '짧다': 'short', '넓다': 'wide', '좁다': 'narrow', '무겁다': 'heavy', '가볍다': 'light', '빠르다': 'fast',
  '느리다': 'slow', '강하다': 'strong', '약하다': 'weak', '좋다': 'good', '나쁘다': 'bad', '새롭다': 'new',
  '깨끗하다': 'clean', '더럽다': 'dirty', '예쁘다': 'pretty', '귀엽다': 'cute', '멋지다': 'cool', '아름답다': 'beautiful',
  '쉽다': 'easy', '어렵다': 'difficult', '재미있다': 'fun', '재미없다': 'boring', '중요하다': 'important',
  '덥다': 'hot (weather)', '춥다': 'cold (weather)', '뜨겁다': 'hot', '차갑다': 'cold', '따뜻하다': 'warm',
  '시원하다': 'cool', '밝다': 'bright', '어둡다': 'dark', '조용하다': 'quiet', '시끄럽다': 'noisy', '바쁘다': 'busy',
  '피곤하다': 'tired', '아프다': 'sick', '같다': 'same', '다르다': 'different', '비슷하다': 'similar', '특별하다': 'special',
  // 동사
  '가다': 'go', '오다': 'come', '먹다': 'eat', '마시다': 'drink', '자다': 'sleep', '일어나다': 'wake up',
  '걷다': 'walk', '뛰다': 'run', '서다': 'stand', '앉다': 'sit', '보다': 'see', '듣다': 'listen', '말하다': 'speak',
  '읽다': 'read', '쓰다': 'write', '사다': 'buy', '팔다': 'sell', '주다': 'give', '받다': 'receive', '만나다': 'meet',
  '웃다': 'laugh', '울다': 'cry', '놀다': 'play', '쉬다': 'rest', '열다': 'open', '닫다': 'close', '찾다': 'find',
  '만들다': 'make', '고치다': 'fix', '씻다': 'wash', '배우다': 'learn', '가르치다': 'teach', '생각하다': 'think',
  '알다': 'know', '모르다': "don't know", '기억하다': 'remember', '잊다': 'forget', '믿다': 'believe', '돕다': 'help',
  '기다리다': 'wait', '시작하다': 'start', '끝나다': 'end', '살다': 'live', '죽다': 'die', '되다': 'become',
  '있다': 'exist', '없다': 'not exist', '하다': 'do', '필요하다': 'need', '원하다': 'want',
  // 부사 / 의문사 / 대명사
  '아주': 'very', '너무': 'too', '조금': 'a little', '많이': 'a lot', '빨리': 'quickly', '천천히': 'slowly',
  '함께': 'together', '같이': 'together', '혼자': 'alone', '다시': 'again', '정말': 'really', '그리고': 'and',
  '하지만': 'but', '그래서': 'so', '또': 'also',
  '나': 'I', '너': 'you', '우리': 'we', '여기': 'here', '거기': 'there', '어디': 'where', '누구': 'who',
  '무엇': 'what', '뭐': 'what', '왜': 'why', '어떻게': 'how', '언제': 'when', '얼마': 'how much',
  // 동사 (격식/한자어)
  '발생하다': 'occur', '존재하다': 'exist', '포함하다': 'include', '제공하다': 'provide', '제외하다': 'exclude',
  '구성하다': 'compose', '표현하다': 'express', '분석하다': 'analyze', '판단하다': 'judge', '평가하다': 'evaluate',
  '측정하다': 'measure', '증가하다': 'increase', '감소하다': 'decrease', '유지하다': 'maintain', '개발하다': 'develop',
  '생산하다': 'produce', '소비하다': 'consume', '제작하다': 'produce', '건설하다': 'construct', '파괴하다': 'destroy',
  '보호하다': 'protect', '공격하다': 'attack', '방어하다': 'defend', '지원하다': 'support', '협력하다': 'cooperate',
  '참여하다': 'participate', '신청하다': 'apply', '등록하다': 'register', '제출하다': 'submit', '거절하다': 'refuse',
  '승인하다': 'approve', '허락하다': 'permit', '금지하다': 'forbid', '명령하다': 'command', '요청하다': 'request',
  '요구하다': 'demand', '주장하다': 'insist', '반대하다': 'oppose', '동의하다': 'agree', '찬성하다': 'approve',
  '인정하다': 'admit', '거부하다': 'reject', '검사하다': 'inspect', '조사하다': 'investigate', '연구하다': 'research',
  '발표하다': 'announce', '보고하다': 'report', '기록하다': 'record', '저장하다': 'save', '삭제하다': 'delete',
  '수정하다': 'edit', '복사하다': 'copy', '인쇄하다': 'print', '연결하다': 'connect', '분리하다': 'separate',
  '교환하다': 'exchange', '변경하다': 'change', '처리하다': 'process', '관리하다': 'manage', '운영하다': 'operate',
  '진행하다': 'proceed', '완성하다': 'complete', '달성하다': 'achieve', '해결하다': 'solve', '극복하다': 'overcome',
  '적용하다': 'apply', '활용하다': 'utilize', '제한하다': 'limit', '예방하다': 'prevent', '치료하다': 'treat',
  '회복하다': 'recover', '발달하다': 'develop', '모방하다': 'imitate', '창조하다': 'create', '의미하다': 'mean',
  '시도하다': 'try', '도전하다': 'challenge', '경험하다': 'experience', '체험하다': 'experience', '익히다': 'master',
  // 동사 (생활)
  '보내다': 'send', '던지다': 'throw', '잡다': 'catch', '밀다': 'push', '당기다': 'pull', '들다': 'hold',
  '떨어지다': 'fall', '넘어지다': 'fall over', '날다': 'fly', '수영하다': 'swim', '흔들다': 'shake', '두드리다': 'knock',
  '때리다': 'hit', '차다': 'kick', '자르다': 'cut', '붙이다': 'attach', '묶다': 'tie', '풀다': 'untie', '접다': 'fold',
  '펴다': 'spread', '싸다': 'wrap', '붓다': 'pour', '섞다': 'mix', '끓이다': 'boil', '굽다': 'grill', '튀기다': 'fry',
  '삶다': 'boil', '볶다': 'stir-fry', '자라다': 'grow', '키우다': 'raise', '심다': 'plant', '짓다': 'build',
  '부수다': 'break', '움직이다': 'move', '멈추다': 'stop', '돌다': 'turn', '오르다': 'climb', '건너다': 'cross',
  '지나가다': 'pass', '도착하다': 'arrive', '출발하다': 'depart', '떠나다': 'leave', '머물다': 'stay', '돌아오다': 'return',
  '보이다': 'be seen', '들리다': 'be heard', '대답하다': 'answer', '설명하다': 'explain', '소개하다': 'introduce',
  '약속하다': 'promise', '싸우다': 'fight', '도와주다': 'help', '사과하다': 'apologize', '칭찬하다': 'praise',
  '혼내다': 'scold', '결정하다': 'decide', '선택하다': 'choose', '계획하다': 'plan', '바꾸다': 'change', '참다': 'endure',
  '포기하다': 'give up', '노력하다': 'make an effort', '성공하다': 'succeed', '실패하다': 'fail', '이기다': 'win',
  '지다': 'lose', '연습하다': 'practice', '외우다': 'memorize', '이해하다': 'understand', '상상하다': 'imagine',
  '나누다': 'divide', '모으다': 'collect', '버리다': 'throw away', '줍다': 'pick up', '빌리다': 'borrow', '갚다': 'repay',
  '넣다': 'put in', '꺼내다': 'take out', '돕다(추가)': 'help', '구하다': 'save', '얻다': 'obtain', '벌다': 'earn',
  '다니다': 'attend', '향하다': 'head toward', '마주치다': 'run into', '들르다': 'drop by', '줄서다': 'line up',
  '양보하다': 'yield', '미루다': 'postpone', '서두르다': 'hurry', '중단하다': 'interrupt', '취소하다': 'cancel',
  '예약하다': 'reserve', '주문하다': 'order', '배달하다': 'deliver', '지불하다': 'pay', '저축하다': 'save up',
  '투자하다': 'invest', '청소하다': 'clean', '빨래하다': 'do laundry', '정리하다': 'organize', '고르다': 'choose',
  '비교하다': 'compare', '반복하다': 'repeat', '계속하다': 'continue', '그만두다': 'quit', '용서하다': 'forgive',
  '배신하다': 'betray', '떠오르다': 'come to mind', '가라앉다': 'sink', '빠지다': 'drown', '시들다': 'wither',
  '설레다': 'flutter', '깨닫다': 'realize', '무시하다': 'ignore', '존중하다': 'respect', '돌보다': 'care for',
  '기르다': 'raise', '낳다': 'give birth', '견디다': 'endure', '맞서다': 'confront', '구조하다': 'rescue',
  // 형용사
  '멀다': 'far', '가깝다': 'near', '깊다': 'deep', '얕다': 'shallow', '굵다': 'thick', '가늘다': 'thin',
  '단단하다': 'hard', '부드럽다': 'soft', '거칠다': 'rough', '둥글다': 'round', '곧다': 'straight', '젖다': 'wet',
  '위험하다': 'dangerous', '안전하다': 'safe', '건강하다': 'healthy', '편하다': 'comfortable', '불편하다': 'inconvenient',
  '졸리다': 'sleepy', '부지런하다': 'diligent', '솔직하다': 'frank', '겸손하다': 'humble', '어리다': 'young',
  '젊다': 'young', '늙다': 'old', '그립다': 'nostalgic', '부럽다': 'envious', '귀찮다': 'bothersome', '심심하다': 'bored',
  '비싸다': 'expensive', '흔하다': 'common', '드물다': 'rare', '가난하다': 'poor', '부유하다': 'rich', '신기하다': 'amazing',
  '가능하다': 'possible', '소중하다': 'precious', '평범하다': 'ordinary', '이상하다': 'strange', '확실하다': 'certain',
  '분명하다': 'clear', '복잡하다': 'complex', '단순하다': 'simple', '정확하다': 'accurate', '자세하다': 'detailed',
  '대단하다': 'amazing', '훌륭하다': 'excellent', '완벽하다': 'perfect', '충분하다': 'enough', '부족하다': 'insufficient',
  '풍부하다': 'abundant', '다양하다': 'diverse', '자유롭다': 'free', '즐겁다': 'enjoyable', '놀랍다': 'surprising',
  '딱딱하다': 'stiff', '적당하다': 'moderate', '간단하다': 'simple', '거대하다': 'huge', '날씬하다': 'slim',
  '당연하다': 'natural', '엄격하다': 'strict', '관대하다': 'generous', '침착하다': 'calm', '대담하다': 'bold',
  '익숙하다': 'familiar', '낯설다': 'unfamiliar',
  // 명사 (자주 쓰는)
  '관심': 'interest', '흥미': 'interest', '실력': 'ability', '효과': 'effect', '영향': 'influence', '변화': 'change',
  '발전': 'development', '성장': 'growth', '과정': 'process', '단계': 'stage', '순서': 'order', '수준': 'level',
  '정도': 'degree', '양': 'amount', '비율': 'ratio', '평균': 'average', '일부': 'part', '나머지': 'rest',
  '중간': 'middle', '끝': 'end', '기억': 'memory', '추억': 'memories', '기분': 'mood', '느낌': 'feeling',
  '성격': 'personality', '태도': 'attitude', '행동': 'behavior', '분위기': 'atmosphere', '표정': 'expression',
  '목소리': 'voice', '웃음': 'laughter', '눈물': 'tears', '일상': 'daily life', '생활': 'life', '인생': 'life',
  '죽음': 'death', '의미': 'meaning', '가치': 'value', '목적': 'purpose', '장점': 'strength', '단점': 'weakness',
  '특징': 'feature', '조건': 'condition', '결심': 'resolution', '실수': 'mistake', '잘못': 'fault', '자세': 'posture',
  '이유': 'reason', '원인': 'cause', '결과': 'result', '결론': 'conclusion', '핵심': 'core', '주제': 'topic',
  '경향': 'tendency', '유행': 'trend', '인기': 'popularity', '평판': 'reputation', '분야': 'field', '항목': 'item',
  '목록': 'list', '순위': 'ranking', '등급': 'grade', '단위': 'unit', '기준': 'standard',
  // 명사 (사회/학문/기술)
  '세계': 'world', '사회': 'society', '문화': 'culture', '정치': 'politics', '법': 'law', '자유': 'freedom',
  '평화': 'peace', '전쟁': 'war', '환경': 'environment', '자연': 'nature', '미래': 'future', '과거': 'past',
  '현재': 'present', '꿈': 'dream', '희망': 'hope', '목표': 'goal', '약속': 'promise', '비밀': 'secret',
  '진실': 'truth', '거짓말': 'lie', '방법': 'method', '능력': 'ability', '경험': 'experience', '기회': 'chance',
  '습관': 'habit', '취미': 'hobby', '여행': 'travel', '선물': 'gift', '뉴스': 'news', '정보': 'information',
  '소식': 'news', '내용': 'content', '종류': 'kind', '문학': 'literature', '철학': 'philosophy', '역사': 'history',
  '과학자': 'scientist', '실험': 'experiment', '관찰': 'observation', '발견': 'discovery', '에너지': 'energy',
  '전기': 'electricity', '기계': 'machine', '도구': 'tool', '컴퓨터': 'computer', '인터넷': 'internet',
  '전화': 'phone', '휴대폰': 'cellphone', '검색': 'search', '계정': 'account', '비밀번호': 'password',
  '게임': 'game', '사진': 'photo', '영화': 'movie', '음악': 'music', '노래': 'song', '운동': 'exercise', '건강': 'health',
  '병': 'illness', '감기': 'cold', '약': 'medicine', '치료': 'treatment', '수술': 'surgery',
  // 동물
  '참새': 'sparrow', '비둘기': 'pigeon', '까마귀': 'crow', '독수리': 'eagle', '부엉이': 'owl', '올빼미': 'owl',
  '제비': 'swallow', '갈매기': 'seagull', '펭귄': 'penguin', '타조': 'ostrich', '공작': 'peacock', '고래': 'whale',
  '상어': 'shark', '돌고래': 'dolphin', '해파리': 'jellyfish', '메뚜기': 'grasshopper', '잠자리': 'dragonfly',
  '매미': 'cicada', '개미': 'ant', '파리': 'fly', '바퀴벌레': 'cockroach', '달팽이': 'snail', '지렁이': 'earthworm',
  '사슴': 'deer', '늑대': 'wolf', '표범': 'leopard', '기린': 'giraffe', '하마': 'hippo', '코뿔소': 'rhino',
  '캥거루': 'kangaroo', '판다': 'panda', '다람쥐': 'squirrel', '박쥐': 'bat', '악어': 'crocodile', '도마뱀': 'lizard',
  '염소': 'goat', '낙타': 'camel', '너구리': 'raccoon', '멧돼지': 'wild boar', '가오리': 'ray', '장어': 'eel',
  '잉어': 'carp', '붕어': 'crucian carp', '메기': 'catfish', '두루미': 'crane', '백조': 'swan', '앵무새': 'parrot',
  '까치': 'magpie', '고슴도치': 'hedgehog', '반딧불이': 'firefly', '무당벌레': 'ladybug', '사마귀': 'mantis',
  '귀뚜라미': 'cricket', '올챙이': 'tadpole',
  // 식물
  '소나무': 'pine', '대나무': 'bamboo', '버드나무': 'willow', '은행나무': 'ginkgo', '잔디': 'lawn', '이끼': 'moss',
  '선인장': 'cactus', '백합': 'lily', '튤립': 'tulip', '국화': 'chrysanthemum', '민들레': 'dandelion', '연꽃': 'lotus',
  '양배추': 'cabbage', '상추': 'lettuce', '무': 'radish', '콩나물': 'bean sprouts', '부추': 'chives', '인삼': 'ginseng',
  '줄기': 'stem', '새싹': 'sprout', '꽃잎': 'petal', '도토리': 'acorn', '화초': 'plant', '묘목': 'sapling',
  '비료': 'fertilizer', '곡식': 'grain', '보리': 'barley', '밀': 'wheat', '목화': 'cotton', '갈대': 'reed',
  '잡초': 'weed', '가시': 'thorn', '덩굴': 'vine',
  // 음식
  '갈비': 'ribs', '삼겹살': 'pork belly', '불고기': 'bulgogi', '잡채': 'japchae', '냉면': 'cold noodles', '죽': 'porridge',
  '떡국': 'rice cake soup', '젤리': 'jelly', '푸딩': 'pudding', '도넛': 'donut', '와플': 'waffle', '팬케이크': 'pancake',
  '크림': 'cream', '시럽': 'syrup', '견과류': 'nuts', '올리브': 'olive', '참기름': 'sesame oil', '깨': 'sesame',
  '소주': 'soju', '막걸리': 'makgeolli', '참치': 'tuna', '연어': 'salmon', '고등어': 'mackerel', '멸치': 'anchovy',
  '굴': 'oyster', '낙지': 'octopus', '브로콜리': 'broccoli', '파프리카': 'bell pepper', '체리': 'cherry', '망고': 'mango',
  '파인애플': 'pineapple', '키위': 'kiwi', '한식': 'Korean food', '일식': 'Japanese food', '중식': 'Chinese food',
  '양식': 'Western food', '채식': 'vegetarian', '외식': 'eating out', '정식': 'set meal', '안주': 'bar snack',
  '현미': 'brown rice', '찹쌀': 'glutinous rice', '재료': 'ingredient', '후식': 'dessert',
  // 생활용품
  '가구': 'furniture', '서랍': 'drawer', '선반': 'shelf', '옷장': 'wardrobe', '식탁': 'dining table', '전자레인지': 'microwave',
  '청소기': 'vacuum', '다리미': 'iron', '선풍기': 'fan', '난로': 'heater', '콘센트': 'outlet', '전구': 'light bulb',
  '양초': 'candle', '성냥': 'match', '빗': 'comb', '화장품': 'cosmetics', '향수': 'perfume', '휴지': 'tissue',
  '쓰레기': 'trash', '쓰레기통': 'trash can', '빗자루': 'broom', '걸레': 'rag', '양동이': 'bucket', '사다리': 'ladder',
  '망치': 'hammer', '상자': 'box', '봉투': 'envelope', '액자': 'frame', '화분': 'flower pot', '달력': 'calendar',
  '주전자': 'kettle', '전기밥솥': 'rice cooker', '정수기': 'water purifier', '가습기': 'humidifier', '수세미': 'scrubber',
  '옷걸이': 'hanger', '변기': 'toilet', '욕조': 'bathtub', '샤워기': 'shower', '수도꼭지': 'faucet', '손전등': 'flashlight',
  '건전지': 'battery', '충전기': 'charger', '리모컨': 'remote',
  // 옷 / 액세서리
  '티셔츠': 't-shirt', '청바지': 'jeans', '반바지': 'shorts', '원피스': 'dress', '스웨터': 'sweater', '가디건': 'cardigan',
  '점퍼': 'jacket', '패딩': 'padded jacket', '조끼': 'vest', '정장': 'suit', '교복': 'uniform', '잠옷': 'pajamas',
  '속옷': 'underwear', '수영복': 'swimsuit', '운동화': 'sneakers', '구두': 'dress shoes', '부츠': 'boots',
  '슬리퍼': 'slippers', '샌들': 'sandals', '손수건': 'handkerchief', '귀걸이': 'earring', '팔찌': 'bracelet',
  '선글라스': 'sunglasses', '마스크': 'mask', '배낭': 'backpack',
  // 신체
  '눈썹': 'eyebrow', '속눈썹': 'eyelash', '보조개': 'dimple', '주름': 'wrinkle', '수염': 'beard', '손톱': 'nail',
  '주먹': 'fist', '침': 'saliva', '땀': 'sweat', '콧물': 'snot', '숨': 'breath', '골반': 'pelvis', '손등': 'back of hand',
  '정강이': 'shin', '겨드랑이': 'armpit', '배꼽': 'navel', '목구멍': 'throat', '잇몸': 'gums', '앞니': 'front tooth',
  '갈비뼈': 'rib', '척추': 'spine', '근육': 'muscle', '신경': 'nerve', '위': 'stomach', '폐': 'lung', '간': 'liver',
  '혈관': 'blood vessel', '체온': 'body temperature', '맥박': 'pulse', '호흡': 'breathing', '소화': 'digestion',
  '영양': 'nutrition', '체력': 'stamina', '혈압': 'blood pressure', '통증': 'pain', '상처': 'wound',
  // 장소 / 직업
  '사무실': 'office', '매장': 'store', '창고': 'warehouse', '연구소': 'research center', '실험실': 'laboratory',
  '체육관': 'gym', '기숙사': 'dormitory', '휴게실': 'lounge', '회의실': 'meeting room', '응급실': 'emergency room',
  '매표소': 'ticket office', '골목': 'alley', '광장': 'plaza', '가로등': 'streetlight', '우체통': 'mailbox',
  '대문': 'gate', '마당': 'yard', '옥상': 'rooftop', '지하': 'basement', '차고': 'garage', '베란다': 'balcony',
  '복도': 'hallway', '로비': 'lobby', '엘리베이터': 'elevator', '비상구': 'emergency exit', '정문': 'main gate',
  '엔지니어': 'engineer', '디자이너': 'designer', '프로그래머': 'programmer', '통역사': 'interpreter', '번역가': 'translator',
  '소방관': 'firefighter', '비서': 'secretary', '회계사': 'accountant', '약사': 'pharmacist', '수의사': 'vet',
  '변호사': 'lawyer', '판사': 'judge', '기자': 'reporter', '작가': 'writer', '화가': 'painter', '가수': 'singer',
  '배우': 'actor', '농부': 'farmer', '어부': 'fisherman', '미용사': 'hairdresser', '교수': 'professor',
  // 자연 / 지리
  '대륙': 'continent', '반도': 'peninsula', '평야': 'plain', '고원': 'plateau', '빙하': 'glacier', '온천': 'hot spring',
  '화석': 'fossil', '광물': 'mineral', '보석': 'jewel', '진주': 'pearl', '황금': 'gold', '절벽': 'cliff', '늪': 'swamp',
  '초원': 'grassland', '정글': 'jungle', '지평선': 'horizon', '일출': 'sunrise', '일몰': 'sunset', '산불': 'wildfire',
  '해일': 'tsunami', '폭설': 'heavy snow', '오염': 'pollution', '멸종': 'extinction', '생태계': 'ecosystem',
  '위성': 'satellite', '적도': 'equator', '북극': 'north pole', '남극': 'south pole', '습도': 'humidity', '기압': 'pressure',
  // 감정 / 심리
  '절망': 'despair', '우울': 'depression', '불안': 'anxiety', '공포': 'fear', '분노': 'anger', '증오': 'hatred',
  '혐오': 'disgust', '동정': 'sympathy', '호감': 'fondness', '매력': 'charm', '설렘': 'flutter', '안도': 'relief',
  '흥분': 'excitement', '자존심': 'pride', '자존감': 'self-esteem', '열정': 'passion', '의욕': 'motivation',
  '끈기': 'perseverance', '호기심': 'curiosity', '자신감': 'confidence', '용기': 'courage', '질투': 'jealousy',
  '후회': 'regret', '감동': 'being moved', '만족': 'satisfaction', '긴장감': 'tension', '책임감': 'responsibility',
  // 시간 / 기타
  '한여름': 'midsummer', '장마': 'rainy season', '환절기': 'change of seasons', '연말': 'year-end', '설날': "New Year's Day",
  '추석': 'Chuseok', '공휴일': 'public holiday', '기념일': 'anniversary', '마감': 'deadline', '기한': 'deadline',
  '출장': 'business trip', '야근': 'overtime', '퇴직': 'retirement', '승진': 'promotion', '해고': 'dismissal',
  '이직': 'job change', '부서': 'department', '신입': 'newcomer', '아르바이트': 'part-time job', '재택근무': 'remote work',
  // 배치
  '가두다': 'lock up', '가려움': 'itch', '가리키다': 'point', '가사': 'lyrics', '가설': 'hypothesis', '가운데': 'middle',
  '가장': 'most', '가져가다': 'take', '가져오다': 'bring', '가죽': 'leather', '가지다': 'have', '가치관': 'values',
  '각각': 'each', '각도': 'angle', '간식': 'snack', '간장': 'soy sauce', '간접': 'indirect', '갈다': 'grind',
  '갈등': 'conflict', '감': 'persimmon', '감독': 'director', '감상': 'appreciation', '감염': 'infection', '감옥': 'prison',
  '감정': 'emotion', '감추다': 'hide', '감탄': 'admiration', '갑자기': 'suddenly', '강도': 'intensity', '강사': 'instructor',
  '강의': 'lecture', '강조하다': 'emphasize', '강철': 'steel', '개념': 'concept', '개성': 'individuality', '개수': 'count',
  '개인': 'individual', '거들다': 'assist', '거래': 'transaction', '거의': 'almost', '걱정하다': 'worry',
  '건조하다': 'dry', '건축': 'architecture', '걸다': 'hang', '걸리다': 'take (time)', '걸작': 'masterpiece',
  '검색창': 'search bar', '게': 'crab', '게다가': 'moreover', '게시물': 'post', '게으름': 'laziness', '격려': 'encouragement',
  '격차': 'gap', '결국': 'eventually', '결석': 'absence', '결코': 'never', '결혼식': 'wedding', '경기': 'match',
  '경로': 'path', '경영': 'management', '경우': 'case', '경치': 'scenery', '계곡': 'valley', '계약': 'contract',
  '계획': 'plan', '고객': 'customer', '고구마': 'sweet potato', '고등학교': 'high school', '고맙다': 'thankful',
  '고모': 'aunt', '고무': 'rubber', '고민하다': 'agonize', '고속도로': 'highway', '고요하다': 'serene', '고용': 'employment',
  '고추': 'chili', '곡선': 'curve', '곧': 'soon', '골절': 'fracture', '곱다': 'lovely', '곱하기': 'multiplication',
  '곱하다': 'multiply', '공감': 'empathy', '공동체': 'community', '공무원': 'civil servant', '공부하다': 'study',
  '공식': 'formula', '공업': 'industry', '공연': 'performance', '과장': 'manager', '과제': 'assignment', '관객': 'audience',
  '관광': 'tourism', '관광객': 'tourist', '관람': 'viewing', '관절': 'joint', '관점': 'viewpoint', '관중': 'spectators',
  '광고': 'advertisement', '괜찮아': "it's okay", '굉장히': 'extremely', '교통체증': 'traffic jam', '구경하다': 'sightsee',
  '구독': 'subscription', '구르다': 'roll', '구리': 'copper', '구이': 'grilled dish', '구조': 'structure',
  '구체적이다': 'concrete', '구토': 'vomiting', '국경': 'border', '국민': 'citizens', '국자': 'ladle', '국적': 'nationality',
  '국제': 'international', '군대': 'army', '군인': 'soldier', '굳다': 'harden', '굴리다': 'roll', '권리': 'right',
  '권투': 'boxing', '권한': 'authority', '궤도': 'orbit', '귀신': 'ghost', '귀하다': 'precious', '귓불': 'earlobe',
  '규모': 'scale', '규칙': 'rule', '균형': 'balance', '그': 'he', '그것': 'that', '그녀': 'she', '그들': 'they',
  '그래도': 'still', '그러나': 'however', '그런데': 'by the way', '그리다': 'draw', '그리워하다': 'miss', '그림': 'picture',
  '그림자': 'shadow', '그저께': 'two days ago', '극장': 'theater', '근력': 'muscle strength', '근처': 'nearby',
  '금리': 'interest rate', '금메달': 'gold medal', '금색': 'gold', '금속': 'metal', '기관': 'institution',
  '기념품': 'souvenir', '기대하다': 'expect', '기도': 'prayer', '기독교': 'Christianity', '기록': 'record', '기부': 'donation',
  '기어가다': 'crawl', '기업': 'company', '기온': 'temperature', '기침': 'cough', '기타': 'guitar', '기하': 'geometry',
  '기후': 'climate', '길이': 'length', '김': 'seaweed', '김밥': 'gimbap', '깊이': 'depth', '깎다': 'peel',
  '깔끔하다': 'neat', '깨다': 'wake up', '깨달음': 'enlightenment', '깨지다': 'break', '껌': 'gum', '꽃게': 'blue crab',
  '꾸미다': 'decorate', '꿀': 'honey', '꿰매다': 'sew', '끄다': 'turn off', '끄덕이다': 'nod', '끈': 'string',
  '끌다': 'pull', '끓다': 'boil', '끝내다': 'finish', '나가다': 'go out', '나눠주다': 'distribute', '나들이': 'outing',
  '나사': 'screw', '나오다': 'come out', '나이': 'age', '나침반': 'compass', '나타나다': 'appear', '낚시': 'fishing',
  '난민': 'refugee', '날카롭다': 'sharp', '낡다': 'old', '남동생': 'younger brother', '남매': 'siblings', '남쪽': 'south',
  '납': 'lead', '낭비': 'waste', '내려가다': 'go down', '내장': 'internal organs', '냄비': 'pot', '냄새': 'smell',
  '냅킨': 'napkin', '냉정하다': 'cool-headed', '너비': 'width', '넉넉하다': 'ample', '널다': 'hang out', '넓이': 'area',
  '넘치다': 'overflow', '넷': 'four', '노동': 'labor', '노동자': 'worker', '노래방': 'karaoke', '노래하다': 'sing',
  '노력': 'effort', '노을': 'sunset glow', '노트북': 'laptop', '녹다': 'melt', '녹음': 'recording', '녹차': 'green tea',
  '녹화': 'video recording', '논리': 'logic', '논문': 'thesis', '농구': 'basketball', '농도': 'concentration', '농업': 'agriculture',
  '농작물': 'crops', '농장': 'farm', '농촌': 'rural area', '높이': 'height', '놓다': 'put down', '놓치다': 'miss',
  '뇌': 'brain', '누르다': 'press', '눕다': 'lie down', '느끼다': 'feel', '늘': 'always', '늘다': 'increase',
  '늘리다': 'increase', '다가가다': 'approach', '다듬다': 'trim', '다섯': 'five', '다운로드': 'download', '다음': 'next',
  '다이아몬드': 'diamond', '다이어트': 'diet', '다투다': 'quarrel', '다행히': 'fortunately', '닦다': 'wipe', '단골': 'regular',
  '단백질': 'protein', '단체': 'group', '단풍': 'autumn leaves', '닫히다': 'close', '달리기': 'running', '달콤하다': 'sweet',
  '담요': 'blanket', '답답하다': 'frustrating', '당구': 'billiards', '당신': 'you', '당장': 'right now', '당황하다': 'panic',
  '대개': 'usually', '대본': 'script', '대부분': 'most', '대사관': 'embassy', '대양': 'ocean', '대추': 'jujube',
  '대출': 'loan', '대통령': 'president', '대학': 'university', '대화하다': 'converse', '댓글': 'comment', '더위': 'heat',
  '더하다': 'add', '덜': 'less', '데려가다': 'take along', '데이터': 'data', '데이트': 'date', '도덕': 'morality',
  '도마': 'cutting board', '도망가다': 'run away', '도시락': 'lunchbox', '도자기': 'pottery', '독립': 'independence',
  '독서': 'reading', '독점': 'monopoly', '독특하다': 'unique', '돌아가다': 'go back', '돌풍': 'gust', '동경': 'longing',
  '동굴': 'cave', '동맥': 'artery', '동시에': 'at the same time', '동아리': 'club', '동쪽': 'east', '동창': 'alumnus',
  '된장': 'soybean paste', '두껍다': 'thick', '두께': 'thickness', '두렵다': 'fearful', '두부': 'tofu', '두통': 'headache',
  '둘': 'two', '둘레': 'circumference', '뒤': 'back', '뒤집다': 'flip', '드디어': 'finally', '드라마': 'drama',
  '드레스': 'dress', '들어가다': 'enter', '들판': 'field', '등록금': 'tuition', '등산': 'hiking', '디자인': 'design',
  '디저트': 'dessert', '따르다': 'follow', '땅콩': 'peanut', '떡': 'rice cake', '떡볶이': 'tteokbokki', '떨다': 'tremble',
  '떼다': 'detach', '또는': 'or', '또한': 'also', '뚫다': 'pierce', '뚱뚱하다': 'fat', '라이벌': 'rival', '랩': 'wrap',
  '레슬링': 'wrestling', '로그인': 'login', '로봇': 'robot', '리듬': 'rhythm', '마라톤': 'marathon', '마르다': 'dry',
  '마무리하다': 'finish up', '마음': 'heart', '마지막': 'last', '마침내': 'finally', '마케팅': 'marketing', '막내': 'youngest',
  '막다': 'block', '막히다': 'be blocked', '만두': 'dumpling', '만약': 'if', '만지다': 'touch', '만화': 'comic',
  '말리다': 'dry', '맛보다': 'taste', '망설이다': 'hesitate', '맞히다': 'guess right', '맡기다': 'entrust', '맡다': 'take charge',
  '매끄럽다': 'smooth', '매년': 'every year', '매달': 'every month', '매우': 'very', '매주': 'every week', '매출': 'sales',
  '맹세하다': 'swear', '머리카락': 'hair', '먼저': 'first', '먼지': 'dust', '멍': 'bruise', '메뉴': 'menu', '메우다': 'fill',
  '멜로디': 'melody', '며느리': 'daughter-in-law', '며칠': 'a few days', '면': 'noodles', '면역': 'immunity', '면적': 'area',
  '면허': 'license', '명': 'people (counter)', '명상': 'meditation', '명성': 'fame', '명소': 'attraction', '명작': 'masterpiece',
  '명절': 'holiday', '명함': 'business card', '명확하다': 'clear', '몇': 'how many', '모니터': 'monitor', '모두': 'all',
  '모든': 'every', '모레': 'day after tomorrow', '모습': 'appearance', '모이다': 'gather', '모임': 'gathering',
  '모자라다': 'lack', '모퉁이': 'corner', '목도리': 'scarf', '목마르다': 'thirsty', '목사': 'pastor', '못': 'nail',
  '못생기다': 'ugly', '무게': 'weight', '무너지다': 'collapse', '무대': 'stage', '무덥다': 'humid', '무역': 'trade',
  '무용': 'dance', '문어': 'octopus', '문화재': 'cultural asset', '물리': 'physics', '물러나다': 'step back', '물론': 'of course',
  '미끄러지다': 'slip', '미나리': 'water parsley', '미리': 'in advance', '미소짓다': 'smile', '미술관': 'art gallery',
  '미신': 'superstition', '미역': 'seaweed', '미적분': 'calculus', '믹서기': 'blender', '민족': 'ethnic group',
  '밀가루': 'flour', '밀물': 'high tide', '바뀌다': 'change', '바늘': 'needle', '바둑': 'go (game)', '바라다': 'wish',
  '바라보다': 'gaze', '바위': 'rock', '바이러스': 'virus', '바이올린': 'violin', '바퀴': 'wheel', '박사': 'doctorate',
  '박자': 'beat', '밖': 'outside', '반': 'half', '반갑다': 'glad', '반드시': 'surely', '반찬': 'side dish', '반칙': 'foul',
  '발가락': 'toe', '발레': 'ballet', '발명': 'invention', '발목': 'ankle', '발바닥': 'sole', '발열': 'fever', '발표': 'presentation',
  '밝히다': 'reveal', '밧줄': 'rope', '방문하다': 'visit', '방식': 'way', '방향': 'direction', '배고프다': 'hungry',
  '배구': 'volleyball', '배려': 'consideration', '배추': 'napa cabbage', '배터리': 'battery', '백': 'hundred', '백신': 'vaccine',
  '뱉다': 'spit out', '버릇': 'habit', '버튼': 'button', '버티다': 'hold out', '번호': 'number', '벌써': 'already',
  '범위': 'range', '범죄': 'crime', '법칙': 'law', '벗다': 'take off', '벚꽃': 'cherry blossom', '베이컨': 'bacon',
  '벤치': 'bench', '벽돌': 'brick', '벽화': 'mural', '변비': 'constipation', '변하다': 'change', '별로': 'not really',
  '보고서': 'report', '보리차': 'barley tea', '보안': 'security', '보험': 'insurance', '복습': 'review', '복지': 'welfare',
  '복통': 'stomachache', '볶음밥': 'fried rice', '볼': 'cheek', '볼링': 'bowling', '볼펜': 'ballpoint pen', '부담': 'burden',
  '부분': 'part', '부장': 'department head', '부풀다': 'swell', '북쪽': 'north', '분': 'minute', '분량': 'amount',
  '분수': 'fraction', '분자': 'molecule', '불교': 'Buddhism', '불만': 'dissatisfaction', '불타다': 'burn', '불행': 'misfortune',
  '붕대': 'bandage', '브레이크': 'brake', '비겁함': 'cowardice', '비용': 'cost', '비자': 'visa', '비중': 'proportion',
  '비타민': 'vitamin', '빈도': 'frequency', '빈혈': 'anemia', '빚': 'debt', '빛': 'light', '빛나다': 'shine', '빨대': 'straw',
  '빼다': 'subtract', '빼앗다': 'take away', '뾰족하다': 'pointy', '사각형': 'square', '사고': 'accident', '사귀다': 'date',
  '사라지다': 'disappear', '사막': 'desert', '사상': 'thought', '사슬': 'chain', '사실': 'fact', '사업': 'business',
  '사용하다': 'use', '사위': 'son-in-law', '사이': 'between', '사진작가': 'photographer', '사찰': 'temple', '사촌': 'cousin',
  '사탕': 'candy', '산소': 'oxygen', '산업': 'industry', '산책하다': 'take a walk', '상상력': 'imagination', '상식': 'common sense',
  '상업': 'commerce', '상태': 'state', '상품': 'product', '상황': 'situation', '새우': 'shrimp', '새해': 'new year',
  '샌드위치': 'sandwich', '샐러드': 'salad', '생강': 'ginger', '생물': 'biology', '서로': 'each other', '서쪽': 'west',
  '서핑': 'surfing', '석사': "master's", '석유': 'oil', '석탄': 'coal', '선': 'line', '선거': 'election', '선배': 'senior',
  '선수': 'athlete', '설득하다': 'persuade', '설사': 'diarrhea', '설치': 'installation', '섬유질': 'fiber', '성공': 'success',
  '성당': 'cathedral', '성적표': 'report card', '성취감': 'sense of achievement', '세균': 'germ', '세기': 'century',
  '세대': 'generation', '세면대': 'washbasin', '세제': 'detergent', '세포': 'cell', '셋': 'three', '소름끼치다': 'creepy',
  '소리': 'sound', '소문': 'rumor', '소비자': 'consumer', '소설': 'novel', '소스': 'sauce', '소시지': 'sausage',
  '소포': 'parcel', '소풍': 'picnic', '소프트웨어': 'software', '속도': 'speed', '속삭이다': 'whisper', '속이다': 'deceive',
  '손목': 'wrist', '손바닥': 'palm', '손해': 'loss', '쇼핑': 'shopping', '수단': 'means', '수도': 'capital', '수분': 'moisture',
  '수소': 'hydrogen', '수영': 'swimming', '수익': 'profit', '수입': 'income', '수집': 'collection', '수출': 'export',
  '수평선': 'horizon', '수프': 'soup', '순간': 'moment', '숨기다': 'hide', '숫자': 'number', '숲': 'forest', '스님': 'monk',
  '스마트폰': 'smartphone', '스스로': 'oneself', '스승': 'master', '스케이트': 'skating', '스키': 'ski', '스테이크': 'steak',
  '스트레스': 'stress', '스피커': 'speaker', '승부': 'match', '승차권': 'ticket', '시': 'poem', '시간표': 'timetable',
  '시금치': 'spinach', '시대': 'era', '시멘트': 'cement', '시민': 'citizen', '시위': 'protest', '시작': 'start',
  '식단': 'menu', '식초': 'vinegar', '신': 'god', '신념': 'belief', '신뢰': 'trust', '신부': 'bride', '신호': 'signal',
  '실': 'thread', '실망하다': 'be disappointed', '실업': 'unemployment', '실패': 'failure', '심리': 'psychology',
  '심판': 'referee', '쌍둥이': 'twins', '쌓다': 'pile up', '썰물': 'low tide', '쓰러지다': 'collapse', '씹다': 'chew',
  '아까': 'a moment ago', '아끼다': 'cherish', '아래': 'below', '아마': 'maybe', '아무리': 'no matter how', '악기': 'instrument',
  '악마': 'devil', '악보': 'sheet music', '안심하다': 'feel relieved', '안전': 'safety', '알람': 'alarm', '알레르기': 'allergy',
  '알루미늄': 'aluminum', '알리다': 'inform', '앞': 'front', '앞치마': 'apron', '애매하다': 'vague', '앱': 'app',
  '야구': 'baseball', '약간': 'slightly', '약혼': 'engagement', '얇다': 'thin', '양념': 'seasoning', '양심': 'conscience',
  '어느': 'which', '어색하다': 'awkward', '어업': 'fishery', '언어': 'language', '얼다': 'freeze', '얼음': 'ice',
  '엄청': 'extremely', '업로드': 'upload', '엉덩이': 'hip', '에어컨': 'air conditioner', '엔진': 'engine', '여권': 'passport',
  '여동생': 'younger sister', '여러': 'several', '역시': 'as expected', '역할': 'role', '연극': 'play', '연금': 'pension',
  '연락처': 'contact', '연못': 'pond', '연주': 'performance', '열': 'fever', '열등감': 'inferiority complex', '열리다': 'open',
  '엽서': 'postcard', '영상': 'video', '영원': 'eternity', '영혼': 'soul', '옆': 'beside', '예금': 'deposit',
  '예배': 'worship', '예술': 'art', '예의': 'manners', '옛날': 'old days', '오른쪽': 'right', '오빠': 'older brother',
  '오징어': 'squid', '오해': 'misunderstanding', '오히려': 'rather', '옥수수': 'corn', '와이파이': 'Wi-Fi', '완전': 'completely',
  '왜냐하면': 'because', '외국': 'foreign country', '외국인': 'foreigner', '외치다': 'shout', '왼쪽': 'left', '요가': 'yoga',
  '요리사': 'chef', '요점': 'point', '요즘': 'these days', '욕심': 'greed', '용량': 'capacity', '우동': 'udon',
  '우승': 'victory', '우정': 'friendship', '우표': 'stamp', '운': 'luck', '운동장': 'playground', '운명': 'destiny',
  '운전': 'driving', '울타리': 'fence', '원': 'circle', '원리': 'principle', '원자': 'atom', '월세': 'rent',
  '웹사이트': 'website', '위기': 'crisis', '위로': 'comfort', '위치': 'location', '위험': 'danger', '유도': 'judo',
  '유리': 'glass', '유산': 'heritage', '유적': 'ruins', '유치원': 'kindergarten', '윤리': 'ethics', '은색': 'silver',
  '음료': 'beverage', '응급처치': 'first aid', '응원': 'cheering', '의견': 'opinion', '의무': 'duty', '의심하다': 'doubt',
  '이것': 'this', '이론': 'theory', '이름': 'name', '이마': 'forehead', '이메일': 'email', '이모': 'aunt', '이미': 'already',
  '이별': 'farewell', '이익': 'profit', '이자': 'interest', '이전': 'before', '이후': 'after', '인격': 'character',
  '인공지능': 'AI', '인구': 'population', '인권': 'human rights', '인내': 'patience', '인종': 'race', '인턴': 'intern',
  '인형': 'doll', '일부러': 'on purpose', '일정': 'schedule', '일하다': 'work', '잃다': 'lose', '입구': 'entrance',
  '입다': 'wear', '입맛': 'appetite', '입시': 'entrance exam', '입원': 'hospitalization', '입장': 'position', '입장권': 'admission ticket',
  // 마지막 배치 (전체 커버 완성)
  '가지': 'eggplant', '개다': 'fold', '개학': 'start of term', '거래처': 'client', '거르다': 'filter', '거스름돈': 'change',
  '건강검진': 'checkup', '검도': 'kendo', '격려하다': 'encourage', '겸손함': 'humility', '경쟁사': 'competitor',
  '계산대': 'cashier', '계약서': 'contract', '계획표': 'schedule', '고명': 'topping', '고무장갑': 'rubber gloves',
  '고소하다': 'savory', '골프': 'golf', '곱셈': 'multiplication', '공기청정기': 'air purifier', '공평하다': 'fair',
  '관찰력': 'observation', '광대뼈': 'cheekbone', '괜찮아요': "it's okay", '교과목': 'subject', '교환권': 'voucher',
  '국악': 'Korean music', '권': 'volume', '권하다': 'recommend', '그늘': 'shade', '그럴듯하다': 'plausible', '그루': 'tree (counter)',
  '극지방': 'polar region', '기대다': 'lean', '기질': 'temperament', '기침하다': 'cough', '깻잎': 'perilla leaf', '꼬끼오': 'cock-a-doodle-doo',
  '꼭': 'surely', '꼼꼼히': 'meticulously', '꿀꿀': 'oink', '끈적이다': 'be sticky', '나누기': 'division', '나눗셈': 'division',
  '나타내다': 'represent', '낙천적이다': 'optimistic', '내려오다': 'come down', '내쉬다': 'exhale', '노려보다': 'glare',
  '녹아내리다': 'melt', '논쟁하다': 'argue', '농담하다': 'joke', '누에': 'silkworm', '눅눅하다': 'damp', '눈치채다': 'notice',
  '느긋하다': 'relaxed', '느끼하다': 'greasy', '늘어나다': 'stretch', '늦가을': 'late autumn', '늦추다': 'delay',
  '다락방': 'attic', '다림질하다': 'iron', '다짐하다': 'vow', '달래다': 'soothe', '달빛': 'moonlight', '담그다': 'soak',
  '담백하다': 'plain', '담장': 'wall', '답장하다': 'reply', '대': 'unit (counter)', '대걸레': 'mop', '대기': 'atmosphere',
  '대기실': 'waiting room', '대수': 'algebra', '대접하다': 'treat', '대충': 'roughly', '더하기': 'addition', '덧셈': 'addition',
  '데우다': 'heat up', '데치다': 'blanch', '도장': 'stamp', '돌리다': 'turn', '돌잔치': 'first birthday party', '동안': 'during',
  '되풀이하다': 'repeat', '두근거리다': 'throb', '두근두근': 'thump', '두배': 'double', '둔하다': 'dull', '둘러보다': 'look around',
  '드러내다': 'reveal', '들뜨다': 'be excited', '들어오다': 'come in', '들이마시다': 'inhale', '따라가다': 'follow',
  '따라서': 'therefore', '땅콩버터': 'peanut butter', '떠다니다': 'float', '떠맡다': 'undertake', '떠올리다': 'recall',
  '떫다': 'astringent', '뜨개질하다': 'knit', '뜨끈하다': 'warm', '마리': 'animal (counter)', '마요네즈': 'mayonnaise',
  '마우스': 'mouse', '마치다': 'finish', '만': 'ten thousand', '맏이': 'eldest', '말랑말랑하다': 'soft', '맞아': "that's right",
  '매끈하다': 'smooth', '매다': 'tie', '매콤하다': 'spicy', '멍멍': 'woof', '메달': 'medal', '메마르다': 'dry up',
  '메시지': 'message', '면역력': 'immunity', '모르겠어': "I don't know", '모르다': 'not know', '모호하다': 'ambiguous',
  '못마땅하다': 'displeased', '무르다': 'soft', '무승부': 'draw', '무치다': 'season', '무한하다': 'infinite', '문지르다': 'rub',
  '물다': 'bite', '미끄럽다': 'slippery', '미세하다': 'minute', '미워하다': 'hate', '미지근하다': 'lukewarm', '밀도': 'density',
  '밑간': 'marinade', '바로잡다': 'correct', '바르다': 'apply', '바삭하다': 'crispy', '반들반들': 'shiny', '반성하다': 'reflect',
  '반지름': 'radius', '반짝반짝': 'twinkle', '반짝이다': 'sparkle', '반품하다': 'return', '발등': 'instep', '발언하다': 'speak',
  '발표회': 'recital', '방정식': 'equation', '배경음악': 'background music', '배달음식': 'delivery food', '배려하다': 'be considerate',
  '배짱': 'guts', '백업': 'backup', '번': 'time (counter)', '번지다': 'spread', '범주': 'category', '변명하다': 'make excuses',
  '보글보글': 'bubbling', '보살피다': 'care for', '보온병': 'thermos', '보증서': 'warranty', '보통': 'usually', '복습하다': 'review',
  '볶음': 'stir-fry', '본성': 'nature', '볼트': 'bolt', '부당하다': 'unfair', '부들부들': 'trembling', '부딪치다': 'collide',
  '부러지다': 'break', '부르다': 'call', '부지런함': 'diligence', '부탁하다': 'ask a favor', '부피': 'volume', '분지': 'basin',
  '분포': 'distribution', '불안하다': 'anxious', '붐비다': 'be crowded', '붓': 'brush', '뷔페': 'buffet', '블루베리': 'blueberry',
  '비난하다': 'criticize', '비리다': 'fishy', '비범하다': 'extraordinary', '비비다': 'rub', '비빔밥': 'bibimbap', '비우다': 'empty',
  '비행': 'flight', '빛바래다': 'fade', '빨래집게': 'clothespin', '빳빳하다': 'stiff', '빼기': 'subtraction', '뺄셈': 'subtraction',
  '뻔하다': 'obvious', '사랑니': 'wisdom tooth', '사랑하다': 'love', '사무': 'office work', '사직': 'resignation', '산만하다': 'distracted',
  '산호초': 'coral reef', '살짝': 'lightly', '살펴보다': 'examine', '살피다': 'look out', '삶': 'life', '삼각형': 'triangle',
  '삼촌': 'uncle', '삼키다': 'swallow', '상냥함': 'gentleness', '상하다': 'spoil', '새다': 'leak', '새콤하다': 'sour',
  '생각': 'thought', '생각나다': 'come to mind', '생기다': 'arise', '생수': 'bottled water', '서리': 'frost', '서명': 'signature',
  '서비스': 'service', '석사': "master's", '선선하다': 'cool', '설거지하다': 'wash dishes', '설날': 'New Year', '설명서': 'manual',
  '성실하다': 'sincere', '성질': 'nature', '세다': 'count', '세련되다': 'sophisticated', '세우다': 'set up', '소개팅': 'blind date',
  '소극적이다': 'passive', '소리치다': 'shout', '소망': 'wish', '소수': 'decimal', '소심하다': 'timid', '소재': 'material',
  '소질': 'aptitude', '속다': 'be deceived', '솔방울': 'pinecone', '송이': 'bunch', '수량': 'quantity', '수리하다': 'repair',
  '수수하다': 'plain', '수순': 'procedure', '수치심': 'shame', '숟가락': 'spoon', '숨다': 'hide', '스며들다': 'seep',
  '습성': 'habit', '시끌벅적하다': 'bustling', '시리얼': 'cereal', '시어머니': 'mother-in-law', '시작되다': 'begin',
  '시키다': 'order', '시험지': 'test paper', '식다': 'cool down', '식사': 'meal', '식욕': 'appetite', '식용유': 'cooking oil',
  '식재료': 'ingredients', '식히다': 'cool', '신다': 'put on (shoes)', '신분증': 'ID card', '신선하다': 'fresh', '신앙': 'faith',
  '신중함': 'caution', '신호등': 'traffic light', '신혼여행': 'honeymoon', '실례합니다': 'excuse me', '실습': 'practicum',
  '실용적이다': 'practical', '싫어하다': 'dislike', '심각하다': 'serious', '쌀쌀하다': 'chilly', '쌍': 'pair', '쓰다듬다': 'stroke',
  '쓰레받기': 'dustpan', '아깝다': 'wasteful', '아무튼': 'anyway', '아스파라거스': 'asparagus', '아이디': 'ID', '아이스크림': 'ice cream',
  '아장아장': 'toddling', '아직': 'yet', '안': 'inside', '안내소': 'information desk', '안녕히계세요': 'goodbye', '안전벨트': 'seatbelt',
  '알겠어': 'got it', '알림': 'notification', '알아채다': 'notice', '암기': 'memorization', '압박': 'pressure', '앞당기다': 'move up',
  '애완동물': 'pet', '야옹': 'meow', '약도': 'sketch map', '약속시간': 'appointment time', '양념장': 'sauce', '양수': 'positive number',
  '어기다': 'break (a rule)', '어수선하다': 'messy', '어지럼증': 'dizziness', '어쩌면': 'maybe', '얼어붙다': 'freeze',
  '업데이트': 'update', '엉금엉금': 'crawling', '에스컬레이터': 'escalator', '여권사진': 'passport photo', '여보세요': 'hello',
  '여행하다': 'travel', '엮다': 'weave', '연기': 'smoke', '연설하다': 'give a speech', '연약하다': 'frail', '연장': 'tool',
  '연장전': 'overtime', '연초': 'beginning of year', '염좌': 'sprain', '영': 'zero', '영양제': 'supplement', '영원하다': 'eternal',
  '예민하다': 'sensitive', '예방접종': 'vaccination', '예습': 'preview', '예습하다': 'prepare lessons', '예절': 'etiquette',
  '오로지': 'only', '오존층': 'ozone layer', '오케스트라': 'orchestra', '오한': 'chills', '오해하다': 'misunderstand',
  '올라가다': 'go up', '올라오다': 'come up', '요리법': 'recipe', '요리하다': 'cook', '욕하다': 'curse', '용적': 'capacity',
  '우박': 'hail', '우연히': 'by chance', '운동하다': 'exercise', '운석': 'meteorite', '운전하다': 'drive', '울긋불긋': 'colorful',
  '울리다': 'ring', '울퉁불퉁하다': 'bumpy', '위로하다': 'comfort', '위협하다': 'threaten', '윙윙': 'buzz', '유전자': 'gene',
  '유형': 'type', '은하수': 'Milky Way', '음수': 'negative number', '음정': 'pitch', '응원단': 'cheering squad', '응원하다': 'cheer',
  '의식하다': 'be conscious', '의지하다': 'rely on', '이루다': 'achieve', '이민': 'immigration', '이사하다': 'move', '이상적이다': 'ideal',
  '이슬': 'dew', '이슬람교': 'Islam', '이쑤시개': 'toothpick', '이야기': 'story', '이어가다': 'continue', '이어폰': 'earphones',
  '이용하다': 'use', '이해력': 'comprehension', '인내심': 'patience', '인사하다': 'greet', '인연': 'connection', '인원': 'number of people',
  '일교차': 'temperature range', '일시적이다': 'temporary', '일어서다': 'stand up', '입술': 'lips', '입학식': 'entrance ceremony',
  '입학하다': 'enroll', '자갈': 'gravel', '자격': 'qualification', '자격증': 'certificate', '자두': 'plum', '자매': 'sisters',
  '자물쇠': 'lock', '자부심': 'pride', '자석': 'magnet', '자연스럽다': 'natural', '자영업': 'self-employment', '자원': 'resource',
  '자주': 'often', '작곡': 'composition', '작품': 'work', '잔': 'glass (counter)', '잔돈': 'change', '잔치': 'feast',
  '잘부탁해': 'nice to meet you', '잘하다': 'be good at', '잠': 'sleep', '잠깐': 'a moment', '잠수하다': 'dive', '잠시': 'a while',
  '잡곡': 'grains', '잡히다': 'be caught', '장': 'sheet (counter)', '장기': 'janggi', '장난감': 'toy', '장단': 'rhythm',
  '장래': 'future', '장례식': 'funeral', '장미': 'rose', '장학금': 'scholarship', '재': 'ash', '재개하다': 'resume', '재고': 'stock',
  '재능': 'talent', '재다': 'measure', '재미': 'fun', '재질': 'material', '재채기하다': 'sneeze', '재판': 'trial', '재활': 'rehab',
  '잼': 'jam', '쟁반': 'tray', '저': 'I', '저것': 'that', '저기': 'over there', '저리다': 'be numb', '저절로': 'by itself',
  '적': 'enemy', '적극적이다': 'active', '적금': 'savings', '적시다': 'wet', '전': 'pancake', '전공': 'major', '전등': 'lamp',
  '전복': 'abalone', '전봇대': 'utility pole', '전부': 'all', '전시': 'exhibition', '전시회': 'exhibition', '전염병': 'epidemic',
  '전체': 'whole', '전통': 'tradition', '전통문화': 'traditional culture', '전하다': 'convey', '전학': 'transfer', '전혀': 'not at all',
  '절대': 'absolutely', '절반': 'half', '절약': 'saving', '절이다': 'pickle', '절임': 'pickles', '절차': 'procedure', '점': 'mole',
  '점검하다': 'inspect', '점원': 'clerk', '점점': 'gradually', '점차': 'gradually', '접착제': 'glue', '젓가락': 'chopsticks',
  '정규직': 'full-time', '정당하다': 'just', '정돈하다': 'tidy up', '정류장': 'bus stop', '정맥': 'vein', '정부': 'government',
  '정성': 'sincerity', '정수': 'integer', '정신': 'spirit', '정오': 'noon', '정원': 'garden', '정의': 'definition',
  '정직함': 'honesty', '정책': 'policy', '정체성': 'identity', '제대로': 'properly', '제도': 'system', '제목': 'title',
  '제사': 'memorial rite', '제일': 'most', '제자': 'disciple', '조각': 'piece', '조각상': 'statue', '조개': 'clam',
  '조류': 'tide', '조림': 'braised dish', '조이다': 'tighten', '조직': 'organization', '조카': 'nephew', '존경': 'respect',
  '졸다': 'doze', '졸업식': 'graduation', '졸업장': 'diploma', '졸업하다': 'graduate', '종교': 'religion', '종목': 'event',
  '종아리': 'calf', '종이': 'paper', '종종': 'sometimes', '좋아하다': 'like', '좌석': 'seat', '죄책감': 'guilt', '주걱': 'rice paddle',
  '주룩주룩': 'pouring', '주사': 'injection', '주소': 'address', '주식': 'stock', '주유소': 'gas station', '주저하다': 'hesitate',
  '주제곡': 'theme song', '주차장': 'parking lot', '준비': 'preparation', '준비하다': 'prepare', '준우승': 'runner-up',
  '줄다': 'decrease', '줄어들다': 'shrink', '줄이다': 'reduce', '줄자': 'tape measure', '중력': 'gravity', '중반': 'middle',
  '중심': 'center', '중학교': 'middle school', '쥐다': 'grip', '즉': 'namely', '즐거움': 'joy', '즐겨찾기': 'bookmark',
  '증거': 'evidence', '증권': 'securities', '증명': 'proof', '지각': 'lateness', '지겹다': 'tiresome', '지구촌': 'global village',
  '지나치다': 'pass by', '지도': 'map', '지루하다': 'boring', '지름': 'diameter', '지름길': 'shortcut', '지방': 'fat',
  '지속적이다': 'continuous', '지식': 'knowledge', '지옥': 'hell', '지인': 'acquaintance', '지저분하다': 'messy', '지진': 'earthquake',
  '지치다': 'get tired', '지키다': 'protect', '지팡이': 'cane', '지혜': 'wisdom', '직각': 'right angle', '직선': 'straight line',
  '직접': 'directly', '진눈깨비': 'sleet', '진동': 'vibration', '진료': 'medical care', '진리': 'truth', '진짜': 'real',
  '진흙': 'mud', '질기다': 'tough', '질서': 'order', '질투하다': 'be jealous', '집단': 'group', '집중력': 'concentration',
  '집중하다': 'concentrate', '짝수': 'even number', '째깍째깍': 'tick-tock', '짹짹': 'tweet', '쫄깃하다': 'chewy', '쫓다': 'chase',
  '찌개': 'stew', '찢다': 'tear', '찢어지다': 'be torn', '차별': 'discrimination', '차분하다': 'calm', '차이': 'difference',
  '차지하다': 'occupy', '착각하다': 'mistake', '참가하다': 'participate', '참아내다': 'endure', '창의력': 'creativity', '채우다': 'fill',
  '채점': 'grading', '책임': 'responsibility', '책장': 'bookshelf', '챙기다': 'take care of', '처방전': 'prescription', '처벌': 'punishment',
  '처음': 'first', '척': 'ship (counter)', '천': 'thousand', '천국': 'heaven', '천만에요': "you're welcome", '천사': 'angel',
  '천연가스': 'natural gas', '천주교': 'Catholicism', '철사': 'wire', '청첩장': 'wedding invitation', '청춘': 'youth', '체': 'sieve',
  '체격': 'physique', '체계': 'system', '체스': 'chess', '체온계': 'thermometer', '체조': 'gymnastics', '체중': 'body weight',
  '체질': 'constitution', '쳐다보다': 'stare', '초': 'second', '초대하다': 'invite', '초등학교': 'elementary school', '초반': 'early stage',
  '초밥': 'sushi', '초콜릿': 'chocolate', '촉촉하다': 'moist', '촌스럽다': 'tacky', '최근': 'recently', '최대': 'maximum', '최소': 'minimum',
  '추상적이다': 'abstract', '추세': 'trend', '추위': 'cold', '축구': 'soccer', '축의금': 'wedding gift money', '축제': 'festival',
  '축축하다': 'damp', '축하하다': 'congratulate', '출구': 'exit', '출근': 'commute', '출근하다': 'go to work', '출석': 'attendance',
  '춤': 'dance', '충격': 'shock', '충돌하다': 'collide', '충전': 'charging', '취직': 'getting a job', '취향': 'taste', '치통': 'toothache',
  '친절함': 'kindness', '침실': 'bedroom', '칫솔': 'toothbrush', '카드게임': 'card game', '카레': 'curry', '카메라': 'camera',
  '칵테일': 'cocktail', '캠핑': 'camping', '케이크': 'cake', '케첩': 'ketchup', '켜다': 'turn on', '켤레': 'pair', '코스모스': 'cosmos',
  '코트': 'coat', '콘서트': 'concert', '콘크리트': 'concrete', '쾅': 'bang', '쿠키': 'cookie', '쿠폰': 'coupon', '쿵': 'thud',
  '클릭': 'click', '키': 'height', '키보드': 'keyboard', '타다': 'ride', '탁구': 'table tennis', '탄산수': 'sparkling water',
  '탄산음료': 'soda', '탄수화물': 'carbohydrate', '태권도': 'taekwondo', '태블릿': 'tablet', '태어나다': 'be born', '터널': 'tunnel',
  '터지다': 'burst', '터치': 'touch', '턱': 'chin', '텀블러': 'tumbler', '테니스': 'tennis', '테이프': 'tape', '텔레비전': 'television',
  '토론': 'debate', '토론하다': 'discuss', '토스터': 'toaster', '토스트': 'toast', '톱': 'saw', '통계': 'statistics', '통과하다': 'pass',
  '통로': 'aisle', '통밀': 'whole wheat', '통일': 'unification', '통장': 'bankbook', '통화하다': 'talk on the phone', '퇴근': 'leaving work',
  '퇴근하다': 'leave work', '퇴원': 'discharge', '투자': 'investment', '튀김': 'tempura', '튀다': 'bounce', '특기': 'specialty',
  '특성': 'characteristic', '특히': 'especially', '튼튼하다': 'sturdy', '틀리다': 'be wrong', '파': 'green onion', '파다': 'dig',
  '파도': 'wave', '파산': 'bankruptcy', '파업': 'strike', '파일': 'file', '파티': 'party', '판소리': 'pansori', '팔꿈치': 'elbow',
  '퍼센트': 'percent', '퍼즐': 'puzzle', '페인트': 'paint', '펜치': 'pliers', '편안하다': 'comfortable', '편지': 'letter',
  '평등': 'equality', '평생': 'lifetime', '평소': 'usually', '평온': 'tranquility', '평평하다': 'flat', '평화롭다': 'peaceful',
  '포근하다': 'cozy', '포인트': 'point', '포장하다': 'wrap', '폭': 'width', '폭발하다': 'explode', '폭신폭신': 'fluffy', '폭우': 'downpour',
  '폭포': 'waterfall', '폭풍': 'storm', '폴더': 'folder', '표': 'ticket', '푹신하다': 'fluffy', '품절': 'sold out', '품종': 'breed',
  '품질': 'quality', '풍경': 'scenery', '풍선': 'balloon', '풍습': 'custom', '풍족하다': 'abundant', '프라이팬': 'frying pan',
  '프로그램': 'program', '프리랜서': 'freelancer', '프린터': 'printer', '플라스틱': 'plastic', '피로': 'fatigue', '피아노': 'piano',
  '피어나다': 'bloom', '피자': 'pizza', '피하다': 'avoid', '하나': 'one', '하드웨어': 'hardware', '하찮다': 'trivial', '하트': 'heart',
  '하품하다': 'yawn', '학기': 'semester', '학년': 'grade', '학원': 'academy', '학위': 'degree', '학점': 'credit', '한가하다': 'free',
  '한겨울': 'midwinter', '한계': 'limit', '한복': 'hanbok', '한산하다': 'quiet', '한지': 'Korean paper', '한참': 'a while',
  '핥다': 'lick', '함부로': 'recklessly', '합격하다': 'pass', '합계': 'total', '합리적이다': 'reasonable', '합창': 'chorus',
  '합치다': 'combine', '합하다': 'sum', '항공편': 'flight', '항구': 'port', '해바라기': 'sunflower', '해킹': 'hacking', '해협': 'strait',
  '핸드폰': 'cellphone', '햄': 'ham', '햄버거': 'hamburger', '햇빛': 'sunlight', '행복하다': 'happy', '행사': 'event', '행성': 'planet',
  '행운': 'luck', '향기': 'scent', '허물다': 'demolish', '허벅지': 'thigh', '헌법': 'constitution', '헤매다': 'wander', '헤어지다': 'break up',
  '헬멧': 'helmet', '헹구다': 'rinse', '혀': 'tongue', '혁명': 'revolution', '현실적이다': 'realistic', '혈당': 'blood sugar',
  '협상하다': 'negotiate', '형제': 'brothers', '형태': 'form', '혜성': 'comet', '호두': 'walnut', '호르몬': 'hormone', '호박': 'pumpkin',
  '호일': 'foil', '혹시': 'by any chance', '혼란': 'chaos', '홀수': 'odd number', '홍보': 'PR', '홍수': 'flood', '화가나다': 'get angry',
  '화려하다': 'splendid', '화면': 'screen', '화산': 'volcano', '화상': 'burn', '화질': 'image quality', '화창하다': 'sunny',
  '화학': 'chemistry', '화해': 'reconciliation', '확인하다': 'confirm', '환갑': '60th birthday', '환불하다': 'refund', '환승': 'transfer',
  '환율': 'exchange rate', '환자': 'patient', '환전': 'currency exchange', '환풍기': 'ventilation fan', '활발하다': 'lively',
  '황사': 'yellow dust', '황혼': 'twilight', '회': 'sashimi', '회계': 'accounting', '회사원': 'office worker', '회식': 'company dinner',
  '회오리': 'tornado', '회원가입': 'sign up', '횟수': 'number of times', '횡단보도': 'crosswalk', '효율적이다': 'efficient',
  '후문': 'back gate', '후반': 'second half', '후배': 'junior', '후추': 'pepper', '후회하다': 'regret', '훨씬': 'much more',
  '휘발유': 'gasoline', '휴가': 'vacation', '휴식': 'rest', '휴학': 'leave of absence', '흐르다': 'flow', '흔들리다': 'shake', '힘': 'strength',
  '더': 'more', '더럽히다': 'dirty', '부탁해': 'please', '싫어해': 'dislike', '졸졸': 'trickling', '좋아해': 'like', '축하해': 'congrats',
  '질문': 'question', '대답': 'answer',
  // 반대말 쌍 보강용 추가
  '행복하다': 'happy', '불행하다': 'unhappy', '맞다': 'correct', '늦다': 'late', '이르다': 'early', '진하다': 'thick', '연하다': 'light', '맑다': 'clear', '흐리다': 'cloudy', '싱겁다': 'bland', '부정확하다': 'inaccurate', '내리다': 'go down', '전진하다': 'advance', '후퇴하다': 'retreat', '흩어지다': 'scatter', '수요': 'demand', '공급': 'supply', '실제': 'reality', '어둠': 'darkness', '승리': 'victory', '패배': 'defeat', '거짓': 'falsehood', '어린이': 'child', '노인': 'elderly', '공개': 'disclosure', '퇴장': 'exit',
}
