export interface Word { en: string; ko: string; ja: string; yomi: string }

/**
 * 중등 기본 영단어 900 (Korea middle-school essential English vocabulary).
 * en + Korean meaning are finalised; ja (Japanese) + yomi (kana) are filled in
 * batches. Words with ja='' are shown EN+KO only (JA toggle hidden until filled).
 */
export const MIDDLE_WORDS: Word[] = [
  { en: 'plan', ko: '계획(하다)', ja: '', yomi: '' }, { en: 'area', ko: '지역, 분야', ja: '', yomi: '' }, { en: 'subway', ko: '지하철', ja: '', yomi: '' }, { en: 'understand', ko: '이해하다', ja: '', yomi: '' },
  { en: 'interest', ko: '관심(흥미)을 끌다', ja: '', yomi: '' }, { en: 'park', ko: '공원, 주차하다', ja: '', yomi: '' }, { en: 'activity', ko: '활동', ja: '', yomi: '' }, { en: 'set', ko: '두다(놓다), 세우다', ja: '', yomi: '' },
  { en: 'make', ko: '만들다', ja: '', yomi: '' }, { en: 'finish', ko: '끝내다(끝나다)', ja: '', yomi: '' }, { en: 'wait', ko: '기다리다', ja: '', yomi: '' }, { en: 'village', ko: '마을', ja: '', yomi: '' },
  { en: 'person', ko: '사람', ja: '', yomi: '' }, { en: 'report', ko: '보고(보도)(하다)', ja: '', yomi: '' }, { en: 'mean', ko: '의미하다', ja: '', yomi: '' }, { en: 'sell', ko: '팔다', ja: '', yomi: '' },
  { en: 'leave', ko: '떠나다, 내버려두다', ja: '', yomi: '' }, { en: 'letter', ko: '편지', ja: '', yomi: '' }, { en: 'clone', ko: '복제생물, 복제하다', ja: '', yomi: '' }, { en: 'begin', ko: '시작하다', ja: '', yomi: '' },
  { en: 'voice', ko: '목소리', ja: '', yomi: '' }, { en: 'wear', ko: '입고(신고, 쓰고)있다', ja: '', yomi: '' }, { en: 'agree', ko: '동의하다', ja: '', yomi: '' }, { en: 'ground', ko: '운동장, 땅', ja: '', yomi: '' },
  { en: 'land', ko: '육지, 착륙하다', ja: '', yomi: '' }, { en: 'goal', ko: '목표(목적), 골(득점)', ja: '', yomi: '' }, { en: 'art', ko: '미술, 예술, 기술', ja: '', yomi: '' }, { en: 'wash', ko: '씻다', ja: '', yomi: '' },
  { en: 'surprise', ko: '놀라게 하다, 놀람', ja: '', yomi: '' }, { en: 'group', ko: '무리, 집단', ja: '', yomi: '' }, { en: 'line', ko: '선(줄), 줄을 서다', ja: '', yomi: '' }, { en: 'spring', ko: '봄, 용수철, 샘, 튀다', ja: '', yomi: '' },
  { en: 'arm', ko: '팔, (~s)무기', ja: '', yomi: '' }, { en: 'waste', ko: '낭비하다, 쓰레기', ja: '', yomi: '' }, { en: 'rock', ko: '바위, 록음악, 흔들다', ja: '', yomi: '' }, { en: 'way', ko: '방법, 길', ja: '', yomi: '' },
  { en: 'grow', ko: '성장하다, 기르다, 되다', ja: '', yomi: '' }, { en: 'use', ko: '사용(이용)하다', ja: '', yomi: '' }, { en: 'fact', ko: '사실', ja: '', yomi: '' }, { en: 'part', ko: '부분, 가르다', ja: '', yomi: '' },
  { en: 'follow', ko: '따르다', ja: '', yomi: '' }, { en: 'visit', ko: '방문하다', ja: '', yomi: '' }, { en: 'draw', ko: '그리다, 끌다, 뽑다', ja: '', yomi: '' }, { en: 'bottle', ko: '병', ja: '', yomi: '' },
  { en: 'bear', ko: '낳다, 곰', ja: '', yomi: '' }, { en: 'fall', ko: '떨어지다, 가을, 폭포', ja: '', yomi: '' }, { en: 'vacation', ko: '휴가, 방학', ja: '', yomi: '' }, { en: 'vegetable', ko: '채소, 야채', ja: '', yomi: '' },
  { en: 'die', ko: '죽다', ja: '', yomi: '' }, { en: 'result', ko: '결과(로 생기다)', ja: '', yomi: '' }, { en: 'wish', ko: '바라다, 소원(소망)', ja: '', yomi: '' }, { en: 'smell', ko: '냄새(나다)', ja: '', yomi: '' },
  { en: 'remember', ko: '기억하다', ja: '', yomi: '' }, { en: 'take', ko: '데려(가져)가다', ja: '', yomi: '' }, { en: 'lose', ko: '지다, 잃다', ja: '', yomi: '' }, { en: 'hold', ko: '잡고 있다, 개최하다', ja: '', yomi: '' },
  { en: 'restaurant', ko: '레스토랑, 식당', ja: '', yomi: '' }, { en: 'matter', ko: '문제, 물질, 중요하다', ja: '', yomi: '' }, { en: 'enjoy', ko: '즐기다', ja: '', yomi: '' }, { en: 'store', ko: '가게, 비축하다', ja: '', yomi: '' },
  { en: 'get', ko: '얻다', ja: '', yomi: '' }, { en: 'save', ko: '구하다, 저축(절약)하다', ja: '', yomi: '' }, { en: 'wall', ko: '벽, 담', ja: '', yomi: '' }, { en: 'weight', ko: '무게, 몸무게', ja: '', yomi: '' },
  { en: 'stay', ko: '머무르다, ~인 채로 있다', ja: '', yomi: '' }, { en: 'fly', ko: '날다, 파리', ja: '', yomi: '' }, { en: 'send', ko: '보내다', ja: '', yomi: '' }, { en: 'office', ko: '사무실, 관청', ja: '', yomi: '' },
  { en: 'contest', ko: '경쟁(경연)(하다)', ja: '', yomi: '' }, { en: 'miss', ko: '놓치다, 그리워하다', ja: '', yomi: '' }, { en: 'experience', ko: '경험(하다)', ja: '', yomi: '' }, { en: 'side', ko: '측면', ja: '', yomi: '' },
  { en: 'point', ko: '요점, 점수, 가리키다', ja: '', yomi: '' }, { en: 'invent', ko: '발명하다, 지어내다', ja: '', yomi: '' }, { en: 'mind', ko: '마음, 꺼리다', ja: '', yomi: '' }, { en: 'end', ko: '끝(나다)', ja: '', yomi: '' },
  { en: 'win', ko: '이기다, 획득하다', ja: '', yomi: '' }, { en: 'happen', ko: '일어나다, 우연히~하다', ja: '', yomi: '' }, { en: 'listen', ko: '듣다', ja: '', yomi: '' }, { en: 'find', ko: '찾아내다', ja: '', yomi: '' },
  { en: 'earth', ko: '지구, 땅', ja: '', yomi: '' }, { en: 'shape', ko: '모양, (건강)상태', ja: '', yomi: '' }, { en: 'problem', ko: '문제', ja: '', yomi: '' }, { en: 'rule', ko: '규칙, 지배(하다)', ja: '', yomi: '' },
  { en: 'cover', ko: '덮다(씌우다), 덮개', ja: '', yomi: '' }, { en: 'hurt', ko: '다치게 하다, 다친, 상처', ja: '', yomi: '' }, { en: 'build', ko: '건축하다', ja: '', yomi: '' }, { en: 'introduce', ko: '소개하다', ja: '', yomi: '' },
  { en: 'buy', ko: '사다', ja: '', yomi: '' }, { en: 'fire', ko: '불', ja: '', yomi: '' }, { en: 'turn', ko: '돌(리)다, 차례, 회전', ja: '', yomi: '' }, { en: 'move', ko: '움직이다, 감동시키다', ja: '', yomi: '' },
  { en: 'keep', ko: '유지하다', ja: '', yomi: '' }, { en: 'learn', ko: '배우다', ja: '', yomi: '' }, { en: 'event', ko: '사건, 행사', ja: '', yomi: '' }, { en: 'cartoon', ko: '만화(영화)', ja: '', yomi: '' },
  { en: 'break', ko: '깨뜨리다, 휴식(시간)', ja: '', yomi: '' }, { en: 'culture', ko: '문화', ja: '', yomi: '' }, { en: 'believe', ko: '믿다', ja: '', yomi: '' }, { en: 'change', ko: '변화(하다), 거스름돈', ja: '', yomi: '' },
  { en: 'smart', ko: '영리한', ja: '', yomi: '' }, { en: 'healthy', ko: '건강한, 건강에 좋은', ja: '', yomi: '' }, { en: 'state', ko: '국가(주), 상태', ja: '', yomi: '' }, { en: 'act', ko: '행동(하다), 연기(하다)', ja: '', yomi: '' },
  { en: 'slow', ko: '느린, 늦추다', ja: '', yomi: '' }, { en: 'collect', ko: '모으다, 수집하다', ja: '', yomi: '' }, { en: 'produce', ko: '생산하다', ja: '', yomi: '' }, { en: 'large', ko: '큰, 넓은', ja: '', yomi: '' },
  { en: 'succeed', ko: '성공하다, 승계하다', ja: '', yomi: '' }, { en: 'pity', ko: '동정, 유감스러운 일', ja: '', yomi: '' }, { en: 'advertisement', ko: '광고', ja: '', yomi: '' }, { en: 'other', ko: '다른(것(사람))', ja: '', yomi: '' },
  { en: 'machine', ko: '기계', ja: '', yomi: '' }, { en: 'dirty', ko: '더러운', ja: '', yomi: '' }, { en: 'soldier', ko: '군인, 병사', ja: '', yomi: '' }, { en: 'enter', ko: '들어가다, 입학하다', ja: '', yomi: '' },
  { en: 'reach', ko: '도착하다, 이르다', ja: '', yomi: '' }, { en: 'past', ko: '과거(의), 지나간', ja: '', yomi: '' }, { en: 'space', ko: '공간, 우주', ja: '', yomi: '' }, { en: 'pour', ko: '따르다, (퍼)붓다', ja: '', yomi: '' },
  { en: 'country', ko: '나라, 시골', ja: '', yomi: '' }, { en: 'easy', ko: '쉬운, 편한', ja: '', yomi: '' }, { en: 'dialog', ko: '대화', ja: '', yomi: '' }, { en: 'custom', ko: '관습, 풍습', ja: '', yomi: '' },
  { en: 'fix', ko: '고치다, 고정시키다', ja: '', yomi: '' }, { en: 'gather', ko: '모으다(모이다)', ja: '', yomi: '' }, { en: 'hungry', ko: '배고픈', ja: '', yomi: '' }, { en: 'difference', ko: '다름, 차이', ja: '', yomi: '' },
  { en: 'hard', ko: '열심히, 단단한', ja: '', yomi: '' }, { en: 'add', ko: '더하다', ja: '', yomi: '' }, { en: 'sad', ko: '슬픈', ja: '', yomi: '' }, { en: 'different', ko: '다른', ja: '', yomi: '' },
  { en: 'sick', ko: '병든, 아픈', ja: '', yomi: '' }, { en: 'early', ko: '초기의, 이른(일찍)', ja: '', yomi: '' }, { en: 'explain', ko: '설명하다', ja: '', yomi: '' }, { en: 'serve', ko: '봉사하다, 시중들다', ja: '', yomi: '' },
  { en: 'president', ko: '대통령, 장(長)', ja: '', yomi: '' }, { en: 'protect', ko: '보호하다', ja: '', yomi: '' }, { en: 'hate', ko: '싫어하다', ja: '', yomi: '' }, { en: 'skill', ko: '기술(기능)', ja: '', yomi: '' },
  { en: 'treat', ko: '다루다, 치료하다, 대접하다', ja: '', yomi: '' }, { en: 'receive', ko: '받다', ja: '', yomi: '' }, { en: 'true', ko: '진짜의, 참된', ja: '', yomi: '' }, { en: 'seem', ko: '~처럼 보이다', ja: '', yomi: '' },
  { en: 'lot', ko: '다량(다수)', ja: '', yomi: '' }, { en: 'full', ko: '가득 찬', ja: '', yomi: '' }, { en: 'such', ko: '그러한(것(사람))', ja: '', yomi: '' }, { en: 'breathe', ko: '숨 쉬다, 호흡하다', ja: '', yomi: '' },
  { en: 'fine', ko: '좋은, 훌륭한, 잘', ja: '', yomi: '' }, { en: 'arrive', ko: '도착하다', ja: '', yomi: '' }, { en: 'free', ko: '자유로운, 무료의', ja: '', yomi: '' }, { en: 'interesting', ko: '재미있는', ja: '', yomi: '' },
  { en: 'roll', ko: '구르다, 말다, 두루마리', ja: '', yomi: '' }, { en: 'real', ko: '진짜의, 현실의', ja: '', yomi: '' }, { en: 'famous', ko: '유명한', ja: '', yomi: '' }, { en: 'able', ko: '~할 수 있는', ja: '', yomi: '' },
  { en: 'holiday', ko: '공휴일', ja: '', yomi: '' }, { en: 'last', ko: '지난', ja: '', yomi: '' }, { en: 'still', ko: '여전히, 움직이지 않는', ja: '', yomi: '' }, { en: 'science', ko: '과학', ja: '', yomi: '' },
  { en: 'bake', ko: '굽다', ja: '', yomi: '' }, { en: 'difficult', ko: '어려운', ja: '', yomi: '' }, { en: 'discover', ko: '발견하다', ja: '', yomi: '' }, { en: 'front', ko: '앞(정면)의', ja: '', yomi: '' },
  { en: 'community', ko: '공동체, 지역사회', ja: '', yomi: '' }, { en: 'advertise', ko: '광고(선전)하다', ja: '', yomi: '' }, { en: 'foreign', ko: '외국의', ja: '', yomi: '' }, { en: 'lie', ko: '눕다, ~에 있다, 거짓말(하다)', ja: '', yomi: '' },
  { en: 'burn', ko: '(불)타다, (불)태우다', ja: '', yomi: '' }, { en: 'ready', ko: '준비된', ja: '', yomi: '' }, { en: 'continue', ko: '계속하다', ja: '', yomi: '' }, { en: 'return', ko: '되돌아가다, 돌려주다', ja: '', yomi: '' },
  { en: 'important', ko: '중요한', ja: '', yomi: '' }, { en: 'wise', ko: '슬기로운, 현명한', ja: '', yomi: '' }, { en: 'realize', ko: '깨닫다, 실현하다', ja: '', yomi: '' }, { en: 'age', ko: '나이, 시대', ja: '', yomi: '' },
  { en: 'busy', ko: '바쁜, 번화한', ja: '', yomi: '' }, { en: 'field', ko: '들판, 경기장, 분야', ja: '', yomi: '' }, { en: 'sail', ko: '항해하다, 돛', ja: '', yomi: '' }, { en: 'fill', ko: '가득 채우다(차다)', ja: '', yomi: '' },
  { en: 'bright', ko: '빛나는, 밝은, 똑똑한', ja: '', yomi: '' }, { en: 'subject', ko: '과목, 주제', ja: '', yomi: '' }, { en: 'develop', ko: '발전하다, 개발하다', ja: '', yomi: '' }, { en: 'prevent', ko: '막다, 못하게 하다', ja: '', yomi: '' },
  { en: 'chance', ko: '기회, 가망', ja: '', yomi: '' }, { en: 'divide', ko: '나누다', ja: '', yomi: '' }, { en: 'light', ko: '빛(불), 밝은(가벼운)', ja: '', yomi: '' }, { en: 'improve', ko: '개선하다, 향상되다', ja: '', yomi: '' },
  { en: 'careful', ko: '주의 깊은, 조심하는', ja: '', yomi: '' }, { en: 'few', ko: '거의 없는, 소수(조금)(의)', ja: '', yomi: '' }, { en: 'hot', ko: '뜨거운, 더운, 매운', ja: '', yomi: '' }, { en: 'poor', ko: '가난한, 불쌍한, 서투른', ja: '', yomi: '' },
  { en: 'disappear', ko: '사라지다', ja: '', yomi: '' }, { en: 'only', ko: '오직, 유일한', ja: '', yomi: '' }, { en: 'popular', ko: '인기 있는, 대중의', ja: '', yomi: '' }, { en: 'shine', ko: '빛나다', ja: '', yomi: '' },
  { en: 'increase', ko: '늘리다, 증가(하다)', ja: '', yomi: '' }, { en: 'marry', ko: '~와 결혼하다', ja: '', yomi: '' }, { en: 'proud', ko: '자랑스러운', ja: '', yomi: '' }, { en: 'delicious', ko: '맛있는', ja: '', yomi: '' },
  { en: 'fault', ko: '잘못, 결점', ja: '', yomi: '' }, { en: 'flase', ko: '거짓의, 가짜의', ja: '', yomi: '' }, { en: 'lake', ko: '호수', ja: '', yomi: '' }, { en: 'view', ko: '견해, 전망, 바라보다', ja: '', yomi: '' },
  { en: 'rich', ko: '부유한, 풍부한', ja: '', yomi: '' }, { en: 'instead', ko: '대신에', ja: '', yomi: '' }, { en: 'project', ko: '계획(사업)', ja: '', yomi: '' }, { en: 'danger', ko: '위험', ja: '', yomi: '' },
  { en: 'balance', ko: '균형(을 잡다)', ja: '', yomi: '' }, { en: 'male', ko: '남성(의), 수컷(의)', ja: '', yomi: '' }, { en: 'moment', ko: '때, 순간', ja: '', yomi: '' }, { en: 'flight', ko: '항공편, 비행', ja: '', yomi: '' },
  { en: 'national', ko: '국가의, 민족의', ja: '', yomi: '' }, { en: 'behavior', ko: '행동', ja: '', yomi: '' }, { en: 'several', ko: '몇몇의', ja: '', yomi: '' }, { en: 'meaning', ko: '의미, 뜻', ja: '', yomi: '' },
  { en: 'magazine', ko: '잡지', ja: '', yomi: '' }, { en: 'hometown', ko: '고향', ja: '', yomi: '' }, { en: 'proverb', ko: '격언, 속담', ja: '', yomi: '' }, { en: 'effort', ko: '노력', ja: '', yomi: '' },
  { en: 'bar', ko: '막대, 빗장, 술집', ja: '', yomi: '' }, { en: 'peace', ko: '평화', ja: '', yomi: '' }, { en: 'wisdom', ko: '지혜', ja: '', yomi: '' }, { en: 'trouble', ko: '곤란(곤경), 괴롭히다', ja: '', yomi: '' },
  { en: 'key', ko: '열쇠, 비결, 중요한', ja: '', yomi: '' }, { en: 'traffic', ko: '교통(량)', ja: '', yomi: '' }, { en: 'afraid', ko: '두려워하는, 걱정하는', ja: '', yomi: '' }, { en: 'bath', ko: '목욕', ja: '', yomi: '' },
  { en: 'company', ko: '회사, 친구, 교제', ja: '', yomi: '' }, { en: 'straw', ko: '(밀)짚, 빨대', ja: '', yomi: '' }, { en: 'huge', ko: '거대한', ja: '', yomi: '' }, { en: 'creature', ko: '생물', ja: '', yomi: '' },
  { en: 'regular', ko: '규칙적인, 보통의', ja: '', yomi: '' }, { en: 'fan', ko: '팬(~광), 선풍기(부채)', ja: '', yomi: '' }, { en: 'college', ko: '대학', ja: '', yomi: '' }, { en: 'luck', ko: '행운', ja: '', yomi: '' },
  { en: 'magic', ko: '마술(의)', ja: '', yomi: '' }, { en: 'empty', ko: '빈', ja: '', yomi: '' }, { en: 'zoo', ko: '동물원', ja: '', yomi: '' }, { en: 'advice', ko: '조언, 충고', ja: '', yomi: '' },
  { en: 'record', ko: '기록(하다), 녹음하다', ja: '', yomi: '' }, { en: 'ghost', ko: '유령', ja: '', yomi: '' }, { en: 'memory', ko: '기억력', ja: '', yomi: '' }, { en: 'library', ko: '도서관', ja: '', yomi: '' },
  { en: 'hole', ko: '구멍', ja: '', yomi: '' }, { en: 'note', ko: '노트, 음(표), 주의하다', ja: '', yomi: '' }, { en: 'palace', ko: '궁전', ja: '', yomi: '' }, { en: 'secret', ko: '비밀의', ja: '', yomi: '' },
  { en: 'insect', ko: '곤충', ja: '', yomi: '' }, { en: 'amazing', ko: '놀랄만한', ja: '', yomi: '' }, { en: 'type', ko: '유형', ja: '', yomi: '' }, { en: 'bill', ko: '청구서, 지폐, 법안', ja: '', yomi: '' },
  { en: 'environment', ko: '환경', ja: '', yomi: '' }, { en: 'scene', ko: '장면, 현장', ja: '', yomi: '' }, { en: 'electricity', ko: '전기', ja: '', yomi: '' }, { en: 'bank', ko: '은행, 둑', ja: '', yomi: '' },
  { en: 'image', ko: '이미지, 모습', ja: '', yomi: '' }, { en: 'everyday', ko: '매일의, 일상의', ja: '', yomi: '' }, { en: 'international', ko: '국제의', ja: '', yomi: '' }, { en: 'truth', ko: '진실, 진리', ja: '', yomi: '' },
  { en: 'soft', ko: '부드러운', ja: '', yomi: '' }, { en: 'terrible', ko: '끔찍한, 지독한', ja: '', yomi: '' }, { en: 'disease', ko: '질병', ja: '', yomi: '' }, { en: 'nation', ko: '국가, 민족', ja: '', yomi: '' },
  { en: 'model', ko: '모형, 모델, 모범', ja: '', yomi: '' }, { en: 'charity', ko: '자선(단체)', ja: '', yomi: '' }, { en: 'fresh', ko: '새로운, 신선한', ja: '', yomi: '' }, { en: 'hobby', ko: '취미', ja: '', yomi: '' },
  { en: 'address', ko: '주소, 연설', ja: '', yomi: '' }, { en: 'factory', ko: '공장', ja: '', yomi: '' }, { en: 'pleasure', ko: '기쁨, 즐거움', ja: '', yomi: '' }, { en: 'heavy', ko: '무거운, 심한', ja: '', yomi: '' },
  { en: 'date', ko: '날짜, 데이트', ja: '', yomi: '' }, { en: 'campaign', ko: '캠페인, 운동', ja: '', yomi: '' }, { en: 'storm', ko: '폭풍우', ja: '', yomi: '' }, { en: 'cute', ko: '귀여운', ja: '', yomi: '' },
  { en: 'tear', ko: '눈물, 찢(어지)다', ja: '', yomi: '' }, { en: 'coin', ko: '동전', ja: '', yomi: '' }, { en: 'distance', ko: '거리', ja: '', yomi: '' }, { en: 'expensive', ko: '비싼', ja: '', yomi: '' },
  { en: 'sense', ko: '느낌, 감각, 분별력', ja: '', yomi: '' }, { en: 'flag', ko: '국기, 깃발', ja: '', yomi: '' }, { en: 'blind', ko: '눈먼', ja: '', yomi: '' }, { en: 'bridge', ko: '(건너는)다리', ja: '', yomi: '' },
  { en: 'army', ko: '육군, 군대', ja: '', yomi: '' }, { en: 'valley', ko: '골짜기, 계곡', ja: '', yomi: '' }, { en: 'map', ko: '지도', ja: '', yomi: '' }, { en: 'yard', ko: '마당, 뜰', ja: '', yomi: '' },
  { en: 'tourist', ko: '관광객', ja: '', yomi: '' }, { en: 'recipe', ko: '조리법', ja: '', yomi: '' }, { en: 'rainbow', ko: '무지개', ja: '', yomi: '' }, { en: 'candle', ko: '양초', ja: '', yomi: '' },
  { en: 'sentence', ko: '문장', ja: '', yomi: '' }, { en: 'pal', ko: '친구', ja: '', yomi: '' }, { en: 'race', ko: '경주하다, 인종', ja: '', yomi: '' }, { en: 'simple', ko: '간단한, 단순한', ja: '', yomi: '' },
  { en: 'technology', ko: '과학기술, 테크놀로지', ja: '', yomi: '' }, { en: 'being', ko: '존재, 생물', ja: '', yomi: '' }, { en: 'pain', ko: '고통, (~s)수고', ja: '', yomi: '' }, { en: 'garage', ko: '차고', ja: '', yomi: '' },
  { en: 'fit', ko: '맞추다, 건강한, 알맞은', ja: '', yomi: '' }, { en: 'shock', ko: '깜짝 놀라게 하다, 충격', ja: '', yomi: '' }, { en: 'score', ko: '점수, 득점(하다)', ja: '', yomi: '' }, { en: 'support', ko: '지지하다, 원조(하다)', ja: '', yomi: '' },
  { en: 'obey', ko: '따르다, 복종하다', ja: '', yomi: '' }, { en: 'pair', ko: '쌍(벌, 켤레)', ja: '', yomi: '' }, { en: 'cancer', ko: '암', ja: '', yomi: '' }, { en: 'repair', ko: '고치다, 수리(하다)', ja: '', yomi: '' },
  { en: 'strike', ko: '치다, 치기', ja: '', yomi: '' }, { en: 'offer', ko: '제공하다', ja: '', yomi: '' }, { en: 'low', ko: '낮은(낮게)', ja: '', yomi: '' }, { en: 'lock', ko: '자물쇠를 채우다', ja: '', yomi: '' },
  { en: 'will', ko: '의지(뜻), 유언(유서)', ja: '', yomi: '' }, { en: 'elect', ko: '선출하다', ja: '', yomi: '' }, { en: 'melt', ko: '녹이다', ja: '', yomi: '' }, { en: 'bow', ko: '절(하다), 활', ja: '', yomi: '' },
  { en: 'officer', ko: '장교, 관리(임원)', ja: '', yomi: '' }, { en: 'bucket', ko: '양동이', ja: '', yomi: '' }, { en: 'guest', ko: '손님', ja: '', yomi: '' }, { en: 'beat', ko: '이기다, 박자', ja: '', yomi: '' },
  { en: 'yet', ko: '아직, 이미, 그렇지만', ja: '', yomi: '' }, { en: 'warn', ko: '경고하다', ja: '', yomi: '' }, { en: 'suffer', ko: '고통을 겪다', ja: '', yomi: '' }, { en: 'cage', ko: '새장, 우리', ja: '', yomi: '' },
  { en: 'advance', ko: '진보하다, 전진하다', ja: '', yomi: '' }, { en: 'communication', ko: '의사소통, 통신', ja: '', yomi: '' }, { en: 'possible', ko: '가능한', ja: '', yomi: '' }, { en: 'diet', ko: '음식, 다이어트', ja: '', yomi: '' },
  { en: 'temple', ko: '사원, 절', ja: '', yomi: '' }, { en: 'talent', ko: '재능', ja: '', yomi: '' }, { en: 'therefore', ko: '그러므로', ja: '', yomi: '' }, { en: 'appreciate', ko: '감사하다, 가치를 깨닫다', ja: '', yomi: '' },
  { en: 'journey', ko: '여행', ja: '', yomi: '' }, { en: 'figure', ko: '숫자, 모습, 인물, 도형', ja: '', yomi: '' }, { en: 'athlete', ko: '운동선수', ja: '', yomi: '' }, { en: 'thought', ko: '생각, 사고', ja: '', yomi: '' },
  { en: 'expect', ko: '기대하다', ja: '', yomi: '' }, { en: 'situation', ko: '상황', ja: '', yomi: '' }, { en: 'belong', ko: '~에 속하다', ja: '', yomi: '' }, { en: 'pride', ko: '자랑, 자존심', ja: '', yomi: '' },
  { en: 'litter', ko: '쓰레기, 난잡함', ja: '', yomi: '' }, { en: 'sheet', ko: '시트, (종이)한장', ja: '', yomi: '' }, { en: 'ceremony', ko: '의식, 의례', ja: '', yomi: '' }, { en: 'inside', ko: '안쪽', ja: '', yomi: '' },
  { en: 'especially', ko: '특히', ja: '', yomi: '' }, { en: 'bend', ko: '구부리다', ja: '', yomi: '' }, { en: 'breeze', ko: '산들바람, 미풍', ja: '', yomi: '' }, { en: 'god', ko: '신, 조물주', ja: '', yomi: '' },
  { en: 'transportation', ko: '운송, 교통수단', ja: '', yomi: '' }, { en: 'breath', ko: '숨, 호흡', ja: '', yomi: '' }, { en: 'else', ko: '그밖에', ja: '', yomi: '' }, { en: 'neighborhood', ko: '이웃', ja: '', yomi: '' },
  { en: 'ago', ko: '~전에', ja: '', yomi: '' }, { en: 'diver', ko: '잠수부', ja: '', yomi: '' }, { en: 'captain', ko: '선장(기장), 주장', ja: '', yomi: '' }, { en: 'cure', ko: '치료하다, 치료(법)', ja: '', yomi: '' },
  { en: 'float', ko: '뜨다(띄우다), 떠다니다', ja: '', yomi: '' }, { en: 'remain', ko: '남아있다', ja: '', yomi: '' }, { en: 'ever', ko: '이전에, 언제나, 언젠가', ja: '', yomi: '' }, { en: 'almost', ko: '거의', ja: '', yomi: '' },
  { en: 'boil', ko: '끓다', ja: '', yomi: '' }, { en: 'wave', ko: '파도(물결), 흔들다', ja: '', yomi: '' }, { en: 'appear', ko: '나타나다, ~인 것 같다', ja: '', yomi: '' }, { en: 'vote', ko: '투표하다', ja: '', yomi: '' },
  { en: 'probably', ko: '아마', ja: '', yomi: '' }, { en: 'suddenly', ko: '갑자기', ja: '', yomi: '' }, { en: 'suit', ko: '정장 한 벌, ~복, 맞다', ja: '', yomi: '' }, { en: 'level', ko: '수준, 높이', ja: '', yomi: '' },
  { en: 'cyberspace', ko: '사이버공간', ja: '', yomi: '' }, { en: 'cell', ko: '세포', ja: '', yomi: '' }, { en: 'replace', ko: '대신하다, 교체하다', ja: '', yomi: '' }, { en: 'growth', ko: '성장, 증가', ja: '', yomi: '' },
  { en: 'finally', ko: '마침내, 마지막으로', ja: '', yomi: '' }, { en: 'weak', ko: '약한', ja: '', yomi: '' }, { en: 'wrap', ko: '포장하다', ja: '', yomi: '' }, { en: 'dictionary', ko: '사전', ja: '', yomi: '' },
  { en: 'kite', ko: '연', ja: '', yomi: '' }, { en: 'choice', ko: '선택', ja: '', yomi: '' }, { en: 'off', ko: '떨어져', ja: '', yomi: '' }, { en: 'temperature', ko: '온도, 기온, 체온', ja: '', yomi: '' },
  { en: 'countryside', ko: '시골', ja: '', yomi: '' }, { en: 'deep', ko: '깊은(깊게)', ja: '', yomi: '' }, { en: 'loud', ko: '큰소리의', ja: '', yomi: '' }, { en: 'quickly', ko: '빨리, 곧', ja: '', yomi: '' },
  { en: 'maybe', ko: '아마, 어쩌면', ja: '', yomi: '' }, { en: 'dislike', ko: '싫어하다, 싫어함', ja: '', yomi: '' }, { en: 'tie', ko: '묶다, 동점(이 되다)', ja: '', yomi: '' }, { en: 'impress', ko: '감명을 주다', ja: '', yomi: '' },
  { en: 'skip', ko: '건너뛰다', ja: '', yomi: '' }, { en: 'earn', ko: '(돈을)벌다, 얻다', ja: '', yomi: '' }, { en: 'garbage', ko: '쓰레기', ja: '', yomi: '' }, { en: 'already', ko: '이미, 벌써', ja: '', yomi: '' },
  { en: 'notice', ko: '알아차리다, 주의, 통지', ja: '', yomi: '' }, { en: 'symbol', ko: '상징, 기호', ja: '', yomi: '' }, { en: 'difficulty', ko: '어려움, 곤란', ja: '', yomi: '' }, { en: 'far', ko: '멀리', ja: '', yomi: '' },
  { en: 'manage', ko: '관리하다, 해내다', ja: '', yomi: '' }, { en: 'rush', ko: '서둘러가다, 돌진', ja: '', yomi: '' }, { en: 'dot', ko: '점', ja: '', yomi: '' }, { en: 'hang', ko: '매달리다, 목매달다', ja: '', yomi: '' },
  { en: 'deal', ko: '다루다, 거래(하다)', ja: '', yomi: '' }, { en: 'limit', ko: '한계, 제한하다', ja: '', yomi: '' }, { en: 'freeze', ko: '얼리다', ja: '', yomi: '' }, { en: 'fair', ko: '공정한, 박람회', ja: '', yomi: '' },
  { en: 'gun', ko: '총, 대포', ja: '', yomi: '' }, { en: 'satellite', ko: '인공위성', ja: '', yomi: '' }, { en: 'exactly', ko: '정확하게', ja: '', yomi: '' }, { en: 'pardon', ko: '사면, 용서', ja: '', yomi: '' },
  { en: 'wet', ko: '젖은, 비오는', ja: '', yomi: '' }, { en: 'forgive', ko: '용서하다', ja: '', yomi: '' }, { en: 'patient', ko: '참을성 있는, 환자', ja: '', yomi: '' }, { en: 'badly', ko: '잘못, 서툴게, 몹시', ja: '', yomi: '' },
  { en: 'mess', ko: '엉망, 혼란', ja: '', yomi: '' }, { en: 'autumn', ko: '가을', ja: '', yomi: '' }, { en: 'familiar', ko: '친숙한', ja: '', yomi: '' }, { en: 'signal', ko: '신호를 보내다', ja: '', yomi: '' },
  { en: 'pack', ko: '짐을 싸다, 상자', ja: '', yomi: '' }, { en: 'convenient', ko: '편리한', ja: '', yomi: '' }, { en: 'greet', ko: '인사하다', ja: '', yomi: '' }, { en: 'calm', ko: '차분한, 고요, 진정하다', ja: '', yomi: '' },
  { en: 'swallow', ko: '삼키다, 제비', ja: '', yomi: '' }, { en: 'jog', ko: '조깅하다', ja: '', yomi: '' }, { en: 'mad', ko: '화난, 열광적인, 미친', ja: '', yomi: '' }, { en: 'exist', ko: '존재하다(있다)', ja: '', yomi: '' },
  { en: 'standard', ko: '표준, 기준', ja: '', yomi: '' }, { en: 'anyway', ko: '어쨌든, 아무튼', ja: '', yomi: '' }, { en: 'stretch', ko: '펴다(뻗다), 잡아 늘리다', ja: '', yomi: '' }, { en: 'easily', ko: '쉽게', ja: '', yomi: '' },
  { en: 'stair', ko: '계단', ja: '', yomi: '' }, { en: 'ahead', ko: '앞에', ja: '', yomi: '' }, { en: 'local', ko: '지역의', ja: '', yomi: '' }, { en: 'anywhere', ko: '어디든지, 어디엔가', ja: '', yomi: '' },
  { en: 'nod', ko: '끄덕이다, 끄덕임', ja: '', yomi: '' }, { en: 'connect', ko: '연결하다', ja: '', yomi: '' }, { en: 'quite', ko: '꽤, 아주', ja: '', yomi: '' }, { en: 'medical', ko: '의학의', ja: '', yomi: '' },
  { en: 'active', ko: '활동적인, 적극적인', ja: '', yomi: '' }, { en: 'quarter', ko: '4분의 1', ja: '', yomi: '' }, { en: 'scenery', ko: '경치, 풍경', ja: '', yomi: '' }, { en: 'contact', ko: '접촉하다', ja: '', yomi: '' },
  { en: 'mostly', ko: '대부분, 대개', ja: '', yomi: '' }, { en: 'glue', ko: '풀, 아교(로 붙이다)', ja: '', yomi: '' }, { en: 'graduate', ko: '졸업하다, 졸업생', ja: '', yomi: '' }, { en: 'envy', ko: '부러워하다, 부러움', ja: '', yomi: '' },
  { en: 'handsome', ko: '잘생긴', ja: '', yomi: '' }, { en: 'measure', ko: '재다(측정하다), 조치', ja: '', yomi: '' }, { en: 'flat', ko: '평범한, 바람 빠진', ja: '', yomi: '' }, { en: 'rid', ko: '제거하다, 벗어나게 하다', ja: '', yomi: '' },
  { en: 'yell', ko: '외치다, 소리치다', ja: '', yomi: '' }, { en: 'completely', ko: '완전히', ja: '', yomi: '' }, { en: 'floor', ko: '(마루)바닥, 층', ja: '', yomi: '' }, { en: 'sink', ko: '가라앉다, 개수대', ja: '', yomi: '' },
  { en: 'dead', ko: '죽은', ja: '', yomi: '' }, { en: 'public', ko: '대중의, 공공의', ja: '', yomi: '' }, { en: 'suppose', ko: '추측하다, 가정하다', ja: '', yomi: '' }, { en: 'outside', ko: '밖에', ja: '', yomi: '' },
  { en: 'reduce', ko: '줄이다, 감소하다', ja: '', yomi: '' }, { en: 'simply', ko: '단지, 간단히', ja: '', yomi: '' }, { en: 'correct', ko: '올바른, 바로잡다', ja: '', yomi: '' }, { en: 'remove', ko: '제거하다, 치우다', ja: '', yomi: '' },
  { en: 'forecast', ko: '예보하다', ja: '', yomi: '' }, { en: 'straight', ko: '똑바로, 즉시', ja: '', yomi: '' }, { en: 'final', ko: '마지막의, 결승', ja: '', yomi: '' }, { en: 'chat', ko: '잡담하다, 채팅하다', ja: '', yomi: '' },
  { en: 'someday', ko: '(미래의)언젠가', ja: '', yomi: '' }, { en: 'folk', ko: '사람들, 민속의', ja: '', yomi: '' }, { en: 'material', ko: '물질의', ja: '', yomi: '' }, { en: 'police', ko: '경찰', ja: '', yomi: '' },
  { en: 'comfortable', ko: '편안한', ja: '', yomi: '' }, { en: 'merry', ko: '즐거운, 유쾌한', ja: '', yomi: '' }, { en: 'chemical', ko: '화학물질, 화학의', ja: '', yomi: '' }, { en: 'twice', ko: '두 번, 두 배로', ja: '', yomi: '' },
  { en: 'encourge', ko: '용기를 북돋우다', ja: '', yomi: '' }, { en: 'whisper', ko: '속삭이다, 속삭임', ja: '', yomi: '' }, { en: 'focus', ko: '집중하다', ja: '', yomi: '' }, { en: 'sweet', ko: '단, 친절한', ja: '', yomi: '' },
  { en: 'indeed', ko: '정말, 사실은', ja: '', yomi: '' }, { en: 'puzzle', ko: '혼란시키다', ja: '', yomi: '' }, { en: 'recommend', ko: '추천하다, 조언하다', ja: '', yomi: '' }, { en: 'perhaps', ko: '아마도', ja: '', yomi: '' },
  { en: 'abroad', ko: '외국에', ja: '', yomi: '' }, { en: 'pleasant', ko: '쾌적한(유쾌한), 상냥한', ja: '', yomi: '' }, { en: 'abstract', ko: '추상적인', ja: '', yomi: '' }, { en: 'necessary', ko: '필요한', ja: '', yomi: '' },
  { en: 'decision', ko: '결정', ja: '', yomi: '' }, { en: 'predict', ko: '예언하다', ja: '', yomi: '' }, { en: 'spill', ko: '엎지르다', ja: '', yomi: '' }, { en: 'boring', ko: '지루한', ja: '', yomi: '' },
  { en: 'wide', ko: '넓은, 넓게', ja: '', yomi: '' }, { en: 'spray', ko: '(물을)뿌리다, 분무기', ja: '', yomi: '' }, { en: 'debate', ko: '토론하다', ja: '', yomi: '' }, { en: 'relative', ko: '친척, 상대적인', ja: '', yomi: '' },
  { en: 'steal', ko: '훔치다', ja: '', yomi: '' }, { en: 'case', ko: '경우, 케이스(용기)', ja: '', yomi: '' }, { en: 'prove', ko: '증명하다, 판명되다', ja: '', yomi: '' }, { en: 'claim', ko: '주장하다, 요구하다', ja: '', yomi: '' },
  { en: 'forward', ko: '앞으로', ja: '', yomi: '' }, { en: 'fantastic', ko: '환상적인', ja: '', yomi: '' }, { en: 'rubber', ko: '고무', ja: '', yomi: '' }, { en: 'forever', ko: '영원히', ja: '', yomi: '' },
  { en: 'faithful', ko: '충실한, 믿음직한', ja: '', yomi: '' }, { en: 'courage', ko: '용기', ja: '', yomi: '' }, { en: 'source', ko: '원천, 근원, 출처', ja: '', yomi: '' }, { en: 'self', ko: '자기(자신), 자아', ja: '', yomi: '' },
  { en: 'issue', ko: '문제(쟁점), 발행하다', ja: '', yomi: '' }, { en: 'astronaut', ko: '우주비행사', ja: '', yomi: '' }, { en: 'chairman', ko: '의장(회장)', ja: '', yomi: '' }, { en: 'escape', ko: '탈출하다', ja: '', yomi: '' },
  { en: 'salty', ko: '짠', ja: '', yomi: '' }, { en: 'homeless', ko: '집이 없는', ja: '', yomi: '' }, { en: 'kingdom', ko: '왕국', ja: '', yomi: '' }, { en: 'disabled', ko: '장애가 있는', ja: '', yomi: '' },
  { en: 'attempt', ko: '시도하다', ja: '', yomi: '' }, { en: 'central', ko: '중심(중앙)의', ja: '', yomi: '' }, { en: 'stomach', ko: '위, 배(복부)', ja: '', yomi: '' }, { en: 'creative', ko: '창조적인', ja: '', yomi: '' },
  { en: 'tough', ko: '힘든, 강(인)한, 질긴', ja: '', yomi: '' }, { en: 'humorous', ko: '유머가 넘치는', ja: '', yomi: '' }, { en: 'fever', ko: '열, 열병', ja: '', yomi: '' }, { en: 'dynasty', ko: '왕조', ja: '', yomi: '' },
  { en: 'silent', ko: '침묵하는, 조용한', ja: '', yomi: '' }, { en: 'reservation', ko: '예약', ja: '', yomi: '' }, { en: 'castle', ko: '성(城)', ja: '', yomi: '' }, { en: 'normal', ko: '정상의', ja: '', yomi: '' },
  { en: 'specific', ko: '특정한, 구체적인', ja: '', yomi: '' }, { en: 'extra', ko: '여분의, 추가의', ja: '', yomi: '' }, { en: 'stuff', ko: '물건(재료), 채우다', ja: '', yomi: '' }, { en: 'damage', ko: '손상시키다', ja: '', yomi: '' },
  { en: 'painful', ko: '아픈, 고통스러운', ja: '', yomi: '' }, { en: 'shore', ko: '바닷가, 호숫가, 강가', ja: '', yomi: '' }, { en: 'lifelong', ko: '평생의', ja: '', yomi: '' }, { en: 'lack', ko: '부족하다, 결핍되다', ja: '', yomi: '' },
  { en: 'official', ko: '공식의, 관리(임원)', ja: '', yomi: '' }, { en: 'intelligent', ko: '총명한', ja: '', yomi: '' }, { en: 'lifetime', ko: '일생, 평생', ja: '', yomi: '' }, { en: 'effective', ko: '효과적인', ja: '', yomi: '' },
  { en: 'shot', ko: '발사, 던지기, 주사', ja: '', yomi: '' }, { en: 'darkness', ko: '어둠', ja: '', yomi: '' }, { en: 'award', ko: '상을 주다', ja: '', yomi: '' }, { en: 'attack', ko: '공격하다, 발작', ja: '', yomi: '' },
  { en: 'sore', ko: '아픈, 쑤시는', ja: '', yomi: '' }, { en: 'demand', ko: '요구하다, 수요', ja: '', yomi: '' }, { en: 'complaint', ko: '불평, 항의', ja: '', yomi: '' }, { en: 'responsible', ko: '책임 있는', ja: '', yomi: '' },
  { en: 'population', ko: '인구', ja: '', yomi: '' }, { en: 'greenhouse', ko: '온실', ja: '', yomi: '' }, { en: 'peaceful', ko: '평화로운', ja: '', yomi: '' }, { en: 'engine', ko: '엔진, 기관(차)', ja: '', yomi: '' },
  { en: 'drug', ko: '약', ja: '', yomi: '' }, { en: 'harmful', ko: '해로운', ja: '', yomi: '' }, { en: 'loose', ko: '풀린, 헐거운', ja: '', yomi: '' }, { en: 'conflict', ko: '대립하다', ja: '', yomi: '' },
  { en: 'fur', ko: '모피', ja: '', yomi: '' }, { en: 'greedy', ko: '탐욕스러운', ja: '', yomi: '' }, { en: 'regard', ko: '여기다', ja: '', yomi: '' }, { en: 'opposite', ko: '정반대의, 반대쪽의(에)', ja: '', yomi: '' },
  { en: 'broadcast', ko: '방송하다', ja: '', yomi: '' }, { en: 'nervous', ko: '초조한, 신경의', ja: '', yomi: '' }, { en: 'original', ko: '원래의, 독창적인', ja: '', yomi: '' }, { en: 'eager', ko: '열망하는', ja: '', yomi: '' },
  { en: 'joke', ko: '농담하다', ja: '', yomi: '' }, { en: 'adventure', ko: '모험', ja: '', yomi: '' }, { en: 'upper', ko: '위쪽의, 높은', ja: '', yomi: '' }, { en: 'triangle', ko: '삼각형', ja: '', yomi: '' },
  { en: 'curious', ko: '호기심강한', ja: '', yomi: '' }, { en: 'saying', ko: '속담, 격언', ja: '', yomi: '' }, { en: 'imagination', ko: '상상, 창의성', ja: '', yomi: '' }, { en: 'cough', ko: '기침하다', ja: '', yomi: '' },
  { en: 'visitor', ko: '방문객', ja: '', yomi: '' }, { en: 'container', ko: '용기(그릇)', ja: '', yomi: '' }, { en: 'bloom', ko: '꽃피다', ja: '', yomi: '' }, { en: 'pattern', ko: '양식, 무늬', ja: '', yomi: '' },
  { en: 'dragon', ko: '용', ja: '', yomi: '' }, { en: 'prediction', ko: '예언, 예측', ja: '', yomi: '' }, { en: 'separate', ko: '분리된, 분리하다', ja: '', yomi: '' }, { en: 'royal', ko: '왕의', ja: '', yomi: '' },
  { en: 'exchange', ko: '교환하다, 주고받다', ja: '', yomi: '' }, { en: 'honest', ko: '정직한', ja: '', yomi: '' }, { en: 'foggy', ko: '안개 낀', ja: '', yomi: '' }, { en: 'fear', ko: '두려움, 두려워하다', ja: '', yomi: '' },
  { en: 'electronic', ko: '전자의', ja: '', yomi: '' }, { en: 'childhood', ko: '어린 시절, 유년시절', ja: '', yomi: '' }, { en: 'humor', ko: '유머', ja: '', yomi: '' }, { en: 'asleep', ko: '잠든', ja: '', yomi: '' },
  { en: 'supply', ko: '공급품, 공급하다', ja: '', yomi: '' }, { en: 'foolish', ko: '어리석은', ja: '', yomi: '' }, { en: 'total', ko: '전체의, 총계(의), 완전한', ja: '', yomi: '' }, { en: 'flea', ko: '벼룩', ja: '', yomi: '' },
  { en: 'direct', ko: '직접, 지시하다', ja: '', yomi: '' }, { en: 'ugly', ko: '추한', ja: '', yomi: '' }, { en: 'silly', ko: '어리석은', ja: '', yomi: '' }, { en: 'doll', ko: '인형', ja: '', yomi: '' },
  { en: 'industry', ko: '산업, 근면', ja: '', yomi: '' }, { en: 'illness', ko: '병', ja: '', yomi: '' }, { en: 'quarrel', ko: '말다툼하다', ja: '', yomi: '' }, { en: 'weapon', ko: '무기', ja: '', yomi: '' },
  { en: 'role', ko: '역할', ja: '', yomi: '' }, { en: 'generation', ko: '세대', ja: '', yomi: '' }, { en: 'harm', ko: '손해, 해치다', ja: '', yomi: '' }, { en: 'throat', ko: '목구멍', ja: '', yomi: '' },
  { en: 'palm', ko: '손바닥, 야자', ja: '', yomi: '' }, { en: 'release', ko: '풀어주다, 내놓다', ja: '', yomi: '' }, { en: 'drown', ko: '익사하다', ja: '', yomi: '' }, { en: 'obtain', ko: '얻다, 획득하다', ja: '', yomi: '' },
  { en: 'nail', ko: '손톱, 못', ja: '', yomi: '' }, { en: 'curiosity', ko: '호기심', ja: '', yomi: '' }, { en: 'means', ko: '수단, 방법', ja: '', yomi: '' }, { en: 'account', ko: '설명하다, 계좌', ja: '', yomi: '' },
  { en: 'intend', ko: '작정이다, 의도하다', ja: '', yomi: '' }, { en: 'shelter', ko: '피난처', ja: '', yomi: '' }, { en: 'item', ko: '품목, 항목', ja: '', yomi: '' }, { en: 'package', ko: '꾸러미, 포장하다', ja: '', yomi: '' },
  { en: 'responsibility', ko: '책임', ja: '', yomi: '' }, { en: 'victory', ko: '승리', ja: '', yomi: '' }, { en: 'feature', ko: '특징', ja: '', yomi: '' }, { en: 'twist', ko: '비틀다, 꼬다', ja: '', yomi: '' },
  { en: 'arrange', ko: '준비하다, 배열하다', ja: '', yomi: '' }, { en: 'crash', ko: '충돌하다', ja: '', yomi: '' }, { en: 'apologize', ko: '사과하다', ja: '', yomi: '' }, { en: 'photo', ko: '사진', ja: '', yomi: '' },
  { en: 'pressure', ko: '압력', ja: '', yomi: '' }, { en: 'statement', ko: '진술, 성명', ja: '', yomi: '' }, { en: 'sweep', ko: '쓸다, 청소하다', ja: '', yomi: '' }, { en: 'harbor', ko: '항구', ja: '', yomi: '' },
  { en: 'collection', ko: '수집', ja: '', yomi: '' }, { en: 'threaten', ko: '위협하다', ja: '', yomi: '' }, { en: 'explode', ko: '폭발하다', ja: '', yomi: '' }, { en: 'departure', ko: '출발', ja: '', yomi: '' },
  { en: 'rumor', ko: '소문', ja: '', yomi: '' }, { en: 'contrast', ko: '대조하다, 대비되다', ja: '', yomi: '' }, { en: 'horizon', ko: '수평선', ja: '', yomi: '' }, { en: 'thread', ko: '실, 실을 꿰다', ja: '', yomi: '' },
  { en: 'unification', ko: '통일', ja: '', yomi: '' }, { en: 'admire', ko: '존경하다, 감탄하다', ja: '', yomi: '' }, { en: 'passenger', ko: '승객', ja: '', yomi: '' }, { en: 'production', ko: '생산', ja: '', yomi: '' },
  { en: 'vehicle', ko: '탈것', ja: '', yomi: '' }, { en: 'unite', ko: '합치다', ja: '', yomi: '' }, { en: 'associate', ko: '연상하다', ja: '', yomi: '' }, { en: 'arrest', ko: '체포하다', ja: '', yomi: '' },
  { en: 'trust', ko: '신뢰하다', ja: '', yomi: '' }, { en: 'desire', ko: '욕구, 바라다', ja: '', yomi: '' }, { en: 'mission', ko: '특별임무, 선교', ja: '', yomi: '' }, { en: 'behave', ko: '행동하다', ja: '', yomi: '' },
  { en: 'research', ko: '연구하다', ja: '', yomi: '' }, { en: 'cooperation', ko: '협력, 협동', ja: '', yomi: '' }, { en: 'depress', ko: '우울하게하다', ja: '', yomi: '' }, { en: 'convenience', ko: '편리, 편의', ja: '', yomi: '' },
  { en: 'flavor', ko: '맛을 내다', ja: '', yomi: '' }, { en: 'scream', ko: '소리를 지르다', ja: '', yomi: '' }, { en: 'identify', ko: '정체를 밝히다', ja: '', yomi: '' }, { en: 'occur', ko: '일어나다, 생각나다', ja: '', yomi: '' },
  { en: 'gym', ko: '체육관, 체조', ja: '', yomi: '' }, { en: 'narrator', ko: '해설자, 내레이터', ja: '', yomi: '' }, { en: 'deny', ko: '부정하다', ja: '', yomi: '' }, { en: 'wildlife', ko: '야생생물', ja: '', yomi: '' },
  { en: 'frustrate', ko: '좌절시키다', ja: '', yomi: '' }, { en: 'misunderstand', ko: '오해하다', ja: '', yomi: '' }, { en: 'influence', ko: '영향을 미치다', ja: '', yomi: '' }, { en: 'ladder', ko: '사다리', ja: '', yomi: '' },
  { en: 'servant', ko: '하인', ja: '', yomi: '' }, { en: 'convert', ko: '바꾸다, 변환하다', ja: '', yomi: '' }, { en: 'survey', ko: '조사하다', ja: '', yomi: '' }, { en: 'mention', ko: '언급하다', ja: '', yomi: '' },
  { en: 'attendant', ko: '시중드는 사람', ja: '', yomi: '' }, { en: 'punish', ko: '벌하다', ja: '', yomi: '' }, { en: 'tongue', ko: '혀', ja: '', yomi: '' }, { en: 'sunset', ko: '일몰, 해넘이', ja: '', yomi: '' },
  { en: 'establish', ko: '설립하다', ja: '', yomi: '' }, { en: 'load', ko: '짐을 싣다', ja: '', yomi: '' }, { en: 'bullet', ko: '총알', ja: '', yomi: '' }, { en: 'consist', ko: '이루어져있다', ja: '', yomi: '' },
  { en: 'expression', ko: '표현', ja: '', yomi: '' }, { en: 'operate', ko: '작동하다, 수술하다', ja: '', yomi: '' }, { en: 'entertain', ko: '즐겁게 하다', ja: '', yomi: '' }, { en: 'merchant', ko: '상인', ja: '', yomi: '' },
  { en: 'examine', ko: '조사하다', ja: '', yomi: '' }, { en: 'treatment', ko: '치료', ja: '', yomi: '' }, { en: 'port', ko: '항구', ja: '', yomi: '' }, { en: 'lung', ko: '폐, 허파', ja: '', yomi: '' },
  { en: 'preserve', ko: '보존하다, 보호하다', ja: '', yomi: '' }, { en: 'operation', ko: '수술, 운전, 작전', ja: '', yomi: '' }, { en: 'senior', ko: '상급생, 연장자', ja: '', yomi: '' }, { en: 'deceive', ko: '속이다', ja: '', yomi: '' },
  { en: 'manufacture', ko: '제조하다', ja: '', yomi: '' }, { en: 'blossom', ko: '꽃(피다)', ja: '', yomi: '' }, { en: 'failure', ko: '실패', ja: '', yomi: '' }, { en: 'confidence', ko: '신뢰, 자신(감)', ja: '', yomi: '' },
  { en: 'stare', ko: '응시하다', ja: '', yomi: '' }, { en: 'translate', ko: '번역하다', ja: '', yomi: '' }, { en: 'admiral', ko: '해군제독', ja: '', yomi: '' }, { en: 'erase', ko: '지우다', ja: '', yomi: '' },
  { en: 'frame', ko: '틀, 테', ja: '', yomi: '' }, { en: 'require', ko: '필요로 하다', ja: '', yomi: '' }, { en: 'contain', ko: '포함하다', ja: '', yomi: '' }, { en: 'surface', ko: '표면', ja: '', yomi: '' },
  { en: 'panic', ko: '공포, 공포를 느끼다', ja: '', yomi: '' }, { en: 'index', ko: '색인, 지표(지수)', ja: '', yomi: '' }, { en: 'unify', ko: '통일하다', ja: '', yomi: '' }, { en: 'association', ko: '협회', ja: '', yomi: '' },
  { en: 'attach', ko: '붙이다, 첨부하다', ja: '', yomi: '' }, { en: 'dessert', ko: '후식, 디저트', ja: '', yomi: '' }, { en: 'usual', ko: '보통의, 평소의', ja: '', yomi: '' }, { en: 'bound', ko: '꼭 할 것 같은', ja: '', yomi: '' },
  { en: 'crosswalk', ko: '횡단보도', ja: '', yomi: '' }, { en: 'differ', ko: '다르다', ja: '', yomi: '' }, { en: 'rapid', ko: '매우 빠른, 신속한', ja: '', yomi: '' }, { en: 'various', ko: '다양한, 여러 가지의', ja: '', yomi: '' },
  { en: 'accuse', ko: '고발하다', ja: '', yomi: '' }, { en: 'careless', ko: '부주의한', ja: '', yomi: '' }, { en: 'playground', ko: '놀이터, 운동장', ja: '', yomi: '' }, { en: 'mend', ko: '고치다, 수리하다', ja: '', yomi: '' },
  { en: 'mild', ko: '온화한', ja: '', yomi: '' }, { en: 'react', ko: '반응하다', ja: '', yomi: '' }, { en: 'odd', ko: '이상한, 잡다한, 홀수의', ja: '', yomi: '' }, { en: 'purchase', ko: '사다, 구입(하다)', ja: '', yomi: '' },
  { en: 'grave', ko: '무덤', ja: '', yomi: '' }, { en: 'distinguish', ko: '구별하다, 식별하다', ja: '', yomi: '' }, { en: 'needle', ko: '바늘', ja: '', yomi: '' }, { en: 'peer', ko: '또래', ja: '', yomi: '' },
  { en: 'civil', ko: '시민의, 민간의', ja: '', yomi: '' }, { en: 'skyscraper', ko: '초고층건물, 마천루', ja: '', yomi: '' }, { en: 'clever', ko: '영리한', ja: '', yomi: '' }, { en: 'lunar', ko: '달의', ja: '', yomi: '' },
  { en: 'secretary', ko: '비서', ja: '', yomi: '' }, { en: 'surround', ko: '둘러싸다', ja: '', yomi: '' }, { en: 'cheerful', ko: '명랑한, 유쾌한', ja: '', yomi: '' }, { en: 'emphasize', ko: '강조하다', ja: '', yomi: '' },
  { en: 'possess', ko: '소유하다', ja: '', yomi: '' }, { en: 'neither', ko: '어느 쪽도 아니다', ja: '', yomi: '' }, { en: 'backbone', ko: '등뼈, 척추', ja: '', yomi: '' }, { en: 'persuade', ko: '설득하다', ja: '', yomi: '' },
  { en: 'method', ko: '방법', ja: '', yomi: '' }, { en: 'pill', ko: '알약', ja: '', yomi: '' }, { en: 'wealthy', ko: '부유한', ja: '', yomi: '' }, { en: 'tiny', ko: '아주 작은', ja: '', yomi: '' },
  { en: 'distant', ko: '먼', ja: '', yomi: '' }, { en: 'unnecessary', ko: '불필요한', ja: '', yomi: '' }, { en: 'worldwide', ko: '세계적인, 세계 곳곳에', ja: '', yomi: '' }, { en: 'urgent', ko: '긴급한', ja: '', yomi: '' },
  { en: 'rob', ko: '빼앗다, 강탈하다', ja: '', yomi: '' }, { en: 'spicy', ko: '매운', ja: '', yomi: '' }, { en: 'reserve', ko: '예약하다', ja: '', yomi: '' }, { en: 'smooth', ko: '매끄러운, 부드러운', ja: '', yomi: '' },
  { en: 'conscious', ko: '의식하고 있는', ja: '', yomi: '' }, { en: 'swear', ko: '맹세하다, 욕하다', ja: '', yomi: '' }, { en: 'available', ko: '이용할 수 있는', ja: '', yomi: '' }, { en: 'alike', ko: '비슷한, 같은', ja: '', yomi: '' },
  { en: 'select', ko: '고르다, 뽑다', ja: '', yomi: '' }, { en: 'approve', ko: '승인하다, 찬성하다', ja: '', yomi: '' }, { en: 'disgusting', ko: '역겨운, 메스꺼운', ja: '', yomi: '' }, { en: 'response', ko: '반응, 응답', ja: '', yomi: '' },
  { en: 'independent', ko: '독립된', ja: '', yomi: '' }, { en: 'shy', ko: '수줍어하는', ja: '', yomi: '' }, { en: 'eastern', ko: '동쪽의', ja: '', yomi: '' }, { en: 'warmth', ko: '따뜻함', ja: '', yomi: '' },
  { en: 'continent', ko: '대륙', ja: '', yomi: '' }, { en: 'rate', ko: '비율', ja: '', yomi: '' }, { en: 'shut', ko: '닫다', ja: '', yomi: '' }, { en: 'range', ko: '범위', ja: '', yomi: '' },
  { en: 'cease', ko: '그만두다, 그치다', ja: '', yomi: '' }, { en: 'grand', ko: '웅대한', ja: '', yomi: '' }, { en: 'awful', ko: '끔찍한, 굉장한', ja: '', yomi: '' }, { en: 'former', ko: '이전의', ja: '', yomi: '' },
  { en: 'helpless', ko: '스스로 돌볼 수 없는', ja: '', yomi: '' }, { en: 'criticize', ko: '비난하다, 비평하다', ja: '', yomi: '' }, { en: 'inform', ko: '알리다, 통지하다', ja: '', yomi: '' }, { en: 'seek', ko: '구하다, 찾다', ja: '', yomi: '' },
  { en: 'ignore', ko: '무시하다', ja: '', yomi: '' }, { en: 'shell', ko: '껍질', ja: '', yomi: '' }, { en: 'refrigerator', ko: '냉장고', ja: '', yomi: '' }, { en: 'reveal', ko: '드러내다', ja: '', yomi: '' },
  { en: 'awkward', ko: '어색한', ja: '', yomi: '' }, { en: 'forbid', ko: '금지하다, 막다', ja: '', yomi: '' }, { en: 'reject', ko: '거부하다, 거절하다', ja: '', yomi: '' }, { en: 'security', ko: '보안, 보호', ja: '', yomi: '' },
  { en: 'combine', ko: '결합하다', ja: '', yomi: '' }, { en: 'compose', ko: '작곡하다, 구성하다', ja: '', yomi: '' }, { en: 'employ', ko: '고용하다', ja: '', yomi: '' }, { en: 'raw', ko: '날것의', ja: '', yomi: '' },
  { en: 'dare', ko: '감히~하다', ja: '', yomi: '' }, { en: 'willing', ko: '기꺼이 하는', ja: '', yomi: '' }, { en: 'absorb', ko: '빨아들이다, 흡수하다', ja: '', yomi: '' }, { en: 'plenty', ko: '많음, 충분함', ja: '', yomi: '' },
  { en: 'wander', ko: '돌아다니다, 배회하다', ja: '', yomi: '' }, { en: 'attractive', ko: '매력적인', ja: '', yomi: '' }, { en: 'spare', ko: '여가의, 여별의', ja: '', yomi: '' }, { en: 'incredible', ko: '믿을 수 없는, 엄청난', ja: '', yomi: '' },
  { en: 'calculate', ko: '계산하다', ja: '', yomi: '' }, { en: 'hammer', ko: '망치', ja: '', yomi: '' }, { en: 'owe', ko: '빚지고 있다', ja: '', yomi: '' }, { en: 'unique', ko: '유일한, 독특한', ja: '', yomi: '' },
  { en: 'defend', ko: '방어하다', ja: '', yomi: '' }, { en: 'found', ko: '설립하다', ja: '', yomi: '' }, { en: 'steady', ko: '꾸준한, 안정된', ja: '', yomi: '' }, { en: 'genetic', ko: '유전의', ja: '', yomi: '' },
  { en: 'envelope', ko: '봉투', ja: '', yomi: '' }, { en: 'extend', ko: '연장하다, 확장하다', ja: '', yomi: '' }, { en: 'conduct', ko: '수행하다, 지휘하다', ja: '', yomi: '' }, { en: 'hard-working', ko: '열심히 일하는, 근면한', ja: '', yomi: '' },
  { en: 'hunger', ko: '배고픔, 굶주림', ja: '', yomi: '' }, { en: 'literature', ko: '문학', ja: '', yomi: '' }, { en: 'rare', ko: '드문, 살짝 구운', ja: '', yomi: '' }, { en: 'skin', ko: '피부, 가죽, 껍질', ja: '', yomi: '' },
  { en: 'atmosphere', ko: '대기, 분위기', ja: '', yomi: '' }, { en: 'slight', ko: '약간의, 가벼운', ja: '', yomi: '' }, { en: 'romantic', ko: '낭만적인', ja: '', yomi: '' }, { en: 'resource', ko: '자원', ja: '', yomi: '' },
  { en: 'satisfactory', ko: '만족스러운', ja: '', yomi: '' }, { en: 'instrument', ko: '기구, 도구, 악기', ja: '', yomi: '' }, { en: 'oar', ko: '(배의)노', ja: '', yomi: '' }, { en: 'aspect', ko: '면, 양상', ja: '', yomi: '' },
  { en: 'court', ko: '법정, 코트, 궁정', ja: '', yomi: '' }, { en: 'definite', ko: '명확한', ja: '', yomi: '' }, { en: 'knee', ko: '무릎', ja: '', yomi: '' }, { en: 'nest', ko: '둥지, 보금자리', ja: '', yomi: '' },
  { en: 'bug', ko: '작은 곤충', ja: '', yomi: '' }, { en: 'tube', ko: '관(통), 튜브(용기)', ja: '', yomi: '' }, { en: 'license', ko: '면허', ja: '', yomi: '' }, { en: 'beast', ko: '짐승, 야수', ja: '', yomi: '' },
  { en: 'sum', ko: '금액, 합계, 요약하다', ja: '', yomi: '' }, { en: 'gap', ko: '틈, 격차', ja: '', yomi: '' }, { en: 'tradition', ko: '전통', ja: '', yomi: '' }, { en: 'destination', ko: '목적지', ja: '', yomi: '' },
  { en: 'justice', ko: '정의', ja: '', yomi: '' }, { en: 'authority', ko: '권한, 권위, 당국', ja: '', yomi: '' }, { en: 'voyage', ko: '긴 항해', ja: '', yomi: '' }, { en: 'outline', ko: '개요, 윤곽', ja: '', yomi: '' },
  { en: 'ordinary', ko: '보통의, 평범한', ja: '', yomi: '' }, { en: 'democracy', ko: '민주주의', ja: '', yomi: '' }, { en: 'scale', ko: '규모, 등급, 저울', ja: '', yomi: '' }, { en: 'private', ko: '사적인', ja: '', yomi: '' },
  { en: 'ceiling', ko: '천장', ja: '', yomi: '' }, { en: 'wage', ko: '임금, 노임', ja: '', yomi: '' }, { en: 'aware', ko: '알아차린, 알고 있는', ja: '', yomi: '' }, { en: 'rank', ko: '계급, 지위', ja: '', yomi: '' },
  { en: 'aisle', ko: '긴 통로', ja: '', yomi: '' }, { en: 'affair', ko: '일, 문제, 사건', ja: '', yomi: '' }, { en: 'labor', ko: '노동하다', ja: '', yomi: '' }, { en: 'pure', ko: '순수한, 맑은', ja: '', yomi: '' },
  { en: 'revolution', ko: '혁명', ja: '', yomi: '' }, { en: 'holy', ko: '신성한, 성스러운', ja: '', yomi: '' }, { en: 'concern', ko: '걱정, 관심, 관계되다', ja: '', yomi: '' }, { en: 'complicated', ko: '복잡한', ja: '', yomi: '' },
  { en: 'anger', ko: '화', ja: '', yomi: '' }, { en: 'jail', ko: '감옥, 교도소', ja: '', yomi: '' }, { en: 'pupil', ko: '학생, 눈동자', ja: '', yomi: '' }, { en: 'idle', ko: '한가한, 빈둥거리다', ja: '', yomi: '' },
  { en: 'mud', ko: '진흙', ja: '', yomi: '' }, { en: 'severe', ko: '심각한, 엄한', ja: '', yomi: '' }, { en: 'chef', ko: '주방장, 요리사', ja: '', yomi: '' }, { en: 'detective', ko: '형사, 탐정', ja: '', yomi: '' },
  { en: 'spot', ko: '장소, 지점, (반)점', ja: '', yomi: '' }, { en: 'blanket', ko: '담요', ja: '', yomi: '' }, { en: 'diligent', ko: '부지런한, 근면한', ja: '', yomi: '' }, { en: 'mankind', ko: '인류', ja: '', yomi: '' },
  { en: 'outer', ko: '외부의', ja: '', yomi: '' }, { en: 'opportunity', ko: '기회', ja: '', yomi: '' }, { en: 'leather', ko: '가죽', ja: '', yomi: '' }, { en: 'device', ko: '장치', ja: '', yomi: '' },
  { en: 'spectator', ko: '관객, 구경꾼', ja: '', yomi: '' }, { en: 'futurology', ko: '미래학', ja: '', yomi: '' }, { en: 'dictation', ko: '받아쓰기', ja: '', yomi: '' }, { en: 'efficient', ko: '능률적인, 효율적인', ja: '', yomi: '' },
  { en: 'blackboard', ko: '칠판', ja: '', yomi: '' }, { en: 'logical', ko: '논리적인', ja: '', yomi: '' }, { en: 'indoor', ko: '실내의', ja: '', yomi: '' }, { en: 'jam', ko: '막힘, 혼잡, (먹는)잼', ja: '', yomi: '' },
  { en: 'awake', ko: '깨어있는, 깨우다', ja: '', yomi: '' }, { en: 'broad', ko: '넓은', ja: '', yomi: '' }, { en: 'germ', ko: '병균, 싹', ja: '', yomi: '' }, { en: 'occupation', ko: '직업, 점령', ja: '', yomi: '' },
  { en: 'prison', ko: '감옥, 교도소', ja: '', yomi: '' }, { en: 'illusion', ko: '환상, 착각', ja: '', yomi: '' }, { en: 'steel', ko: '강철', ja: '', yomi: '' }, { en: 'counselor', ko: '상담원, 카운슬러', ja: '', yomi: '' },
  { en: 'journalism', ko: '저널리즘, 언론계', ja: '', yomi: '' }, { en: 'immigrant', ko: '이민자', ja: '', yomi: '' }, { en: 'target', ko: '목표, 표적(과녁)', ja: '', yomi: '' }, { en: 'occasion', ko: '때, 경우, 특별한 행사', ja: '', yomi: '' },
  { en: 'illegal', ko: '불법의', ja: '', yomi: '' }, { en: 'chemistry', ko: '화학', ja: '', yomi: '' }, { en: 'crime', ko: '범죄', ja: '', yomi: '' }, { en: 'dumb', ko: '벙어리의, 멍청한', ja: '', yomi: '' },
  { en: 'document', ko: '문서', ja: '', yomi: '' }, { en: 'navy', ko: '해군', ja: '', yomi: '' }, { en: 'semester', ko: '학기', ja: '', yomi: '' }, { en: 'instruction', ko: '지시', ja: '', yomi: '' },
  { en: 'bubble', ko: '거품', ja: '', yomi: '' }, { en: 'burden', ko: '짐, 부담', ja: '', yomi: '' }, { en: 'jewel', ko: '보석', ja: '', yomi: '' }, { en: 'fortune', ko: '행운, 큰돈', ja: '', yomi: '' },
  { en: 'conductor', ko: '지휘자, 차장', ja: '', yomi: '' }, { en: 'property', ko: '재산', ja: '', yomi: '' }, { en: 'profession', ko: '전문직, 전문직업인', ja: '', yomi: '' }, { en: 'length', ko: '길이', ja: '', yomi: '' },
  { en: 'obvious', ko: '명백한', ja: '', yomi: '' }, { en: 'process', ko: '과정, 처리하다', ja: '', yomi: '' }, { en: 'error', ko: '잘못, 실수, 오류', ja: '', yomi: '' }, { en: 'contribute', ko: '기부하다, 기여하다', ja: '', yomi: '' },
]
