// 천수경 (Cheonsugyeong / Thousand-Hands Sutra) — recitation viewer data.
//
// hanja (원문) + reading (독음) + structure are public domain. translation/
// translationJa/translationEn (meanings), readingJa, and sectionEn are ToolBoxy's
// OWN renderings; readingEn is a Revised-Romanization of the Korean reading.
// 진언/다라니/명호 lines are transliterations.
//
// AUTO-GENERATED — do not edit by hand (see scripts/gen-cheon-en.mjs et al.).

export interface SutraLine {
  order: number
  section: number
  sectionKo: string
  sectionHanja: string
  sectionEn: string
  type: string
  hanja: string
  reading: string
  readingJa: string
  readingEn: string
  translation: string
  translationJa: string
  translationEn: string
  repeat: number
  note: string
}

export const CHEONSUGYEONG: SutraLine[] = [
  {
    "order": 1,
    "section": 1,
    "sectionKo": "정구업진언",
    "sectionHanja": "淨口業眞言",
    "type": "진언",
    "hanja": "",
    "reading": "수리수리 마하수리 수수리 사바하",
    "translation": "",
    "repeat": 3,
    "note": "구업을 청정케 하는 진언 / 음역 진언 — 번역하지 않고 음 그대로 봉독",
    "translationJa": "",
    "readingJa": "しゅりしゅり まかしゅり しゅしゅり そわか",
    "sectionEn": "Mantra for Purifying Speech-Karma",
    "readingEn": "surisuri mahasuri susuri sabaha",
    "translationEn": ""
  },
  {
    "order": 2,
    "section": 2,
    "sectionKo": "오방내외안위제신진언",
    "sectionHanja": "五方內外安慰諸神眞言",
    "type": "진언",
    "hanja": "",
    "reading": "나무 사만다 못다남 옴 도로 도로 지미 사바하",
    "translation": "",
    "repeat": 3,
    "note": "오방내외 신중을 편안하게 모시는 진언 / 음역 진언 — 번역하지 않고 음 그대로 봉독",
    "translationJa": "",
    "readingJa": "なむ さまんだ もとなん おん どろどろ ちみ そわか",
    "sectionEn": "Mantra to Comfort the Spirits of the Five Directions",
    "readingEn": "namu samanda motdanam om doro doro jimi sabaha",
    "translationEn": ""
  },
  {
    "order": 3,
    "section": 3,
    "sectionKo": "개경게",
    "sectionHanja": "開經偈",
    "type": "게송",
    "hanja": "無上甚深微妙法",
    "reading": "무상심심미묘법",
    "translation": "더없이 높고 깊은 미묘한 진리를",
    "repeat": 1,
    "note": "경전을 펴는 게송",
    "translationJa": "この上なく深く妙なる真理を",
    "readingJa": "むじょうじんじんみみょうほう",
    "sectionEn": "Verse for Opening the Sutra",
    "readingEn": "musangsimsimmimyobeop",
    "translationEn": "The supreme, profound, and sublime Dharma —"
  },
  {
    "order": 4,
    "section": 3,
    "sectionKo": "개경게",
    "sectionHanja": "開經偈",
    "type": "게송",
    "hanja": "百千萬劫難遭遇",
    "reading": "백천만겁난조우",
    "translation": "헤아릴 수 없는 세월에도 만나기 어려운데",
    "repeat": 1,
    "note": "경전을 펴는 게송",
    "translationJa": "計り知れない歳月にも出会いがたいのに",
    "readingJa": "ひゃくせんまんごうなんそうぐう",
    "sectionEn": "Verse for Opening the Sutra",
    "readingEn": "baekcheonmangeopnanjou",
    "translationEn": "hard to encounter even in countless ages —"
  },
  {
    "order": 5,
    "section": 3,
    "sectionKo": "개경게",
    "sectionHanja": "開經偈",
    "type": "게송",
    "hanja": "我今聞見得受持",
    "reading": "아금문견득수지",
    "translation": "제가 지금 보고 듣고 받아 지니게 되었으니",
    "repeat": 1,
    "note": "경전을 펴는 게송",
    "translationJa": "私は今、見て聞いて受け持つことができたので",
    "readingJa": "がこんもんけんとくじゅじ",
    "sectionEn": "Verse for Opening the Sutra",
    "readingEn": "ageummungyeondeuksuji",
    "translationEn": "now I see, hear, receive, and uphold it;"
  },
  {
    "order": 6,
    "section": 3,
    "sectionKo": "개경게",
    "sectionHanja": "開經偈",
    "type": "게송",
    "hanja": "願解如來眞實義",
    "reading": "원해여래진실의",
    "translation": "부처님의 참뜻을 깨닫기를 발원합니다",
    "repeat": 1,
    "note": "경전을 펴는 게송",
    "translationJa": "仏の真意を悟れますよう願います",
    "readingJa": "がんげにょらいしんじつぎ",
    "sectionEn": "Verse for Opening the Sutra",
    "readingEn": "wonhaeyeoraejinsilui",
    "translationEn": "I vow to understand the Buddha's true meaning."
  },
  {
    "order": 7,
    "section": 4,
    "sectionKo": "개법장진언",
    "sectionHanja": "開法藏眞言",
    "type": "진언",
    "hanja": "",
    "reading": "옴 아라남 아라다",
    "translation": "",
    "repeat": 3,
    "note": "법장을 여는 진언 / 음역 진언 — 번역하지 않고 음 그대로 봉독",
    "translationJa": "",
    "readingJa": "おん あらなん あらだ",
    "sectionEn": "Mantra for Opening the Dharma Treasury",
    "readingEn": "om aranam arada",
    "translationEn": ""
  },
  {
    "order": 8,
    "section": 5,
    "sectionKo": "천수천안관자재보살광대원만무애대비심대다라니계청",
    "sectionHanja": "千手千眼觀自在菩薩廣大圓滿無㝵大悲心大陀羅尼啓請",
    "type": "계청",
    "hanja": "千手千眼觀自在菩薩廣大圓滿",
    "reading": "천수천안 관자재보살 광대원만",
    "translation": "천 개의 손과 천 개의 눈을 지니신 관자재보살은 그 자비가 넓고 원만하시며",
    "repeat": 1,
    "note": "대비주를 청하는 계청",
    "translationJa": "千の手と千の眼を持つ観自在菩薩は、その慈悲が広く円満であり",
    "readingJa": "せんじゅせんげん かんじざいぼさつ こうだいえんまん",
    "sectionEn": "Invocation of the Great Compassion Dharani of the Thousand-Hand, Thousand-Eye Bodhisattva",
    "readingEn": "cheonsucheonan gwanjajaebosal gwangdaewonman",
    "translationEn": "Avalokiteshvara of a thousand hands and a thousand eyes, whose compassion is vast and perfect,"
  },
  {
    "order": 9,
    "section": 5,
    "sectionKo": "천수천안관자재보살광대원만무애대비심대다라니계청",
    "sectionHanja": "千手千眼觀自在菩薩廣大圓滿無㝵大悲心大陀羅尼啓請",
    "type": "계청",
    "hanja": "無㝵大悲心大陀羅尼啓請",
    "reading": "무애대비심 대다라니 계청",
    "translation": "걸림 없는 큰 자비심의 대다라니를 청하여 받듭니다",
    "repeat": 1,
    "note": "대비주를 청하는 계청",
    "translationJa": "とらわれのない大いなる慈悲心の大陀羅尼を請い、お受けします",
    "readingJa": "むげ だいひしん だいだらに けいしょう",
    "sectionEn": "Invocation of the Great Compassion Dharani of the Thousand-Hand, Thousand-Eye Bodhisattva",
    "readingEn": "muaedaebisim daedarani gyecheong",
    "translationEn": "I invoke and uphold the Great Dharani of unobstructed, boundless compassion."
  },
  {
    "order": 10,
    "section": 5,
    "sectionKo": "천수천안관자재보살광대원만무애대비심대다라니계청",
    "sectionHanja": "千手千眼觀自在菩薩廣大圓滿無㝵大悲心大陀羅尼啓請",
    "type": "계청",
    "hanja": "稽首觀音大悲主",
    "reading": "계수관음대비주",
    "translation": "대자비의 주인이신 관세음보살께 머리 숙여 절하옵니다",
    "repeat": 1,
    "note": "대비주를 청하는 계청",
    "translationJa": "大慈悲の主である観世音菩薩に、頭を垂れて礼拝します",
    "readingJa": "けいしゅ かんのん だいひしゅ",
    "sectionEn": "Invocation of the Great Compassion Dharani of the Thousand-Hand, Thousand-Eye Bodhisattva",
    "readingEn": "gyesugwaneumdaebiju",
    "translationEn": "I bow my head to Avalokiteshvara, lord of great compassion."
  },
  {
    "order": 11,
    "section": 5,
    "sectionKo": "천수천안관자재보살광대원만무애대비심대다라니계청",
    "sectionHanja": "千手千眼觀自在菩薩廣大圓滿無㝵大悲心大陀羅尼啓請",
    "type": "계청",
    "hanja": "願力洪深相好身",
    "reading": "원력홍심상호신",
    "translation": "크고 깊은 원력으로 거룩한 모습을 갖추시고",
    "repeat": 1,
    "note": "대비주를 청하는 계청",
    "translationJa": "大きく深い願力で尊いお姿を備えられ",
    "readingJa": "がんりき こうじん そうごうしん",
    "sectionEn": "Invocation of the Great Compassion Dharani of the Thousand-Hand, Thousand-Eye Bodhisattva",
    "readingEn": "wonryeokhongsimsanghosin",
    "translationEn": "With vast and deep vows you bear a holy form,"
  },
  {
    "order": 12,
    "section": 5,
    "sectionKo": "천수천안관자재보살광대원만무애대비심대다라니계청",
    "sectionHanja": "千手千眼觀自在菩薩廣大圓滿無㝵大悲心大陀羅尼啓請",
    "type": "계청",
    "hanja": "千臂莊嚴普護持",
    "reading": "천비장엄보호지",
    "translation": "천 개의 팔로 장엄하여 모든 중생을 두루 지켜 주시며",
    "repeat": 1,
    "note": "대비주를 청하는 계청",
    "translationJa": "千の腕で荘厳し、すべての衆生をあまねく守ってくださり",
    "readingJa": "せんぴ しょうごん ふごじ",
    "sectionEn": "Invocation of the Great Compassion Dharani of the Thousand-Hand, Thousand-Eye Bodhisattva",
    "readingEn": "cheonbijangeombohoji",
    "translationEn": "adorned with a thousand arms to protect all beings,"
  },
  {
    "order": 13,
    "section": 5,
    "sectionKo": "천수천안관자재보살광대원만무애대비심대다라니계청",
    "sectionHanja": "千手千眼觀自在菩薩廣大圓滿無㝵大悲心大陀羅尼啓請",
    "type": "계청",
    "hanja": "千眼光明遍觀照",
    "reading": "천안광명변관조",
    "translation": "천 개의 눈에서 나오는 광명으로 두루 살펴 비추시네",
    "repeat": 1,
    "note": "대비주를 청하는 계청",
    "translationJa": "千の眼から放つ光明であまねく照らし見られる",
    "readingJa": "せんげん こうみょう へんかんしょう",
    "sectionEn": "Invocation of the Great Compassion Dharani of the Thousand-Hand, Thousand-Eye Bodhisattva",
    "readingEn": "cheonangwangmyeongbyeongwanjo",
    "translationEn": "and with light from a thousand eyes you watch over and illumine all."
  },
  {
    "order": 14,
    "section": 5,
    "sectionKo": "천수천안관자재보살광대원만무애대비심대다라니계청",
    "sectionHanja": "千手千眼觀自在菩薩廣大圓滿無㝵大悲心大陀羅尼啓請",
    "type": "계청",
    "hanja": "眞實語中宣密語",
    "reading": "진실어중선밀어",
    "translation": "진실한 말씀 가운데 은밀한 다라니를 펴시고",
    "repeat": 1,
    "note": "대비주를 청하는 계청",
    "translationJa": "真実の言葉のうちに秘めた陀羅尼を説き",
    "readingJa": "しんじつご ちゅう せんみつご",
    "sectionEn": "Invocation of the Great Compassion Dharani of the Thousand-Hand, Thousand-Eye Bodhisattva",
    "readingEn": "jinsileojungseonmileo",
    "translationEn": "Within words of truth you reveal the secret Dharani,"
  },
  {
    "order": 15,
    "section": 5,
    "sectionKo": "천수천안관자재보살광대원만무애대비심대다라니계청",
    "sectionHanja": "千手千眼觀自在菩薩廣大圓滿無㝵大悲心大陀羅尼啓請",
    "type": "계청",
    "hanja": "無爲心內起悲心",
    "reading": "무위심내기비심",
    "translation": "함이 없는 마음 안에서 자비의 마음을 일으키시어",
    "repeat": 1,
    "note": "대비주를 청하는 계청",
    "translationJa": "無為の心の中から慈悲の心を起こされ",
    "readingJa": "むい しんない き ひしん",
    "sectionEn": "Invocation of the Great Compassion Dharani of the Thousand-Hand, Thousand-Eye Bodhisattva",
    "readingEn": "muwisimnaegibisim",
    "translationEn": "and from a mind of non-action you give rise to compassion,"
  },
  {
    "order": 16,
    "section": 5,
    "sectionKo": "천수천안관자재보살광대원만무애대비심대다라니계청",
    "sectionHanja": "千手千眼觀自在菩薩廣大圓滿無㝵大悲心大陀羅尼啓請",
    "type": "계청",
    "hanja": "速令滿足諸希求",
    "reading": "속령만족제희구",
    "translation": "모든 바람을 어서 채워 주시고",
    "repeat": 1,
    "note": "대비주를 청하는 계청",
    "translationJa": "あらゆる願いを速やかに満たしてくださり",
    "readingJa": "そくりょう まんぞく しょけぐ",
    "sectionEn": "Invocation of the Great Compassion Dharani of the Thousand-Hand, Thousand-Eye Bodhisattva",
    "readingEn": "sokryeongmanjokjehuigu",
    "translationEn": "swiftly fulfilling every wish"
  },
  {
    "order": 17,
    "section": 5,
    "sectionKo": "천수천안관자재보살광대원만무애대비심대다라니계청",
    "sectionHanja": "千手千眼觀自在菩薩廣大圓滿無㝵大悲心大陀羅尼啓請",
    "type": "계청",
    "hanja": "永使滅除諸罪業",
    "reading": "영사멸제제죄업",
    "translation": "온갖 죄업을 길이 없애 주시네",
    "repeat": 1,
    "note": "대비주를 청하는 계청",
    "translationJa": "もろもろの罪業を永く除いてくださる",
    "readingJa": "ようし めつじょ しょざいごう",
    "sectionEn": "Invocation of the Great Compassion Dharani of the Thousand-Hand, Thousand-Eye Bodhisattva",
    "readingEn": "yeongsamyeoljejejoeeop",
    "translationEn": "and forever dissolving all karmic wrongs."
  },
  {
    "order": 18,
    "section": 5,
    "sectionKo": "천수천안관자재보살광대원만무애대비심대다라니계청",
    "sectionHanja": "千手千眼觀自在菩薩廣大圓滿無㝵大悲心大陀羅尼啓請",
    "type": "계청",
    "hanja": "天龍衆聖同慈護",
    "reading": "천룡중성동자호",
    "translation": "천룡과 모든 성현이 함께 자비로 지켜 주시고",
    "repeat": 1,
    "note": "대비주를 청하는 계청",
    "translationJa": "天龍と聖賢たちが共に慈悲をもって護られ",
    "readingJa": "てんりゅう しゅしょう どうじご",
    "sectionEn": "Invocation of the Great Compassion Dharani of the Thousand-Hand, Thousand-Eye Bodhisattva",
    "readingEn": "cheonryongjungseongdongjaho",
    "translationEn": "Heavenly dragons and all sages guard with compassion,"
  },
  {
    "order": 19,
    "section": 5,
    "sectionKo": "천수천안관자재보살광대원만무애대비심대다라니계청",
    "sectionHanja": "千手千眼觀自在菩薩廣大圓滿無㝵大悲心大陀羅尼啓請",
    "type": "계청",
    "hanja": "百千三昧頓薰修",
    "reading": "백천삼매돈훈수",
    "translation": "백천의 삼매를 한순간에 닦아 이루니",
    "repeat": 1,
    "note": "대비주를 청하는 계청",
    "translationJa": "百千の三昧を一瞬にして成し遂げ",
    "readingJa": "ひゃくせん さんまい とんくんじゅ",
    "sectionEn": "Invocation of the Great Compassion Dharani of the Thousand-Hand, Thousand-Eye Bodhisattva",
    "readingEn": "baekcheonsammaedonhunsu",
    "translationEn": "and in a single moment a hundred thousand samadhis are perfected;"
  },
  {
    "order": 20,
    "section": 5,
    "sectionKo": "천수천안관자재보살광대원만무애대비심대다라니계청",
    "sectionHanja": "千手千眼觀自在菩薩廣大圓滿無㝵大悲心大陀羅尼啓請",
    "type": "계청",
    "hanja": "受持身是光明幢",
    "reading": "수지신시광명당",
    "translation": "이 다라니를 지닌 몸은 광명의 깃발이요",
    "repeat": 1,
    "note": "대비주를 청하는 계청",
    "translationJa": "この陀羅尼を持つ身は光明の幢(はた)であり",
    "readingJa": "じゅじしん ぜ こうみょうどう",
    "sectionEn": "Invocation of the Great Compassion Dharani of the Thousand-Hand, Thousand-Eye Bodhisattva",
    "readingEn": "sujisinsigwangmyeongdang",
    "translationEn": "the body that upholds this Dharani is a banner of light,"
  },
  {
    "order": 21,
    "section": 5,
    "sectionKo": "천수천안관자재보살광대원만무애대비심대다라니계청",
    "sectionHanja": "千手千眼觀自在菩薩廣大圓滿無㝵大悲心大陀羅尼啓請",
    "type": "계청",
    "hanja": "受持心是神通藏",
    "reading": "수지심시신통장",
    "translation": "이 다라니를 지닌 마음은 신통의 곳간이라",
    "repeat": 1,
    "note": "대비주를 청하는 계청",
    "translationJa": "この陀羅尼を持つ心は神通の蔵である",
    "readingJa": "じゅじしん ぜ じんづうぞう",
    "sectionEn": "Invocation of the Great Compassion Dharani of the Thousand-Hand, Thousand-Eye Bodhisattva",
    "readingEn": "sujisimsisintongjang",
    "translationEn": "and the mind that upholds it is a storehouse of spiritual power."
  },
  {
    "order": 22,
    "section": 5,
    "sectionKo": "천수천안관자재보살광대원만무애대비심대다라니계청",
    "sectionHanja": "千手千眼觀自在菩薩廣大圓滿無㝵大悲心大陀羅尼啓請",
    "type": "계청",
    "hanja": "洗滌塵勞願濟海",
    "reading": "세척진로원제해",
    "translation": "온갖 번뇌를 씻어 내고 고통의 바다를 건너",
    "repeat": 1,
    "note": "대비주를 청하는 계청",
    "translationJa": "もろもろの煩悩を洗い流し、苦しみの海を渡り",
    "readingJa": "せんでき じんろう がんさいかい",
    "sectionEn": "Invocation of the Great Compassion Dharani of the Thousand-Hand, Thousand-Eye Bodhisattva",
    "readingEn": "secheokjinrowonjehae",
    "translationEn": "It washes away every affliction and crosses the sea of suffering,"
  },
  {
    "order": 23,
    "section": 5,
    "sectionKo": "천수천안관자재보살광대원만무애대비심대다라니계청",
    "sectionHanja": "千手千眼觀自在菩薩廣大圓滿無㝵大悲心大陀羅尼啓請",
    "type": "계청",
    "hanja": "超證菩提方便門",
    "reading": "초증보리방편문",
    "translation": "깨달음에 이르는 방편의 문을 뛰어넘어 증득하오며",
    "repeat": 1,
    "note": "대비주를 청하는 계청",
    "translationJa": "悟りに至る方便の門を超えて証得し",
    "readingJa": "ちょうしょう ぼだい ほうべんもん",
    "sectionEn": "Invocation of the Great Compassion Dharani of the Thousand-Hand, Thousand-Eye Bodhisattva",
    "readingEn": "chojeungboribangpyeonmun",
    "translationEn": "and swiftly realizes the gateway of skillful means to awakening."
  },
  {
    "order": 24,
    "section": 5,
    "sectionKo": "천수천안관자재보살광대원만무애대비심대다라니계청",
    "sectionHanja": "千手千眼觀自在菩薩廣大圓滿無㝵大悲心大陀羅尼啓請",
    "type": "계청",
    "hanja": "我今稱誦誓歸依",
    "reading": "아금칭송서귀의",
    "translation": "제가 이제 외워 받들며 귀의하기를 맹세하오니",
    "repeat": 1,
    "note": "대비주를 청하는 계청",
    "translationJa": "私は今、唱え奉り帰依することを誓いますので",
    "readingJa": "がこん しょうじゅ せいきえ",
    "sectionEn": "Invocation of the Great Compassion Dharani of the Thousand-Hand, Thousand-Eye Bodhisattva",
    "readingEn": "ageumchingsongseogwiui",
    "translationEn": "Now I recite, uphold, and vow to take refuge;"
  },
  {
    "order": 25,
    "section": 5,
    "sectionKo": "천수천안관자재보살광대원만무애대비심대다라니계청",
    "sectionHanja": "千手千眼觀自在菩薩廣大圓滿無㝵大悲心大陀羅尼啓請",
    "type": "계청",
    "hanja": "所願從心悉圓滿",
    "reading": "소원종심실원만",
    "translation": "바라는 모든 일이 마음대로 다 이루어지이다",
    "repeat": 1,
    "note": "대비주를 청하는 계청",
    "translationJa": "願うすべてが心のままに叶いますように",
    "readingJa": "しょがん じゅうしん しつえんまん",
    "sectionEn": "Invocation of the Great Compassion Dharani of the Thousand-Hand, Thousand-Eye Bodhisattva",
    "readingEn": "sowonjongsimsilwonman",
    "translationEn": "may all that I wish be fulfilled as my heart desires."
  },
  {
    "order": 26,
    "section": 5,
    "sectionKo": "천수천안관자재보살광대원만무애대비심대다라니계청",
    "sectionHanja": "千手千眼觀自在菩薩廣大圓滿無㝵大悲心大陀羅尼啓請",
    "type": "발원",
    "hanja": "南無大悲觀世音 願我速知一切法",
    "reading": "나무대비관세음 원아속지일체법",
    "translation": "대비하신 관세음께 귀의하오니, 제가 모든 법을 어서 알게 하소서",
    "repeat": 1,
    "note": "십원(十願)",
    "translationJa": "大悲の観世音に帰依します。私が一切の法を速やかに知れますように",
    "readingJa": "なむ だいひ かんぜおん がんが そくち いっさいほう",
    "sectionEn": "Invocation of the Great Compassion Dharani of the Thousand-Hand, Thousand-Eye Bodhisattva",
    "readingEn": "namudaebigwanseeum wonasokjiilchebeop",
    "translationEn": "Homage to Avalokiteshvara of great compassion: may I swiftly know all dharmas."
  },
  {
    "order": 27,
    "section": 5,
    "sectionKo": "천수천안관자재보살광대원만무애대비심대다라니계청",
    "sectionHanja": "千手千眼觀自在菩薩廣大圓滿無㝵大悲心大陀羅尼啓請",
    "type": "발원",
    "hanja": "南無大悲觀世音 願我早得智慧眼",
    "reading": "나무대비관세음 원아조득지혜안",
    "translation": "대비하신 관세음께 귀의하오니, 제가 지혜의 눈을 어서 얻게 하소서",
    "repeat": 1,
    "note": "십원(十願)",
    "translationJa": "大悲の観世音に帰依します。私が智慧の眼を速やかに得られますように",
    "readingJa": "なむ だいひ かんぜおん がんが そうとく ちえげん",
    "sectionEn": "Invocation of the Great Compassion Dharani of the Thousand-Hand, Thousand-Eye Bodhisattva",
    "readingEn": "namudaebigwanseeum wonajodeukjihyean",
    "translationEn": "Homage to Avalokiteshvara of great compassion: may I swiftly attain the eye of wisdom."
  },
  {
    "order": 28,
    "section": 5,
    "sectionKo": "천수천안관자재보살광대원만무애대비심대다라니계청",
    "sectionHanja": "千手千眼觀自在菩薩廣大圓滿無㝵大悲心大陀羅尼啓請",
    "type": "발원",
    "hanja": "南無大悲觀世音 願我速度一切衆",
    "reading": "나무대비관세음 원아속도일체중",
    "translation": "대비하신 관세음께 귀의하오니, 제가 모든 중생을 어서 건지게 하소서",
    "repeat": 1,
    "note": "십원(十願)",
    "translationJa": "大悲の観世音に帰依します。私が一切の衆生を速やかに救えますように",
    "readingJa": "なむ だいひ かんぜおん がんが そくど いっさいしゅ",
    "sectionEn": "Invocation of the Great Compassion Dharani of the Thousand-Hand, Thousand-Eye Bodhisattva",
    "readingEn": "namudaebigwanseeum wonasokdoilchejung",
    "translationEn": "Homage to Avalokiteshvara of great compassion: may I swiftly ferry all beings across."
  },
  {
    "order": 29,
    "section": 5,
    "sectionKo": "천수천안관자재보살광대원만무애대비심대다라니계청",
    "sectionHanja": "千手千眼觀自在菩薩廣大圓滿無㝵大悲心大陀羅尼啓請",
    "type": "발원",
    "hanja": "南無大悲觀世音 願我早得善方便",
    "reading": "나무대비관세음 원아조득선방편",
    "translation": "대비하신 관세음께 귀의하오니, 제가 좋은 방편을 어서 얻게 하소서",
    "repeat": 1,
    "note": "십원(十願)",
    "translationJa": "大悲の観世音に帰依します。私が善き方便を速やかに得られますように",
    "readingJa": "なむ だいひ かんぜおん がんが そうとく ぜんほうべん",
    "sectionEn": "Invocation of the Great Compassion Dharani of the Thousand-Hand, Thousand-Eye Bodhisattva",
    "readingEn": "namudaebigwanseeum wonajodeukseonbangpyeon",
    "translationEn": "Homage to Avalokiteshvara of great compassion: may I swiftly gain skillful means."
  },
  {
    "order": 30,
    "section": 5,
    "sectionKo": "천수천안관자재보살광대원만무애대비심대다라니계청",
    "sectionHanja": "千手千眼觀自在菩薩廣大圓滿無㝵大悲心大陀羅尼啓請",
    "type": "발원",
    "hanja": "南無大悲觀世音 願我速乘般若船",
    "reading": "나무대비관세음 원아속승반야선",
    "translation": "대비하신 관세음께 귀의하오니, 제가 반야의 배에 어서 오르게 하소서",
    "repeat": 1,
    "note": "십원(十願)",
    "translationJa": "大悲の観世音に帰依します。私が般若の舟に速やかに乗れますように",
    "readingJa": "なむ だいひ かんぜおん がんが そくじょう はんにゃせん",
    "sectionEn": "Invocation of the Great Compassion Dharani of the Thousand-Hand, Thousand-Eye Bodhisattva",
    "readingEn": "namudaebigwanseeum wonasokseungbanyaseon",
    "translationEn": "Homage to Avalokiteshvara of great compassion: may I swiftly board the ship of prajna (wisdom)."
  },
  {
    "order": 31,
    "section": 5,
    "sectionKo": "천수천안관자재보살광대원만무애대비심대다라니계청",
    "sectionHanja": "千手千眼觀自在菩薩廣大圓滿無㝵大悲心大陀羅尼啓請",
    "type": "발원",
    "hanja": "南無大悲觀世音 願我早得越苦海",
    "reading": "나무대비관세음 원아조득월고해",
    "translation": "대비하신 관세음께 귀의하오니, 제가 고통의 바다를 어서 건너게 하소서",
    "repeat": 1,
    "note": "십원(十願)",
    "translationJa": "大悲の観世音に帰依します。私が苦しみの海を速やかに渡れますように",
    "readingJa": "なむ だいひ かんぜおん がんが そうとく おっくかい",
    "sectionEn": "Invocation of the Great Compassion Dharani of the Thousand-Hand, Thousand-Eye Bodhisattva",
    "readingEn": "namudaebigwanseeum wonajodeukwolgohae",
    "translationEn": "Homage to Avalokiteshvara of great compassion: may I swiftly cross the sea of suffering."
  },
  {
    "order": 32,
    "section": 5,
    "sectionKo": "천수천안관자재보살광대원만무애대비심대다라니계청",
    "sectionHanja": "千手千眼觀自在菩薩廣大圓滿無㝵大悲心大陀羅尼啓請",
    "type": "발원",
    "hanja": "南無大悲觀世音 願我速得戒定道",
    "reading": "나무대비관세음 원아속득계정도",
    "translation": "대비하신 관세음께 귀의하오니, 제가 계·정·혜의 길을 어서 얻게 하소서",
    "repeat": 1,
    "note": "십원(十願)",
    "translationJa": "大悲の観世音に帰依します。私が戒・定・慧の道を速やかに得られますように",
    "readingJa": "なむ だいひ かんぜおん がんが そくとく かいじょうどう",
    "sectionEn": "Invocation of the Great Compassion Dharani of the Thousand-Hand, Thousand-Eye Bodhisattva",
    "readingEn": "namudaebigwanseeum wonasokdeukgyejeongdo",
    "translationEn": "Homage to Avalokiteshvara of great compassion: may I swiftly attain the path of precepts, meditation, and wisdom."
  },
  {
    "order": 33,
    "section": 5,
    "sectionKo": "천수천안관자재보살광대원만무애대비심대다라니계청",
    "sectionHanja": "千手千眼觀自在菩薩廣大圓滿無㝵大悲心大陀羅尼啓請",
    "type": "발원",
    "hanja": "南無大悲觀世音 願我早登圓寂山",
    "reading": "나무대비관세음 원아조등원적산",
    "translation": "대비하신 관세음께 귀의하오니, 제가 열반의 산에 어서 오르게 하소서",
    "repeat": 1,
    "note": "십원(十願)",
    "translationJa": "大悲の観世音に帰依します。私が涅槃の山に速やかに登れますように",
    "readingJa": "なむ だいひ かんぜおん がんが そうとう えんじゃくさん",
    "sectionEn": "Invocation of the Great Compassion Dharani of the Thousand-Hand, Thousand-Eye Bodhisattva",
    "readingEn": "namudaebigwanseeum wonajodeungwonjeoksan",
    "translationEn": "Homage to Avalokiteshvara of great compassion: may I swiftly ascend the mountain of nirvana."
  },
  {
    "order": 34,
    "section": 5,
    "sectionKo": "천수천안관자재보살광대원만무애대비심대다라니계청",
    "sectionHanja": "千手千眼觀自在菩薩廣大圓滿無㝵大悲心大陀羅尼啓請",
    "type": "발원",
    "hanja": "南無大悲觀世音 願我速會無爲舍",
    "reading": "나무대비관세음 원아속회무위사",
    "translation": "대비하신 관세음께 귀의하오니, 제가 함이 없는 집에 어서 이르게 하소서",
    "repeat": 1,
    "note": "십원(十願)",
    "translationJa": "大悲の観世音に帰依します。私が無為の家に速やかに至れますように",
    "readingJa": "なむ だいひ かんぜおん がんが そくえ むいしゃ",
    "sectionEn": "Invocation of the Great Compassion Dharani of the Thousand-Hand, Thousand-Eye Bodhisattva",
    "readingEn": "namudaebigwanseeum wonasokhoemuwisa",
    "translationEn": "Homage to Avalokiteshvara of great compassion: may I swiftly reach the house of non-action."
  },
  {
    "order": 35,
    "section": 5,
    "sectionKo": "천수천안관자재보살광대원만무애대비심대다라니계청",
    "sectionHanja": "千手千眼觀自在菩薩廣大圓滿無㝵大悲心大陀羅尼啓請",
    "type": "발원",
    "hanja": "南無大悲觀世音 願我早同法性身",
    "reading": "나무대비관세음 원아조동법성신",
    "translation": "대비하신 관세음께 귀의하오니, 제가 법성의 몸과 어서 하나 되게 하소서",
    "repeat": 1,
    "note": "십원(十願)",
    "translationJa": "大悲の観世音に帰依します。私が法性の身と速やかに一つになれますように",
    "readingJa": "なむ だいひ かんぜおん がんが そうどう ほっしょうしん",
    "sectionEn": "Invocation of the Great Compassion Dharani of the Thousand-Hand, Thousand-Eye Bodhisattva",
    "readingEn": "namudaebigwanseeum wonajodongbeopseongsin",
    "translationEn": "Homage to Avalokiteshvara of great compassion: may I swiftly become one with the body of dharma-nature."
  },
  {
    "order": 36,
    "section": 5,
    "sectionKo": "천수천안관자재보살광대원만무애대비심대다라니계청",
    "sectionHanja": "千手千眼觀自在菩薩廣大圓滿無㝵大悲心大陀羅尼啓請",
    "type": "발원",
    "hanja": "我若向刀山 刀山自摧折",
    "reading": "아약향도산 도산자최절",
    "translation": "제가 칼산을 향하면 그 칼산이 저절로 꺾이고",
    "repeat": 1,
    "note": "육향(六向)",
    "translationJa": "私が刀の山に向かえば、その刀の山がおのずと砕け折れ",
    "readingJa": "がにゃく こうとうざん とうざん じざいしゃくせつ",
    "sectionEn": "Invocation of the Great Compassion Dharani of the Thousand-Hand, Thousand-Eye Bodhisattva",
    "readingEn": "ayakhyangdosan dosanjachoejeol",
    "translationEn": "If I face a mountain of swords, it shatters of itself;"
  },
  {
    "order": 37,
    "section": 5,
    "sectionKo": "천수천안관자재보살광대원만무애대비심대다라니계청",
    "sectionHanja": "千手千眼觀自在菩薩廣大圓滿無㝵大悲心大陀羅尼啓請",
    "type": "발원",
    "hanja": "我若向火湯 火湯自枯竭",
    "reading": "아약향화탕 화탕자고갈",
    "translation": "제가 끓는 불길을 향하면 그 불이 저절로 말라 없어지며",
    "repeat": 1,
    "note": "육향(六向)",
    "translationJa": "私が燃え盛る炎に向かえば、その火がおのずと枯れ尽き",
    "readingJa": "がにゃく こうかとう かとう じざいこかつ",
    "sectionEn": "Invocation of the Great Compassion Dharani of the Thousand-Hand, Thousand-Eye Bodhisattva",
    "readingEn": "ayakhyanghwatang hwatangjagogal",
    "translationEn": "if I face a cauldron of fire, the fire dries up of itself;"
  },
  {
    "order": 38,
    "section": 5,
    "sectionKo": "천수천안관자재보살광대원만무애대비심대다라니계청",
    "sectionHanja": "千手千眼觀自在菩薩廣大圓滿無㝵大悲心大陀羅尼啓請",
    "type": "발원",
    "hanja": "我若向地獄 地獄自消滅",
    "reading": "아약향지옥 지옥자소멸",
    "translation": "제가 지옥을 향하면 그 지옥이 저절로 사라지고",
    "repeat": 1,
    "note": "육향(六向)",
    "translationJa": "私が地獄に向かえば、その地獄がおのずと消え去り",
    "readingJa": "がにゃく こうじごく じごく じざいしょうめつ",
    "sectionEn": "Invocation of the Great Compassion Dharani of the Thousand-Hand, Thousand-Eye Bodhisattva",
    "readingEn": "ayakhyangjiok jiokjasomyeol",
    "translationEn": "if I face the hells, the hells vanish of themselves;"
  },
  {
    "order": 39,
    "section": 5,
    "sectionKo": "천수천안관자재보살광대원만무애대비심대다라니계청",
    "sectionHanja": "千手千眼觀自在菩薩廣大圓滿無㝵大悲心大陀羅尼啓請",
    "type": "발원",
    "hanja": "我若向餓鬼 餓鬼自飽滿",
    "reading": "아약향아귀 아귀자포만",
    "translation": "제가 아귀를 향하면 그 아귀가 저절로 배부르며",
    "repeat": 1,
    "note": "육향(六向)",
    "translationJa": "私が餓鬼に向かえば、その餓鬼がおのずと満ち足り",
    "readingJa": "がにゃく こうがき がき じざいほうまん",
    "sectionEn": "Invocation of the Great Compassion Dharani of the Thousand-Hand, Thousand-Eye Bodhisattva",
    "readingEn": "ayakhyangagwi agwijapoman",
    "translationEn": "if I face the hungry ghosts, they are filled of themselves;"
  },
  {
    "order": 40,
    "section": 5,
    "sectionKo": "천수천안관자재보살광대원만무애대비심대다라니계청",
    "sectionHanja": "千手千眼觀自在菩薩廣大圓滿無㝵大悲心大陀羅尼啓請",
    "type": "발원",
    "hanja": "我若向修羅 惡心自調伏",
    "reading": "아약향수라 악심자조복",
    "translation": "제가 아수라를 향하면 그 악한 마음이 저절로 다스려지고",
    "repeat": 1,
    "note": "육향(六向)",
    "translationJa": "私が修羅に向かえば、その悪しき心がおのずと調(ととの)い",
    "readingJa": "がにゃく こうしゅら あくしん じざいじょうぶく",
    "sectionEn": "Invocation of the Great Compassion Dharani of the Thousand-Hand, Thousand-Eye Bodhisattva",
    "readingEn": "ayakhyangsura aksimjajobok",
    "translationEn": "if I face the asuras, their malice is subdued of itself;"
  },
  {
    "order": 41,
    "section": 5,
    "sectionKo": "천수천안관자재보살광대원만무애대비심대다라니계청",
    "sectionHanja": "千手千眼觀自在菩薩廣大圓滿無㝵大悲心大陀羅尼啓請",
    "type": "발원",
    "hanja": "我若向畜生 自得大智慧",
    "reading": "아약향축생 자득대지혜",
    "translation": "제가 축생을 향하면 저절로 큰 지혜를 얻게 되이다",
    "repeat": 1,
    "note": "육향(六向)",
    "translationJa": "私が畜生に向かえば、おのずと大いなる智慧を得られますように",
    "readingJa": "がにゃく こうちくしょう じとく だいちえ",
    "sectionEn": "Invocation of the Great Compassion Dharani of the Thousand-Hand, Thousand-Eye Bodhisattva",
    "readingEn": "ayakhyangchuksaeng jadeukdaejihye",
    "translationEn": "if I face the animals, they gain great wisdom of themselves."
  },
  {
    "order": 42,
    "section": 5,
    "sectionKo": "천수천안관자재보살광대원만무애대비심대다라니계청",
    "sectionHanja": "千手千眼觀自在菩薩廣大圓滿無㝵大悲心大陀羅尼啓請",
    "type": "칭명",
    "hanja": "南無 관세음보살마하살",
    "reading": "나무 관세음보살마하살",
    "translation": "",
    "repeat": 1,
    "note": "명호(이름) — 음 그대로 봉독",
    "translationJa": "",
    "readingJa": "なむ かんぜおんぼさつまかさつ",
    "sectionEn": "Invocation of the Great Compassion Dharani of the Thousand-Hand, Thousand-Eye Bodhisattva",
    "readingEn": "namu gwanseeumbosalmahasal",
    "translationEn": ""
  },
  {
    "order": 43,
    "section": 5,
    "sectionKo": "천수천안관자재보살광대원만무애대비심대다라니계청",
    "sectionHanja": "千手千眼觀自在菩薩廣大圓滿無㝵大悲心大陀羅尼啓請",
    "type": "칭명",
    "hanja": "南無 대세지보살마하살",
    "reading": "나무 대세지보살마하살",
    "translation": "",
    "repeat": 1,
    "note": "명호(이름) — 음 그대로 봉독",
    "translationJa": "",
    "readingJa": "なむ だいせいしぼさつまかさつ",
    "sectionEn": "Invocation of the Great Compassion Dharani of the Thousand-Hand, Thousand-Eye Bodhisattva",
    "readingEn": "namu daesejibosalmahasal",
    "translationEn": ""
  },
  {
    "order": 44,
    "section": 5,
    "sectionKo": "천수천안관자재보살광대원만무애대비심대다라니계청",
    "sectionHanja": "千手千眼觀自在菩薩廣大圓滿無㝵大悲心大陀羅尼啓請",
    "type": "칭명",
    "hanja": "南無 천수보살마하살",
    "reading": "나무 천수보살마하살",
    "translation": "",
    "repeat": 1,
    "note": "명호(이름) — 음 그대로 봉독",
    "translationJa": "",
    "readingJa": "なむ せんじゅぼさつまかさつ",
    "sectionEn": "Invocation of the Great Compassion Dharani of the Thousand-Hand, Thousand-Eye Bodhisattva",
    "readingEn": "namu cheonsubosalmahasal",
    "translationEn": ""
  },
  {
    "order": 45,
    "section": 5,
    "sectionKo": "천수천안관자재보살광대원만무애대비심대다라니계청",
    "sectionHanja": "千手千眼觀自在菩薩廣大圓滿無㝵大悲心大陀羅尼啓請",
    "type": "칭명",
    "hanja": "南無 여의륜보살마하살",
    "reading": "나무 여의륜보살마하살",
    "translation": "",
    "repeat": 1,
    "note": "명호(이름) — 음 그대로 봉독",
    "translationJa": "",
    "readingJa": "なむ にょいりんぼさつまかさつ",
    "sectionEn": "Invocation of the Great Compassion Dharani of the Thousand-Hand, Thousand-Eye Bodhisattva",
    "readingEn": "namu yeouiryunbosalmahasal",
    "translationEn": ""
  },
  {
    "order": 46,
    "section": 5,
    "sectionKo": "천수천안관자재보살광대원만무애대비심대다라니계청",
    "sectionHanja": "千手千眼觀自在菩薩廣大圓滿無㝵大悲心大陀羅尼啓請",
    "type": "칭명",
    "hanja": "南無 대륜보살마하살",
    "reading": "나무 대륜보살마하살",
    "translation": "",
    "repeat": 1,
    "note": "명호(이름) — 음 그대로 봉독",
    "translationJa": "",
    "readingJa": "なむ だいりんぼさつまかさつ",
    "sectionEn": "Invocation of the Great Compassion Dharani of the Thousand-Hand, Thousand-Eye Bodhisattva",
    "readingEn": "namu daeryunbosalmahasal",
    "translationEn": ""
  },
  {
    "order": 47,
    "section": 5,
    "sectionKo": "천수천안관자재보살광대원만무애대비심대다라니계청",
    "sectionHanja": "千手千眼觀自在菩薩廣大圓滿無㝵大悲心大陀羅尼啓請",
    "type": "칭명",
    "hanja": "南無 관자재보살마하살",
    "reading": "나무 관자재보살마하살",
    "translation": "",
    "repeat": 1,
    "note": "명호(이름) — 음 그대로 봉독",
    "translationJa": "",
    "readingJa": "なむ かんじざいぼさつまかさつ",
    "sectionEn": "Invocation of the Great Compassion Dharani of the Thousand-Hand, Thousand-Eye Bodhisattva",
    "readingEn": "namu gwanjajaebosalmahasal",
    "translationEn": ""
  },
  {
    "order": 48,
    "section": 5,
    "sectionKo": "천수천안관자재보살광대원만무애대비심대다라니계청",
    "sectionHanja": "千手千眼觀自在菩薩廣大圓滿無㝵大悲心大陀羅尼啓請",
    "type": "칭명",
    "hanja": "南無 정취보살마하살",
    "reading": "나무 정취보살마하살",
    "translation": "",
    "repeat": 1,
    "note": "명호(이름) — 음 그대로 봉독",
    "translationJa": "",
    "readingJa": "なむ しょうしゅぼさつまかさつ",
    "sectionEn": "Invocation of the Great Compassion Dharani of the Thousand-Hand, Thousand-Eye Bodhisattva",
    "readingEn": "namu jeongchwibosalmahasal",
    "translationEn": ""
  },
  {
    "order": 49,
    "section": 5,
    "sectionKo": "천수천안관자재보살광대원만무애대비심대다라니계청",
    "sectionHanja": "千手千眼觀自在菩薩廣大圓滿無㝵大悲心大陀羅尼啓請",
    "type": "칭명",
    "hanja": "南無 만월보살마하살",
    "reading": "나무 만월보살마하살",
    "translation": "",
    "repeat": 1,
    "note": "명호(이름) — 음 그대로 봉독",
    "translationJa": "",
    "readingJa": "なむ まんがつぼさつまかさつ",
    "sectionEn": "Invocation of the Great Compassion Dharani of the Thousand-Hand, Thousand-Eye Bodhisattva",
    "readingEn": "namu manwolbosalmahasal",
    "translationEn": ""
  },
  {
    "order": 50,
    "section": 5,
    "sectionKo": "천수천안관자재보살광대원만무애대비심대다라니계청",
    "sectionHanja": "千手千眼觀自在菩薩廣大圓滿無㝵大悲心大陀羅尼啓請",
    "type": "칭명",
    "hanja": "南無 수월보살마하살",
    "reading": "나무 수월보살마하살",
    "translation": "",
    "repeat": 1,
    "note": "명호(이름) — 음 그대로 봉독",
    "translationJa": "",
    "readingJa": "なむ すいげつぼさつまかさつ",
    "sectionEn": "Invocation of the Great Compassion Dharani of the Thousand-Hand, Thousand-Eye Bodhisattva",
    "readingEn": "namu suwolbosalmahasal",
    "translationEn": ""
  },
  {
    "order": 51,
    "section": 5,
    "sectionKo": "천수천안관자재보살광대원만무애대비심대다라니계청",
    "sectionHanja": "千手千眼觀自在菩薩廣大圓滿無㝵大悲心大陀羅尼啓請",
    "type": "칭명",
    "hanja": "南無 군다리보살마하살",
    "reading": "나무 군다리보살마하살",
    "translation": "",
    "repeat": 1,
    "note": "명호(이름) — 음 그대로 봉독",
    "translationJa": "",
    "readingJa": "なむ ぐんだりぼさつまかさつ",
    "sectionEn": "Invocation of the Great Compassion Dharani of the Thousand-Hand, Thousand-Eye Bodhisattva",
    "readingEn": "namu gundaribosalmahasal",
    "translationEn": ""
  },
  {
    "order": 52,
    "section": 5,
    "sectionKo": "천수천안관자재보살광대원만무애대비심대다라니계청",
    "sectionHanja": "千手千眼觀自在菩薩廣大圓滿無㝵大悲心大陀羅尼啓請",
    "type": "칭명",
    "hanja": "南無 십일면보살마하살",
    "reading": "나무 십일면보살마하살",
    "translation": "",
    "repeat": 1,
    "note": "명호(이름) — 음 그대로 봉독",
    "translationJa": "",
    "readingJa": "なむ じゅういちめんぼさつまかさつ",
    "sectionEn": "Invocation of the Great Compassion Dharani of the Thousand-Hand, Thousand-Eye Bodhisattva",
    "readingEn": "namu sipilmyeonbosalmahasal",
    "translationEn": ""
  },
  {
    "order": 53,
    "section": 5,
    "sectionKo": "천수천안관자재보살광대원만무애대비심대다라니계청",
    "sectionHanja": "千手千眼觀自在菩薩廣大圓滿無㝵大悲心大陀羅尼啓請",
    "type": "칭명",
    "hanja": "南無 제대보살마하살",
    "reading": "나무 제대보살마하살",
    "translation": "",
    "repeat": 1,
    "note": "명호(이름) — 음 그대로 봉독",
    "translationJa": "",
    "readingJa": "なむ しょだいぼさつまかさつ",
    "sectionEn": "Invocation of the Great Compassion Dharani of the Thousand-Hand, Thousand-Eye Bodhisattva",
    "readingEn": "namu jedaebosalmahasal",
    "translationEn": ""
  },
  {
    "order": 54,
    "section": 5,
    "sectionKo": "천수천안관자재보살광대원만무애대비심대다라니계청",
    "sectionHanja": "千手千眼觀自在菩薩廣大圓滿無㝵大悲心大陀羅尼啓請",
    "type": "칭명",
    "hanja": "南無 本師 阿彌陀佛",
    "reading": "나무 본사 아미타불",
    "translation": "",
    "repeat": 3,
    "note": "명호(이름) — 음 그대로 봉독",
    "translationJa": "",
    "readingJa": "なむ ほんし あみだぶつ",
    "sectionEn": "Invocation of the Great Compassion Dharani of the Thousand-Hand, Thousand-Eye Bodhisattva",
    "readingEn": "namu bonsa amitabul",
    "translationEn": ""
  },
  {
    "order": 55,
    "section": 6,
    "sectionKo": "신묘장구대다라니",
    "sectionHanja": "神妙章句大陀羅尼",
    "type": "다라니",
    "hanja": "",
    "reading": "나모라 다나다라 야야 나막알약 바로기제 새바라야",
    "translation": "",
    "repeat": 1,
    "note": "신묘한 대다라니 / 음역 진언 — 번역하지 않고 음 그대로 봉독",
    "translationJa": "",
    "readingJa": "なむ からたんのう とらやーやー なむ おりやー ぼりょきーちー しふらーやー",
    "sectionEn": "The Great Dharani (Sublime Verses)",
    "readingEn": "namora danadara yaya namakalyak barogije saebaraya",
    "translationEn": ""
  },
  {
    "order": 56,
    "section": 6,
    "sectionKo": "신묘장구대다라니",
    "sectionHanja": "神妙章句大陀羅尼",
    "type": "다라니",
    "hanja": "",
    "reading": "모지사다바야 마하사다바야 마하가로 니가야 옴 살바 바예수",
    "translation": "",
    "repeat": 1,
    "note": "신묘한 대다라니 / 음역 진언 — 번역하지 않고 음 그대로 봉독",
    "translationJa": "",
    "readingJa": "ふじさとぼーやー もこさとぼーやー もこきゃーるにきゃーやー えん さーはらはーえー",
    "sectionEn": "The Great Dharani (Sublime Verses)",
    "readingEn": "mojisadabaya mahasadabaya mahagaro nigaya om salba bayesu",
    "translationEn": ""
  },
  {
    "order": 57,
    "section": 6,
    "sectionKo": "신묘장구대다라니",
    "sectionHanja": "神妙章句大陀羅尼",
    "type": "다라니",
    "hanja": "",
    "reading": "다라나 가라야 다사명 나막 까리다바 이맘알야 바로기제 새바라",
    "translation": "",
    "repeat": 1,
    "note": "신묘한 대다라니 / 음역 진언 — 번역하지 않고 음 그대로 봉독",
    "translationJa": "",
    "readingJa": "しゅーたんのうとんしゃー なむ しきりーといもー おりやー ぼりょきーちー しふらー",
    "sectionEn": "The Great Dharani (Sublime Verses)",
    "readingEn": "darana garaya dasamyeong namak kkaridaba imamalya barogije saebara",
    "translationEn": ""
  },
  {
    "order": 58,
    "section": 6,
    "sectionKo": "신묘장구대다라니",
    "sectionHanja": "神妙章句大陀羅尼",
    "type": "다라니",
    "hanja": "",
    "reading": "다바 니라간타 나막하리나야 마발다 이사미 살발타 사다남 수반아예염",
    "translation": "",
    "repeat": 1,
    "note": "신묘한 대다라니 / 음역 진언 — 번역하지 않고 음 그대로 봉독",
    "translationJa": "",
    "readingJa": "りんとうばー なむ のらーきんじー けいりー もこーはーどーしゃーめー さーぼーおーとうじょー しゅーべん おーしゅーいん",
    "sectionEn": "The Great Dharani (Sublime Verses)",
    "readingEn": "daba niraganta namakharinaya mabalda isami salbalta sadanam subanayeyeom",
    "translationEn": ""
  },
  {
    "order": 59,
    "section": 6,
    "sectionKo": "신묘장구대다라니",
    "sectionHanja": "神妙章句大陀羅尼",
    "type": "다라니",
    "hanja": "",
    "reading": "살바보다남 바바마라 미수다감 다냐타 옴 아로계 아로가 마지로가",
    "translation": "",
    "repeat": 1,
    "note": "신묘한 대다라니 / 음역 진언 — 번역하지 않고 음 그대로 봉독",
    "translationJa": "",
    "readingJa": "さーぼーさーとー のーもーぼーぎゃー もーはーてーちょー とじっとう とにゃーたー えん おーぼーろーけー ろーきゃーちー きゃーらーちー",
    "sectionEn": "The Great Dharani (Sublime Verses)",
    "readingEn": "salbabodanam babamara misudagam danyata om arogye aroga majiroga",
    "translationEn": ""
  },
  {
    "order": 60,
    "section": 6,
    "sectionKo": "신묘장구대다라니",
    "sectionHanja": "神妙章句大陀羅尼",
    "type": "다라니",
    "hanja": "",
    "reading": "지가란제 혜혜하례 마하모지 사다바 사마라 사마라 하리나야",
    "translation": "",
    "repeat": 1,
    "note": "신묘한 대다라니 / 음역 진언 — 번역하지 않고 음 그대로 봉독",
    "translationJa": "",
    "readingJa": "いーけいりー もーこーふじさーとー さーぼーさーぼー もーらーもーらー もーけいもーけい りーとーいん",
    "sectionEn": "The Great Dharani (Sublime Verses)",
    "readingEn": "jigaranje hyehyeharye mahamoji sadaba samara samara harinaya",
    "translationEn": ""
  },
  {
    "order": 61,
    "section": 6,
    "sectionKo": "신묘장구대다라니",
    "sectionHanja": "神妙章句大陀羅尼",
    "type": "다라니",
    "hanja": "",
    "reading": "구로구로 갈마 사다야 사다야 도로도로 미연제 마하미연제",
    "translation": "",
    "repeat": 1,
    "note": "신묘한 대다라니 / 음역 진언 — 번역하지 않고 음 그대로 봉독",
    "translationJa": "",
    "readingJa": "くーろーくーろー けーもー どーろーどーろー ばじゃやーちー もーこーばじゃやーちー",
    "sectionEn": "The Great Dharani (Sublime Verses)",
    "readingEn": "guroguro galma sadaya sadaya dorodoro miyeonje mahamiyeonje",
    "translationEn": ""
  },
  {
    "order": 62,
    "section": 6,
    "sectionKo": "신묘장구대다라니",
    "sectionHanja": "神妙章句大陀羅尼",
    "type": "다라니",
    "hanja": "",
    "reading": "다라다라 다린 나례 새바라 자라자라 마라미마라 아마라",
    "translation": "",
    "repeat": 1,
    "note": "신묘한 대다라니 / 음역 진언 — 번역하지 않고 음 그대로 봉독",
    "translationJa": "",
    "readingJa": "だーらーだーらー ちりにー しふらーやー しゃーらーしゃーらー まーまーはーまーらー",
    "sectionEn": "The Great Dharani (Sublime Verses)",
    "readingEn": "daradara darin narye saebara jarajara maramimara amara",
    "translationEn": ""
  },
  {
    "order": 63,
    "section": 6,
    "sectionKo": "신묘장구대다라니",
    "sectionHanja": "神妙章句大陀羅尼",
    "type": "다라니",
    "hanja": "",
    "reading": "몰제예혜혜 로계새바라 라아 미사미 나사야 나베 사미사미 나사야",
    "translation": "",
    "repeat": 1,
    "note": "신묘한 대다라니 / 음역 진언 — 번역하지 않고 음 그대로 봉독",
    "translationJa": "",
    "readingJa": "ぼくていりー いーけいいーけい しつのうしつのう あらさんふらしゃり はーざーはーざん ふらしゃやー",
    "sectionEn": "The Great Dharani (Sublime Verses)",
    "readingEn": "moljeyehyehye rogyesaebara raa misami nasaya nabe samisami nasaya",
    "translationEn": ""
  },
  {
    "order": 64,
    "section": 6,
    "sectionKo": "신묘장구대다라니",
    "sectionHanja": "神妙章句大陀羅尼",
    "type": "다라니",
    "hanja": "",
    "reading": "모하자라 미사미 나사야 호로호로 마라호로 하례 바나마나바",
    "translation": "",
    "repeat": 1,
    "note": "신묘한 대다라니 / 음역 진언 — 번역하지 않고 음 그대로 봉독",
    "translationJa": "",
    "readingJa": "くーろーくーろー まーらー くーろーくーろー けいりー さーらーさーらー",
    "sectionEn": "The Great Dharani (Sublime Verses)",
    "readingEn": "mohajara misami nasaya horohoro marahoro harye banamanaba",
    "translationEn": ""
  },
  {
    "order": 65,
    "section": 6,
    "sectionKo": "신묘장구대다라니",
    "sectionHanja": "神妙章句大陀羅尼",
    "type": "다라니",
    "hanja": "",
    "reading": "사라사라 시리시리 소로소로 못쟈못쟈 모다야 모다야 매다리야",
    "translation": "",
    "repeat": 1,
    "note": "신묘한 대다라니 / 음역 진언 — 번역하지 않고 음 그대로 봉독",
    "translationJa": "",
    "readingJa": "しりしり そろそろ ふじやーふじやー ふどやーふどやー みーちりやー",
    "sectionEn": "The Great Dharani (Sublime Verses)",
    "readingEn": "sarasara sirisiri sorosoro motjyamotjya modaya modaya maedariya",
    "translationEn": ""
  },
  {
    "order": 66,
    "section": 6,
    "sectionKo": "신묘장구대다라니",
    "sectionHanja": "神妙章句大陀羅尼",
    "type": "다라니",
    "hanja": "",
    "reading": "니라간타 가마사 날사남 바라하라나야 마낙 사바하",
    "translation": "",
    "repeat": 1,
    "note": "신묘한 대다라니 / 음역 진언 — 번역하지 않고 음 그대로 봉독",
    "translationJa": "",
    "readingJa": "のらーきんじー ちりしゅにのー はーやーもーのー そもこー",
    "sectionEn": "The Great Dharani (Sublime Verses)",
    "readingEn": "niraganta gamasa nalsanam baraharanaya manak sabaha",
    "translationEn": ""
  },
  {
    "order": 67,
    "section": 6,
    "sectionKo": "신묘장구대다라니",
    "sectionHanja": "神妙章句大陀羅尼",
    "type": "다라니",
    "hanja": "",
    "reading": "싯다야 사바하 마하싯다야 사바하 싯다유예 새바라야 사바하",
    "translation": "",
    "repeat": 1,
    "note": "신묘한 대다라니 / 음역 진언 — 번역하지 않고 음 그대로 봉독",
    "translationJa": "",
    "readingJa": "しったやー そもこー もこしったやー そもこー しっだゆーきー しふらーやー そもこー",
    "sectionEn": "The Great Dharani (Sublime Verses)",
    "readingEn": "sitdaya sabaha mahasitdaya sabaha sitdayuye saebaraya sabaha",
    "translationEn": ""
  },
  {
    "order": 68,
    "section": 6,
    "sectionKo": "신묘장구대다라니",
    "sectionHanja": "神妙章句大陀羅尼",
    "type": "다라니",
    "hanja": "",
    "reading": "니라간타야 사바하 바라하 목카싱하 목카야 사바하",
    "translation": "",
    "repeat": 1,
    "note": "신묘한 대다라니 / 음역 진언 — 번역하지 않고 음 그대로 봉독",
    "translationJa": "",
    "readingJa": "のらーきんじー そもこー まーらーのーらー そもこー",
    "sectionEn": "The Great Dharani (Sublime Verses)",
    "readingEn": "niragantaya sabaha baraha mokkasingha mokkaya sabaha",
    "translationEn": ""
  },
  {
    "order": 69,
    "section": 6,
    "sectionKo": "신묘장구대다라니",
    "sectionHanja": "神妙章句大陀羅尼",
    "type": "다라니",
    "hanja": "",
    "reading": "바나마 하따야 사바하 자가라 욕다야 사바하",
    "translation": "",
    "repeat": 1,
    "note": "신묘한 대다라니 / 음역 진언 — 번역하지 않고 음 그대로 봉독",
    "translationJa": "",
    "readingJa": "しらすー おもぎゃーやー そもこー そぼもこ あしったやー そもこー",
    "sectionEn": "The Great Dharani (Sublime Verses)",
    "readingEn": "banama hattaya sabaha jagara yokdaya sabaha",
    "translationEn": ""
  },
  {
    "order": 70,
    "section": 6,
    "sectionKo": "신묘장구대다라니",
    "sectionHanja": "神妙章句大陀羅尼",
    "type": "다라니",
    "hanja": "",
    "reading": "상카섭나네 모다나야 사바하 마하라 구타다라야 사바하",
    "translation": "",
    "repeat": 1,
    "note": "신묘한 대다라니 / 음역 진언 — 번역하지 않고 음 그대로 봉독",
    "translationJa": "",
    "readingJa": "しゃきらー あしったやー そもこー ほどもぎゃ しったやー そもこー",
    "sectionEn": "The Great Dharani (Sublime Verses)",
    "readingEn": "sangkaseopnane modanaya sabaha mahara gutadaraya sabaha",
    "translationEn": ""
  },
  {
    "order": 71,
    "section": 6,
    "sectionKo": "신묘장구대다라니",
    "sectionHanja": "神妙章句大陀羅尼",
    "type": "다라니",
    "hanja": "",
    "reading": "바마사간타 이사시체다 가릿나 이나야 사바하",
    "translation": "",
    "repeat": 1,
    "note": "신묘한 대다라니 / 음역 진언 — 번역하지 않고 음 그대로 봉독",
    "translationJa": "",
    "readingJa": "のらきんじー はーぎゃらやー そもこー",
    "sectionEn": "The Great Dharani (Sublime Verses)",
    "readingEn": "bamasaganta isasicheda garitna inaya sabaha",
    "translationEn": ""
  },
  {
    "order": 72,
    "section": 6,
    "sectionKo": "신묘장구대다라니",
    "sectionHanja": "神妙章句大陀羅尼",
    "type": "다라니",
    "hanja": "",
    "reading": "먀가라 잘마니바 사나야 사바하",
    "translation": "",
    "repeat": 1,
    "note": "신묘한 대다라니 / 음역 진언 — 번역하지 않고 음 그대로 봉독",
    "translationJa": "",
    "readingJa": "もーばりー しょうぎゃらやー そもこー",
    "sectionEn": "The Great Dharani (Sublime Verses)",
    "readingEn": "myagara jalmaniba sanaya sabaha",
    "translationEn": ""
  },
  {
    "order": 73,
    "section": 6,
    "sectionKo": "신묘장구대다라니",
    "sectionHanja": "神妙章句大陀羅尼",
    "type": "다라니",
    "hanja": "",
    "reading": "나모라 다나다라 야야 나막알야 바로기제 새바라야 사바하",
    "translation": "",
    "repeat": 3,
    "note": "대다라니 결문(3번) / 음역 진언 — 번역하지 않고 음 그대로 봉독",
    "translationJa": "",
    "readingJa": "なむ からたんのう とらやーやー なむ おりやー ぼりょきーちー しふらやー そもこー",
    "sectionEn": "The Great Dharani (Sublime Verses)",
    "readingEn": "namora danadara yaya namakalya barogije saebaraya sabaha",
    "translationEn": ""
  },
  {
    "order": 74,
    "section": 7,
    "sectionKo": "사방찬",
    "sectionHanja": "四方讚",
    "type": "게송",
    "hanja": "一灑東方潔道場",
    "reading": "일쇄동방결도량",
    "translation": "동쪽에 물을 뿌리니 도량이 깨끗해지고",
    "repeat": 1,
    "note": "사방을 깨끗이 하는 찬 / 독송은 하지 않음",
    "translationJa": "東に水を灑(そそ)げば道場が清められ",
    "readingJa": "いっさ とうほう けつどうじょう",
    "sectionEn": "Praise of the Four Directions",
    "readingEn": "ilswaedongbanggyeoldoryang",
    "translationEn": "Sprinkling water to the east, the sanctuary is cleansed;"
  },
  {
    "order": 75,
    "section": 7,
    "sectionKo": "사방찬",
    "sectionHanja": "四方讚",
    "type": "게송",
    "hanja": "二灑南方得淸凉",
    "reading": "이쇄남방득청량",
    "translation": "남쪽에 물을 뿌리니 시원하고 맑아지며",
    "repeat": 1,
    "note": "사방을 깨끗이 하는 찬 / 독송은 하지 않음",
    "translationJa": "南に水を灑げば清涼を得",
    "readingJa": "にさ なんぽう とくしょうりょう",
    "sectionEn": "Praise of the Four Directions",
    "readingEn": "iswaenambangdeukcheongryang",
    "translationEn": "sprinkling to the south, it grows cool and clear;"
  },
  {
    "order": 76,
    "section": 7,
    "sectionKo": "사방찬",
    "sectionHanja": "四方讚",
    "type": "게송",
    "hanja": "三灑西方俱淨土",
    "reading": "삼쇄서방구정토",
    "translation": "서쪽에 물을 뿌리니 정토를 이루고",
    "repeat": 1,
    "note": "사방을 깨끗이 하는 찬 / 독송은 하지 않음",
    "translationJa": "西に水を灑げば浄土をなし",
    "readingJa": "さんさ さいほう ぐじょうど",
    "sectionEn": "Praise of the Four Directions",
    "readingEn": "samswaeseobanggujeongto",
    "translationEn": "sprinkling to the west, a Pure Land is formed;"
  },
  {
    "order": 77,
    "section": 7,
    "sectionKo": "사방찬",
    "sectionHanja": "四方讚",
    "type": "게송",
    "hanja": "四灑北方永安康",
    "reading": "사쇄북방영안강",
    "translation": "북쪽에 물을 뿌리니 길이 평안해지네",
    "repeat": 1,
    "note": "사방을 깨끗이 하는 찬 / 독송은 하지 않음",
    "translationJa": "北に水を灑げば永く安らかになる",
    "readingJa": "しさ ほっぽう ようあんこう",
    "sectionEn": "Praise of the Four Directions",
    "readingEn": "saswaebukbangyeongangang",
    "translationEn": "sprinkling to the north, lasting peace is gained."
  },
  {
    "order": 78,
    "section": 8,
    "sectionKo": "도량찬",
    "sectionHanja": "道場讚",
    "type": "게송",
    "hanja": "道場淸淨無瑕穢",
    "reading": "도량청정무하예",
    "translation": "도량이 맑고 깨끗하여 티끌 하나 없으니",
    "repeat": 1,
    "note": "청정한 도량의 찬 / 독송은 하지 않음",
    "translationJa": "道場が清らかで一点の汚れもなく",
    "readingJa": "どうじょう しょうじょう むかえ",
    "sectionEn": "Praise of the Sacred Place",
    "readingEn": "doryangcheongjeongmuhaye",
    "translationEn": "The sanctuary is pure and clear, without a speck of dust,"
  },
  {
    "order": 79,
    "section": 8,
    "sectionKo": "도량찬",
    "sectionHanja": "道場讚",
    "type": "게송",
    "hanja": "三寶天龍降此地",
    "reading": "삼보천룡강차지",
    "translation": "삼보와 천룡이 이 땅에 내려오시네",
    "repeat": 1,
    "note": "청정한 도량의 찬 / 독송은 하지 않음",
    "translationJa": "三宝と天龍がこの地に降りてこられる",
    "readingJa": "さんぼう てんりゅう ごうしじ",
    "sectionEn": "Praise of the Sacred Place",
    "readingEn": "sambocheonryonggangchaji",
    "translationEn": "and the Three Jewels and heavenly dragons descend to this place."
  },
  {
    "order": 80,
    "section": 8,
    "sectionKo": "도량찬",
    "sectionHanja": "道場讚",
    "type": "게송",
    "hanja": "我今持誦妙眞言",
    "reading": "아금지송묘진언",
    "translation": "제가 이제 미묘한 진언을 외우오니",
    "repeat": 1,
    "note": "청정한 도량의 찬 / 독송은 하지 않음",
    "translationJa": "私は今、妙なる真言を唱えますので",
    "readingJa": "がこん じじゅ みょうしんごん",
    "sectionEn": "Praise of the Sacred Place",
    "readingEn": "ageumjisongmyojineon",
    "translationEn": "Now I recite the sublime mantra;"
  },
  {
    "order": 81,
    "section": 8,
    "sectionKo": "도량찬",
    "sectionHanja": "道場讚",
    "type": "게송",
    "hanja": "願賜慈悲密加護",
    "reading": "원사자비밀가호",
    "translation": "자비를 베푸시어 가만히 지켜 주소서",
    "repeat": 1,
    "note": "청정한 도량의 찬 / 독송은 하지 않음",
    "translationJa": "慈悲を垂れ、ひそかにお守りください",
    "readingJa": "がんし じひ みつかご",
    "sectionEn": "Praise of the Sacred Place",
    "readingEn": "wonsajabimilgaho",
    "translationEn": "in compassion, quietly watch over and protect us."
  },
  {
    "order": 82,
    "section": 9,
    "sectionKo": "참회게",
    "sectionHanja": "懺悔偈",
    "type": "게송",
    "hanja": "我昔所造諸惡業",
    "reading": "아석소조제악업",
    "translation": "제가 지난날 지은 모든 나쁜 업은",
    "repeat": 1,
    "note": "죄업을 뉘우치는 게송 / 독송은 하지 않음",
    "translationJa": "私が過去に作ったすべての悪業は",
    "readingJa": "がしゃく しょぞう しょあくごう",
    "sectionEn": "Verse of Repentance",
    "readingEn": "aseoksojojeakeop",
    "translationEn": "All the evil karma I have made in the past"
  },
  {
    "order": 83,
    "section": 9,
    "sectionKo": "참회게",
    "sectionHanja": "懺悔偈",
    "type": "게송",
    "hanja": "皆由無始貪瞋癡",
    "reading": "개유무시탐진치",
    "translation": "모두 비롯함이 없는 탐냄·성냄·어리석음에서 말미암아",
    "repeat": 1,
    "note": "죄업을 뉘우치는 게송 / 독송은 하지 않음",
    "translationJa": "みな始まりのない貪り・瞋り・愚かさによって",
    "readingJa": "かいゆ むし とんじんち",
    "sectionEn": "Verse of Repentance",
    "readingEn": "gaeyumusitamjinchi",
    "translationEn": "arose from beginningless greed, hatred, and delusion,"
  },
  {
    "order": 84,
    "section": 9,
    "sectionKo": "참회게",
    "sectionHanja": "懺悔偈",
    "type": "게송",
    "hanja": "從身口意之所生",
    "reading": "종신구의지소생",
    "translation": "몸과 입과 뜻으로 지은 것이니",
    "repeat": 1,
    "note": "죄업을 뉘우치는 게송 / 독송은 하지 않음",
    "translationJa": "身と口と意によって作ったものであり",
    "readingJa": "じゅう しんくい ししょしょう",
    "sectionEn": "Verse of Repentance",
    "readingEn": "jongsinguuijisosaeng",
    "translationEn": "born of body, speech, and mind;"
  },
  {
    "order": 85,
    "section": 9,
    "sectionKo": "참회게",
    "sectionHanja": "懺悔偈",
    "type": "게송",
    "hanja": "一切我今皆懺悔",
    "reading": "일체아금개참회",
    "translation": "그 모든 것을 제가 이제 다 참회합니다",
    "repeat": 1,
    "note": "죄업을 뉘우치는 게송 / 독송은 하지 않음",
    "translationJa": "そのすべてを私は今、ことごとく懺悔します",
    "readingJa": "いっさい がこん かいさんげ",
    "sectionEn": "Verse of Repentance",
    "readingEn": "ilcheageumgaechamhoe",
    "translationEn": "all of it I now repent."
  },
  {
    "order": 86,
    "section": 10,
    "sectionKo": "참제업장십이존불",
    "sectionHanja": "懺除業障十二尊佛",
    "type": "칭명",
    "hanja": "南無懺除業障寶勝藏佛",
    "reading": "나무 참제업장보승장불",
    "translation": "",
    "repeat": 1,
    "note": "열두 부처님 칭명(가지참회) / 독송은 하지 않음 / 명호(이름) — 음 그대로 봉독",
    "translationJa": "",
    "readingJa": "なむ さんじょごっしょう ほうしょうぞうぶつ",
    "sectionEn": "The Twelve Buddhas Who Remove Karmic Hindrances",
    "readingEn": "namu chamjeeopjangboseungjangbul",
    "translationEn": ""
  },
  {
    "order": 87,
    "section": 10,
    "sectionKo": "참제업장십이존불",
    "sectionHanja": "懺除業障十二尊佛",
    "type": "칭명",
    "hanja": "寶光王火炎照佛",
    "reading": "보광왕화렴조불",
    "translation": "",
    "repeat": 1,
    "note": "열두 부처님 칭명(가지참회) / 독송은 하지 않음 / 명호(이름) — 음 그대로 봉독",
    "translationJa": "",
    "readingJa": "ほうこうおう かえんじょうぶつ",
    "sectionEn": "The Twelve Buddhas Who Remove Karmic Hindrances",
    "readingEn": "bogwangwanghwaryeomjobul",
    "translationEn": ""
  },
  {
    "order": 88,
    "section": 10,
    "sectionKo": "참제업장십이존불",
    "sectionHanja": "懺除業障十二尊佛",
    "type": "칭명",
    "hanja": "一切香華自在力王佛",
    "reading": "일체향화자재력왕불",
    "translation": "",
    "repeat": 1,
    "note": "열두 부처님 칭명(가지참회) / 독송은 하지 않음 / 명호(이름) — 음 그대로 봉독",
    "translationJa": "",
    "readingJa": "いっさいこうげ じざいりきおうぶつ",
    "sectionEn": "The Twelve Buddhas Who Remove Karmic Hindrances",
    "readingEn": "ilchehyanghwajajaeryeokwangbul",
    "translationEn": ""
  },
  {
    "order": 89,
    "section": 10,
    "sectionKo": "참제업장십이존불",
    "sectionHanja": "懺除業障十二尊佛",
    "type": "칭명",
    "hanja": "百億恒河沙決定佛",
    "reading": "백억항하사결정불",
    "translation": "",
    "repeat": 1,
    "note": "열두 부처님 칭명(가지참회) / 독송은 하지 않음 / 명호(이름) — 음 그대로 봉독",
    "translationJa": "",
    "readingJa": "ひゃくおく ごうがしゃ けつじょうぶつ",
    "sectionEn": "The Twelve Buddhas Who Remove Karmic Hindrances",
    "readingEn": "baekeokhanghasagyeoljeongbul",
    "translationEn": ""
  },
  {
    "order": 90,
    "section": 10,
    "sectionKo": "참제업장십이존불",
    "sectionHanja": "懺除業障十二尊佛",
    "type": "칭명",
    "hanja": "振威德佛",
    "reading": "진위덕불",
    "translation": "",
    "repeat": 1,
    "note": "열두 부처님 칭명(가지참회) / 독송은 하지 않음 / 명호(이름) — 음 그대로 봉독",
    "translationJa": "",
    "readingJa": "しんいとくぶつ",
    "sectionEn": "The Twelve Buddhas Who Remove Karmic Hindrances",
    "readingEn": "jinwideokbul",
    "translationEn": ""
  },
  {
    "order": 91,
    "section": 10,
    "sectionKo": "참제업장십이존불",
    "sectionHanja": "懺除業障十二尊佛",
    "type": "칭명",
    "hanja": "金剛堅强消伏壞散佛",
    "reading": "금강견강소복괴산불",
    "translation": "",
    "repeat": 1,
    "note": "열두 부처님 칭명(가지참회) / 독송은 하지 않음 / 명호(이름) — 음 그대로 봉독",
    "translationJa": "",
    "readingJa": "こんごう けんごう しょうぶく えさんぶつ",
    "sectionEn": "The Twelve Buddhas Who Remove Karmic Hindrances",
    "readingEn": "geumganggyeongangsobokgoesanbul",
    "translationEn": ""
  },
  {
    "order": 92,
    "section": 10,
    "sectionKo": "참제업장십이존불",
    "sectionHanja": "懺除業障十二尊佛",
    "type": "칭명",
    "hanja": "寶光月殿妙音尊王佛",
    "reading": "보광월전묘음존왕불",
    "translation": "",
    "repeat": 1,
    "note": "열두 부처님 칭명(가지참회) / 독송은 하지 않음 / 명호(이름) — 음 그대로 봉독",
    "translationJa": "",
    "readingJa": "ほうこうがってん みょうおんそんのうぶつ",
    "sectionEn": "The Twelve Buddhas Who Remove Karmic Hindrances",
    "readingEn": "bogwangwoljeonmyoeumjonwangbul",
    "translationEn": ""
  },
  {
    "order": 93,
    "section": 10,
    "sectionKo": "참제업장십이존불",
    "sectionHanja": "懺除業障十二尊佛",
    "type": "칭명",
    "hanja": "歡喜藏摩尼寶積佛",
    "reading": "환희장마니보적불",
    "translation": "",
    "repeat": 1,
    "note": "열두 부처님 칭명(가지참회) / 독송은 하지 않음 / 명호(이름) — 음 그대로 봉독",
    "translationJa": "",
    "readingJa": "かんぎぞう まにほうしゃくぶつ",
    "sectionEn": "The Twelve Buddhas Who Remove Karmic Hindrances",
    "readingEn": "hwanhuijangmanibojeokbul",
    "translationEn": ""
  },
  {
    "order": 94,
    "section": 10,
    "sectionKo": "참제업장십이존불",
    "sectionHanja": "懺除業障十二尊佛",
    "type": "칭명",
    "hanja": "無盡香勝王佛",
    "reading": "무진향승왕불",
    "translation": "",
    "repeat": 1,
    "note": "열두 부처님 칭명(가지참회) / 독송은 하지 않음 / 명호(이름) — 음 그대로 봉독",
    "translationJa": "",
    "readingJa": "むじんこう しょうおうぶつ",
    "sectionEn": "The Twelve Buddhas Who Remove Karmic Hindrances",
    "readingEn": "mujinhyangseungwangbul",
    "translationEn": ""
  },
  {
    "order": 95,
    "section": 10,
    "sectionKo": "참제업장십이존불",
    "sectionHanja": "懺除業障十二尊佛",
    "type": "칭명",
    "hanja": "獅子月佛",
    "reading": "사자월불",
    "translation": "",
    "repeat": 1,
    "note": "열두 부처님 칭명(가지참회) / 독송은 하지 않음 / 명호(이름) — 음 그대로 봉독",
    "translationJa": "",
    "readingJa": "ししがつぶつ",
    "sectionEn": "The Twelve Buddhas Who Remove Karmic Hindrances",
    "readingEn": "sajawolbul",
    "translationEn": ""
  },
  {
    "order": 96,
    "section": 10,
    "sectionKo": "참제업장십이존불",
    "sectionHanja": "懺除業障十二尊佛",
    "type": "칭명",
    "hanja": "歡喜莊嚴珠王佛",
    "reading": "환희장엄주왕불",
    "translation": "",
    "repeat": 1,
    "note": "열두 부처님 칭명(가지참회) / 독송은 하지 않음 / 명호(이름) — 음 그대로 봉독",
    "translationJa": "",
    "readingJa": "かんぎ しょうごん じゅおうぶつ",
    "sectionEn": "The Twelve Buddhas Who Remove Karmic Hindrances",
    "readingEn": "hwanhuijangeomjuwangbul",
    "translationEn": ""
  },
  {
    "order": 97,
    "section": 10,
    "sectionKo": "참제업장십이존불",
    "sectionHanja": "懺除業障十二尊佛",
    "type": "칭명",
    "hanja": "帝寶幢摩尼勝光佛",
    "reading": "제보당마니승광불",
    "translation": "",
    "repeat": 1,
    "note": "열두 부처님 칭명(가지참회) / 독송은 하지 않음 / 명호(이름) — 음 그대로 봉독",
    "translationJa": "",
    "readingJa": "ていほうどう まにしょうこうぶつ",
    "sectionEn": "The Twelve Buddhas Who Remove Karmic Hindrances",
    "readingEn": "jebodangmaniseunggwangbul",
    "translationEn": ""
  },
  {
    "order": 98,
    "section": 11,
    "sectionKo": "십악참회",
    "sectionHanja": "十惡懺悔",
    "type": "게송",
    "hanja": "殺生重罪今日懺悔",
    "reading": "살생중죄금일참회",
    "translation": "산 목숨을 해친 무거운 죄를 오늘 참회합니다",
    "repeat": 1,
    "note": "열 가지 악업을 참회함 / 독송은 하지 않음",
    "translationJa": "生き物を殺した重い罪を、今日懺悔します",
    "readingJa": "せっしょう じゅうざい こんにちさんげ",
    "sectionEn": "Repentance of the Ten Evil Acts",
    "readingEn": "salsaengjungjoegeumilchamhoe",
    "translationEn": "Today I repent the grave wrong of killing living beings."
  },
  {
    "order": 99,
    "section": 11,
    "sectionKo": "십악참회",
    "sectionHanja": "十惡懺悔",
    "type": "게송",
    "hanja": "偸盜重罪今日懺悔",
    "reading": "투도중죄금일참회",
    "translation": "도둑질한 무거운 죄를 오늘 참회합니다",
    "repeat": 1,
    "note": "열 가지 악업을 참회함 / 독송은 하지 않음",
    "translationJa": "盗みをはたらいた重い罪を、今日懺悔します",
    "readingJa": "ちゅうとう じゅうざい こんにちさんげ",
    "sectionEn": "Repentance of the Ten Evil Acts",
    "readingEn": "tudojungjoegeumilchamhoe",
    "translationEn": "Today I repent the grave wrong of stealing."
  },
  {
    "order": 100,
    "section": 11,
    "sectionKo": "십악참회",
    "sectionHanja": "十惡懺悔",
    "type": "게송",
    "hanja": "邪婬重罪今日懺悔",
    "reading": "사음중죄금일참회",
    "translation": "삿된 음행의 무거운 죄를 오늘 참회합니다",
    "repeat": 1,
    "note": "열 가지 악업을 참회함 / 독송은 하지 않음",
    "translationJa": "邪淫(じゃいん)の重い罪を、今日懺悔します",
    "readingJa": "じゃいん じゅうざい こんにちさんげ",
    "sectionEn": "Repentance of the Ten Evil Acts",
    "readingEn": "saeumjungjoegeumilchamhoe",
    "translationEn": "Today I repent the grave wrong of sexual misconduct."
  },
  {
    "order": 101,
    "section": 11,
    "sectionKo": "십악참회",
    "sectionHanja": "十惡懺悔",
    "type": "게송",
    "hanja": "妄語重罪今日懺悔",
    "reading": "망어중죄금일참회",
    "translation": "거짓말한 무거운 죄를 오늘 참회합니다",
    "repeat": 1,
    "note": "열 가지 악업을 참회함 / 독송은 하지 않음",
    "translationJa": "嘘をついた重い罪を、今日懺悔します",
    "readingJa": "もうご じゅうざい こんにちさんげ",
    "sectionEn": "Repentance of the Ten Evil Acts",
    "readingEn": "mangeojungjoegeumilchamhoe",
    "translationEn": "Today I repent the grave wrong of false speech."
  },
  {
    "order": 102,
    "section": 11,
    "sectionKo": "십악참회",
    "sectionHanja": "十惡懺悔",
    "type": "게송",
    "hanja": "綺語重罪今日懺悔",
    "reading": "기어중죄금일참회",
    "translation": "꾸며서 말한 무거운 죄를 오늘 참회합니다",
    "repeat": 1,
    "note": "열 가지 악업을 참회함 / 독송은 하지 않음",
    "translationJa": "飾り立てて語った重い罪を、今日懺悔します",
    "readingJa": "きご じゅうざい こんにちさんげ",
    "sectionEn": "Repentance of the Ten Evil Acts",
    "readingEn": "gieojungjoegeumilchamhoe",
    "translationEn": "Today I repent the grave wrong of frivolous speech."
  },
  {
    "order": 103,
    "section": 11,
    "sectionKo": "십악참회",
    "sectionHanja": "十惡懺悔",
    "type": "게송",
    "hanja": "兩舌重罪今日懺悔",
    "reading": "양설중죄금일참회",
    "translation": "이간질한 무거운 죄를 오늘 참회합니다",
    "repeat": 1,
    "note": "열 가지 악업을 참회함 / 독송은 하지 않음",
    "translationJa": "仲を裂く言葉の重い罪を、今日懺悔します",
    "readingJa": "りょうぜつ じゅうざい こんにちさんげ",
    "sectionEn": "Repentance of the Ten Evil Acts",
    "readingEn": "yangseoljungjoegeumilchamhoe",
    "translationEn": "Today I repent the grave wrong of divisive speech."
  },
  {
    "order": 104,
    "section": 11,
    "sectionKo": "십악참회",
    "sectionHanja": "十惡懺悔",
    "type": "게송",
    "hanja": "惡口重罪今日懺悔",
    "reading": "악구중죄금일참회",
    "translation": "험한 말을 한 무거운 죄를 오늘 참회합니다",
    "repeat": 1,
    "note": "열 가지 악업을 참회함 / 독송은 하지 않음",
    "translationJa": "荒々しい言葉を吐いた重い罪を、今日懺悔します",
    "readingJa": "あっく じゅうざい こんにちさんげ",
    "sectionEn": "Repentance of the Ten Evil Acts",
    "readingEn": "akgujungjoegeumilchamhoe",
    "translationEn": "Today I repent the grave wrong of harsh speech."
  },
  {
    "order": 105,
    "section": 11,
    "sectionKo": "십악참회",
    "sectionHanja": "十惡懺悔",
    "type": "게송",
    "hanja": "貪愛重罪今日懺悔",
    "reading": "탐애중죄금일참회",
    "translation": "탐내고 집착한 무거운 죄를 오늘 참회합니다",
    "repeat": 1,
    "note": "열 가지 악업을 참회함 / 독송은 하지 않음",
    "translationJa": "貪り執着した重い罪を、今日懺悔します",
    "readingJa": "とんあい じゅうざい こんにちさんげ",
    "sectionEn": "Repentance of the Ten Evil Acts",
    "readingEn": "tamaejungjoegeumilchamhoe",
    "translationEn": "Today I repent the grave wrong of greed and attachment."
  },
  {
    "order": 106,
    "section": 11,
    "sectionKo": "십악참회",
    "sectionHanja": "十惡懺悔",
    "type": "게송",
    "hanja": "瞋恚重罪今日懺悔",
    "reading": "진애중죄금일참회",
    "translation": "성내고 미워한 무거운 죄를 오늘 참회합니다",
    "repeat": 1,
    "note": "열 가지 악업을 참회함 / 독송은 하지 않음",
    "translationJa": "瞋り憎んだ重い罪を、今日懺悔します",
    "readingJa": "しんに じゅうざい こんにちさんげ",
    "sectionEn": "Repentance of the Ten Evil Acts",
    "readingEn": "jinaejungjoegeumilchamhoe",
    "translationEn": "Today I repent the grave wrong of anger and hatred."
  },
  {
    "order": 107,
    "section": 11,
    "sectionKo": "십악참회",
    "sectionHanja": "十惡懺悔",
    "type": "게송",
    "hanja": "癡暗重罪今日懺悔",
    "reading": "치암중죄금일참회",
    "translation": "어리석고 어두운 무거운 죄를 오늘 참회합니다",
    "repeat": 1,
    "note": "열 가지 악업을 참회함 / 독송은 하지 않음",
    "translationJa": "愚かで暗い重い罪を、今日懺悔します",
    "readingJa": "ちあん じゅうざい こんにちさんげ",
    "sectionEn": "Repentance of the Ten Evil Acts",
    "readingEn": "chiamjungjoegeumilchamhoe",
    "translationEn": "Today I repent the grave wrong of ignorance and delusion."
  },
  {
    "order": 108,
    "section": 11,
    "sectionKo": "십악참회",
    "sectionHanja": "十惡懺悔",
    "type": "게송",
    "hanja": "百劫積集罪 一念頓蕩盡",
    "reading": "백겁적집죄 일념돈탕진",
    "translation": "오랜 세월 쌓인 죄가 한 생각에 모두 씻기니",
    "repeat": 1,
    "note": "열 가지 악업을 참회함 / 독송은 하지 않음",
    "translationJa": "長い歳月に積もった罪が一念ですべて洗われ",
    "readingJa": "ひゃくごう しゃくじゅうざい いちねん とんとうじん",
    "sectionEn": "Repentance of the Ten Evil Acts",
    "readingEn": "baekgeopjeokjipjoe ilnyeomdontangjin",
    "translationEn": "Wrongs piled up over countless ages are washed away in a single thought,"
  },
  {
    "order": 109,
    "section": 11,
    "sectionKo": "십악참회",
    "sectionHanja": "十惡懺悔",
    "type": "게송",
    "hanja": "如火焚枯草 滅盡無有餘",
    "reading": "여화분고초 멸진무유여",
    "translation": "불이 마른 풀을 태우듯 남김없이 사라지네",
    "repeat": 1,
    "note": "열 가지 악업을 참회함 / 독송은 하지 않음",
    "translationJa": "火が枯れ草を焼くように残らず消え去る",
    "readingJa": "にょか ぼんこそう めつじん むうよ",
    "sectionEn": "Repentance of the Ten Evil Acts",
    "readingEn": "yeohwabungocho myeoljinmuyuyeo",
    "translationEn": "vanishing without remainder, as fire consumes dry grass."
  },
  {
    "order": 110,
    "section": 11,
    "sectionKo": "십악참회",
    "sectionHanja": "十惡懺悔",
    "type": "게송",
    "hanja": "罪無自性從心起",
    "reading": "죄무자성종심기",
    "translation": "죄는 본래 제 성품이 없어 마음을 따라 일어나니",
    "repeat": 1,
    "note": "열 가지 악업을 참회함 / 독송은 하지 않음",
    "translationJa": "罪は本来それ自体の性がなく、心に従って起こるもので",
    "readingJa": "ざいむ じしょう じゅうしんき",
    "sectionEn": "Repentance of the Ten Evil Acts",
    "readingEn": "joemujaseongjongsimgi",
    "translationEn": "Wrong has no nature of its own; it arises following the mind."
  },
  {
    "order": 111,
    "section": 11,
    "sectionKo": "십악참회",
    "sectionHanja": "十惡懺悔",
    "type": "게송",
    "hanja": "心若滅時罪亦亡",
    "reading": "심약멸시죄역망",
    "translation": "마음이 사라질 때 죄도 함께 없어지네",
    "repeat": 1,
    "note": "열 가지 악업을 참회함 / 독송은 하지 않음",
    "translationJa": "心が滅するとき、罪も共に消える",
    "readingJa": "しんにゃく めつじ ざいやくぼう",
    "sectionEn": "Repentance of the Ten Evil Acts",
    "readingEn": "simyakmyeolsijoeyeokmang",
    "translationEn": "When the mind is extinguished, wrong is extinguished too."
  },
  {
    "order": 112,
    "section": 11,
    "sectionKo": "십악참회",
    "sectionHanja": "十惡懺悔",
    "type": "게송",
    "hanja": "罪亡心滅兩俱空",
    "reading": "죄망심멸양구공",
    "translation": "죄가 없어지고 마음도 사라져 둘 다 비면",
    "repeat": 1,
    "note": "열 가지 악업을 참회함 / 독송은 하지 않음",
    "translationJa": "罪が消え、心も滅して、ともに空(くう)となれば",
    "readingJa": "ざいぼう しんめつ りょうくくう",
    "sectionEn": "Repentance of the Ten Evil Acts",
    "readingEn": "joemangsimmyeolyanggugong",
    "translationEn": "When both wrong and mind are gone and both are empty —"
  },
  {
    "order": 113,
    "section": 11,
    "sectionKo": "십악참회",
    "sectionHanja": "十惡懺悔",
    "type": "게송",
    "hanja": "是卽名爲眞懺悔",
    "reading": "시즉명위진참회",
    "translation": "이것을 바로 참된 참회라 하네",
    "repeat": 1,
    "note": "열 가지 악업을 참회함 / 독송은 하지 않음",
    "translationJa": "これをこそ真の懺悔という",
    "readingJa": "ぜそく みょうい しんさんげ",
    "sectionEn": "Repentance of the Ten Evil Acts",
    "readingEn": "sijeukmyeongwijinchamhoe",
    "translationEn": "this is called true repentance."
  },
  {
    "order": 114,
    "section": 12,
    "sectionKo": "참회진언",
    "sectionHanja": "懺悔眞言",
    "type": "진언",
    "hanja": "",
    "reading": "옴 살바 못자모지 사다야 사바하",
    "translation": "",
    "repeat": 3,
    "note": "죄업을 뉘우치는 진언 / 음역 진언 — 번역하지 않고 음 그대로 봉독",
    "translationJa": "",
    "readingJa": "おん さらば ぼっしゃもじ さだや そわか",
    "sectionEn": "Mantra of Repentance",
    "readingEn": "om salba motjamoji sadaya sabaha",
    "translationEn": ""
  },
  {
    "order": 115,
    "section": 13,
    "sectionKo": "준제찬",
    "sectionHanja": "准提讚",
    "type": "게송",
    "hanja": "准提功德聚",
    "reading": "준제공덕취",
    "translation": "준제주는 모든 공덕이 모인 것이니",
    "repeat": 1,
    "note": "준제주의 찬 / 독송은 하지 않음",
    "translationJa": "准提呪はあらゆる功徳が集まったものであり",
    "readingJa": "じゅんでい くどくじゅ",
    "sectionEn": "Praise of Cundi",
    "readingEn": "junjegongdeokchwi",
    "translationEn": "The Cundi mantra is a gathering of all merit;"
  },
  {
    "order": 116,
    "section": 13,
    "sectionKo": "준제찬",
    "sectionHanja": "准提讚",
    "type": "게송",
    "hanja": "寂靜心常誦",
    "reading": "적정심상송",
    "translation": "고요한 마음으로 늘 외우면",
    "repeat": 1,
    "note": "준제주의 찬 / 독송은 하지 않음",
    "translationJa": "静かな心で常に唱えれば",
    "readingJa": "じゃくじょう しんじょうじゅ",
    "sectionEn": "Praise of Cundi",
    "readingEn": "jeokjeongsimsangsong",
    "translationEn": "recite it always with a still mind,"
  },
  {
    "order": 117,
    "section": 13,
    "sectionKo": "준제찬",
    "sectionHanja": "准提讚",
    "type": "게송",
    "hanja": "一切諸大難 無能侵是人",
    "reading": "일체제대난 무능침시인",
    "translation": "온갖 큰 재난도 이 사람을 침범하지 못하리",
    "repeat": 1,
    "note": "준제주의 찬 / 독송은 하지 않음",
    "translationJa": "いかなる大きな災難もこの人を侵すことはできない",
    "readingJa": "いっさい しょだいなん むのう しんぜにん",
    "sectionEn": "Praise of Cundi",
    "readingEn": "ilchejedaenan muneungchimsiin",
    "translationEn": "and no great disaster can befall such a person."
  },
  {
    "order": 118,
    "section": 13,
    "sectionKo": "준제찬",
    "sectionHanja": "准提讚",
    "type": "게송",
    "hanja": "天上及人間",
    "reading": "천상급인간",
    "translation": "하늘에서나 사람 사이에서나",
    "repeat": 1,
    "note": "준제주의 찬 / 독송은 하지 않음",
    "translationJa": "天においても人の世においても",
    "readingJa": "てんじょう ぎゅう にんげん",
    "sectionEn": "Praise of Cundi",
    "readingEn": "cheonsanggeupingan",
    "translationEn": "Whether among the heavens or among humankind,"
  },
  {
    "order": 119,
    "section": 13,
    "sectionKo": "준제찬",
    "sectionHanja": "准提讚",
    "type": "게송",
    "hanja": "受福如佛等",
    "reading": "수복여불등",
    "translation": "부처와 다름없는 복을 받으며",
    "repeat": 1,
    "note": "준제주의 찬 / 독송은 하지 않음",
    "translationJa": "仏と変わらぬ福を受け",
    "readingJa": "じゅふく にょぶつとう",
    "sectionEn": "Praise of Cundi",
    "readingEn": "subokyeobuldeung",
    "translationEn": "one receives blessings no different from a Buddha's,"
  },
  {
    "order": 120,
    "section": 13,
    "sectionKo": "준제찬",
    "sectionHanja": "准提讚",
    "type": "게송",
    "hanja": "遇此如意珠",
    "reading": "우차여의주",
    "translation": "이 여의주와 같은 다라니를 만난 이는",
    "repeat": 1,
    "note": "준제주의 찬 / 독송은 하지 않음",
    "translationJa": "この如意珠のような陀羅尼に出会った者は",
    "readingJa": "ぐうし にょいしゅ",
    "sectionEn": "Praise of Cundi",
    "readingEn": "uchayeouiju",
    "translationEn": "and whoever meets this wish-fulfilling Dharani"
  },
  {
    "order": 121,
    "section": 13,
    "sectionKo": "준제찬",
    "sectionHanja": "准提讚",
    "type": "게송",
    "hanja": "定獲無等等",
    "reading": "정획무등등",
    "translation": "반드시 그 무엇과도 견줄 수 없는 깨달음을 얻으리라",
    "repeat": 1,
    "note": "준제주의 찬 / 독송은 하지 않음",
    "translationJa": "必ず何ものにも比べられない悟りを得るであろう",
    "readingJa": "じょうぎゃく むとうとう",
    "sectionEn": "Praise of Cundi",
    "readingEn": "jeonghoekmudeungdeung",
    "translationEn": "will surely attain the unequaled awakening."
  },
  {
    "order": 122,
    "section": 13,
    "sectionKo": "준제찬",
    "sectionHanja": "准提讚",
    "type": "칭명",
    "hanja": "南無 七俱胝佛母大准提菩薩",
    "reading": "나무 칠구지불모대준제보살",
    "translation": "",
    "repeat": 3,
    "note": "명호(이름) — 음 그대로 봉독",
    "translationJa": "",
    "readingJa": "なむ しちくてい ぶつも だいじゅんでい ぼさつ",
    "sectionEn": "Praise of Cundi",
    "readingEn": "namu chilgujibulmodaejunjebosal",
    "translationEn": ""
  },
  {
    "order": 123,
    "section": 14,
    "sectionKo": "정법계진언",
    "sectionHanja": "淨法界眞言",
    "type": "진언",
    "hanja": "",
    "reading": "옴 람",
    "translation": "",
    "repeat": 3,
    "note": "법계를 맑게 하는 진언 / 음역 진언 — 번역하지 않고 음 그대로 봉독",
    "translationJa": "",
    "readingJa": "おん らん",
    "sectionEn": "Mantra for Purifying the Dharma Realm",
    "readingEn": "om ram",
    "translationEn": ""
  },
  {
    "order": 124,
    "section": 15,
    "sectionKo": "호신진언",
    "sectionHanja": "護身眞言",
    "type": "진언",
    "hanja": "",
    "reading": "옴 치림",
    "translation": "",
    "repeat": 3,
    "note": "몸을 보호하는 진언 / 음역 진언 — 번역하지 않고 음 그대로 봉독",
    "translationJa": "",
    "readingJa": "おん ちりん",
    "sectionEn": "Mantra for Protecting the Body",
    "readingEn": "om chirim",
    "translationEn": ""
  },
  {
    "order": 125,
    "section": 16,
    "sectionKo": "관세음보살본심미묘육자대명왕진언",
    "sectionHanja": "觀世音菩薩本心微妙六字大明王眞言",
    "type": "진언",
    "hanja": "",
    "reading": "옴 마니 반메 훔",
    "translation": "",
    "repeat": 3,
    "note": "관세음보살님의 본마음을 보여주는 육자대명왕진언 / 음역 진언 — 번역하지 않고 음 그대로 봉독",
    "translationJa": "",
    "readingJa": "おん まに はんどめい うん",
    "sectionEn": "Six-Syllable Mantra of Avalokiteshvara",
    "readingEn": "om mani banme hum",
    "translationEn": ""
  },
  {
    "order": 126,
    "section": 17,
    "sectionKo": "준제진언",
    "sectionHanja": "准提眞言",
    "type": "진언",
    "hanja": "",
    "reading": "나무 사다남 삼먁삼못다 구치남 다냐타 옴 자례주례 준제 사바하 부림",
    "translation": "",
    "repeat": 3,
    "note": "음역 진언 — 번역하지 않고 음 그대로 봉독",
    "translationJa": "",
    "readingJa": "なむ さーたーなん さんみゃくさんぼだ くちなん たにやた おん しゃれいしゅれい じゅんでい そわか ぶりん",
    "sectionEn": "Cundi Mantra",
    "readingEn": "namu sadanam sammyaksammotda guchinam danyata om jaryejurye junje sabaha burim",
    "translationEn": ""
  },
  {
    "order": 127,
    "section": 18,
    "sectionKo": "준제발원",
    "sectionHanja": "准提發願",
    "type": "발원",
    "hanja": "我今持誦大准提",
    "reading": "아금지송대준제",
    "translation": "제가 이제 대준제 다라니를 외우오니",
    "repeat": 1,
    "note": "준제보살의 발원 / 독송은 하지 않음",
    "translationJa": "私は今、大准提の陀羅尼を唱えますので",
    "readingJa": "がこん じじゅ だいじゅんでい",
    "sectionEn": "Cundi Aspiration",
    "readingEn": "ageumjisongdaejunje",
    "translationEn": "Now I recite the Great Cundi Dharani,"
  },
  {
    "order": 128,
    "section": 18,
    "sectionKo": "준제발원",
    "sectionHanja": "准提發願",
    "type": "발원",
    "hanja": "卽發菩提廣大願",
    "reading": "즉발보리광대원",
    "translation": "곧 깨달음을 향한 크고 넓은 원을 세우고",
    "repeat": 1,
    "note": "준제보살의 발원 / 독송은 하지 않음",
    "translationJa": "ただちに悟りへの大きく広い願を立て",
    "readingJa": "そくほつ ぼだい こうだいがん",
    "sectionEn": "Cundi Aspiration",
    "readingEn": "jeukbalborigwangdaewon",
    "translationEn": "and at once set forth the vast vow for awakening (bodhi)."
  },
  {
    "order": 129,
    "section": 18,
    "sectionKo": "준제발원",
    "sectionHanja": "准提發願",
    "type": "발원",
    "hanja": "願我定慧速圓明",
    "reading": "원아정혜속원명",
    "translation": "저의 선정과 지혜가 어서 두루 밝아지며",
    "repeat": 1,
    "note": "준제보살의 발원 / 독송은 하지 않음",
    "translationJa": "私の禅定と智慧が速やかにあまねく明らかになり",
    "readingJa": "がんが じょうえ そくえんみょう",
    "sectionEn": "Cundi Aspiration",
    "readingEn": "wonajeonghyesokwonmyeong",
    "translationEn": "May my meditation and wisdom swiftly grow bright,"
  },
  {
    "order": 130,
    "section": 18,
    "sectionKo": "준제발원",
    "sectionHanja": "准提發願",
    "type": "발원",
    "hanja": "願我功德皆成就",
    "reading": "원아공덕개성취",
    "translation": "저의 모든 공덕이 다 이루어지고",
    "repeat": 1,
    "note": "준제보살의 발원 / 독송은 하지 않음",
    "translationJa": "私のすべての功徳がことごとく成就し",
    "readingJa": "がんが くどく かいじょうじゅ",
    "sectionEn": "Cundi Aspiration",
    "readingEn": "wonagongdeokgaeseongchwi",
    "translationEn": "may all my merit be fulfilled,"
  },
  {
    "order": 131,
    "section": 18,
    "sectionKo": "준제발원",
    "sectionHanja": "准提發願",
    "type": "발원",
    "hanja": "願我勝福遍莊嚴",
    "reading": "원아승복변장엄",
    "translation": "저의 뛰어난 복덕이 두루 장엄해지며",
    "repeat": 1,
    "note": "준제보살의 발원 / 독송은 하지 않음",
    "translationJa": "私の優れた福徳があまねく荘厳となり",
    "readingJa": "がんが しょうふく へんしょうごん",
    "sectionEn": "Cundi Aspiration",
    "readingEn": "wonaseungbokbyeonjangeom",
    "translationEn": "may my excellent blessings be wholly adorned,"
  },
  {
    "order": 132,
    "section": 18,
    "sectionKo": "준제발원",
    "sectionHanja": "准提發願",
    "type": "발원",
    "hanja": "願共衆生成佛道",
    "reading": "원공중생성불도",
    "translation": "모든 중생과 함께 불도를 이루기를 발원합니다",
    "repeat": 1,
    "note": "준제보살의 발원 / 독송은 하지 않음",
    "translationJa": "すべての衆生と共に仏道を成すことを願います",
    "readingJa": "がんぐ しゅじょう じょうぶつどう",
    "sectionEn": "Cundi Aspiration",
    "readingEn": "wongongjungsaengseongbuldo",
    "translationEn": "and may I, with all beings, realize the Buddha Way."
  },
  {
    "order": 133,
    "section": 19,
    "sectionKo": "여래십대발원문",
    "sectionHanja": "如來十大發願文",
    "type": "발원",
    "hanja": "願我永離三惡道",
    "reading": "원아영리삼악도",
    "translation": "제가 지옥·아귀·축생의 삼악도를 길이 떠나기를 원하며",
    "repeat": 1,
    "note": "부처님께 발하는 열 가지 원",
    "translationJa": "私が地獄・餓鬼・畜生の三悪道を永く離れることを願い",
    "readingJa": "がんが ようり さんなくどう",
    "sectionEn": "The Ten Great Vows of the Tathagata",
    "readingEn": "wonayeongrisamakdo",
    "translationEn": "I vow to depart forever from the three evil paths of hell, hungry ghosts, and animals;"
  },
  {
    "order": 134,
    "section": 19,
    "sectionKo": "여래십대발원문",
    "sectionHanja": "如來十大發願文",
    "type": "발원",
    "hanja": "願我速斷貪瞋癡",
    "reading": "원아속단탐진치",
    "translation": "제가 탐냄·성냄·어리석음을 어서 끊기를 원하며",
    "repeat": 1,
    "note": "부처님께 발하는 열 가지 원",
    "translationJa": "私が貪り・瞋り・愚かさを速やかに断つことを願い",
    "readingJa": "がんが そくだん とんじんち",
    "sectionEn": "The Ten Great Vows of the Tathagata",
    "readingEn": "wonasokdantamjinchi",
    "translationEn": "I vow to swiftly cut off greed, hatred, and delusion;"
  },
  {
    "order": 135,
    "section": 19,
    "sectionKo": "여래십대발원문",
    "sectionHanja": "如來十大發願文",
    "type": "발원",
    "hanja": "願我常聞佛法僧",
    "reading": "원아상문불법승",
    "translation": "제가 부처와 가르침과 승가를 늘 듣기를 원하며",
    "repeat": 1,
    "note": "부처님께 발하는 열 가지 원",
    "translationJa": "私が仏と法と僧を常に聞くことを願い",
    "readingJa": "がんが じょうもん ぶっぽうそう",
    "sectionEn": "The Ten Great Vows of the Tathagata",
    "readingEn": "wonasangmunbulbeopseung",
    "translationEn": "I vow to always hear of the Buddha, Dharma, and Sangha;"
  },
  {
    "order": 136,
    "section": 19,
    "sectionKo": "여래십대발원문",
    "sectionHanja": "如來十大發願文",
    "type": "발원",
    "hanja": "願我勤修戒定慧",
    "reading": "원아근수계정혜",
    "translation": "제가 계·정·혜를 부지런히 닦기를 원하며",
    "repeat": 1,
    "note": "부처님께 발하는 열 가지 원",
    "translationJa": "私が戒・定・慧を励んで修めることを願い",
    "readingJa": "がんが ごんしゅ かいじょうえ",
    "sectionEn": "The Ten Great Vows of the Tathagata",
    "readingEn": "wonageunsugyejeonghye",
    "translationEn": "I vow to diligently cultivate precepts, meditation, and wisdom;"
  },
  {
    "order": 137,
    "section": 19,
    "sectionKo": "여래십대발원문",
    "sectionHanja": "如來十大發願文",
    "type": "발원",
    "hanja": "願我恒隨諸佛學",
    "reading": "원아항수제불학",
    "translation": "제가 모든 부처님을 따라 늘 배우기를 원하며",
    "repeat": 1,
    "note": "부처님께 발하는 열 가지 원",
    "translationJa": "私がすべての仏に従って常に学ぶことを願い",
    "readingJa": "がんが ごうずい しょぶつがく",
    "sectionEn": "The Ten Great Vows of the Tathagata",
    "readingEn": "wonahangsujebulhak",
    "translationEn": "I vow to always learn by following all Buddhas;"
  },
  {
    "order": 138,
    "section": 19,
    "sectionKo": "여래십대발원문",
    "sectionHanja": "如來十大發願文",
    "type": "발원",
    "hanja": "願我不退菩提心",
    "reading": "원아불퇴보리심",
    "translation": "제가 깨달음을 향한 마음에서 물러나지 않기를 원하며",
    "repeat": 1,
    "note": "부처님께 발하는 열 가지 원",
    "translationJa": "私が悟りを求める心から退かないことを願い",
    "readingJa": "がんが ふたい ぼだいしん",
    "sectionEn": "The Ten Great Vows of the Tathagata",
    "readingEn": "wonabultoeborisim",
    "translationEn": "I vow never to retreat from the mind set on awakening;"
  },
  {
    "order": 139,
    "section": 19,
    "sectionKo": "여래십대발원문",
    "sectionHanja": "如來十大發願文",
    "type": "발원",
    "hanja": "願我決定生安養",
    "reading": "원아결정생안양",
    "translation": "제가 반드시 극락에 태어나기를 원하며",
    "repeat": 1,
    "note": "부처님께 발하는 열 가지 원",
    "translationJa": "私が必ず極楽に生まれることを願い",
    "readingJa": "がんが けつじょう しょうあんにょう",
    "sectionEn": "The Ten Great Vows of the Tathagata",
    "readingEn": "wonagyeoljeongsaenganyang",
    "translationEn": "I vow to be reborn without fail in the Land of Bliss;"
  },
  {
    "order": 140,
    "section": 19,
    "sectionKo": "여래십대발원문",
    "sectionHanja": "如來十大發願文",
    "type": "발원",
    "hanja": "願我速見阿彌陀",
    "reading": "원아속견아미타",
    "translation": "제가 아미타 부처님을 어서 뵙기를 원하며",
    "repeat": 1,
    "note": "부처님께 발하는 열 가지 원",
    "translationJa": "私が阿弥陀仏に速やかにまみえることを願い",
    "readingJa": "がんが そっけん あみだ",
    "sectionEn": "The Ten Great Vows of the Tathagata",
    "readingEn": "wonasokgyeonamita",
    "translationEn": "I vow to swiftly behold Amitabha Buddha;"
  },
  {
    "order": 141,
    "section": 19,
    "sectionKo": "여래십대발원문",
    "sectionHanja": "如來十大發願文",
    "type": "발원",
    "hanja": "願我分身遍塵刹",
    "reading": "원아분신변진찰",
    "translation": "제가 몸을 나누어 온 세계에 두루 하기를 원하며",
    "repeat": 1,
    "note": "부처님께 발하는 열 가지 원",
    "translationJa": "私が身を分けてあらゆる世界にあまねく及ぶことを願い",
    "readingJa": "がんが ぶんしん へんじんせつ",
    "sectionEn": "The Ten Great Vows of the Tathagata",
    "readingEn": "wonabunsinbyeonjinchal",
    "translationEn": "I vow to divide my body throughout every world;"
  },
  {
    "order": 142,
    "section": 19,
    "sectionKo": "여래십대발원문",
    "sectionHanja": "如來十大發願文",
    "type": "발원",
    "hanja": "願我廣度諸衆生",
    "reading": "원아광도제중생",
    "translation": "제가 모든 중생을 널리 건지기를 원합니다",
    "repeat": 1,
    "note": "부처님께 발하는 열 가지 원",
    "translationJa": "私がすべての衆生を広く救うことを願います",
    "readingJa": "がんが こうど しょしゅじょう",
    "sectionEn": "The Ten Great Vows of the Tathagata",
    "readingEn": "wonagwangdojejungsaeng",
    "translationEn": "I vow to ferry all beings across, far and wide."
  },
  {
    "order": 143,
    "section": 20,
    "sectionKo": "발사홍서원",
    "sectionHanja": "發四弘誓願",
    "type": "발원",
    "hanja": "衆生無邊誓願度",
    "reading": "중생무변서원도",
    "translation": "끝없는 중생을 모두 건지기를 서원합니다",
    "repeat": 1,
    "note": "네 가지 큰 서원",
    "translationJa": "果てしない衆生をことごとく救うことを誓います",
    "readingJa": "しゅじょう むへん せいがんど",
    "sectionEn": "The Four Great Vows",
    "readingEn": "jungsaengmubyeonseowondo",
    "translationEn": "Beings are numberless; I vow to save them all."
  },
  {
    "order": 144,
    "section": 20,
    "sectionKo": "발사홍서원",
    "sectionHanja": "發四弘誓願",
    "type": "발원",
    "hanja": "煩惱無盡誓願斷",
    "reading": "번뇌무진서원단",
    "translation": "다함없는 번뇌를 모두 끊기를 서원합니다",
    "repeat": 1,
    "note": "네 가지 큰 서원",
    "translationJa": "尽きることのない煩悩をすべて断つことを誓います",
    "readingJa": "ぼんのう むじん せいがんだん",
    "sectionEn": "The Four Great Vows",
    "readingEn": "beonnoemujinseowondan",
    "translationEn": "Afflictions are inexhaustible; I vow to end them all."
  },
  {
    "order": 145,
    "section": 20,
    "sectionKo": "발사홍서원",
    "sectionHanja": "發四弘誓願",
    "type": "발원",
    "hanja": "法門無量誓願學",
    "reading": "법문무량서원학",
    "translation": "한량없는 법문을 모두 배우기를 서원합니다",
    "repeat": 1,
    "note": "네 가지 큰 서원",
    "translationJa": "量りしれない法門をすべて学ぶことを誓います",
    "readingJa": "ほうもん むりょう せいがんがく",
    "sectionEn": "The Four Great Vows",
    "readingEn": "beopmunmuryangseowonhak",
    "translationEn": "Dharma gates are measureless; I vow to learn them all."
  },
  {
    "order": 146,
    "section": 20,
    "sectionKo": "발사홍서원",
    "sectionHanja": "發四弘誓願",
    "type": "발원",
    "hanja": "佛道無上誓願成",
    "reading": "불도무상서원성",
    "translation": "더없이 높은 불도를 이루기를 서원합니다",
    "repeat": 1,
    "note": "네 가지 큰 서원",
    "translationJa": "この上ない仏道を成すことを誓います",
    "readingJa": "ぶつどう むじょう せいがんじょう",
    "sectionEn": "The Four Great Vows",
    "readingEn": "buldomusangseowonseong",
    "translationEn": "The Buddha Way is supreme; I vow to accomplish it."
  },
  {
    "order": 147,
    "section": 20,
    "sectionKo": "발사홍서원",
    "sectionHanja": "發四弘誓願",
    "type": "발원",
    "hanja": "自性衆生誓願度",
    "reading": "자성중생서원도",
    "translation": "제 본성 속의 중생을 모두 건지기를 서원합니다",
    "repeat": 1,
    "note": "네 가지 큰 서원",
    "translationJa": "自性のうちの衆生をことごとく救うことを誓います",
    "readingJa": "じしょう しゅじょう せいがんど",
    "sectionEn": "The Four Great Vows",
    "readingEn": "jaseongjungsaengseowondo",
    "translationEn": "Beings within my own nature — I vow to save them all."
  },
  {
    "order": 148,
    "section": 20,
    "sectionKo": "발사홍서원",
    "sectionHanja": "發四弘誓願",
    "type": "발원",
    "hanja": "自性煩惱誓願斷",
    "reading": "자성번뇌서원단",
    "translation": "제 본성 속의 번뇌를 모두 끊기를 서원합니다",
    "repeat": 1,
    "note": "네 가지 큰 서원",
    "translationJa": "自性のうちの煩悩をすべて断つことを誓います",
    "readingJa": "じしょう ぼんのう せいがんだん",
    "sectionEn": "The Four Great Vows",
    "readingEn": "jaseongbeonnoeseowondan",
    "translationEn": "Afflictions within my own nature — I vow to end them all."
  },
  {
    "order": 149,
    "section": 20,
    "sectionKo": "발사홍서원",
    "sectionHanja": "發四弘誓願",
    "type": "발원",
    "hanja": "自性法門誓願學",
    "reading": "자성법문서원학",
    "translation": "제 본성 속의 법문을 모두 배우기를 서원합니다",
    "repeat": 1,
    "note": "네 가지 큰 서원",
    "translationJa": "自性のうちの法門をすべて学ぶことを誓います",
    "readingJa": "じしょう ほうもん せいがんがく",
    "sectionEn": "The Four Great Vows",
    "readingEn": "jaseongbeopmunseowonhak",
    "translationEn": "Dharma gates within my own nature — I vow to learn them all."
  },
  {
    "order": 150,
    "section": 20,
    "sectionKo": "발사홍서원",
    "sectionHanja": "發四弘誓願",
    "type": "발원",
    "hanja": "自性佛道誓願成",
    "reading": "자성불도서원성",
    "translation": "제 본성 속의 불도를 이루기를 서원합니다",
    "repeat": 1,
    "note": "네 가지 큰 서원",
    "translationJa": "自性のうちの仏道を成すことを誓います",
    "readingJa": "じしょう ぶつどう せいがんじょう",
    "sectionEn": "The Four Great Vows",
    "readingEn": "jaseongbuldoseowonseong",
    "translationEn": "The Buddha Way within my own nature — I vow to accomplish it."
  },
  {
    "order": 151,
    "section": 21,
    "sectionKo": "발원이귀명례삼보",
    "sectionHanja": "發願已歸命禮三寶",
    "type": "귀의",
    "hanja": "發願已歸命禮三寶",
    "reading": "발원이 귀명례삼보",
    "translation": "발원을 마치고 삼보께 목숨 바쳐 절합니다",
    "repeat": 1,
    "note": "발원을 마치고 삼보께 귀명함",
    "translationJa": "発願を終え、三宝に命を捧げて礼拝します",
    "readingJa": "ほつがんい きみょうらい さんぼう",
    "sectionEn": "Taking Refuge in the Three Jewels",
    "readingEn": "balwoni gwimyeongryesambo",
    "translationEn": "Having made these vows, I bow with my whole life to the Three Jewels."
  },
  {
    "order": 152,
    "section": 21,
    "sectionKo": "발원이귀명례삼보",
    "sectionHanja": "發願已歸命禮三寶",
    "type": "귀의",
    "hanja": "南無常住十方佛",
    "reading": "나무상주시방불",
    "translation": "시방에 항상 계신 부처님께 귀의합니다",
    "repeat": 3,
    "note": "삼보 귀명(3번)",
    "translationJa": "十方に常にいます仏に帰依します",
    "readingJa": "なむ じょうじゅう じっぽうぶつ",
    "sectionEn": "Taking Refuge in the Three Jewels",
    "readingEn": "namusangjusibangbul",
    "translationEn": "Homage to the Buddhas ever present throughout the ten directions."
  },
  {
    "order": 153,
    "section": 21,
    "sectionKo": "발원이귀명례삼보",
    "sectionHanja": "發願已歸命禮三寶",
    "type": "귀의",
    "hanja": "南無常住十方法",
    "reading": "나무상주시방법",
    "translation": "시방에 항상 있는 가르침에 귀의합니다",
    "repeat": 3,
    "note": "삼보 귀명(3번)",
    "translationJa": "十方に常にある法に帰依します",
    "readingJa": "なむ じょうじゅう じっぽうほう",
    "sectionEn": "Taking Refuge in the Three Jewels",
    "readingEn": "namusangjusibangbeop",
    "translationEn": "Homage to the Dharma ever present throughout the ten directions."
  },
  {
    "order": 154,
    "section": 21,
    "sectionKo": "발원이귀명례삼보",
    "sectionHanja": "發願已歸命禮三寶",
    "type": "귀의",
    "hanja": "南無常住十方僧",
    "reading": "나무상주시방승",
    "translation": "시방에 항상 계신 승가에 귀의합니다",
    "repeat": 3,
    "note": "삼보 귀명(3번)",
    "translationJa": "十方に常にいます僧伽に帰依します",
    "readingJa": "なむ じょうじゅう じっぽうそう",
    "sectionEn": "Taking Refuge in the Three Jewels",
    "readingEn": "namusangjusibangseung",
    "translationEn": "Homage to the Sangha ever present throughout the ten directions."
  }
]
