export type ToolCategory = 'pdf' | 'image' | 'video' | 'audio' | 'text' | 'developer' | 'file' | 'utility' | 'funny' | 'game' | 'qr' | 'security' | 'finance' | 'health' | 'design' | 'seo' | 'language' | 'classics' | 'random' | 'science' | 'time' | 'device' | 'world' | 'social'
export type Phase = 1 | 2 | 3

export interface ToolMeta {
  slug: string
  category: ToolCategory
  also?: ToolCategory[] // extra categories this tool is cross-listed in (home stays `category`)
  added?: string // ISO date (YYYY-MM-DD) the tool was first published
  isPro: boolean
  isNew: boolean
  phase: Phase
  tags: string[]
  acceptedFileTypes?: string[]
  maxFileSizeMB: { free: number; pro: number }
}

/**
 * Only the most-recently-added tools get a "New" badge — the latest NEW_COUNT by
 * `added` date (ties broken by registry order, where newer tools are prepended).
 * Computed lazily/memoised since TOOLS is declared below.
 */
export const NEW_COUNT = 12
let _newSlugs: Set<string> | null = null
export function isToolNew(tool: ToolMeta): boolean {
  if (!_newSlugs) {
    _newSlugs = new Set(
      TOOLS.map((t, i) => ({ t, i }))
        .sort((a, b) => (a.t.added === b.t.added ? a.i - b.i : (b.t.added || '').localeCompare(a.t.added || '')))
        .slice(0, NEW_COUNT)
        .map((x) => x.t.slug),
    )
  }
  return _newSlugs.has(tool.slug)
}

/**
 * Single source of truth for "installable app" tools — those we ship with a
 * dedicated home-screen icon + offline support. The PWA manifest route reads
 * these to serve the right icon, and the tool title reads them (isAppTool) to
 * show the "App" badge. Add a tool here ONCE and it gets both — the app-install
 * icon and the badge can never drift apart.
 *
 * DICT_APP_TOOLS get a localized label icon (/icons/<slug>-<locale>.png);
 * SINGLE_APP_TOOLS get one locale-independent icon (/icons/<slug>.png).
 */
export const DICT_APP_TOOLS = new Set([
  'korean-to-japanese', 'korean-to-english', 'japanese-to-korean', 'english-to-korean',
  'japanese-to-english', 'english-to-japanese', 'korean-antonyms', 'japanese-antonyms', 'english-antonyms',
])
export const SINGLE_APP_TOOLS = new Set([
  'elementary-japanese-words', 'elementary-english-words', 'white-noise-machine', 'cheonsugyeong',
  'zip-files', 'unzip', 'screen-capture', 'online-notepad',
])
export const APP_TOOLS = new Set([...DICT_APP_TOOLS, ...SINGLE_APP_TOOLS])
// Tools whose installable-app experience is only ready in some locales (others
// fall back to "not an app" until that locale's content is built). Tools not
// listed here are app-ready in every locale.
export const APP_LOCALES: Record<string, readonly string[]> = {
  cheonsugyeong: ['ko', 'ja'], // English recitation/meaning not built yet
}
export function isAppTool(tool: ToolMeta, lang?: string): boolean {
  if (!APP_TOOLS.has(tool.slug)) return false
  const locs = APP_LOCALES[tool.slug]
  return !locs || !lang || locs.includes(lang)
}

export const TOOLS: ToolMeta[] = [
  {slug:'screen-capture',category:'image',also:['video'],added:'2026-06-27',phase:1,isPro:false,isNew:true,tags:['화면 캡처','온라인 화면 캡처','스크린샷','screenshot','screen capture','画面キャプチャ','スクショ'],maxFileSizeMB:{free:0,pro:0} },
  {slug:'online-notepad',category:'text',also:['utility'],added:'2026-06-27',phase:1,isPro:false,isNew:true,tags:['온라인 메모장','메모장','notepad','online notepad','notes','메모','text editor','자동 저장'],maxFileSizeMB:{free:0,pro:0} },
  {slug:'batch-image-editor',category:'image',also:['file'],added:'2026-06-27',phase:1,isPro:false,isNew:true,tags:['이미지 일괄 편집기','올인원 이미지','batch image editor','all-in-one image','画像一括編集'],maxFileSizeMB:{free:0,pro:0} },
  {slug:'batch-image-resizer',category:'image',also:['file'],added:'2026-06-27',phase:1,isPro:false,isNew:true,tags:['이미지 일괄 리사이즈','일괄 크기 변경','batch image resize','bulk resize images','画像一括リサイズ'],maxFileSizeMB:{free:0,pro:0} },
  {slug:'batch-image-converter',category:'image',also:['file'],added:'2026-06-27',phase:1,isPro:false,isNew:true,tags:['이미지 일괄 변환','일괄 포맷 변환','bulk image converter','batch convert images','画像一括変換'],maxFileSizeMB:{free:0,pro:0} },
  {slug:'batch-image-compressor',category:'image',also:['file'],added:'2026-06-27',phase:1,isPro:false,isNew:true,tags:['이미지 일괄 압축','일괄 용량 줄이기','batch compress images','bulk image compressor','画像一括圧縮'],maxFileSizeMB:{free:0,pro:0} },
  {slug:'batch-image-watermark',category:'image',also:['file'],added:'2026-06-27',phase:1,isPro:false,isNew:true,tags:['이미지 일괄 워터마크','일괄 워터마크','batch watermark images','bulk watermark','画像一括透かし'],maxFileSizeMB:{free:0,pro:0} },
  {slug:'batch-image-rename',category:'image',also:['file'],added:'2026-06-27',phase:1,isPro:false,isNew:true,tags:['이미지 일괄 이름변경','일괄 파일명 변경','batch rename images','bulk rename','画像一括リネーム'],maxFileSizeMB:{free:0,pro:0} },
  {slug:'encoding-converter',category:'file',added:'2026-06-26',phase:1,isPro:false,isNew:true,tags:['인코딩 변환','euc-kr utf-8','한글 깨짐','text encoding converter','charset converter'],maxFileSizeMB:{free:50,pro:200} },
  {slug:'csv-to-excel',category:'file',added:'2026-06-26',phase:1,isPro:false,isNew:true,tags:['csv to excel','엑셀 변환','csv xlsx','excel to csv','csv 엑셀 변환'],maxFileSizeMB:{free:50,pro:200} },
  {slug:'nickname-generator',category:'social',added:'2026-06-26',phase:1,isPro:false,isNew:true,tags:['닉네임 생성기','아이디 추천','아이디 만들기','username generator','nickname generator'],maxFileSizeMB:{free:0,pro:0} },
  {slug:'social-image-sizes',category:'social',added:'2026-06-26',phase:1,isPro:false,isNew:true,tags:['sns 이미지 규격','소셜 이미지 크기','인스타 사이즈','social media image sizes','image size guide'],maxFileSizeMB:{free:0,pro:0} },
  {slug:'engagement-rate-calculator',category:'social',added:'2026-06-26',phase:1,isPro:false,isNew:true,tags:['참여율 계산기','인게이지먼트','engagement rate calculator','engagement rate','인플루언서 참여율'],maxFileSizeMB:{free:0,pro:0} },
  {slug:'periodic-table',category:'science',added:'2026-06-26',phase:1,isPro:false,isNew:true,tags:['주기율표','periodic table','원소','元素周期表','화학 원소'],maxFileSizeMB:{free:0,pro:0} },
  {slug:'molar-mass-calculator',category:'science',added:'2026-06-26',phase:1,isPro:false,isNew:true,tags:['분자량 계산기','몰질량','molar mass calculator','molecular weight','화학식 계산'],maxFileSizeMB:{free:0,pro:0} },
  {slug:'element-quiz',category:'science',added:'2026-06-26',phase:1,isPro:false,isNew:true,tags:['원소 기호 퀴즈','원소 기호 외우기','element quiz','periodic table quiz','원소 암기'],maxFileSizeMB:{free:0,pro:0} },
  {slug:'resistor-color-code',category:'science',added:'2026-06-26',phase:1,isPro:false,isNew:true,tags:['저항 색띠 계산기','저항 색상표','resistor color code','resistor calculator','저항값 계산'],maxFileSizeMB:{free:0,pro:0} },
  {slug:'blood-type-inheritance',category:'science',added:'2026-06-26',phase:1,isPro:false,isNew:true,tags:['혈액형 유전','자녀 혈액형','부모 혈액형','blood type calculator','혈액형 계산기'],maxFileSizeMB:{free:0,pro:0} },
  {slug:'scientific-notation-converter',category:'science',also:['developer'],added:'2026-06-26',phase:1,isPro:false,isNew:true,tags:['과학적 표기법','지수 표기','scientific notation','standard form','유효숫자'],maxFileSizeMB:{free:0,pro:0} },
  {slug:'ohms-law-calculator',category:'science',added:'2026-06-26',phase:1,isPro:false,isNew:true,tags:['옴의 법칙','옴의 법칙 계산기','ohms law calculator','전압 전류 저항','V=IR'],maxFileSizeMB:{free:0,pro:0} },
  {slug:'planet-weight-calculator',category:'science',added:'2026-06-26',phase:1,isPro:false,isNew:true,tags:['행성 몸무게','다른 행성 몸무게','planet weight calculator','weight on mars','달에서 몸무게'],maxFileSizeMB:{free:0,pro:0} },
  {slug:'age-on-other-planets',category:'science',added:'2026-06-26',phase:1,isPro:false,isNew:true,tags:['행성 나이','다른 행성 나이','age on other planets','age on mars','화성 나이'],maxFileSizeMB:{free:0,pro:0} },
  {slug:'moon-phase-calculator',category:'science',added:'2026-06-26',phase:1,isPro:false,isNew:true,tags:['달의 위상','오늘 달 모양','moon phase calculator','달 위상','월령'],maxFileSizeMB:{free:0,pro:0} },
  {slug:'spinner-wheel',category:'random',also:['game'],added:'2026-06-25',phase:1,isPro:false,isNew:true,tags:['spinner wheel','돌림판','룰렛','random picker','wheel of names','ルーレット'],maxFileSizeMB:{free:0,pro:0} },
  {slug:'ladder-game',category:'random',added:'2026-06-25',phase:1,isPro:false,isNew:true,tags:['사다리타기','ladder game','amidakuji','あみだくじ','random matching'],maxFileSizeMB:{free:0,pro:0} },
  {slug:'text-to-speech',category:'audio',added:'2026-06-25',phase:1,isPro:false,isNew:true,tags:['text to speech','tts','음성 변환','텍스트 음성 변환','読み上げ','voice generator'],maxFileSizeMB:{free:0,pro:0} },
  {slug:'daedarani',category:'classics',added:'2026-06-25',phase:1,isPro:false,isNew:true,tags:['신묘장구대다라니','대다라니','대비주','108독','daedarani'],maxFileSizeMB:{free:0,pro:0} },
  {slug:'gosaseongeo',category:'classics',added:'2026-06-26',phase:1,isPro:false,isNew:true,tags:['고사성어','고사성어 사전','사자성어','고사성어 뜻','한자성어'],maxFileSizeMB:{free:0,pro:0} },
  {slug:'cheonjamun',category:'classics',added:'2026-06-26',phase:1,isPro:false,isNew:true,tags:['천자문','천자문 뜻','천자문 한자','천자문 따라쓰기','thousand character classic'],maxFileSizeMB:{free:0,pro:0} },
  {slug:'sajasohak',category:'classics',added:'2026-06-26',phase:1,isPro:false,isNew:true,tags:['사자소학','사자소학 뜻','한문 교육','효행','sajasohak'],maxFileSizeMB:{free:0,pro:0} },
  {slug:'banyasimgyeong',category:'classics',added:'2026-06-25',phase:1,isPro:false,isNew:true,tags:['반야심경','반야심경 한글','반야심경 해석','반야심경 독송','한글 반야심경','heart sutra'],maxFileSizeMB:{free:0,pro:0} },
  {slug:'cheonsugyeong',category:'classics',added:'2026-06-25',phase:1,isPro:false,isNew:true,tags:['천수경','천수경 한글','천수경 해석','천수경 독송','한글 천수경','buddhist sutra'],maxFileSizeMB:{free:0,pro:0} },
  {slug:'white-noise-machine',category:'audio',also:['health'],added:'2026-06-25',phase:1,isPro:false,isNew:true,tags:['white noise machine','white noise','백색소음','rain fire ocean sounds','focus sleep sounds'],maxFileSizeMB:{free:0,pro:0} },
  {slug:'high-english-words',category:'language',added:'2026-06-26',phase:1,isPro:false,isNew:true,tags:['high school english words','고등 영어 단어','고등 필수 영단어','english vocabulary trainer','english flashcards'],maxFileSizeMB:{free:0,pro:0} },
  {slug:'middle-english-words',category:'language',added:'2026-06-26',phase:1,isPro:false,isNew:true,tags:['middle school english words','중등 영어 단어','중등 필수 영단어 900','english vocabulary trainer','english flashcards'],maxFileSizeMB:{free:0,pro:0} },
  {slug:'elementary-english-words',category:'language',added:'2026-06-25',phase:1,isPro:false,isNew:true,tags:['elementary english words','english vocabulary trainer','초등 영어 단어','교육부 영단어','english flashcards'],maxFileSizeMB:{free:0,pro:0} },
  {slug:'elementary-japanese-words',category:'language',added:'2026-06-24',phase:1,isPro:false,isNew:true,tags:['elementary japanese words','japanese flashcards','초등 일본어 단어','日本語 単語 暗記','japanese vocabulary trainer'],maxFileSizeMB:{free:0,pro:0} },
  {slug:'korean-antonyms',category:'language',added:'2026-06-24',phase:1,isPro:false,isNew:true,tags:['korean antonyms','korean opposite words','한글 반대말','한국어 반대말','韓国語 反対語'],maxFileSizeMB:{free:0,pro:0} },
  {slug:'japanese-antonyms',category:'language',added:'2026-06-24',phase:1,isPro:false,isNew:true,tags:['japanese antonyms','japanese opposite words','일본어 반대말','日本語 反対語'],maxFileSizeMB:{free:0,pro:0} },
  {slug:'english-antonyms',category:'language',added:'2026-06-24',phase:1,isPro:false,isNew:true,tags:['english antonyms','english opposite words','영어 반대말','英語 反対語'],maxFileSizeMB:{free:0,pro:0} },
  {slug:'korean-to-english',category:'language',added:'2026-06-24',phase:1,isPro:false,isNew:true,tags:['korean to english','korean english word','한글 영어','한국어 영어','韓国語 英語'],maxFileSizeMB:{free:0,pro:0} },
  {slug:'japanese-to-korean',category:'language',added:'2026-06-24',phase:1,isPro:false,isNew:true,tags:['japanese to korean','japanese korean word','일본어 한글','일본어 한국어','日本語 韓国語'],maxFileSizeMB:{free:0,pro:0} },
  {slug:'english-to-korean',category:'language',added:'2026-06-24',phase:1,isPro:false,isNew:true,tags:['english to korean','english korean word','영어 한글','영어 한국어','英語 韓国語'],maxFileSizeMB:{free:0,pro:0} },
  {slug:'japanese-to-english',category:'language',added:'2026-06-24',phase:1,isPro:false,isNew:true,tags:['japanese to english','japanese english word','일본어 영어','日本語 英語'],maxFileSizeMB:{free:0,pro:0} },
  {slug:'english-to-japanese',category:'language',added:'2026-06-24',phase:1,isPro:false,isNew:true,tags:['english to japanese','english japanese word','영어 일본어','英語 日本語'],maxFileSizeMB:{free:0,pro:0} },
  {slug:'video-trimmer',category:'video',added:'2026-06-24',phase:1,isPro:false,isNew:true,tags:['video trimmer','cut video','video cutter','trim video','영상 자르기'],maxFileSizeMB:{free:200,pro:500} },
  {slug:'audio-trimmer',category:'audio',added:'2026-06-24',phase:1,isPro:false,isNew:true,tags:['audio trimmer','cut audio','mp3 cutter','trim audio','오디오 자르기'],maxFileSizeMB:{free:100,pro:300} },
  {slug:'video-to-audio',category:'video',added:'2026-06-24',phase:1,isPro:false,isNew:true,tags:['video to audio','extract audio','video to mp3','audio extractor','오디오 추출'],maxFileSizeMB:{free:200,pro:500} },
  {slug:'korean-to-japanese',category:'language',added:'2026-06-24',phase:1,isPro:false,isNew:true,tags:['korean to japanese','korean japanese word','한글 일본어','한국어 일본어','韓国語 日本語'],maxFileSizeMB:{free:0,pro:0} },
  {slug:'add-pdf-pages',category:'pdf',added:'2026-06-24',phase:1,isPro:false,isNew:true,tags:['add pdf pages','insert pdf page','add blank page pdf','pdf page insert','PDF페이지추가'],maxFileSizeMB:{free:50,pro:200} },
  {slug:'heic-to-png',category:'image',added:'2026-06-24',phase:1,isPro:false,isNew:true,tags:['heic to png','heic converter','iphone photo png','heic png','HEICをPNG'],maxFileSizeMB:{free:30,pro:120} },
  {slug:'pdf-to-png',category:'pdf',added:'2026-06-24',phase:1,isPro:false,isNew:true,tags:['pdf to png','pdf to image','convert pdf','pdf png','PDFをPNG'],maxFileSizeMB:{free:50,pro:200} },
  {slug:'idiom-quiz',category:'game',added:'2026-06-26',phase:1,isPro:false,isNew:true,tags:['사자성어 퀴즈','고사성어 퀴즈','idiom quiz','사자성어 게임','뜻 맞히기'],maxFileSizeMB:{free:0,pro:0} },
  {slug:'game-2048',category:'game',added:'2026-06-26',phase:1,isPro:false,isNew:true,tags:['2048','숫자 합치기','2048 게임','number puzzle','2048 game'],maxFileSizeMB:{free:0,pro:0} },
  {slug:'memory-game',category:'game',added:'2026-06-26',phase:1,isPro:false,isNew:true,tags:['카드 짝맞추기','메모리 게임','memory game','card match','짝 맞추기'],maxFileSizeMB:{free:0,pro:0} },
  {slug:'tic-tac-toe',category:'game',added:'2026-06-26',phase:1,isPro:false,isNew:true,tags:['틱택토','삼목','tic tac toe','오목 아님','ox 게임'],maxFileSizeMB:{free:0,pro:0} },
  {slug:'number-order',category:'game',added:'2026-06-26',phase:1,isPro:false,isNew:true,tags:['숫자 순서','1부터 25','number order','schulte table','집중력 게임'],maxFileSizeMB:{free:0,pro:0} },
  {slug:'color-find',category:'game',added:'2026-06-26',phase:1,isPro:false,isNew:true,tags:['색깔 찾기','다른 색 찾기','color find','different color','색약 테스트 아님'],maxFileSizeMB:{free:0,pro:0} },
  {slug:'aim-trainer',category:'game',added:'2026-06-26',phase:1,isPro:false,isNew:true,tags:['에임 트레이너','과녁 클릭','aim trainer','aim test','마우스 연습'],maxFileSizeMB:{free:0,pro:0} },
  {slug:'sliding-puzzle',category:'game',added:'2026-06-26',phase:1,isPro:false,isNew:true,tags:['15퍼즐','슬라이딩 퍼즐','15 puzzle','sliding puzzle','숫자 퍼즐'],maxFileSizeMB:{free:0,pro:0} },
  {slug:'choseong-quiz',category:'game',added:'2026-06-26',phase:1,isPro:false,isNew:true,tags:['초성 퀴즈','초성게임','choseong quiz','korean initials','ㄱㅅ 퀴즈'],maxFileSizeMB:{free:0,pro:0} },
  {slug:'minesweeper',category:'game',added:'2026-06-26',phase:1,isPro:false,isNew:true,tags:['지뢰찾기','마인스위퍼','minesweeper','지뢰 게임','mine game'],maxFileSizeMB:{free:0,pro:0} },
  {slug:'sudoku',category:'game',added:'2026-06-26',phase:1,isPro:false,isNew:true,tags:['스도쿠','sudoku','숫자 퍼즐','스도쿠 게임','sudoku puzzle'],maxFileSizeMB:{free:0,pro:0} },
  {slug:'word-guess',category:'game',added:'2026-06-26',phase:1,isPro:false,isNew:true,tags:['단어 맞히기','꼬들','워들','wordle','word guess game'],maxFileSizeMB:{free:0,pro:0} },
  {slug:'block-puzzle',category:'game',added:'2026-06-28',phase:1,isPro:false,isNew:true,tags:['블록 퍼즐','테트리스','블록게임','block puzzle','tetris','ブロックパズル'],maxFileSizeMB:{free:0,pro:0} },
  {slug:'snake',category:'game',added:'2026-06-28',phase:1,isPro:false,isNew:true,tags:['스네이크','지렁이 게임','뱀 게임','snake game','スネークゲーム'],maxFileSizeMB:{free:0,pro:0} },
  {slug:'connect-four',category:'game',added:'2026-06-28',phase:1,isPro:false,isNew:true,tags:['사목','커넥트 포','4목','connect four','four in a row','コネクトフォー'],maxFileSizeMB:{free:0,pro:0} },
  {slug:'whack-a-mole',category:'game',added:'2026-06-28',phase:1,isPro:false,isNew:true,tags:['두더지 잡기','두더지게임','whack a mole','mole game','もぐらたたき'],maxFileSizeMB:{free:0,pro:0} },
  {slug:'simon',category:'game',added:'2026-06-28',phase:1,isPro:false,isNew:true,tags:['사이먼 게임','색 순서 기억','메모리 게임','simon game','memory pattern','サイモンゲーム'],maxFileSizeMB:{free:0,pro:0} },
  {slug:'click-speed-test',category:'game',added:'2026-06-24',phase:1,isPro:false,isNew:true,tags:['click speed test','cps test','clicks per second','click speed','cps game'],maxFileSizeMB:{free:0,pro:0} },
  {slug:'add-text-to-image',category:'image',added:'2026-06-24',phase:1,isPro:false,isNew:true,tags:['add text to image','text on photo','image text sticker','add text photo','sticker image'],maxFileSizeMB:{free:30,pro:120} },
  {slug:'qr-scanner',category:'qr',added:'2026-06-24',phase:1,isPro:false,isNew:true,tags:['qr reader','qr scanner','scan qr','decode qr','qr read','qr scanner ko','QR read jp'],maxFileSizeMB:{free:10,pro:40} },
  {slug:'pdf-to-jpg',category:'pdf',added:'2026-06-24',phase:1,isPro:false,isNew:true,tags:['pdf to jpg','pdf to image','convert pdf','pdf image convert','PDF to JPG jp'],maxFileSizeMB:{free:50,pro:200} },
  {slug:'watermark-pdf',category:'pdf',added:'2026-06-24',phase:1,isPro:false,isNew:true,tags:['watermark pdf','add watermark','pdf watermark','PDF watermark jp'],maxFileSizeMB:{free:50,pro:200} },
  {slug:'pdf-page-numbers',category:'pdf',added:'2026-06-24',phase:1,isPro:false,isNew:true,tags:['pdf page numbers','number pages','pdf page number','PDF page number jp'],maxFileSizeMB:{free:50,pro:200} },
  {slug:'heic-to-jpg',category:'image',added:'2026-06-24',phase:1,isPro:false,isNew:true,tags:['heic to jpg','heic converter','iphone photo','heic convert','HEIC jp'],maxFileSizeMB:{free:30,pro:120} },
  {slug:'rotate-image',category:'image',added:'2026-06-24',phase:1,isPro:false,isNew:true,tags:['rotate image','flip image','image rotate','image flip','image rotate jp'],maxFileSizeMB:{free:30,pro:120} },
  {slug:'meme-generator',category:'image',added:'2026-06-24',phase:1,isPro:false,isNew:true,tags:['meme generator','meme maker','meme make','meme jp'],maxFileSizeMB:{free:30,pro:120} },
  {slug:'circle-crop',category:'image',also:['social'],added:'2026-06-24',phase:1,isPro:false,isNew:true,tags:['circle crop','round image','circle crop ko','circle crop jp'],maxFileSizeMB:{free:30,pro:120} },
  {slug:'blur-image',category:'image',added:'2026-06-24',phase:1,isPro:false,isNew:true,tags:['blur image','blur photo','image blur','image blur jp'],maxFileSizeMB:{free:30,pro:120} },
  {slug:'image-filter',category:'image',added:'2026-06-26',phase:1,isPro:false,isNew:true,tags:['사진 필터','이미지 밝기 대비','image filter','photo filter','brightness contrast'],maxFileSizeMB:{free:30,pro:120} },
  {slug:'ocr',category:'image',added:'2026-06-26',phase:1,isPro:false,isNew:true,tags:['ocr','이미지 텍스트 추출','image to text','글자 인식','사진 텍스트'],maxFileSizeMB:{free:20,pro:80} },
  {slug:'video-to-gif',category:'video',added:'2026-06-26',phase:1,isPro:false,isNew:true,tags:['영상 gif 변환','동영상 gif','video to gif','gif 만들기','mp4 to gif'],maxFileSizeMB:{free:50,pro:200} },
  {slug:'compress-pdf',category:'pdf',added:'2026-06-26',phase:1,isPro:false,isNew:true,tags:['pdf 압축','pdf 용량 줄이기','compress pdf','reduce pdf size','pdf compressor'],maxFileSizeMB:{free:50,pro:200} },
  {slug:'zip-files',category:'file',added:'2026-06-26',phase:1,isPro:false,isNew:true,tags:['파일 압축','zip 만들기','zip files','create zip','파일 묶기'],maxFileSizeMB:{free:100,pro:500} },
  {slug:'unzip',category:'file',added:'2026-06-26',phase:1,isPro:false,isNew:true,tags:['압축 풀기','압축 해제','unzip','extract zip','zip 파일 열기'],maxFileSizeMB:{free:100,pro:500} },
  {slug:'reaction-time-test',category:'game',added:'2026-06-24',phase:1,isPro:false,isNew:true,tags:['reaction time','reflex','game','test','leaderboard','반응속도','反応速度'],maxFileSizeMB:{free:0,pro:0} },
  {slug:'mortgage-calculator',category:'finance',added:'2026-06-24',phase:1,isPro:false,isNew:true,tags:['mortgage','home loan','calculator','住宅ローン','주택담보대출'],maxFileSizeMB:{free:0,pro:0} },
  {slug:'auto-loan-calculator',category:'finance',added:'2026-06-24',phase:1,isPro:false,isNew:true,tags:['auto loan','car loan','calculator','自動車ローン','자동차 대출'],maxFileSizeMB:{free:0,pro:0} },
  {slug:'retirement-calculator',category:'finance',added:'2026-06-24',phase:1,isPro:false,isNew:true,tags:['retirement','savings','nest egg','老後資金','은퇴 자금'],maxFileSizeMB:{free:0,pro:0} },
  {slug:'inflation-calculator',category:'finance',added:'2026-06-24',phase:1,isPro:false,isNew:true,tags:['inflation','purchasing power','calculator','インフレ','인플레이션'],maxFileSizeMB:{free:0,pro:0} },
  {slug:'screen-recorder',category:'video',added:'2026-06-23',phase:1,isPro:false,isNew:true,tags:['screen recorder','record','capture','webm','画面録画','화면 녹화'],maxFileSizeMB:{free:0,pro:0} },
  {slug:'webcam-test',category:'device',added:'2026-06-23',phase:1,isPro:false,isNew:true,tags:['webcam','camera','test','check','ウェブカメラ','웹캠'],maxFileSizeMB:{free:0,pro:0} },
  {slug:'refresh-rate-test',category:'device',added:'2026-06-26',phase:1,isPro:false,isNew:true,tags:['주사율 테스트','모니터 주사율','refresh rate test','monitor hz','fps test'],maxFileSizeMB:{free:0,pro:0} },
  {slug:'screen-test',category:'device',added:'2026-06-26',phase:1,isPro:false,isNew:true,tags:['화면 테스트','죽은 픽셀','dead pixel test','screen test','monitor test'],maxFileSizeMB:{free:0,pro:0} },
  {slug:'speaker-test',category:'device',added:'2026-06-26',phase:1,isPro:false,isNew:true,tags:['스피커 테스트','좌우 소리','speaker test','left right audio','stereo test'],maxFileSizeMB:{free:0,pro:0} },
  {slug:'mic-test',category:'device',added:'2026-06-26',phase:1,isPro:false,isNew:true,tags:['마이크 테스트','마이크 점검','mic test','microphone test','audio input'],maxFileSizeMB:{free:0,pro:0} },
  {slug:'keyboard-test',category:'device',added:'2026-06-26',phase:1,isPro:false,isNew:true,tags:['키보드 테스트','키 눌림 점검','keyboard test','key tester','stuck key'],maxFileSizeMB:{free:0,pro:0} },
  {slug:'mouse-test',category:'device',added:'2026-06-26',phase:1,isPro:false,isNew:true,tags:['마우스 테스트','마우스 점검','mouse test','mouse button test','polling rate'],maxFileSizeMB:{free:0,pro:0} },
  {slug:'country-calling-codes',category:'world',added:'2026-06-26',phase:1,isPro:false,isNew:true,tags:['국가번호','국가 전화번호','country calling code','dialing code','국제전화 번호'],maxFileSizeMB:{free:0,pro:0} },
  {slug:'flag-quiz',category:'world',added:'2026-06-26',phase:1,isPro:false,isNew:true,tags:['국기 퀴즈','세계 국기','flag quiz','guess the flag','나라 국기'],maxFileSizeMB:{free:0,pro:0} },
  {slug:'capital-quiz',category:'world',added:'2026-06-26',phase:1,isPro:false,isNew:true,tags:['수도 퀴즈','나라 수도','capital quiz','world capitals','수도 맞히기'],maxFileSizeMB:{free:0,pro:0} },
  {slug:'country-compare',category:'world',added:'2026-06-26',phase:1,isPro:false,isNew:true,tags:['나라 정보 비교','국가 비교','country compare','compare countries','나라 비교'],maxFileSizeMB:{free:0,pro:0} },
  {slug:'capital-distance',category:'world',added:'2026-06-26',phase:1,isPro:false,isNew:true,tags:['두 도시 거리','수도 간 거리','distance between cities','capital distance','도시 거리 계산'],maxFileSizeMB:{free:0,pro:0} },
  {slug:'time-difference',category:'world',added:'2026-06-26',phase:1,isPro:false,isNew:true,tags:['시차 계산기','나라 시차','time difference','한국 미국 시차','timezone difference'],maxFileSizeMB:{free:0,pro:0} },
  {slug:'plug-type',category:'world',added:'2026-06-26',phase:1,isPro:false,isNew:true,tags:['나라별 콘센트','플러그 타입','power plug type','콘센트 모양','travel adapter'],maxFileSizeMB:{free:0,pro:0} },
  {slug:'youtube-thumbnail',category:'image',also:['social'],added:'2026-06-26',phase:1,isPro:false,isNew:true,tags:['유튜브 썸네일','썸네일 다운로드','youtube thumbnail','thumbnail downloader','유튜브 이미지'],maxFileSizeMB:{free:0,pro:0} },
  {slug:'savings-calculator',category:'finance',added:'2026-06-26',phase:1,isPro:false,isNew:true,tags:['적금 계산기','적금 이자','savings calculator','만기 수령액','적금 만기'],maxFileSizeMB:{free:0,pro:0} },
  {slug:'social-character-counter',category:'social',added:'2026-06-26',phase:1,isPro:false,isNew:true,tags:['글자수 세기','sns 글자수','인스타 글자수','트위터 글자수','유튜브 글자수','글자수 제한','character counter','instagram caption length'],maxFileSizeMB:{free:0,pro:0} },
  {slug:'instagram-line-break',category:'social',added:'2026-06-26',phase:1,isPro:false,isNew:true,tags:['인스타 줄바꿈','인스타그램 줄바꿈','instagram line break','캡션 줄바꿈','띄어쓰기'],maxFileSizeMB:{free:0,pro:0} },
  {slug:'hashtag-generator',category:'social',added:'2026-06-26',phase:1,isPro:false,isNew:true,tags:['해시태그 생성','해시태그 만들기','hashtag generator','인스타 해시태그','#태그'],maxFileSizeMB:{free:0,pro:0} },
  {slug:'voice-recorder',category:'audio',added:'2026-06-23',phase:1,isPro:false,isNew:true,tags:['voice recorder','audio','microphone','record','ボイスレコーダー','음성 녹음'],maxFileSizeMB:{free:0,pro:0} },
  {slug:'tone-generator',category:'audio',added:'2026-06-23',phase:1,isPro:false,isNew:true,tags:['tone','frequency','hz','sound','test','トーン','주파수'],maxFileSizeMB:{free:0,pro:0} },
  {slug:'merge-pdf',category:'pdf',added:'2026-06-23',phase:1,isPro:false,isNew:true,tags:['pdf','merge','combine','join','結合','병합'],maxFileSizeMB:{free:0,pro:0} },
  {slug:'split-pdf',category:'pdf',added:'2026-06-23',phase:1,isPro:false,isNew:true,tags:['pdf','split','extract','pages','分割','분할'],maxFileSizeMB:{free:0,pro:0} },
  {slug:'rotate-pdf',category:'pdf',added:'2026-06-23',phase:1,isPro:false,isNew:true,tags:['pdf','rotate','turn','回転','회전'],maxFileSizeMB:{free:0,pro:0} },
  {slug:'remove-pdf-pages',category:'pdf',added:'2026-06-23',phase:1,isPro:false,isNew:true,tags:['pdf','delete','remove','pages','削除','삭제'],maxFileSizeMB:{free:0,pro:0} },
  {slug:'fancy-text-generator',category:'funny',also:['social'],added:'2026-06-23',phase:1,isPro:false,isNew:true,tags:['fancy text','font','unicode','instagram','폰트','フォント'],maxFileSizeMB:{free:0,pro:0} },
  {slug:'favicon-generator',category:'image',added:'2026-06-23',phase:1,isPro:false,isNew:true,tags:['favicon','icon','generator','ico','ファビコン','파비콘'],maxFileSizeMB:{free:0,pro:0} },
  {slug:'webp-converter',category:'image',added:'2026-06-23',phase:1,isPro:false,isNew:true,tags:['webp','convert','png','jpg','compress'],maxFileSizeMB:{free:0,pro:0} },
  {slug:'image-to-pdf',category:'pdf',added:'2026-06-23',phase:1,isPro:false,isNew:true,tags:['image','pdf','convert','jpg','png'],maxFileSizeMB:{free:0,pro:0} },
  {slug:'compound-interest-calculator',category:'finance',added:'2026-06-23',phase:1,isPro:false,isNew:true,tags:['compound interest','investment','savings','複利','복리'],maxFileSizeMB:{free:0,pro:0} },
  {slug:'salary-converter',category:'finance',added:'2026-06-23',phase:1,isPro:false,isNew:true,tags:['salary','hourly','annual','wage','給与','급여'],maxFileSizeMB:{free:0,pro:0} },
  {slug:'vat-calculator',category:'finance',added:'2026-06-23',phase:1,isPro:false,isNew:true,tags:['vat','sales tax','消費税','부가세'],maxFileSizeMB:{free:0,pro:0} },
  {slug:'savings-goal-calculator',category:'finance',added:'2026-06-23',phase:1,isPro:false,isNew:true,tags:['savings','goal','budget','貯金','저축'],maxFileSizeMB:{free:0,pro:0} },
  {slug:'random-string-generator',category:'security',added:'2026-06-23',phase:1,isPro:false,isNew:true,tags:['random','string','token','password','generator'],maxFileSizeMB:{free:0,pro:0} },
  {slug:'wifi-qr-generator',category:'qr',added:'2026-06-23',phase:1,isPro:false,isNew:true,tags:['wifi','qr','password','network','ssid','wifi qr'],maxFileSizeMB:{free:0,pro:0} },
  {slug:'vcard-qr-generator',category:'qr',added:'2026-06-23',phase:1,isPro:false,isNew:true,tags:['vcard','qr','contact','business card','連絡先'],maxFileSizeMB:{free:0,pro:0} },
  {slug:'email-qr-generator',category:'qr',added:'2026-06-23',phase:1,isPro:false,isNew:true,tags:['email','qr','mailto'],maxFileSizeMB:{free:0,pro:0} },
  {slug:'phone-qr-generator',category:'qr',added:'2026-06-23',phase:1,isPro:false,isNew:true,tags:['phone','qr','tel','sms','call'],maxFileSizeMB:{free:0,pro:0} },
  {slug:'body-fat-calculator',category:'health',added:'2026-06-23',phase:1,isPro:false,isNew:true,tags:['body fat','navy','fitness','health','体脂肪','체지방'],maxFileSizeMB:{free:0,pro:0} },
  {slug:'due-date-calculator',category:'health',added:'2026-06-23',phase:1,isPro:false,isNew:true,tags:['pregnancy','due date','baby','出産予定日','출산예정일'],maxFileSizeMB:{free:0,pro:0} },
  {slug:'target-heart-rate-calculator',category:'health',added:'2026-06-23',phase:1,isPro:false,isNew:true,tags:['heart rate','zone','cardio','心拍数','심박수'],maxFileSizeMB:{free:0,pro:0} },
  {slug:'ideal-weight-calculator',category:'health',added:'2026-06-23',phase:1,isPro:false,isNew:true,tags:['ideal weight','devine','health','適正体重','적정체중'],maxFileSizeMB:{free:0,pro:0} },
  {slug:'ovulation-calculator',category:'health',added:'2026-06-23',phase:1,isPro:false,isNew:true,tags:['ovulation','fertility','cycle','排卵日','배란일'],maxFileSizeMB:{free:0,pro:0} },
  {slug:'robots-txt-generator',category:'seo',also:['developer'],added:'2026-06-23',phase:1,isPro:false,isNew:true,tags:['robots','seo','crawler','webmaster'],maxFileSizeMB:{free:0,pro:0} },
  {slug:'sitemap-generator',category:'seo',also:['developer'],added:'2026-06-23',phase:1,isPro:false,isNew:true,tags:['sitemap','xml','seo','webmaster'],maxFileSizeMB:{free:0,pro:0} },
  {slug:'utm-builder',category:'seo',added:'2026-06-23',phase:1,isPro:false,isNew:true,tags:['utm','campaign','url','marketing','analytics'],maxFileSizeMB:{free:0,pro:0} },
  {slug:'schema-markup-generator',category:'seo',also:['developer'],added:'2026-06-23',phase:1,isPro:false,isNew:true,tags:['schema','json-ld','structured data','seo'],maxFileSizeMB:{free:0,pro:0} },
  {slug:'htaccess-redirect-generator',category:'seo',also:['developer'],added:'2026-06-23',phase:1,isPro:false,isNew:true,tags:['htaccess','redirect','301','apache'],maxFileSizeMB:{free:0,pro:0} },
  {slug:'romaji-kana-converter',category:'language',also:['text'],added:'2026-06-23',phase:1,isPro:false,isNew:true,tags:['romaji','hiragana','katakana','kana','japanese','ローマ字','変換'],maxFileSizeMB:{free:0,pro:0} },
  {slug:'fullwidth-halfwidth-converter',category:'language',also:['text'],added:'2026-06-23',phase:1,isPro:false,isNew:true,tags:['fullwidth','halfwidth','全角','半角','変換','zenkaku','hankaku'],maxFileSizeMB:{free:0,pro:0} },
  {slug:'hiragana-katakana-converter',category:'language',also:['text'],added:'2026-06-23',phase:1,isPro:false,isNew:true,tags:['hiragana','katakana','ひらがな','カタカナ','変換','japanese'],maxFileSizeMB:{free:0,pro:0} },
  {slug:'hangul-romaja-converter',category:'language',also:['text'],added:'2026-06-23',phase:1,isPro:false,isNew:true,tags:['hangul','romaja','한글','로마자','korean','romanization'],maxFileSizeMB:{free:0,pro:0} },
  {slug:'dice-roller',category:'random',also:['game'],added:'2026-06-22',phase:1,isPro:false,isNew:true,tags:['dice','roller','random','d6','rpg'],maxFileSizeMB:{free:0,pro:0} },
  {slug:'tip-calculator',category:'finance',added:'2026-06-22',phase:1,isPro:false,isNew:true,tags:['tip','restaurant','split','bill'],maxFileSizeMB:{free:0,pro:0} },
  {slug:'loan-calculator',category:'finance',added:'2026-06-22',phase:1,isPro:false,isNew:true,tags:['loan','mortgage','payment','interest','amortization'],maxFileSizeMB:{free:0,pro:0} },
  {slug:'hash-generator',category:'security',also:['file'],added:'2026-06-22',phase:1,isPro:false,isNew:true,tags:['hash generator'],maxFileSizeMB:{free:0,pro:0} },
  {slug:'timezone-converter',category:'time',added:'2026-06-22',phase:1,isPro:false,isNew:true,tags:['timezone','time','convert','world'],maxFileSizeMB:{free:0,pro:0} },
  {slug:'regex-tester',category:'developer',added:'2026-06-22',phase:1,isPro:false,isNew:true,tags:['regex','regexp','test','pattern','match'],maxFileSizeMB:{free:0,pro:0} },
  {slug:'json-formatter',category:'developer',added:'2026-06-22',phase:1,isPro:false,isNew:true,tags:['json formatter'],maxFileSizeMB:{free:0,pro:0} },
  {slug:'color-mixer',category:'design',added:'2026-06-22',phase:1,isPro:false,isNew:true,tags:['color','mix','blend','combine','palette'],maxFileSizeMB:{free:0,pro:0} },
  {slug:'email-extractor',category:'utility',added:'2026-06-22',phase:1,isPro:false,isNew:true,tags:['email extractor'],maxFileSizeMB:{free:0,pro:0} },
  {slug:'cron-expression-generator',category:'developer',added:'2026-06-22',phase:1,isPro:false,isNew:true,tags:['cron','schedule','expression','unix','job'],maxFileSizeMB:{free:0,pro:0} },
  {slug:'number-base-converter',category:'utility',added:'2026-06-22',phase:1,isPro:false,isNew:true,tags:['binary','hex','octal','decimal','convert'],maxFileSizeMB:{free:0,pro:0} },
  {slug:'css-gradient-generator',category:'design',also:['developer'],added:'2026-06-22',phase:1,isPro:false,isNew:true,tags:['css','gradient','linear','radial','color'],maxFileSizeMB:{free:0,pro:0} },
  {slug:'fibonacci-generator',category:'utility',added:'2026-06-22',phase:1,isPro:false,isNew:true,tags:['fibonacci','sequence','number','math','series'],maxFileSizeMB:{free:0,pro:0} },
  {slug:'date-calculator',category:'time',added:'2026-06-22',phase:1,isPro:false,isNew:true,tags:['date','calculator','difference','days','duration'],maxFileSizeMB:{free:0,pro:0} },
  {slug:'anniversary-calculator',category:'time',added:'2026-06-26',phase:1,isPro:false,isNew:true,tags:['기념일 계산기','100일 계산기','anniversary calculator','커플 디데이','사귄 지'],maxFileSizeMB:{free:0,pro:0} },
  {slug:'chinese-zodiac',category:'time',added:'2026-06-26',phase:1,isPro:false,isNew:true,tags:['띠 계산기','간지 계산기','chinese zodiac','띠별 나이','무슨 띠'],maxFileSizeMB:{free:0,pro:0} },
  {slug:'week-number-calculator',category:'time',added:'2026-06-26',phase:1,isPro:false,isNew:true,tags:['주차 계산기','몇 주차','week number','ISO week','이번 주 몇주차'],maxFileSizeMB:{free:0,pro:0} },
  {slug:'text-to-slug',category:'seo',added:'2026-06-22',phase:1,isPro:false,isNew:true,tags:['slug','url','text','convert','seo'],maxFileSizeMB:{free:0,pro:0} },
  {slug:'number-formatter',category:'utility',added:'2026-06-22',phase:1,isPro:false,isNew:true,tags:['number','format','thousand','locale','separator'],maxFileSizeMB:{free:0,pro:0} },
  {slug:'countdown-timer',category:'time',added:'2026-06-22',phase:1,isPro:false,isNew:true,tags:['countdown','timer','alarm','event','date'],maxFileSizeMB:{free:0,pro:0} },
  {slug:'online-alarm',category:'time',added:'2026-06-26',phase:1,isPro:false,isNew:true,tags:['온라인 알람','알람 맞추기','online alarm','alarm clock','set alarm'],maxFileSizeMB:{free:0,pro:0} },
  {slug:'dday-calculator',category:'time',added:'2026-06-26',phase:1,isPro:false,isNew:true,tags:['디데이','디데이 계산기','d-day calculator','days until','남은 날짜'],maxFileSizeMB:{free:0,pro:0} },
  {slug:'man-age-calculator',category:'time',added:'2026-06-26',phase:1,isPro:false,isNew:true,tags:['만 나이','만 나이 계산기','korean age','만나이 계산','age in korea'],maxFileSizeMB:{free:0,pro:0} },
  {slug:'world-clock',category:'time',added:'2026-06-26',phase:1,isPro:false,isNew:true,tags:['세계 시계','월드클락','world clock','time zones','도시 시간'],maxFileSizeMB:{free:0,pro:0} },
  {slug:'metronome',category:'time',added:'2026-06-26',phase:1,isPro:false,isNew:true,tags:['메트로놈','온라인 메트로놈','metronome','bpm','tempo'],maxFileSizeMB:{free:0,pro:0} },
  {slug:'roman-numeral-converter',category:'utility',added:'2026-06-22',phase:1,isPro:false,isNew:true,tags:['roman','numeral','convert','number','latin'],maxFileSizeMB:{free:0,pro:0} },
  {slug:'morse-code-translator',category:'utility',added:'2026-06-22',phase:1,isPro:false,isNew:true,tags:['morse','code','translate','audio','signal'],maxFileSizeMB:{free:0,pro:0} },
  {slug:'pixel-to-rem-converter',category:'developer',added:'2026-06-22',phase:1,isPro:false,isNew:true,tags:['pixel to rem converter','pixel to rem'],maxFileSizeMB:{free:0,pro:0} },
  {slug:'case-converter',category:'text',added:'2026-06-22',phase:1,isPro:false,isNew:true,tags:['case converter'],maxFileSizeMB:{free:0,pro:0} },
  {slug:'nato-alphabet',category:'text',added:'2026-06-22',phase:1,isPro:false,isNew:true,tags:['nato','alphabet','phonetic','spelling','military'],maxFileSizeMB:{free:0,pro:0} },
  {slug:'word-counter',category:'text',added:'2026-06-22',phase:1,isPro:false,isNew:true,tags:['word counter'],maxFileSizeMB:{free:0,pro:0} },
  {slug:'lorem-ipsum-generator',category:'text',added:'2026-06-22',phase:1,isPro:false,isNew:true,tags:['lorem','ipsum','placeholder','text','dummy'],maxFileSizeMB:{free:0,pro:0} },
  {slug:'opacity-calculator',category:'design',added:'2026-06-22',phase:1,isPro:false,isNew:true,tags:['opacity calculator'],maxFileSizeMB:{free:0,pro:0} },
  {slug:'palindrome-checker',category:'text',added:'2026-06-22',phase:1,isPro:false,isNew:true,tags:['palindrome','text','check','reverse'],maxFileSizeMB:{free:0,pro:0} },
  {slug:'markdown-to-html',category:'text',also:['developer'],added:'2026-06-22',phase:1,isPro:false,isNew:true,tags:['markdown','html','convert','render','preview'],maxFileSizeMB:{free:0,pro:0} },
  {slug:'scientific-calculator',category:'utility',added:'2026-06-22',phase:1,isPro:false,isNew:true,tags:['calculator','scientific','math','sin','cos'],maxFileSizeMB:{free:0,pro:0} },
  {slug:'bmi-calculator',category:'health',added:'2026-06-22',phase:1,isPro:false,isNew:true,tags:['bmi','body','mass','index','health'],maxFileSizeMB:{free:0,pro:0} },
  {slug:'speed-converter',category:'utility',added:'2026-06-22',phase:1,isPro:false,isNew:true,tags:['speed converter'],maxFileSizeMB:{free:0,pro:0} },
  {slug:'calorie-calculator',category:'health',added:'2026-06-22',phase:1,isPro:false,isNew:true,tags:['calorie','tdee','bmr','diet','health'],maxFileSizeMB:{free:0,pro:0} },
  {slug:'pomodoro-timer',category:'time',added:'2026-06-22',phase:1,isPro:false,isNew:true,tags:['pomodoro','timer','focus','work','productivity'],maxFileSizeMB:{free:0,pro:0} },
  {slug:'binary-text-converter',category:'developer',added:'2026-06-22',phase:1,isPro:false,isNew:true,tags:['binary text converter','binary text'],maxFileSizeMB:{free:0,pro:0} },
  {slug:'stopwatch',category:'time',added:'2026-06-22',phase:1,isPro:false,isNew:true,tags:['stopwatch','timer','lap','clock','measure'],maxFileSizeMB:{free:0,pro:0} },
  {slug:'fraction-calculator',category:'utility',added:'2026-06-22',phase:1,isPro:false,isNew:true,tags:['fraction calculator'],maxFileSizeMB:{free:0,pro:0} },
  {slug:'fuel-economy-calculator',category:'finance',added:'2026-06-22',phase:1,isPro:false,isNew:true,tags:['fuel economy','mpg calculator','gas mileage','fuel cost','연비 계산'],maxFileSizeMB:{free:0,pro:0} },
  {slug:'zodiac-sign',category:'utility',added:'2026-06-22',phase:1,isPro:false,isNew:true,tags:['zodiac sign'],maxFileSizeMB:{free:0,pro:0} },
  {slug:'prime-number-checker',category:'utility',added:'2026-06-22',phase:1,isPro:false,isNew:true,tags:['prime','number','sieve','factor','math'],maxFileSizeMB:{free:0,pro:0} },
  {slug:'color-to-tailwind',category:'design',also:['developer'],added:'2026-06-22',phase:1,isPro:false,isNew:true,tags:['color to tailwind'],maxFileSizeMB:{free:0,pro:0} },
  {slug:'unit-converter',category:'utility',added:'2026-06-22',phase:1,isPro:false,isNew:true,tags:['unit','convert','measurement','metric','imperial'],maxFileSizeMB:{free:0,pro:0} },
  {slug:'random-team-generator',category:'random',added:'2026-06-22',phase:1,isPro:false,isNew:true,tags:['random team generator','random team'],maxFileSizeMB:{free:0,pro:0} },
  {slug:'random-name-generator',category:'random',added:'2026-06-22',phase:1,isPro:false,isNew:true,tags:['random name generator','random name'],maxFileSizeMB:{free:0,pro:0} },
  {slug:'investment-calculator',category:'finance',added:'2026-06-22',phase:1,isPro:false,isNew:true,tags:['investment calculator','roi','compound returns','investment growth','투자 계산'],maxFileSizeMB:{free:0,pro:0} },
  {slug:'discount-calculator',category:'finance',added:'2026-06-22',phase:1,isPro:false,isNew:true,tags:['discount','sale','price','percent'],maxFileSizeMB:{free:0,pro:0} },
  {slug:'electricity-cost-calculator',category:'finance',added:'2026-06-22',phase:1,isPro:false,isNew:true,tags:['electricity cost','power bill','energy cost','kwh cost','전기요금 계산'],maxFileSizeMB:{free:0,pro:0} },
  {slug:'grade-calculator',category:'utility',added:'2026-06-22',phase:1,isPro:false,isNew:true,tags:['grade calculator'],maxFileSizeMB:{free:0,pro:0} },
  {slug:'water-intake-calculator',category:'health',added:'2026-06-22',phase:1,isPro:false,isNew:true,tags:['water intake','daily water','hydration calculator','물 섭취량'],maxFileSizeMB:{free:0,pro:0} },
  {slug:'sleep-calculator',category:'health',added:'2026-06-22',phase:1,isPro:false,isNew:true,tags:['sleep calculator','sleep cycle','bedtime calculator','수면 시간'],maxFileSizeMB:{free:0,pro:0} },
  {slug:'pace-calculator',category:'health',added:'2026-06-22',phase:1,isPro:false,isNew:true,tags:['pace calculator','running pace','race time','러닝 페이스'],maxFileSizeMB:{free:0,pro:0} },
  {slug:'circle-calculator',category:'utility',added:'2026-06-22',phase:1,isPro:false,isNew:true,tags:['circle calculator'],maxFileSizeMB:{free:0,pro:0} },
  {slug:'random-quote-generator',category:'utility',added:'2026-06-22',phase:1,isPro:false,isNew:true,tags:['random quote generator','random quote'],maxFileSizeMB:{free:0,pro:0} },
  {slug:'tax-bracket-calculator',category:'finance',added:'2026-06-22',phase:1,isPro:false,isNew:true,tags:['tax bracket','income tax','marginal tax','tax rate','소득세 구간'],maxFileSizeMB:{free:0,pro:0} },
  {slug:'json-to-csv',category:'developer',also:['file'],added:'2026-06-22',phase:1,isPro:false,isNew:true,tags:['json','csv','convert','export','data'],maxFileSizeMB:{free:0,pro:0} },
  {slug:'gpa-calculator',category:'utility',added:'2026-06-22',phase:1,isPro:false,isNew:true,tags:['gpa calculator'],maxFileSizeMB:{free:0,pro:0} },
  {slug:'aspect-ratio-calculator',category:'utility',added:'2026-06-22',phase:1,isPro:false,isNew:true,tags:['aspect','ratio','width','height','resize'],maxFileSizeMB:{free:0,pro:0} },
  {slug:'budget-calculator',category:'finance',added:'2026-06-22',phase:1,isPro:false,isNew:true,tags:['budget calculator','monthly budget','expense planner','50 30 20 rule','예산 계산'],maxFileSizeMB:{free:0,pro:0} },
  {slug:'age-calculator',category:'health',also:['time'],added:'2026-06-22',phase:1,isPro:false,isNew:true,tags:['age','birthday','date','calculate','years'],maxFileSizeMB:{free:0,pro:0} },
  {slug:'coin-flip',category:'random',also:['game'],added:'2026-06-22',phase:1,isPro:false,isNew:true,tags:['coin','flip','random','heads','tails'],maxFileSizeMB:{free:0,pro:0} },
  {slug:'uuid-generator',category:'developer',added:'2026-06-22',phase:1,isPro:false,isNew:true,tags:['uuid generator'],maxFileSizeMB:{free:0,pro:0} },
  {slug:'text-diff',category:'text',added:'2026-06-22',phase:1,isPro:false,isNew:true,tags:['text diff'],maxFileSizeMB:{free:0,pro:0} },
  {slug:'csv-to-json',category:'developer',also:['file'],added:'2026-06-22',phase:1,isPro:false,isNew:true,tags:['csv to json'],maxFileSizeMB:{free:0,pro:0} },
  {slug:'color-palette-generator',category:'design',added:'2026-06-22',phase:1,isPro:false,isNew:true,tags:['color','palette','shades','tints','complementary'],maxFileSizeMB:{free:0,pro:0} },
  {slug:'reading-level-analyzer',category:'text',added:'2026-06-22',phase:1,isPro:false,isNew:true,tags:['reading level analyzer','reading level'],maxFileSizeMB:{free:0,pro:0} },
  {slug:'temperature-converter',category:'utility',added:'2026-06-22',phase:1,isPro:false,isNew:true,tags:['temperature','celsius','fahrenheit','kelvin','convert'],maxFileSizeMB:{free:0,pro:0} },
  {slug:'url-encoder',category:'developer',added:'2026-06-22',phase:1,isPro:false,isNew:true,tags:['url encoder'],maxFileSizeMB:{free:0,pro:0} },
  {slug:'html-entity-encoder',category:'developer',added:'2026-06-22',phase:1,isPro:false,isNew:true,tags:['html entity encoder','html entity'],maxFileSizeMB:{free:0,pro:0} },
  {slug:'character-map',category:'text',added:'2026-06-22',phase:1,isPro:false,isNew:true,tags:['character','unicode','symbol','map','special'],maxFileSizeMB:{free:0,pro:0} },
  {slug:'number-to-words',category:'text',added:'2026-06-22',phase:1,isPro:false,isNew:true,tags:['number','words','english','convert','spell'],maxFileSizeMB:{free:0,pro:0} },
  {slug:'percentage-calculator',category:'utility',added:'2026-06-22',phase:1,isPro:false,isNew:true,tags:['percentage','percent','calculate','ratio','math'],maxFileSizeMB:{free:0,pro:0} },
  {slug:'text-repeater',category:'text',added:'2026-06-22',phase:1,isPro:false,isNew:true,tags:['text','repeat','duplicate','string'],maxFileSizeMB:{free:0,pro:0} },
  {slug:'yaml-validator',category:'developer',added:'2026-06-22',phase:1,isPro:false,isNew:true,tags:['yaml validator'],maxFileSizeMB:{free:0,pro:0} },
  {slug:'character-frequency',category:'text',added:'2026-06-22',phase:1,isPro:false,isNew:true,tags:['character frequency'],maxFileSizeMB:{free:0,pro:0} },
  {slug:'css-box-shadow-generator',category:'design',also:['developer'],added:'2026-06-22',phase:1,isPro:false,isNew:true,tags:['css','box-shadow','shadow','generator','design'],maxFileSizeMB:{free:0,pro:0} },
  {slug:'border-radius-generator',category:'design',also:['developer'],added:'2026-06-22',phase:1,isPro:false,isNew:true,tags:['border radius generator','border radius'],maxFileSizeMB:{free:0,pro:0} },
  {slug:'css-animation-generator',category:'design',also:['developer'],added:'2026-06-22',phase:1,isPro:false,isNew:true,tags:['css','animation','keyframe','transition','effect'],maxFileSizeMB:{free:0,pro:0} },
  {slug:'css-grid-generator',category:'design',also:['developer'],added:'2026-06-22',phase:1,isPro:false,isNew:true,tags:['css','grid','layout','generator','columns'],maxFileSizeMB:{free:0,pro:0} },
  {slug:'pixel-converter',category:'developer',added:'2026-06-23',phase:1,isPro:false,isNew:true,tags:['pixel converter'],maxFileSizeMB:{free:0,pro:0} },
  {slug:'flip-text',category:'funny',added:'2026-06-23',phase:1,isPro:false,isNew:true,tags:['flip text'],maxFileSizeMB:{free:0,pro:0} },
  {slug:'css-minifier',category:'developer',added:'2026-06-22',phase:1,isPro:false,isNew:true,tags:['css','minify','compress','optimize','clean'],maxFileSizeMB:{free:0,pro:0} },
  {slug:'sql-formatter',category:'developer',added:'2026-06-22',phase:1,isPro:false,isNew:true,tags:['sql','format','query','database','beautify'],maxFileSizeMB:{free:0,pro:0} },
  {slug:'cron-parser',category:'developer',added:'2026-06-23',phase:1,isPro:false,isNew:true,tags:['cron parser'],maxFileSizeMB:{free:0,pro:0} },
  {slug:'emoji-picker',category:'text',also:['social'],added:'2026-06-23',phase:1,isPro:false,isNew:true,tags:['emoji picker'],maxFileSizeMB:{free:0,pro:0} },
  {slug:'color-contrast-checker',category:'design',added:'2026-06-22',phase:1,isPro:false,isNew:true,tags:['color','contrast','wcag','accessibility','a11y'],maxFileSizeMB:{free:0,pro:0} },
  {slug:'password-strength-checker',category:'security',added:'2026-06-23',phase:1,isPro:false,isNew:true,tags:['password','strength','security','checker'],maxFileSizeMB:{free:0,pro:0} },
  {slug:'html-color-names',category:'design',added:'2026-06-23',phase:1,isPro:false,isNew:true,tags:['html color names'],maxFileSizeMB:{free:0,pro:0} },
  {slug:'random-number-generator',category:'random',added:'2026-06-22',phase:1,isPro:false,isNew:true,tags:['random','number','generate','dice'],maxFileSizeMB:{free:0,pro:0} },
  {slug:'ip-address-lookup',category:'developer',added:'2026-06-23',phase:1,isPro:false,isNew:true,tags:['ip','address','geolocation','whois','lookup'],maxFileSizeMB:{free:0,pro:0} },
  {slug:'url-parser',category:'developer',added:'2026-06-22',phase:1,isPro:false,isNew:true,tags:['url','parse','query','path','decode'],maxFileSizeMB:{free:0,pro:0} },
  {slug:'html-minifier',category:'developer',added:'2026-06-22',phase:1,isPro:false,isNew:true,tags:['html','minify','compress','optimize','whitespace'],maxFileSizeMB:{free:0,pro:0} },
  {slug:'color-name-finder',category:'design',added:'2026-06-23',phase:1,isPro:false,isNew:true,tags:['color','name','hex','rgb','palette'],maxFileSizeMB:{free:0,pro:0} },
  {slug:'xml-to-json',category:'developer',added:'2026-06-23',phase:1,isPro:false,isNew:true,tags:['xml','json','convert','parse'],maxFileSizeMB:{free:1,pro:10} },
  {slug:'matrix-calculator',category:'utility',added:'2026-06-23',phase:1,isPro:false,isNew:true,tags:['matrix','math','linear','algebra'],maxFileSizeMB:{free:0,pro:0} },
  {slug:'subnet-calculator',category:'developer',added:'2026-06-23',phase:1,isPro:false,isNew:true,tags:['subnet','ip','network','cidr','mask'],maxFileSizeMB:{free:0,pro:0} },
  {slug:'word-frequency-counter',category:'text',added:'2026-06-23',phase:1,isPro:false,isNew:true,tags:['word','frequency','count','text','analysis'],maxFileSizeMB:{free:0,pro:0} },
  {slug:'markdown-table-generator',category:'text',also:['developer'],added:'2026-06-22',phase:1,isPro:false,isNew:true,tags:['markdown','table','generate','md','format'],maxFileSizeMB:{free:0,pro:0} },
  {slug:'css-unit-converter',category:'developer',added:'2026-06-22',phase:1,isPro:false,isNew:true,tags:['css','unit','px','em','rem','convert'],maxFileSizeMB:{free:0,pro:0} },
  {slug:'http-status-codes',category:'developer',added:'2026-06-23',phase:1,isPro:false,isNew:true,tags:['http','status','code','reference','api'],maxFileSizeMB:{free:0,pro:0} },
  {slug:'pixel-art-maker',category:'image',added:'2026-06-23',phase:1,isPro:false,isNew:true,tags:['pixel','art','draw','grid','editor'],maxFileSizeMB:{free:0,pro:0} },
  {slug:'currency-converter',category:'finance',added:'2026-06-22',phase:1,isPro:false,isNew:true,tags:['currency','exchange','rate','convert','money'],maxFileSizeMB:{free:0,pro:0} },
  {slug:'anagram-solver',category:'text',added:'2026-06-23',phase:1,isPro:false,isNew:true,tags:['anagram','words','letters','solve'],maxFileSizeMB:{free:0,pro:0} },
  {slug:'json-to-typescript',category:'developer',added:'2026-06-22',phase:1,isPro:false,isNew:true,tags:['json','typescript','interface','type','generate'],maxFileSizeMB:{free:0,pro:0} },
  {slug:'gradient-text-generator',category:'design',added:'2026-06-23',phase:1,isPro:false,isNew:true,tags:['gradient','text','css','color','webkit'],maxFileSizeMB:{free:0,pro:0} },
  {slug:'uuid-bulk-generator',category:'developer',added:'2026-06-22',phase:1,isPro:false,isNew:true,tags:['uuid','bulk','generate','v4','random'],maxFileSizeMB:{free:0,pro:0} },
  {slug:'typing-speed-test',category:'utility',also:['game'],added:'2026-06-22',phase:1,isPro:false,isNew:true,tags:['typing','speed','wpm','test','keyboard'],maxFileSizeMB:{free:0,pro:0} },
  {slug:'css-specificity-calculator',category:'developer',added:'2026-06-23',phase:1,isPro:false,isNew:true,tags:['css','specificity','selector','calculator'],maxFileSizeMB:{free:0,pro:0} },
  {slug:'file-size-converter',category:'utility',added:'2026-06-23',phase:1,isPro:false,isNew:true,tags:['file','size','bytes','kb','mb','convert'],maxFileSizeMB:{free:0,pro:0} },
  {slug:'image-placeholder-generator',category:'image',added:'2026-06-23',phase:1,isPro:false,isNew:true,tags:['placeholder','image','svg','dummy','size'],maxFileSizeMB:{free:0,pro:0} },
  {slug:'unicode-converter',category:'developer',added:'2026-06-23',phase:1,isPro:false,isNew:true,tags:['unicode','codepoint','escape','convert','utf'],maxFileSizeMB:{free:0,pro:0} },
  {slug:'random-color-generator',category:'design',added:'2026-06-23',phase:1,isPro:false,isNew:true,tags:['random','color','hex','rgb','generate'],maxFileSizeMB:{free:0,pro:0} },
  {slug:'git-commit-generator',category:'developer',added:'2026-06-23',phase:1,isPro:false,isNew:true,tags:['git','commit','message','conventional','generate'],maxFileSizeMB:{free:0,pro:0} },
  {slug:'statistics-calculator',category:'utility',added:'2026-06-23',phase:1,isPro:false,isNew:true,tags:['statistics','mean','median','standard','deviation'],maxFileSizeMB:{free:0,pro:0} },
  {slug:'tax-calculator',category:'finance',added:'2026-06-23',phase:1,isPro:false,isNew:true,tags:['tax','vat','gst','sales','calculator'],maxFileSizeMB:{free:0,pro:0} },
  {slug:'jwt-encoder',category:'security',also:['developer'],added:'2026-06-23',phase:1,isPro:false,isNew:true,tags:['jwt','token','encode','header','payload'],maxFileSizeMB:{free:0,pro:0} },
  {slug:'json-minifier',category:'developer',added:'2026-06-22',phase:1,isPro:false,isNew:true,tags:['json','minify','compress','format','pretty'],maxFileSizeMB:{free:0,pro:0} },
  {slug:'html-to-markdown',category:'text',also:['developer'],added:'2026-06-22',phase:1,isPro:false,isNew:true,tags:['html','markdown','convert','md','text'],maxFileSizeMB:{free:0,pro:0} },
  {slug:'text-to-handwriting',category:'funny',added:'2026-06-23',phase:1,isPro:false,isNew:true,tags:['handwriting','text','canvas','font','style'],maxFileSizeMB:{free:0,pro:0} },
  {slug:'svg-path-visualizer',category:'developer',added:'2026-06-23',phase:1,isPro:false,isNew:true,tags:['svg','path','visualize','d','commands'],maxFileSizeMB:{free:0,pro:0} },
  {slug:'invoice-generator',category:'finance',added:'2026-06-23',phase:1,isPro:false,isNew:true,tags:['invoice','billing','pdf','freelance','business'],maxFileSizeMB:{free:0,pro:0} },
  {slug:'css-clip-path-generator',category:'design',also:['developer'],added:'2026-06-23',phase:1,isPro:false,isNew:true,tags:['css','clip-path','shape','polygon','generator'],maxFileSizeMB:{free:0,pro:0} },
  {slug:'yaml-to-json',category:'developer',also:['file'],added:'2026-06-22',phase:1,isPro:false,isNew:true,tags:['yaml','json','convert','parse','format'],maxFileSizeMB:{free:0,pro:0} },
  {slug:'text-encryption',category:'security',added:'2026-06-23',phase:1,isPro:false,isNew:true,tags:['encrypt','decrypt','caesar','rot13','xor'],maxFileSizeMB:{free:0,pro:0} },
  {slug:'color-blindness-simulator',category:'design',added:'2026-06-22',phase:1,isPro:false,isNew:true,tags:['color','blindness','accessibility','vision','simulate'],maxFileSizeMB:{free:0,pro:0} },
  {slug:'barcode-generator',category:'qr',added:'2026-06-23',phase:1,isPro:false,isNew:true,tags:['barcode','code128','ean','generate','scan'],maxFileSizeMB:{free:0,pro:0} },
  {slug:'css-triangle-generator',category:'design',also:['developer'],added:'2026-06-23',phase:1,isPro:false,isNew:true,tags:['css','triangle','border','arrow','shape'],maxFileSizeMB:{free:0,pro:0} },
  {slug:'email-validator',category:'developer',added:'2026-06-23',phase:1,isPro:false,isNew:true,tags:['email','validate','check','format','syntax'],maxFileSizeMB:{free:0,pro:0} },
  {slug:'screen-resolution-checker',category:'utility',added:'2026-06-23',phase:1,isPro:false,isNew:true,tags:['screen','resolution','display','pixel','viewport'],maxFileSizeMB:{free:0,pro:0} },
  {slug:'calculator',category:'utility',added:'2026-06-23',phase:1,isPro:false,isNew:true,tags:['calculator','math','compute','arithmetic','basic'],maxFileSizeMB:{free:0,pro:0} },
  {slug:'image-color-extractor',category:'image',also:['design'],added:'2026-06-23',phase:1,isPro:false,isNew:true,tags:['image','color','extract','palette','dominant'],maxFileSizeMB:{free:5,pro:10} },
  {slug:'font-pairing-tool',category:'text',added:'2026-06-22',phase:1,isPro:false,isNew:true,tags:['font','pairing','typography','google','design'],maxFileSizeMB:{free:0,pro:0} },
  {slug:'html-color-codes',category:'design',added:'2026-06-23',phase:1,isPro:false,isNew:true,tags:['html','color','codes','reference','hex'],maxFileSizeMB:{free:0,pro:0} },
  {slug:'image-resizer',category:'image',also:['social'],added:'2026-06-22',phase:1,isPro:false,isNew:true,tags:['image','resize','scale','width','height'],maxFileSizeMB:{free:5,pro:10} },
  {slug:'html-table-generator',category:'developer',added:'2026-06-23',phase:1,isPro:false,isNew:true,tags:['html','table','generator','rows','columns'],maxFileSizeMB:{free:0,pro:0} },
  {slug:'xml-formatter',category:'developer',added:'2026-06-22',phase:1,isPro:false,isNew:true,tags:['xml','format','beautify','indent','parse'],maxFileSizeMB:{free:0,pro:0} },
  {slug:'text-to-ascii-art',category:'funny',added:'2026-06-23',phase:1,isPro:false,isNew:true,tags:['ascii','art','text','banner','figlet'],maxFileSizeMB:{free:0,pro:0} },
  {slug:'number-sorter',category:'utility',added:'2026-06-23',phase:1,isPro:false,isNew:true,tags:['number','sort','order','list','rank'],maxFileSizeMB:{free:0,pro:0} },
  {slug:'list-randomizer',category:'random',added:'2026-06-23',phase:1,isPro:false,isNew:true,tags:['list','random','shuffle','order','pick'],maxFileSizeMB:{free:0,pro:0} },
  {slug:'interest-calculator',category:'finance',added:'2026-06-23',phase:1,isPro:false,isNew:true,tags:['interest','compound','simple','loan','finance'],maxFileSizeMB:{free:0,pro:0} },
  {slug:'currency-formatter',category:'finance',added:'2026-06-23',phase:1,isPro:false,isNew:true,tags:['currency','format','money','locale','number'],maxFileSizeMB:{free:0,pro:0} },
  {slug:'json-tree-viewer',category:'developer',added:'2026-06-23',phase:1,isPro:false,isNew:true,tags:['json','tree','viewer','parse','explore'],maxFileSizeMB:{free:0,pro:0} },
  {slug:'whitespace-remover',category:'text',added:'2026-06-22',phase:1,isPro:false,isNew:true,tags:['whitespace','space','trim','remove','clean'],maxFileSizeMB:{free:0,pro:0} },
  {slug:'javascript-minifier',category:'developer',added:'2026-06-23',phase:1,isPro:false,isNew:true,tags:['javascript','minify','compress','js','optimize'],maxFileSizeMB:{free:0,pro:0} },
  {slug:'image-to-base64',category:'image',also:['file'],added:'2026-06-23',phase:1,isPro:false,isNew:true,tags:['image','base64','encode','convert','data-url'],maxFileSizeMB:{free:5,pro:10} },
  {slug:'color-shades-generator',category:'design',added:'2026-06-23',phase:1,isPro:false,isNew:true,tags:['color','shades','tints','palette','design'],maxFileSizeMB:{free:0,pro:0} },
  {slug:'speed-calculator',category:'utility',added:'2026-06-23',phase:1,isPro:false,isNew:true,tags:['speed','distance','time','calculate','travel'],maxFileSizeMB:{free:0,pro:0} },
  {slug:'ip-address-info',category:'developer',added:'2026-06-22',phase:1,isPro:false,isNew:true,tags:['ip','address','network','subnet','lookup'],maxFileSizeMB:{free:0,pro:0} },
  {slug:'data-storage-converter',category:'utility',added:'2026-06-23',phase:1,isPro:false,isNew:true,tags:['data','storage','gb','mb','kb','byte'],maxFileSizeMB:{free:0,pro:0} },
  {slug:'base64-image-viewer',category:'image',added:'2026-06-23',phase:1,isPro:false,isNew:true,tags:['base64','image','viewer','decode','data-url'],maxFileSizeMB:{free:0,pro:0} },
  {slug:'json-schema-validator',category:'developer',added:'2026-06-22',phase:1,isPro:false,isNew:true,tags:['json','schema','validate','ajv','format'],maxFileSizeMB:{free:0,pro:0} },
  {slug:'svg-viewer',category:'developer',added:'2026-06-22',phase:1,isPro:false,isNew:true,tags:['svg','viewer','preview','code','render'],maxFileSizeMB:{free:0,pro:0} },
  {slug:'meta-tag-generator',category:'seo',also:['developer'],added:'2026-06-23',phase:1,isPro:false,isNew:true,tags:['meta','tag','seo','og','html'],maxFileSizeMB:{free:0,pro:0} },
  {slug:'random-palette-generator',category:'design',added:'2026-06-23',phase:1,isPro:false,isNew:true,tags:['color','palette','random','generate','design'],maxFileSizeMB:{free:0,pro:0} },
  {slug:'csv-viewer',category:'developer',also:['file'],added:'2026-06-22',phase:1,isPro:false,isNew:true,tags:['csv','table','view','spreadsheet','data'],maxFileSizeMB:{free:1,pro:5} },
  {slug:'ascii-art-generator',category:'funny',added:'2026-06-22',phase:1,isPro:false,isNew:true,tags:['ascii','art','text','generator'],maxFileSizeMB:{free:0,pro:0} },
  {slug:'base64-decoder',category:'developer',also:['file'],added:'2026-06-22',phase:1,isPro:false,isNew:true,tags:['base64','decode','encoding'],maxFileSizeMB:{free:0,pro:0} },
  {slug:'base64-encoder',category:'developer',also:['file'],added:'2026-06-22',phase:1,isPro:false,isNew:true,tags:['base64','encode','encoding'],maxFileSizeMB:{free:0,pro:0} },
  {slug:'base64-url-encoder',category:'developer',added:'2026-06-22',phase:1,isPro:false,isNew:true,tags:['base64','url','encoding'],maxFileSizeMB:{free:0,pro:0} },
  {slug:'bracket-matcher',category:'developer',added:'2026-06-22',phase:1,isPro:false,isNew:true,tags:['bracket','parser','syntax'],maxFileSizeMB:{free:0,pro:0} },
  {slug:'caesar-cipher',category:'security',added:'2026-06-22',phase:1,isPro:false,isNew:true,tags:['cipher','encryption','encode'],maxFileSizeMB:{free:0,pro:0} },
  {slug:'checksum-generator',category:'security',added:'2026-06-22',phase:1,isPro:false,isNew:true,tags:['checksum','hash','md5'],maxFileSizeMB:{free:0,pro:0} },
  {slug:'chmod-calculator',category:'developer',added:'2026-06-22',phase:1,isPro:false,isNew:true,tags:['chmod','linux','permissions'],maxFileSizeMB:{free:0,pro:0} },
  {slug:'color-converter',category:'design',added:'2026-06-22',phase:1,isPro:false,isNew:true,tags:['color','convert','hex','hsl'],maxFileSizeMB:{free:0,pro:0} },
  {slug:'color-scheme-generator',category:'design',added:'2026-06-22',phase:1,isPro:false,isNew:true,tags:['color','scheme','palette'],maxFileSizeMB:{free:0,pro:0} },
  {slug:'css-box-model-visualizer',category:'design',also:['developer'],added:'2026-06-22',phase:1,isPro:false,isNew:true,tags:['css','box-model','layout'],maxFileSizeMB:{free:0,pro:0} },
  {slug:'css-flexbox-playground',category:'design',also:['developer'],added:'2026-06-22',phase:1,isPro:false,isNew:true,tags:['css','flexbox','layout'],maxFileSizeMB:{free:0,pro:0} },
  {slug:'curl-builder',category:'developer',added:'2026-06-22',phase:1,isPro:false,isNew:true,tags:['curl','http','api'],maxFileSizeMB:{free:0,pro:0} },
  {slug:'diff-checker',category:'developer',added:'2026-06-22',phase:1,isPro:false,isNew:true,tags:['diff','compare','text'],maxFileSizeMB:{free:0,pro:0} },
  {slug:'git-cheat-sheet',category:'developer',added:'2026-06-22',phase:1,isPro:false,isNew:true,tags:['git','reference','commands'],maxFileSizeMB:{free:0,pro:0} },
  {slug:'hex-dump-viewer',category:'developer',added:'2026-06-22',phase:1,isPro:false,isNew:true,tags:['hex','binary','viewer'],maxFileSizeMB:{free:0,pro:0} },
  {slug:'html-color-picker',category:'design',added:'2026-06-22',phase:1,isPro:false,isNew:true,tags:['color','html','picker'],maxFileSizeMB:{free:0,pro:0} },
  {slug:'html-formatter',category:'developer',added:'2026-06-22',phase:1,isPro:false,isNew:true,tags:['html','format','beautify'],maxFileSizeMB:{free:0,pro:0} },
  {slug:'html-previewer',category:'developer',added:'2026-06-22',phase:1,isPro:false,isNew:true,tags:['html','preview','render'],maxFileSizeMB:{free:0,pro:0} },
  {slug:'html-tag-stripper',category:'developer',added:'2026-06-22',phase:1,isPro:false,isNew:true,tags:['html','strip','text'],maxFileSizeMB:{free:0,pro:0} },
  {slug:'ini-parser',category:'developer',added:'2026-06-22',phase:1,isPro:false,isNew:true,tags:['ini','config','parser'],maxFileSizeMB:{free:0,pro:0} },
  {slug:'json-diff',category:'developer',added:'2026-06-22',phase:1,isPro:false,isNew:true,tags:['json','diff','compare'],maxFileSizeMB:{free:0,pro:0} },
  {slug:'json-path-tester',category:'developer',added:'2026-06-22',phase:1,isPro:false,isNew:true,tags:['json','jsonpath','query'],maxFileSizeMB:{free:0,pro:0} },
  {slug:'json-to-xml',category:'developer',added:'2026-06-22',phase:1,isPro:false,isNew:true,tags:['json','xml','convert'],maxFileSizeMB:{free:0,pro:0} },
  {slug:'json-to-yaml',category:'developer',also:['file'],added:'2026-06-22',phase:1,isPro:false,isNew:true,tags:['json','yaml','convert'],maxFileSizeMB:{free:0,pro:0} },
  {slug:'json-validator',category:'developer',added:'2026-06-22',phase:1,isPro:false,isNew:true,tags:['json','validate','lint'],maxFileSizeMB:{free:0,pro:0} },
  {slug:'jwt-decoder',category:'security',also:['developer'],added:'2026-06-22',phase:1,isPro:false,isNew:true,tags:['jwt','token','decode'],maxFileSizeMB:{free:0,pro:0} },
  {slug:'mime-type-checker',category:'developer',added:'2026-06-22',phase:1,isPro:false,isNew:true,tags:['mime','file','type'],maxFileSizeMB:{free:0,pro:0} },
  {slug:'open-graph-preview',category:'seo',added:'2026-06-22',phase:1,isPro:false,isNew:true,tags:['og','seo','preview'],maxFileSizeMB:{free:0,pro:0} },
  {slug:'pixel-ruler',category:'developer',added:'2026-06-22',phase:1,isPro:false,isNew:true,tags:['pixel','ruler','measure'],maxFileSizeMB:{free:0,pro:0} },
  {slug:'regex-library',category:'developer',added:'2026-06-22',phase:1,isPro:false,isNew:true,tags:['regex','library','reference'],maxFileSizeMB:{free:0,pro:0} },
  {slug:'table-generator',category:'developer',added:'2026-06-22',phase:1,isPro:false,isNew:true,tags:['table','html','generate'],maxFileSizeMB:{free:0,pro:0} },
  {slug:'unix-timestamp',category:'developer',added:'2026-06-22',phase:1,isPro:false,isNew:true,tags:['unix','timestamp','epoch'],maxFileSizeMB:{free:0,pro:0} },
  {slug:'url-analyzer',category:'developer',added:'2026-06-22',phase:1,isPro:false,isNew:true,tags:['url','parse','analyze'],maxFileSizeMB:{free:0,pro:0} },
  {slug:'url-decoder',category:'developer',added:'2026-06-22',phase:1,isPro:false,isNew:true,tags:['url','decode','encoding'],maxFileSizeMB:{free:0,pro:0} },
  {slug:'camel-case-converter',category:'text',added:'2026-06-22',phase:1,isPro:false,isNew:true,tags:['camelcase','convert','text'],maxFileSizeMB:{free:0,pro:0} },
  {slug:'column-extractor',category:'text',added:'2026-06-22',phase:1,isPro:false,isNew:true,tags:['column','extract','text'],maxFileSizeMB:{free:0,pro:0} },
  {slug:'line-sort',category:'text',added:'2026-06-22',phase:1,isPro:false,isNew:true,tags:['sort','lines','text'],maxFileSizeMB:{free:0,pro:0} },
  {slug:'list-deduplicator',category:'text',added:'2026-06-22',phase:1,isPro:false,isNew:true,tags:['deduplicate','list','unique'],maxFileSizeMB:{free:0,pro:0} },
  {slug:'markdown-editor',category:'text',also:['developer'],added:'2026-06-22',phase:1,isPro:false,isNew:true,tags:['markdown','editor','preview'],maxFileSizeMB:{free:0,pro:0} },
  {slug:'markdown-preview',category:'text',also:['developer'],added:'2026-06-22',phase:1,isPro:false,isNew:true,tags:['markdown','preview','render'],maxFileSizeMB:{free:0,pro:0} },
  {slug:'reading-time-calculator',category:'text',added:'2026-06-22',phase:1,isPro:false,isNew:true,tags:['reading','time','estimate'],maxFileSizeMB:{free:0,pro:0} },
  {slug:'slug-to-title',category:'seo',added:'2026-06-22',phase:1,isPro:false,isNew:true,tags:['slug','title','convert'],maxFileSizeMB:{free:0,pro:0} },
  {slug:'text-line-numberer',category:'text',added:'2026-06-22',phase:1,isPro:false,isNew:true,tags:['line','number','text'],maxFileSizeMB:{free:0,pro:0} },
  {slug:'text-padder',category:'text',added:'2026-06-22',phase:1,isPro:false,isNew:true,tags:['pad','align','text'],maxFileSizeMB:{free:0,pro:0} },
  {slug:'text-reverser',category:'text',added:'2026-06-22',phase:1,isPro:false,isNew:true,tags:['reverse','text','flip'],maxFileSizeMB:{free:0,pro:0} },
  {slug:'text-rotate',category:'text',added:'2026-06-22',phase:1,isPro:false,isNew:true,tags:['rotate','text','flip'],maxFileSizeMB:{free:0,pro:0} },
  {slug:'text-sort-by-length',category:'text',added:'2026-06-22',phase:1,isPro:false,isNew:true,tags:['sort','length','text'],maxFileSizeMB:{free:0,pro:0} },
  {slug:'text-truncator',category:'text',added:'2026-06-22',phase:1,isPro:false,isNew:true,tags:['truncate','trim','text'],maxFileSizeMB:{free:0,pro:0} },
  {slug:'word-cloud-generator',category:'text',added:'2026-06-22',phase:1,isPro:false,isNew:true,tags:['word-cloud','visualize','text'],maxFileSizeMB:{free:0,pro:0} },
  {slug:'word-wrap',category:'text',added:'2026-06-22',phase:1,isPro:false,isNew:true,tags:['wrap','text','format'],maxFileSizeMB:{free:0,pro:0} },
  {slug:'habit-tracker',category:'utility',added:'2026-06-22',phase:1,isPro:false,isNew:true,tags:['habit','tracker','productivity'],maxFileSizeMB:{free:0,pro:0} },
  {slug:'keyboard-shortcut-tester',category:'utility',added:'2026-06-22',phase:1,isPro:false,isNew:true,tags:['keyboard','shortcut','test'],maxFileSizeMB:{free:0,pro:0} },
  {slug:'number-palindrome',category:'utility',added:'2026-06-22',phase:1,isPro:false,isNew:true,tags:['palindrome','number','check'],maxFileSizeMB:{free:0,pro:0} },
  {slug:'number-sequence-generator',category:'utility',added:'2026-06-22',phase:1,isPro:false,isNew:true,tags:['sequence','number','generate'],maxFileSizeMB:{free:0,pro:0} },
  {slug:'password-generator',category:'security',added:'2026-06-22',phase:1,isPro:false,isNew:true,tags:['password','generate','secure'],maxFileSizeMB:{free:0,pro:0} },
  {slug:'pdf-to-text',category:'pdf',added:'2026-06-22',phase:1,isPro:false,isNew:true,tags:['pdf','text','extract'],maxFileSizeMB:{free:0,pro:0} },
  {slug:'qr-generator',category:'qr',added:'2026-06-22',phase:1,isPro:false,isNew:true,tags:['qr','code','generate'],maxFileSizeMB:{free:0,pro:0} },
  {slug:'speech-to-text',category:'utility',added:'2026-06-22',phase:1,isPro:false,isNew:true,tags:['speech','voice','transcribe'],maxFileSizeMB:{free:0,pro:0} },
  {slug:'color-palette-extractor',category:'image',also:['design'],added:'2026-06-22',phase:1,isPro:false,isNew:true,tags:['color','palette','extract'],maxFileSizeMB:{free:0,pro:0} },
  {slug:'image-color-picker',category:'image',also:['design'],added:'2026-06-22',phase:1,isPro:false,isNew:true,tags:['color','picker','image'],maxFileSizeMB:{free:0,pro:0} },
  {slug:'image-compress',category:'image',added:'2026-06-22',phase:1,isPro:false,isNew:true,tags:['image','compress','optimize'],maxFileSizeMB:{free:0,pro:0} },
  {slug:'image-crop',category:'image',added:'2026-06-22',phase:1,isPro:false,isNew:true,tags:['image','crop','edit'],maxFileSizeMB:{free:0,pro:0} },
  {slug:'jpg-to-png',category:'image',added:'2026-06-22',phase:1,isPro:false,isNew:true,tags:['jpg','png','convert'],maxFileSizeMB:{free:0,pro:0} },
  {slug:'png-to-jpg',category:'image',added:'2026-06-22',phase:1,isPro:false,isNew:true,tags:['png','jpg','convert'],maxFileSizeMB:{free:0,pro:0} },
  {slug:'svg-to-png',category:'image',added:'2026-06-22',phase:1,isPro:false,isNew:true,tags:['svg','png','convert'],maxFileSizeMB:{free:0,pro:0} },
]

export function getToolBySlug(slug: string): ToolMeta | undefined {
  return TOOLS.find((t) => t.slug === slug)
}

export function getToolsByCategory(category: ToolCategory): ToolMeta[] {
  return TOOLS.filter((t) => t.category === category || t.also?.includes(category))
}

export function getToolsByPhase(phase: Phase): ToolMeta[] {
  return TOOLS.filter((t) => t.phase === phase)
}

export function getAllTools(): ToolMeta[] {
  return TOOLS
}

// Ordered by general search demand (with our coverage sanity-checked), not by
// our own tool count. Switch to a data-driven order once GA4/toolStats traffic
// accumulates. `file` is empty and sits last.
export const CATEGORY_META: Record<ToolCategory, { label: string; icon: string; color: string }> = {
  // U+FE0F forces emoji (color) presentation — without it this glyph defaults
  // to a monochrome/text picture and looked grey next to the other icons.
  image:     { label: 'Image',     icon: String.fromCodePoint(0x1F5BC, 0xFE0F), color: 'purple' },
  pdf:       { label: 'PDF',       icon: String.fromCodePoint(0x1F4C4), color: 'red'    },
  finance:   { label: 'Finance',      icon: String.fromCodePoint(0x1F4B0), color: 'emerald' },
  text:      { label: 'Text',      icon: String.fromCodePoint(0x1F4DD), color: 'green'  },
  developer: { label: 'Developer', icon: String.fromCodePoint(0x1F4BB), color: 'blue'   },
  seo:       { label: 'SEO',          icon: String.fromCodePoint(0x1F50D), color: 'sky'     },
  qr:        { label: 'QR & Barcode', icon: String.fromCodePoint(0x1F533), color: 'slate'   },
  design:    { label: 'Color & Design', icon: String.fromCodePoint(0x1F3A8), color: 'fuchsia' },
  health:    { label: 'Health',       icon: String.fromCodePoint(0x1FA7A), color: 'lime'    },
  security:  { label: 'Security',     icon: String.fromCodePoint(0x1F512), color: 'rose'    },
  utility:   { label: 'Utility',   icon: String.fromCodePoint(0x1F527), color: 'teal'   },
  language:  { label: 'Language',     icon: String.fromCodePoint(0x1F310), color: 'cyan'    },
  video:     { label: 'Video',     icon: String.fromCodePoint(0x1F3AC), color: 'pink'   },
  audio:     { label: 'Audio',     icon: String.fromCodePoint(0x1F50A), color: 'yellow' },
  funny:     { label: 'Funny',     icon: String.fromCodePoint(0x1F602), color: 'amber'  },
  game:      { label: 'Game',      icon: String.fromCodePoint(0x1F3AE), color: 'indigo' },
  file:      { label: 'File',      icon: String.fromCodePoint(0x1F4C1), color: 'orange' },
  classics:  { label: 'Classics',  icon: String.fromCodePoint(0x1F4DC), color: 'amber'  },
  random:    { label: 'Random',    icon: String.fromCodePoint(0x1F3B2), color: 'violet' },
  science:   { label: 'Science',   icon: String.fromCodePoint(0x1F9EA), color: 'teal'   },
  time:      { label: 'Time',      icon: String.fromCodePoint(0x23F0), color: 'sky'    },
  device:    { label: 'Device Test', icon: String.fromCodePoint(0x1F5A5, 0xFE0F), color: 'slate' },
  world:     { label: 'World',      icon: String.fromCodePoint(0x1F30F), color: 'cyan' },
  social:    { label: 'Social',     icon: String.fromCodePoint(0x1F4F1), color: 'pink' },
};