// 삼국지 퀴즈 — 입문 30 (승인 목록 1–30). c[0]이 정답 (플레이 시 셔플).
import type { TKQuizQ } from './threeKingdomsQuiz'

const N = (ko: string, ja: string, en: string) => ({ ko, ja, en })

export const QUIZ_EASY: TKQuizQ[] = [
  { id: 'e1', q: N('연의에서 유비·관우·장비가 의형제를 맺은 곳은?', '演義で劉備・関羽・張飛が義兄弟の契りを結んだ場所は？', 'In the novel, where do Liu Bei, Guan Yu and Zhang Fei swear brotherhood?'),
    c: [N('복숭아밭', '桃園', 'A peach orchard'), N('대나무숲', '竹林', 'A bamboo grove'), N('배나무밭', '梨園', 'A pear orchard'), N('소나무숲', '松林', 'A pine forest')],
    expl: N('도원결의 — 연의 1회의 첫 장면으로, 정사에는 없는 창작이에요.', '桃園の誓い — 演義第1回の冒頭場面で、正史にはない創作です。', 'The Peach Garden Oath opens the novel — an invention absent from the histories.'),
    link: { type: 'idiom', slug: 'dowongyeorui' } },
  { id: 'e2', q: N('제갈량의 자(字)는?', '諸葛亮の字（あざな）は？', 'What is Zhuge Liang’s courtesy name?'),
    c: [N('공명', '孔明', 'Kongming'), N('중달', '仲達', 'Zhongda'), N('맹덕', '孟徳', 'Mengde'), N('현덕', '玄徳', 'Xuande')],
    expl: N('제갈공명의 공명이 자예요. 중달은 사마의, 맹덕은 조조, 현덕은 유비의 자입니다.', '諸葛孔明の孔明が字です。仲達は司馬懿、孟徳は曹操、玄徳は劉備の字。', 'Kongming is his courtesy name; Zhongda is Sima Yi’s, Mengde Cao Cao’s, Xuande Liu Bei’s.'),
    link: { type: 'char', slug: 'zhuge-liang' } },
  { id: 'e3', q: N('유비가 제갈량을 얻으려 세 번 찾아간 고사는?', '劉備が諸葛亮を得るため三度訪ねた故事は？', 'Which idiom describes Liu Bei’s three visits to recruit Zhuge Liang?'),
    c: [N('삼고초려', '三顧の礼', 'Three visits to the cottage'), N('읍참마속', '泣いて馬謖を斬る', 'Executing Ma Su in tears'), N('괄목상대', '刮目相待', 'Rub your eyes and look again'), N('파죽지세', '破竹の勢い', 'Splitting bamboo')],
    expl: N('세 번째 방문에서야 만난 정성이 천하삼분지계로 이어졌어요.', '三度目の訪問でようやく会えた誠意が天下三分の計につながりました。', 'The third visit won him the man — and the plan to divide the realm in three.'),
    link: { type: 'idiom', slug: 'samgochoryeo' } },
  { id: 'e4', q: N('적벽대전에서 연합군이 쓴 결정적 전술은?', '赤壁の戦いで連合軍が使った決定的戦術は？', 'What tactic decided the Battle of Red Cliffs?'),
    c: [N('화공', '火攻め', 'Fire attack'), N('수공', '水攻め', 'Flooding'), N('매복', '伏兵', 'Ambush'), N('장기 포위', '長期包囲', 'Prolonged siege')],
    expl: N('황개의 거짓 항복과 불배가 쇠사슬로 묶인 조조 함대를 태웠어요.', '黄蓋の偽降と火船が、鎖で繋がれた曹操の艦隊を焼きました。', 'Huang Gai’s fake surrender and fire ships burned Cao Cao’s chained fleet.'),
    link: { type: 'battle', slug: 'red-cliffs' } },
  { id: 'e5', q: N('"삼국"에 해당하는 세 나라는?', '「三国」に当たる三つの国は？', 'Which three kingdoms give the era its name?'),
    c: [N('위·촉·오', '魏・蜀・呉', 'Wei, Shu and Wu'), N('위·촉·연', '魏・蜀・燕', 'Wei, Shu and Yan'), N('진·한·초', '秦・漢・楚', 'Qin, Han and Chu'), N('위·오·월', '魏・呉・越', 'Wei, Wu and Yue')],
    expl: N('조씨의 위, 유씨의 촉한, 손씨의 오가 정립했어요.', '曹氏の魏、劉氏の蜀漢、孫氏の呉が鼎立しました。', 'The Cao family’s Wei, the Liu family’s Shu-Han and the Sun family’s Wu.') },
  { id: 'e6', q: N('조조가 기틀을 놓은 나라는?', '曹操が礎を築いた国は？', 'Which kingdom did Cao Cao found in all but name?'),
    c: [N('위', '魏', 'Wei'), N('촉', '蜀', 'Shu'), N('오', '呉', 'Wu'), N('진(晉)', '晋', 'Jin')],
    expl: N('제위는 아들 조비가 받았지만 위나라의 실질적 창업자는 조조예요.', '帝位は息子の曹丕が受けましたが、魏の実質的な創業者は曹操です。', 'His son Cao Pi took the throne, but Wei was Cao Cao’s creation.'),
    link: { type: 'char', slug: 'cao-cao' } },
  { id: 'e7', q: N('손권이 다스린 나라는?', '孫権が治めた国は？', 'Which kingdom did Sun Quan rule?'),
    c: [N('오', '呉', 'Wu'), N('위', '魏', 'Wei'), N('촉', '蜀', 'Shu'), N('연', '燕', 'Yan')],
    expl: N('강동의 오 — 삼국 중 가장 오래(280년까지) 버틴 나라예요.', '江東の呉 — 三国で最も長く（280年まで）持ちこたえた国です。', 'Wu of the Southland — the longest-lived of the three, surviving to 280.'),
    link: { type: 'char', slug: 'sun-quan' } },
  { id: 'e8', q: N('여포가 탔다고 전하는 명마는?', '呂布が乗ったと伝わる名馬は？', 'What was the name of Lü Bu’s famous horse?'),
    c: [N('적토마', '赤兎馬', 'Red Hare'), N('적로', '的盧', 'Dilu'), N('절영', '絶影', 'Jueying'), N('조황비전', '爪黄飛電', 'Claw Yellow Lightning')],
    expl: N('"사람 중엔 여포, 말 중엔 적토"라는 말이 남아 있어요.', '「人中の呂布、馬中の赤兎」という言葉が残っています。', '"Among men, Lü Bu; among horses, Red Hare," ran the saying.'),
    link: { type: 'char', slug: 'lv-bu' } },
  { id: 'e9', q: N('소설 삼국지연의의 저자는?', '小説『三国志演義』の著者は？', 'Who wrote the Romance of the Three Kingdoms?'),
    c: [N('나관중', '羅貫中', 'Luo Guanzhong'), N('진수', '陳寿', 'Chen Shou'), N('사마천', '司馬遷', 'Sima Qian'), N('배송지', '裴松之', 'Pei Songzhi')],
    expl: N('진수는 정사 삼국지의 저자, 배송지는 그 주석자예요.', '陳寿は正史『三国志』の著者、裴松之はその注釈者です。', 'Chen Shou wrote the official histories; Pei Songzhi annotated them.') },
  { id: 'e10', q: N('황건적의 난을 이끈 지도자는?', '黄巾の乱を率いた指導者は？', 'Who led the Yellow Turban Rebellion?'),
    c: [N('장각', '張角', 'Zhang Jiao'), N('동탁', '董卓', 'Dong Zhuo'), N('원소', '袁紹', 'Yuan Shao'), N('장로', '張魯', 'Zhang Lu')],
    expl: N('태평도 교주 장각의 봉기가 삼국시대의 막을 열었어요.', '太平道の教主・張角の蜂起が三国時代の幕を開けました。', 'The rising of the Taiping sect leader opened the era.'),
    link: { type: 'char', slug: 'zhang-jiao' } },
  { id: 'e11', q: N('제갈량이 북벌 전 황제에게 올린 글은?', '諸葛亮が北伐の前に皇帝へ奉った文章は？', 'What did Zhuge Liang submit to the throne before marching north?'),
    c: [N('출사표', '出師の表', 'The Chu Shi Biao'), N('계자서', '誡子書', 'The Admonition to My Son'), N('구현령', '求賢令', 'The Seek-the-Worthy Edict'), N('단가행', '短歌行', 'The Short Song')],
    expl: N('"읽고 울지 않으면 충신이 아니다"라는 평을 들은 명문이에요.', '「読んで泣かぬ者は忠臣にあらず」と評された名文です。', 'The memorial no loyal heart, it was said, could read dry-eyed.'),
    link: { type: 'idiom', slug: 'chulsapyo' } },
  { id: 'e12', q: N('장비가 홀로 조조군을 막아선 곳은?', '張飛が単身で曹操軍を止めた場所は？', 'Where did Zhang Fei single-handedly halt Cao Cao’s pursuit?'),
    c: [N('장판교', '長坂橋', 'Changban Bridge'), N('호로관', '虎牢関', 'Hulao Gate'), N('오장원', '五丈原', 'Wuzhang Plains'), N('가정', '街亭', 'Jieting')],
    expl: N('"내가 장익덕이다"라는 일갈은 정사에도 기록된 실화예요.', '「身はこれ張益徳なり」の一喝は正史にも記録された実話です。', 'His roar — "I am Zhang Yide!" — is in the official record.'),
    link: { type: 'battle', slug: 'changban' } },
  { id: 'e13', q: N('장판파에서 조운이 품에 안고 구출한 인물은?', '長坂で趙雲が懐に抱いて救出した人物は？', 'Whom did Zhao Yun carry to safety at Changban?'),
    c: [N('유선(아두)', '劉禅（阿斗）', 'Liu Shan (A-Dou)'), N('관평', '関平', 'Guan Ping'), N('유봉', '劉封', 'Liu Feng'), N('조앙', '曹昂', 'Cao Ang')],
    expl: N('갓난 아들 유선을 구한 이 활약으로 조운은 전설이 되었어요.', '乳飲み子の劉禅を救ったこの活躍で趙雲は伝説になりました。', 'Rescuing the infant heir made Zhao Yun a legend.'),
    link: { type: 'char', slug: 'zhao-yun' } },
  { id: 'e14', q: N('눈물을 흘리며 마속을 벤 사람은?', '涙を流しながら馬謖を斬った人は？', 'Who executed Ma Su in tears?'),
    c: [N('제갈량', '諸葛亮', 'Zhuge Liang'), N('유비', '劉備', 'Liu Bei'), N('조조', '曹操', 'Cao Cao'), N('강유', '姜維', 'Jiang Wei')],
    expl: N('가정 패전의 책임을 물어 아끼던 마속을 군법대로 처형했어요.', '街亭敗戦の責任を問い、目をかけていた馬謖を軍法どおり処刑しました。', 'After Jieting he applied military law to the protégé he loved.'),
    link: { type: 'idiom', slug: 'eupchammasok' } },
  { id: 'e15', q: N('적벽대전에서 손유 연합군을 총지휘한 사람은?', '赤壁の戦いで孫劉連合軍を総指揮した人は？', 'Who commanded the allied forces at Red Cliffs?'),
    c: [N('주유', '周瑜', 'Zhou Yu'), N('노숙', '魯粛', 'Lu Su'), N('제갈량', '諸葛亮', 'Zhuge Liang'), N('손권', '孫権', 'Sun Quan')],
    expl: N('정사 기준 적벽의 주역은 주유예요 — 제갈량의 동남풍은 연의의 창작입니다.', '正史基準で赤壁の主役は周瑜です — 諸葛亮の東南の風は演義の創作。', 'In the histories the hero of Red Cliffs is Zhou Yu; the summoned wind is fiction.'),
    link: { type: 'char', slug: 'zhou-yu' } },
  { id: 'e16', q: N('도원결의 삼형제 중 맏이는?', '桃園の三兄弟の長兄は？', 'Who was the eldest of the three sworn brothers?'),
    c: [N('유비', '劉備', 'Liu Bei'), N('관우', '関羽', 'Guan Yu'), N('장비', '張飛', 'Zhang Fei'), N('조운', '趙雲', 'Zhao Yun')],
    expl: N('유비-관우-장비 순의 의형제로, 조운은 결의 멤버가 아니에요.', '劉備-関羽-張飛の順の義兄弟で、趙雲は誓いのメンバーではありません。', 'Liu Bei, then Guan Yu, then Zhang Fei — Zhao Yun was never part of the oath.'),
    link: { type: 'char', slug: 'liu-bei' } },
  { id: 'e17', q: N('헌제의 선양을 받아 위나라 황제가 된 인물은?', '献帝の禅譲を受けて魏の皇帝になった人物は？', 'Who accepted Emperor Xian’s abdication to become emperor of Wei?'),
    c: [N('조비', '曹丕', 'Cao Pi'), N('조조', '曹操', 'Cao Cao'), N('조식', '曹植', 'Cao Zhi'), N('사마염', '司馬炎', 'Sima Yan')],
    expl: N('조조는 왕에 그쳤고, 아들 조비가 220년 한을 대신했어요.', '曹操は王にとどまり、息子の曹丕が220年に漢に取って代わりました。', 'Cao Cao stopped at king; his son ended the Han in 220.'),
    link: { type: 'char', slug: 'cao-pi' } },
  { id: 'e18', q: N('삼국을 최종 통일한 왕조는?', '三国を最終的に統一した王朝は？', 'Which dynasty finally reunified the realm?'),
    c: [N('진(晉)', '晋', 'Jin'), N('위', '魏', 'Wei'), N('오', '呉', 'Wu'), N('한', '漢', 'Han')],
    expl: N('사마씨의 진이 263년 촉, 265년 위, 280년 오를 차례로 정리했어요.', '司馬氏の晋が263年に蜀、265年に魏、280年に呉を順に整理しました。', 'The Sima family’s Jin absorbed Shu (263), Wei (265) and Wu (280) in turn.'),
    link: { type: 'battle', slug: 'conquest-of-wu' } },
  { id: 'e19', q: N('연의에서 초선이 이간질한 두 사람은?', '演義で貂蟬が仲を裂いた二人は？', 'Whom does Diao Chan set against each other in the novel?'),
    c: [N('동탁과 여포', '董卓と呂布', 'Dong Zhuo and Lü Bu'), N('조조와 원소', '曹操と袁紹', 'Cao Cao and Yuan Shao'), N('유비와 손권', '劉備と孫権', 'Liu Bei and Sun Quan'), N('원소와 원술', '袁紹と袁術', 'Yuan Shao and Yuan Shu')],
    expl: N('연환계 — 초선 자체가 연의의 창작 인물이에요.', '連環の計 — 貂蟬自体が演義の創作人物です。', 'The interlocking scheme — Diao Chan herself is the novel’s invention.'),
    link: { type: 'char', slug: 'diao-chan' } },
  { id: 'e20', q: N('"와룡(누운 용)"이라 불린 인물은?', '「臥龍」と呼ばれた人物は？', 'Who was known as the "Sleeping Dragon"?'),
    c: [N('제갈량', '諸葛亮', 'Zhuge Liang'), N('방통', '龐統', 'Pang Tong'), N('사마의', '司馬懿', 'Sima Yi'), N('강유', '姜維', 'Jiang Wei')],
    expl: N('방통은 봉추(봉황 새끼) — 와룡·봉추 중 하나만 얻어도 천하를 안정시킨다 했죠.', '龐統は鳳雛 — 臥龍・鳳雛のどちらか一人を得れば天下を安んじられると言われました。', 'Pang Tong was the "Fledgling Phoenix" — win either, the saying went, and the realm is yours.'),
    link: { type: 'char', slug: 'zhuge-liang' } },
  { id: 'e21', q: N('고사성어 "계륵"의 뜻은?', '故事成語「鶏肋」の意味は？', 'What does the idiom "chicken ribs" mean?'),
    c: [N('버리긴 아깝지만 큰 쓸모는 없는 것', '捨てるには惜しいが大した役に立たないもの', 'Too good to discard, too little to use'), N('아주 귀한 보물', '非常に貴重な宝物', 'A priceless treasure'), N('매우 위험한 상황', '非常に危険な状況', 'A very dangerous situation'), N('겉과 속이 다른 사람', '表裏のある人', 'A two-faced person')],
    expl: N('한중 철수를 앞둔 조조의 암구호에서 나온 말이에요.', '漢中撤退を前にした曹操の合言葉から生まれた言葉です。', 'From Cao Cao’s watchword before withdrawing from Hanzhong.'),
    link: { type: 'idiom', slug: 'gyereuk' } },
  { id: 'e22', q: N('괄목상대 고사의 주인공은?', '刮目相待の故事の主人公は？', 'Who is the hero of the "rub your eyes" idiom?'),
    c: [N('여몽', '呂蒙', 'Lü Meng'), N('육손', '陸遜', 'Lu Xun'), N('감녕', '甘寧', 'Gan Ning'), N('태사자', '太史慈', 'Taishi Ci')],
    expl: N('손권의 권유로 공부해 노숙을 놀라게 한 그 여몽이에요.', '孫権の勧めで学び、魯粛を驚かせたあの呂蒙です。', 'The general whose studies, urged by Sun Quan, stunned Lu Su.'),
    link: { type: 'idiom', slug: 'gwalmoksangdae' } },
  { id: 'e23', q: N('"백미(흰 눈썹)" 고사의 주인공은?', '「白眉」の故事の主人公は？', 'Whose white eyebrows gave us the idiom for "the finest"?'),
    c: [N('마량', '馬良', 'Ma Liang'), N('마속', '馬謖', 'Ma Su'), N('마초', '馬超', 'Ma Chao'), N('마등', '馬騰', 'Ma Teng')],
    expl: N('마씨 오형제 중 흰 눈썹의 마량이 가장 뛰어났다는 데서 나왔어요.', '馬氏五兄弟のうち白い眉の馬良が最も優れていたことに由来します。', 'Of the five Ma brothers, the white-browed Ma Liang was the finest.'),
    link: { type: 'idiom', slug: 'baekmi' } },
  { id: 'e24', q: N('삼국시대의 막을 연 사건은?', '三国時代の幕を開けた出来事は？', 'Which event opened the Three Kingdoms era?'),
    c: [N('황건적의 난', '黄巾の乱', 'The Yellow Turban Rebellion'), N('동탁의 낙양 입성', '董卓の洛陽入り', 'Dong Zhuo entering Luoyang'), N('적벽대전', '赤壁の戦い', 'The Battle of Red Cliffs'), N('관도대전', '官渡の戦い', 'The Battle of Guandu')],
    expl: N('184년의 대봉기가 지방 무장을 허용시켜 군웅의 시대를 낳았어요.', '184年の大蜂起が地方の武装を許し、群雄の時代を生みました。', 'The rising of 184 legalized local armies — and bred the warlords.'),
    link: { type: 'battle', slug: 'yellow-turban' } },
  { id: 'e25', q: N('유비의 자(字)는?', '劉備の字は？', 'What is Liu Bei’s courtesy name?'),
    c: [N('현덕', '玄徳', 'Xuande'), N('맹덕', '孟徳', 'Mengde'), N('중모', '仲謀', 'Zhongmou'), N('운장', '雲長', 'Yunchang')],
    expl: N('맹덕은 조조, 중모는 손권, 운장은 관우의 자예요.', '孟徳は曹操、仲謀は孫権、雲長は関羽の字です。', 'Mengde is Cao Cao, Zhongmou Sun Quan, Yunchang Guan Yu.'),
    link: { type: 'char', slug: 'liu-bei' } },
  { id: 'e26', q: N('조조의 자(字)는?', '曹操の字は？', 'What is Cao Cao’s courtesy name?'),
    c: [N('맹덕', '孟徳', 'Mengde'), N('현덕', '玄徳', 'Xuande'), N('공근', '公瑾', 'Gongjin'), N('봉선', '奉先', 'Fengxian')],
    expl: N('공근은 주유, 봉선은 여포의 자예요.', '公瑾は周瑜、奉先は呂布の字です。', 'Gongjin is Zhou Yu’s courtesy name, Fengxian Lü Bu’s.'),
    link: { type: 'char', slug: 'cao-cao' } },
  { id: 'e27', q: N('관우가 조조 진영에 있을 때 벤 원소군의 대장은?', '関羽が曹操陣営にいたとき斬った袁紹軍の大将は？', 'Which Yuan Shao general did Guan Yu slay while serving Cao Cao?'),
    c: [N('안량', '顔良', 'Yan Liang'), N('문추', '文醜', 'Wen Chou'), N('화웅', '華雄', 'Hua Xiong'), N('장합', '張郃', 'Zhang He')],
    expl: N('백마 전투의 일격 — 정사 기준 관우의 확실한 전공은 안량뿐이에요.', '白馬の戦いの一撃 — 正史基準で関羽の確実な戦功は顔良のみです。', 'The stroke at Baima — in the histories, Yan Liang is Guan Yu’s one confirmed kill.'),
    link: { type: 'battle', slug: 'guandu' } },
  { id: 'e28', q: N('제갈량이 진중에서 병사한 곳은?', '諸葛亮が陣中で病没した場所は？', 'Where did Zhuge Liang die on campaign?'),
    c: [N('오장원', '五丈原', 'Wuzhang Plains'), N('백제성', '白帝城', 'Baidicheng'), N('가정', '街亭', 'Jieting'), N('성도', '成都', 'Chengdu')],
    expl: N('사마의와 백여 일 대치하던 234년, 쉰넷의 나이였어요.', '司馬懿と百余日対峙していた234年、五十四歳でした。', 'In 234, aged fifty-four, a hundred days into the standoff with Sima Yi.'),
    link: { type: 'battle', slug: 'wuzhang-plains' } },
  { id: 'e29', q: N('유비가 황제에 오르며 세운 나라의 이름은?', '劉備が皇帝に即位して建てた国の名は？', 'What was the name of the state Liu Bei founded as emperor?'),
    c: [N('촉한', '蜀漢', 'Shu-Han'), N('서촉', '西蜀', 'Western Shu'), N('대한', '大漢', 'Great Han'), N('파촉', '巴蜀', 'Ba-Shu')],
    expl: N('한의 정통 계승을 내걸었기에 정식 국호는 "한"이고, 촉한으로 통칭돼요.', '漢の正統継承を掲げたため正式な国号は「漢」で、蜀漢と通称されます。', 'Claiming the Han succession, its formal name was simply "Han" — Shu-Han by convention.'),
    link: { type: 'char', slug: 'liu-bei' } },
  { id: 'e30', q: N('"치세의 능신, 난세의 간웅"이라는 평을 들은 인물은?', '「治世の能臣、乱世の姦雄」と評された人物は？', 'Who was judged "an able minister in peace, a cunning hero in chaos"?'),
    c: [N('조조', '曹操', 'Cao Cao'), N('유비', '劉備', 'Liu Bei'), N('동탁', '董卓', 'Dong Zhuo'), N('사마의', '司馬懿', 'Sima Yi')],
    expl: N('월단평의 허소가 무명 시절의 조조에게 내린 인물평이에요.', '月旦評の許劭が無名時代の曹操に下した人物評です。', 'The verdict of the critic Xu Shao on a young, obscure Cao Cao.'),
    link: { type: 'quote', slug: 'xushao-hero-chaos' } },
]
