// 삼국지 퀴즈 — 고수 30 (승인 목록 61–90). c[0]이 정답. 정사·주석 기준 명시형.
import type { TKQuizQ } from './threeKingdomsQuiz'

const N = (ko: string, ja: string, en: string) => ({ ko, ja, en })

export const QUIZ_HARD: TKQuizQ[] = [
  { id: 'h1', q: N('정사 기준, 동탁군의 화웅을 벤 인물은?', '正史基準で董卓軍の華雄を斬った人物は？', 'In the histories, who actually slew Hua Xiong?'),
    c: [N('손견', '孫堅', 'Sun Jian'), N('관우', '関羽', 'Guan Yu'), N('조조', '曹操', 'Cao Cao'), N('원소', '袁紹', 'Yuan Shao')],
    expl: N('"술이 식기 전에" 벤 관우의 명장면은 연의의 창작이에요.', '「酒が冷める前に」斬った関羽の名場面は演義の創作です。', 'Guan Yu’s warm-wine beheading is the novel’s invention.'),
    link: { type: 'battle', slug: 'hulao-gate' } },
  { id: 'h2', q: N('정사 삼국지에 방대한 주석을 단 남조의 사학자는?', '正史『三国志』に膨大な注を付けた南朝の史学者は？', 'Who wrote the great annotations to the official histories?'),
    c: [N('배송지', '裴松之', 'Pei Songzhi'), N('진수', '陳寿', 'Chen Shou'), N('습착치', '習鑿歯', 'Xi Zuochi'), N('범엽', '范曄', 'Fan Ye')],
    expl: N('강표전·한진춘추 같은 사서를 인용해 정사를 보강했어요.', '江表伝・漢晋春秋などの史書を引用して正史を補強しました。', 'His notes preserve sources like the Jiangbiao Zhuan and Han Jin Chunqiu.') },
  { id: 'h3', q: N('괄목상대·수불석권이 인용된 사서는?', '刮目相待・手不釈巻が引用された史書は？', 'Which source preserves the "rub your eyes" and "book in hand" stories?'),
    c: [N('강표전', '江表伝', 'Jiangbiao Zhuan'), N('한진춘추', '漢晋春秋', 'Han Jin Chunqiu'), N('위략', '魏略', 'Wei Lüe'), N('오력', '呉暦', 'Wu Li')],
    expl: N('여몽전 배송지주가 인용한 강동의 기록이에요.', '呂蒙伝の裴松之注が引用した江東の記録です。', 'Quoted in the annotations to Lü Meng’s biography.'),
    link: { type: 'idiom', slug: 'gwalmoksangdae' } },
  { id: 'h4', q: N('정사 기준, 단도부회(익양 대치 담판)의 주인공은?', '正史基準で単刀赴会（益陽対峙の談判）の主人公は？', 'In the histories, whose parley was the "single blade" meeting?'),
    c: [N('노숙', '魯粛', 'Lu Su'), N('관우', '関羽', 'Guan Yu'), N('여몽', '呂蒙', 'Lü Meng'), N('제갈근', '諸葛瑾', 'Zhuge Jin')],
    expl: N('연의가 관우 시점으로 뒤집은 대표 사례예요.', '演義が関羽視点にひっくり返した代表例です。', 'The classic case of the novel flipping the scene to Guan Yu’s side.'),
    link: { type: 'idiom', slug: 'dandobuhoe' } },
  { id: 'h5', q: N('"자룡은 온몸이 담덩어리"라고 말한 사람은?', '「子龍は一身これ胆なり」と言った人は？', 'Who declared "Zilong is courage from head to foot"?'),
    c: [N('유비', '劉備', 'Liu Bei'), N('제갈량', '諸葛亮', 'Zhuge Liang'), N('관우', '関羽', 'Guan Yu'), N('조조', '曹操', 'Cao Cao')],
    expl: N('한수의 공영계 다음 날, 전장을 둘러본 유비의 감탄이에요.', '漢水の空営の計の翌日、戦場を見回った劉備の感嘆です。', 'Liu Bei’s verdict, touring the field after the empty-camp stand at the Han River.'),
    link: { type: 'quote', slug: 'zhaoyun-courage' } },
  { id: 'h6', q: N('정군산에서 하후연을 잡는 계책을 지휘한 유비의 참모는?', '定軍山で夏侯淵を討つ策を指揮した劉備の参謀は？', 'Which adviser directed the stratagem that killed Xiahou Yuan?'),
    c: [N('법정', '法正', 'Fa Zheng'), N('제갈량', '諸葛亮', 'Zhuge Liang'), N('방통', '龐統', 'Pang Tong'), N('마량', '馬良', 'Ma Liang')],
    expl: N('조조도 "필시 누가 가르쳐 줬을 것"이라 했다는 한중전의 숨은 주역이에요.', '曹操も「きっと誰かに教わったのだ」と言ったという漢中戦の陰の主役です。', 'Even Cao Cao guessed someone else had authored the plan — Fa Zheng had.'),
    link: { type: 'char', slug: 'fa-zheng' } },
  { id: 'h7', q: N('가정 참패 속에서 유일하게 부대를 보전해 돌아온 부장은?', '街亭の惨敗の中、唯一部隊を保全して帰った副将は？', 'Who alone brought his unit home intact from Jieting?'),
    c: [N('왕평', '王平', 'Wang Ping'), N('마대', '馬岱', 'Ma Dai'), N('위연', '魏延', 'Wei Yan'), N('요화', '廖化', 'Liao Hua')],
    expl: N('북을 울리며 버텨 장합의 추격을 막았고, 이 공으로 발탁되었어요.', '太鼓を鳴らして持ちこたえ、張郃の追撃を防ぎ、この功で抜擢されました。', 'His drums and composure checked Zhang He — and made his career.'),
    link: { type: 'char', slug: 'wang-ping' } },
  { id: 'h8', q: N('위연이 북벌에서 거듭 진언한 기습 계책은?', '魏延が北伐で繰り返し進言した奇襲策は？', 'What bold strike did Wei Yan keep proposing?'),
    c: [N('자오곡 기습', '子午谷の奇襲', 'The Ziwu Valley strike'), N('기산 우회', '祁山迂回', 'The Qishan detour'), N('진창 강습', '陳倉強襲', 'Storming Chencang'), N('상용 협공', '上庸挟撃', 'The Shangyong pincer')],
    expl: N('험로로 장안을 직격하자는 도박수 — 제갈량은 채택하지 않았어요.', '険路から長安を直撃する賭けの一手 — 諸葛亮は採用しませんでした。', 'A gamble to hit Chang’an through the gorge — Zhuge Liang never took it.'),
    link: { type: 'char', slug: 'wei-yan' } },
  { id: 'h9', q: N('"사공명 주생중달"이라는 당대의 말을 기록한 사서는?', '「死せる孔明、生ける仲達を走らす」を記録した史書は？', 'Which source records "dead Kongming routed living Zhongda"?'),
    c: [N('한진춘추', '漢晋春秋', 'Han Jin Chunqiu'), N('강표전', '江表伝', 'Jiangbiao Zhuan'), N('구주춘추', '九州春秋', 'Jiuzhou Chunqiu'), N('세설신어', '世説新語', 'Shishuo Xinyu')],
    expl: N('연의의 창작이 아니라 당대 속담을 전한 기록이에요.', '演義の創作ではなく、当時の俗諺を伝えた記録です。', 'Not the novel’s line — a genuine saying of the day, preserved in the record.'),
    link: { type: 'idiom', slug: 'sagongmyeong' } },
  { id: 'h10', q: N('공성계 일화(곽충의 이야기)를 "신빙성 없다"고 반박한 사람은?', '空城の計の逸話（郭沖の話）を「信憑性なし」と退けた人は？', 'Who rejected the empty-fort anecdote as unreliable?'),
    c: [N('배송지', '裴松之', 'Pei Songzhi'), N('진수', '陳寿', 'Chen Shou'), N('나관중', '羅貫中', 'Luo Guanzhong'), N('사마광', '司馬光', 'Sima Guang')],
    expl: N('주석자가 직접 반박한 야사를 연의가 명장면으로 살렸어요.', '注釈者自ら退けた野史を、演義が名場面に仕立てました。', 'The annotator himself debunked the tale the novel made immortal.'),
    link: { type: 'idiom', slug: 'gongseonggye' } },
  { id: 'h11', q: N('초선이라는 인물의 실존 여부는?', '貂蟬という人物は実在した？', 'Did Diao Chan actually exist?'),
    c: [N('연의의 창작 인물이다', '演義の創作人物である', 'No — she is the novel’s invention'), N('정사에 열전이 있다', '正史に列伝がある', 'Yes — she has a biography'), N('후한서에만 나온다', '後漢書にのみ登場する', 'Only in the Book of Later Han'), N('무덤이 발굴되었다', '墓が発掘された', 'Her tomb has been excavated')],
    expl: N('정사에는 여포가 동탁의 시비와 사통했다는 한 줄이 씨앗으로 남아 있을 뿐이에요.', '正史には呂布が董卓の侍女と私通したという一行が種として残るのみです。', 'The seed is one line in the histories: Lü Bu’s affair with a maid of Dong Zhuo.'),
    link: { type: 'char', slug: 'diao-chan' } },
  { id: 'h12', q: N('도원결의에 대한 정사의 실제 기록은?', '桃園の誓いについての正史の実際の記録は？', 'What do the histories actually say of the sworn brotherhood?'),
    c: [N('"은혜가 형제와 같았다"고만 전한다', '「恩は兄弟のごとし」とのみ伝える', 'Only that their bond was "like brothers"'), N('복숭아밭 결의가 그대로 있다', '桃園の誓いがそのまま載っている', 'The peach-garden oath appears verbatim'), N('세 사람이 같은 날 죽었다고 한다', '三人が同じ日に死んだとある', 'That they died on the same day'), N('기록 자체가 없다', '記録自体がない', 'Nothing at all')],
    expl: N('의형제 의식 자체가 연의의 창작이에요.', '義兄弟の儀式自体が演義の創作です。', 'The oath ceremony itself is the novel’s creation.'),
    link: { type: 'idiom', slug: 'dowongyeorui' } },
  { id: 'h13', q: N('이릉대전 직전, 손권이 배후 안정을 위해 위에 취한 조치는?', '夷陵の戦い直前、孫権が背後の安定のため魏に取った措置は？', 'How did Sun Quan secure his rear before Yiling?'),
    c: [N('신하를 칭했다(칭신)', '臣を称した', 'He declared vassalage to Wei'), N('영토를 할양했다', '領土を割譲した', 'He ceded territory'), N('혼인 동맹을 맺었다', '婚姻同盟を結んだ', 'He made a marriage alliance'), N('선전포고를 했다', '宣戦布告した', 'He declared war first')],
    expl: N('실리를 위해 머리를 숙인 대표적 유연 외교예요.', '実利のために頭を下げた代表的な柔軟外交です。', 'The signature act of his bend-don’t-break diplomacy.'),
    link: { type: 'battle', slug: 'yiling' } },
  { id: 'h14', q: N('조비가 시행한 관리 선발 제도는?', '曹丕が施行した官吏選抜制度は？', 'What official-selection system did Cao Pi institute?'),
    c: [N('구품관인법', '九品官人法', 'The nine-rank system'), N('과거제', '科挙', 'The civil examination'), N('둔전제', '屯田制', 'The military-farm system'), N('부병제', '府兵制', 'The garrison-militia system')],
    expl: N('위진남북조 관료제의 틀이 된 제도예요. 둔전제는 조조의 정책이죠.', '魏晋南北朝の官僚制の枠組みとなった制度です。屯田制は曹操の政策。', 'It shaped bureaucracy for centuries; the farm system was his father’s.'),
    link: { type: 'char', slug: 'cao-pi' } },
  { id: 'h15', q: N('손책 사후 실의에 빠진 손권을 말에 태워 일으킨 간언(개문읍도)의 주인공은?', '孫策の死後、失意の孫権を馬に乗せて立たせた諫言（開門揖盗）の主は？', 'Who pulled the grieving Sun Quan onto a horse with the "open gates" rebuke?'),
    c: [N('장소', '張昭', 'Zhang Zhao'), N('주유', '周瑜', 'Zhou Yu'), N('노숙', '魯粛', 'Lu Su'), N('정보', '程普', 'Cheng Pu')],
    expl: N('"슬픔에 문을 열어 두면 도둑을 절하며 맞는 격"이라 다그쳤어요.', '「悲しみに門を開け放つのは盗人に礼して迎えるようなもの」と叱咤しました。', '"Grieve with the gates open, and you bow the robber in," he warned.'),
    link: { type: 'idiom', slug: 'gaemuneupdo' } },
  { id: 'h16', q: N('정사 기준 주유의 사인은?', '正史基準の周瑜の死因は？', 'How did Zhou Yu die, according to the histories?'),
    c: [N('원정 준비 중 병사', '遠征準備中の病死', 'Illness, while preparing a campaign'), N('제갈량에게 화병으로 분사', '諸葛亮への憤死', 'Rage at Zhuge Liang'), N('전투 중 화살상 악화로 즉사', '戦闘中の矢傷で即死', 'Killed outright by an arrow'), N('암살', '暗殺', 'Assassination')],
    expl: N('"세 번 골탕 먹고 분사"는 연의 최대의 캐릭터 왜곡이에요.', '「三たびしてやられて憤死」は演義最大のキャラクター歪曲です。', 'The death-by-vexation is the novel’s greatest character assassination.'),
    link: { type: 'char', slug: 'zhou-yu' } },
  { id: 'h17', q: N('동관에서 마초·한수 연합을 무너뜨린 가후의 계책은?', '潼関で馬超・韓遂連合を崩した賈詡の計は？', 'What scheme of Jia Xu broke the Xiliang coalition at Tong Pass?'),
    c: [N('이간계', '離間の計', 'Sowing discord'), N('고육지계', '苦肉の策', 'The self-injury ruse'), N('공성계', '空城の計', 'The empty fort'), N('연환계', '連環の計', 'The chain scheme')],
    expl: N('글자를 지운 편지 한 통으로 마초의 의심을 부추겼어요.', '文字を塗り消した手紙一通で馬超の疑心を煽りました。', 'One letter full of suspicious erasures set Ma Chao against Han Sui.'),
    link: { type: 'battle', slug: 'tong-pass' } },
  { id: 'h18', q: N('연의가 합비에서 전사시킨 태사자의 실제 사망 시점은?', '演義が合肥で戦死させた太史慈の実際の死亡時期は？', 'When did Taishi Ci really die — the man the novel kills at Hefei?'),
    c: [N('합비 전투 9년 전 병사', '合肥の戦いの9年前に病死', 'Of illness, nine years before Hefei'), N('합비에서 전사', '合肥で戦死', 'In battle at Hefei'), N('적벽에서 전사', '赤壁で戦死', 'At Red Cliffs'), N('오 멸망 때까지 생존', '呉滅亡まで生存', 'He outlived the kingdom')],
    expl: N('206년 병사 — "칠 척 검을 차고..."라는 유언을 남겼어요.', '206年に病死 — 「七尺の剣を帯びて…」の遺言を残しました。', 'He died in 206, leaving the famous "seven-foot sword" lament.'),
    link: { type: 'char', slug: 'taishi-ci' } },
  { id: 'h19', q: N('관우의 뼈를 긁어 치료했다는 연의 장면이 불가능한 이유는?', '関羽の骨を削って治療したという演義の場面が不可能な理由は？', 'Why is the bone-scraping surgery on Guan Yu impossible?'),
    c: [N('화타가 그 전투 11년 전에 죽었다', '華佗がその戦いの11年前に死んでいる', 'Hua Tuo died eleven years before that battle'), N('화타는 외과를 못 했다', '華佗は外科ができなかった', 'Hua Tuo never performed surgery'), N('관우는 화살을 맞은 적이 없다', '関羽は矢を受けたことがない', 'Guan Yu was never wounded by an arrow'), N('마취약이 없던 시대다', '麻酔薬のない時代だ', 'Anesthesia did not exist')],
    expl: N('화타는 208년 옥사, 번성 전투는 219년이에요. 정사에도 관우의 뼈 수술 기록은 있지만 집도의는 무명이죠.', '華佗は208年に獄死、樊城の戦いは219年です。正史にも関羽の骨手術の記録はありますが執刀医は無名です。', 'Hua Tuo died in 208; Fancheng was 219. The histories do record a bone surgery — by an unnamed physician.'),
    link: { type: 'char', slug: 'hua-tuo' } },
  { id: 'h20', q: N('헌제가 선양 후 받은 작위는?', '献帝が禅譲後に受けた爵位は？', 'What title did Emperor Xian receive after abdicating?'),
    c: [N('산양공', '山陽公', 'Duke of Shanyang'), N('안락공', '安楽公', 'Duke of Anle'), N('진류왕', '陳留王', 'Prince of Chenliu'), N('한중왕', '漢中王', 'King of Hanzhong')],
    expl: N('안락공은 유선, 한중왕은 유비 — 헌제는 산양 땅에서 천수를 누렸어요.', '安楽公は劉禅、漢中王は劉備 — 献帝は山陽の地で天寿を全うしました。', 'Anle was Liu Shan’s title, Hanzhong Liu Bei’s. Xian lived out his days at Shanyang.'),
    link: { type: 'char', slug: 'xian-di' } },
  { id: 'h21', q: N('"국궁진췌"가 실린 후출사표를 둘러싼 학계의 논점은?', '「鞠躬尽瘁」が載る後出師表を巡る学界の論点は？', 'What is the scholarly dispute over the Later Chu Shi Biao?'),
    c: [N('후대 위작 여부', '後代の偽作かどうか', 'Whether it is a later forgery'), N('저자가 강유라는 설', '著者が姜維という説', 'Whether Jiang Wei wrote it'), N('연도 오기 여부', '年代の誤記かどうか', 'A dating error'), N('논점이 없다', '論点はない', 'There is no dispute')],
    expl: N('정사에 실리지 않아 진위 논란이 이어져요 — 전출사표는 정사 수록이에요.', '正史に収められておらず真偽論争が続きます — 前出師表は正史所収です。', 'It never appears in the histories, unlike the (undisputed) first memorial.'),
    link: { type: 'quote', slug: 'zhugeliang-jugong' } },
  { id: 'h22', q: N('정사에서 "만인지적"이라 평가된 두 사람은?', '正史で「万人の敵」と評された二人は？', 'Which pair did the histories call "a match for ten thousand"?'),
    c: [N('관우와 장비', '関羽と張飛', 'Guan Yu and Zhang Fei'), N('여포와 조운', '呂布と趙雲', 'Lü Bu and Zhao Yun'), N('마초와 황충', '馬超と黄忠', 'Ma Chao and Huang Zhong'), N('장료와 감녕', '張遼と甘寧', 'Zhang Liao and Gan Ning')],
    expl: N('진수의 평 — "당대의 범 같은 신하(호신)"라는 표현도 함께예요.', '陳寿の評 — 「当代の虎臣」という表現も一緒です。', 'Chen Shou’s verdict, paired with "tiger ministers of their age."'),
    link: { type: 'idiom', slug: 'maninjijeok' } },
  { id: 'h23', q: N('215년 형주 분할(상수 협약)의 경계가 된 강은?', '215年の荊州分割（湘水の和議）の境界となった川は？', 'Which river divided Jing Province in the 215 accord?'),
    c: [N('상수', '湘水', 'The Xiang'), N('한수', '漢水', 'The Han'), N('위수', '渭水', 'The Wei'), N('장강', '長江', 'The Yangtze')],
    expl: N('단도부회 담판 끝의 타협선이었어요.', '単刀赴会の談判の末の妥協線でした。', 'The compromise line drawn after the single-blade parley.'),
    link: { type: 'idiom', slug: 'dandobuhoe' } },
  { id: 'h24', q: N('244년 흥세에서 위의 대규모 침공을 막아낸 촉의 장수는?', '244年、興勢で魏の大規模侵攻を防いだ蜀の将は？', 'Who repelled Wei’s great invasion at Xingshi in 244?'),
    c: [N('왕평', '王平', 'Wang Ping'), N('강유', '姜維', 'Jiang Wei'), N('위연', '魏延', 'Wei Yan'), N('마대', '馬岱', 'Ma Dai')],
    expl: N('"무학의 명장"이 지형으로 대군을 묶어 촉을 구했어요.', '「無学の名将」が地形で大軍を釘付けにして蜀を救いました。', 'The unlettered general pinned an army with terrain — and saved Shu.'),
    link: { type: 'char', slug: 'wang-ping' } },
  { id: 'h25', q: N('진의 오 정벌 함대가 건조된 곳은?', '晋の呉征伐艦隊が建造された場所は？', 'Where was Jin’s invasion fleet built?'),
    c: [N('익주(옛 촉 땅)', '益州（旧蜀の地）', 'Yi Province (old Shu)'), N('낙양', '洛陽', 'Luoyang'), N('합비', '合肥', 'Hefei'), N('요동', '遼東', 'Liaodong')],
    expl: N('왕준이 장강 상류에서 20년 가까이 대형 함선을 준비했어요.', '王濬が長江上流で20年近く大型艦船を準備しました。', 'Wang Jun spent nearly twenty years building great ships on the upper Yangtze.'),
    link: { type: 'battle', slug: 'conquest-of-wu' } },
  { id: 'h26', q: N('마초의 거병과 마등의 처형, 실제 순서는?', '馬超の挙兵と馬騰の処刑、実際の順序は？', 'Ma Chao’s revolt and Ma Teng’s execution — which came first?'),
    c: [N('거병이 먼저, 처형은 그 보복', '挙兵が先、処刑はその報復', 'The revolt first; the execution followed'), N('처형이 먼저, 거병은 복수', '処刑が先、挙兵は復讐', 'The execution first; the revolt avenged it'), N('같은 달의 일이다', '同じ月の出来事', 'They happened the same month'), N('처형은 없었다', '処刑はなかった', 'There was no execution')],
    expl: N('연의가 복수극으로 순서를 뒤집었어요 — 정사는 그 반대입니다.', '演義が復讐劇に順序をひっくり返しました — 正史はその逆です。', 'The novel reversed the order to make a revenge tale; history runs the other way.'),
    link: { type: 'char', slug: 'ma-chao' } },
  { id: 'h27', q: N('양수가 처형될 때의 공식 죄목은?', '楊修が処刑された際の公式な罪目は？', 'On what official charge was Yang Xiu executed?'),
    c: [N('군심을 어지럽힘', '軍心を乱した', 'Unsettling the army'), N('반역 모의', '謀反', 'Plotting treason'), N('군량 횡령', '兵糧横領', 'Embezzling grain'), N('적과 내통', '敵との内通', 'Colluding with the enemy')],
    expl: N('계륵 풀이가 빌미가 됐지만, 배경엔 조식 편에 선 후계 분쟁이 있었어요.', '鶏肋の解読が口実になりましたが、背景には曹植側に立った後継争いがありました。', 'The "chicken ribs" decoding was the pretext; the succession fight was the cause.'),
    link: { type: 'quote', slug: 'yangxiu-ribs' } },
  { id: 'h28', q: N('"산불염고 해불염심(산은 높기를 마다 않고)"이 실린 조조의 시는?', '「山は高きを厭わず」が載る曹操の詩は？', 'Which poem of Cao Cao contains "mountains never tire of height"?'),
    c: [N('단가행', '短歌行', 'The Short Song'), N('구수수', '亀雖寿', 'Though the Tortoise Lives Long'), N('관창해', '観滄海', 'Viewing the Blue Sea'), N('호리행', '蒿里行', 'The Graveyard Song')],
    expl: N('"대주당가"로 시작해 인재 갈망으로 끝나는 그 시예요.', '「対酒当歌」で始まり、人材への渇望で終わるあの詩です。', 'The poem that opens with wine and closes with the hunger for talent.'),
    link: { type: 'quote', slug: 'caocao-mountain-sea' } },
  { id: 'h29', q: N('진수가 오나라 신하 중 유일하게 육손에게만 해 준 대우는?', '陳寿が呉の臣下で唯一陸遜にだけ与えた待遇は？', 'What unique honor did Chen Shou give Lu Xun among Wu’s subjects?'),
    c: [N('단독 열전', '単独の列伝', 'A biography all his own'), N('본기 수록', '本紀に収録', 'A place in the imperial annals'), N('세가 편성', '世家に編成', 'A hereditary-house chapter'), N('평을 생략', '評を省略', 'No appraisal at all')],
    expl: N('군주가 아닌 오나라 인물로는 유일한 단독 열전이에요.', '君主でない呉の人物では唯一の単独列伝です。', 'No other non-sovereign of Wu received a solo biography.'),
    link: { type: 'char', slug: 'lu-xun' } },
  { id: 'h30', q: N('백제성에서 유비가 제갈량에게 남긴 파격의 유언은?', '白帝城で劉備が諸葛亮に残した破格の遺言は？', 'What extraordinary offer did the dying Liu Bei make Zhuge Liang?'),
    c: [N('"아들이 재목이 아니면 그대가 취하라"', '「息子が器でなければ君が取れ」', '"If my son fails, take the throne yourself"'), N('"북벌을 멈추라"', '「北伐をやめよ」', '"Abandon the northern campaigns"'), N('"오와 다시는 화친하지 말라"', '「呉と二度と和睦するな」', '"Never make peace with Wu"'), N('"위연을 중용하라"', '「魏延を重用せよ」', '"Promote Wei Yan"')],
    expl: N('제갈량은 눈물로 충성을 맹세했고, 평생 그 약속을 지켰어요.', '諸葛亮は涙で忠誠を誓い、生涯その約束を守りました。', 'Zhuge Liang wept, vowed loyalty unto death — and kept the vow.'),
    link: { type: 'quote', slug: 'liubei-baidicheng' } },
]
