// 삼국지 공유 사건 데이터 — 연표용 확장분 16 (배치3 승인 계획). 합산 71개.
import type { TKEvent } from './threeKingdomsEvents'

export const EVENTS_EXTRA: TKEvent[] = [
  { id: 'li-guo-chaos', year: 192, type: 'politics', src: 'history',
    title: { ko: '이각·곽사의 난', ja: '李傕・郭汜の乱', en: 'The Li Jue–Guo Si Chaos' },
    desc: { ko: '동탁의 서량 잔당이 사면을 거부당하자 장안을 역습해 왕윤을 처형한다. 조정은 다시 폭력의 수중에 떨어졌다.', ja: '董卓の西涼残党が赦免を拒まれると長安を逆襲し、王允を処刑。朝廷は再び暴力の手中に落ちた。', en: 'Refused amnesty, Dong Zhuo’s Xiliang remnants storm Chang’an and execute Wang Yun — the court falls back into the hands of violence.' },
    people: ['wang-yun', 'lv-bu', 'jia-xu', 'xian-di'] },
  { id: 'xiandi-escape', year: 195, type: 'politics', src: 'history',
    title: { ko: '헌제의 장안 탈출', ja: '献帝の長安脱出', en: 'Emperor Xian Escapes Chang’an' },
    desc: { ko: '이각과 곽사의 내분 틈에 헌제가 낙양을 향한 유랑길에 오른다. 이 떠돌이 조정이 이듬해 조조의 손에 들어간다.', ja: '李傕と郭汜の内紛の隙に献帝が洛陽へ向かう流浪の旅に出る。この流浪の朝廷が翌年、曹操の手に入る。', en: 'Amid his captors’ infighting, Emperor Xian flees toward Luoyang — the wandering court that Cao Cao would take in the following year.' },
    people: ['xian-di'] },
  { id: 'xuzhou-lost', year: 200, type: 'battle', src: 'history',
    title: { ko: '유비, 서주를 잃다', ja: '劉備、徐州を失う', en: 'Liu Bei Loses Xuzhou' },
    desc: { ko: '조조에게서 독립을 꾀하던 유비가 전격 공격에 무너져 원소에게 달아난다. 관우는 이때 조조에게 사로잡혔다.', ja: '曹操からの独立を図っていた劉備が電撃攻撃に崩れ、袁紹のもとへ逃れる。関羽はこのとき曹操に捕らえられた。', en: 'Breaking from Cao Cao, Liu Bei is crushed by a lightning strike and flees to Yuan Shao. It was here that Guan Yu fell into Cao Cao’s hands.' },
    people: ['liu-bei', 'cao-cao', 'guan-yu', 'zhang-fei'] },
  { id: 'four-commanderies', year: 209, type: 'politics', src: 'history',
    title: { ko: '유비, 형남 4군 확보', ja: '劉備、荊南四郡を確保', en: 'Liu Bei Takes the Four Southern Commanderies' },
    desc: { ko: '적벽의 여세로 유비가 무릉·장사·계양·영릉을 거두며 처음으로 제대로 된 근거지를 갖는다. 황충과 위연이 이 무렵 합류했다.', ja: '赤壁の余勢を駆って劉備が武陵・長沙・桂陽・零陵を収め、初めてまともな根拠地を持つ。黄忠と魏延がこの頃合流した。', en: 'Riding Red Cliffs’ momentum, Liu Bei gathers the four commanderies south of the Yangtze — his first real territory. Huang Zhong and Wei Yan joined around this time.' },
    people: ['liu-bei', 'huang-zhong', 'wei-yan', 'zhao-yun'] },
  { id: 'marriage-alliance', year: 209, type: 'politics', src: 'history',
    title: { ko: '손유 혼인 동맹', ja: '孫劉の婚姻同盟', en: 'The Sun–Liu Marriage Alliance' },
    desc: { ko: '손권이 누이를 유비에게 시집보내 동맹을 다진다. 연의는 이를 주유의 미인계와 금낭묘계의 무대로 극화했다.', ja: '孫権が妹を劉備に嫁がせて同盟を固める。演義はこれを周瑜の美人計と錦嚢の計の舞台に脚色した。', en: 'Sun Quan weds his sister to Liu Bei to cement the alliance — the episode the novel restages as Zhou Yu’s honey trap and the brocade-bag stratagems.' },
    people: ['liu-bei', 'sun-quan', 'zhou-yu', 'zhuge-liang', 'zhao-yun'] },
  { id: 'yizhou-entry', year: 211, type: 'politics', src: 'history',
    title: { ko: '유비의 익주 입성', ja: '劉備の益州入り', en: 'Liu Bei Enters Yi Province' },
    desc: { ko: '장로 토벌을 명분으로 유장의 초청을 받은 유비가 방통·법정과 함께 촉 땅에 들어선다. 3년 뒤 그 땅의 주인이 바뀐다.', ja: '張魯討伐を名分に劉璋の招きを受けた劉備が、龐統・法正とともに蜀の地に入る。3年後、その地の主が変わる。', en: 'Invited by Liu Zhang to fight Zhang Lu, Liu Bei enters the land of Shu with Pang Tong and Fa Zheng. Within three years it would have a new master.' },
    people: ['liu-bei', 'pang-tong', 'fa-zheng'] },
  { id: 'zhanglu-surrender', year: 215, type: 'politics', src: 'history',
    title: { ko: '장로의 항복 — 조조 한중 확보', ja: '張魯の降伏 — 曹操漢中確保', en: 'Zhang Lu Surrenders Hanzhong' },
    desc: { ko: '오두미도의 장로가 조조에게 항복하며 한중이 위의 손에 들어간다. "촉은 하루에도 수십 번 놀란다"는 말이 나온 위기였다.', ja: '五斗米道の張魯が曹操に降伏し、漢中が魏の手に入る。「蜀は一日に数十度も震える」と言われた危機だった。', en: 'Zhang Lu of the Five Pecks of Rice sect yields Hanzhong to Cao Cao — the crisis in which, it was said, Shu trembled dozens of times a day.' },
    people: ['cao-cao', 'zhang-he'] },
  { id: 'caocao-king', year: 216, type: 'politics', src: 'history',
    title: { ko: '조조, 위왕에 오르다', ja: '曹操、魏王に', en: 'Cao Cao Becomes King of Wei' },
    desc: { ko: '위공을 거쳐 왕위까지 오르며 조조는 황제와 한 계단 차이가 된다. 한실 부흥이라는 명분은 사실상 형해화되었다.', ja: '魏公を経て王位まで上り、曹操は皇帝と一段の差になる。漢室復興という大義名分は事実上形骸化した。', en: 'From duke to king: Cao Cao now stands one step from the throne, and the cause of "restoring the Han" is a shell.' },
    people: ['cao-cao', 'xian-di'] },
  { id: 'caopi-invasion', year: 222, type: 'battle', src: 'history',
    title: { ko: '조비의 3로 오 정벌', ja: '曹丕の三路呉征伐', en: 'Cao Pi’s Three-Route Invasion of Wu' },
    desc: { ko: '이릉 직후 오가 신하의 예를 거두자 조비가 세 갈래로 남정한다. 조인의 유수 공격이 꺾이는 등 성과 없이 물러났다.', ja: '夷陵の直後、呉が臣下の礼を撤回すると曹丕が三方面から南征。曹仁の濡須攻撃が挫かれるなど成果なく退いた。', en: 'When Wu dropped its vassalage after Yiling, Cao Pi struck south on three routes — and withdrew empty-handed, Cao Ren’s attack at Ruxu among the failures.' },
    people: ['cao-pi', 'cao-ren', 'sun-quan'] },
  { id: 'chencang', year: 228, type: 'battle', src: 'history',
    title: { ko: '진창 공방전 (2차 북벌)', ja: '陳倉攻防戦（第二次北伐）', en: 'Siege of Chencang' },
    desc: { ko: '겨울, 제갈량이 진창성을 급습하지만 학소가 천여 병력으로 20여 일을 버텨낸다. 군량이 다한 촉군은 철수했다.', ja: '冬、諸葛亮が陳倉城を急襲するが、郝昭が千余りの兵力で20余日持ちこたえる。兵糧の尽きた蜀軍は撤退した。', en: 'That winter Zhuge Liang stormed Chencang, but Hao Zhao’s thousand-odd defenders held for over twenty days until Shu’s grain ran out.' },
    people: ['zhuge-liang', 'wang-ping'] },
  { id: 'sunquan-emperor', year: 229, type: 'politics', src: 'history',
    title: { ko: '손권 칭제 — 삼국 정립 완성', ja: '孫権即位 — 三国鼎立の完成', en: 'Sun Quan Takes the Throne' },
    desc: { ko: '손권이 황제를 칭하며 위·촉·오 세 황제가 병립하는 명실상부한 삼국시대가 완성된다. 촉은 실리를 택해 이를 인정했다.', ja: '孫権が皇帝を称し、魏・蜀・呉の三皇帝が並び立つ名実ともの三国時代が完成する。蜀は実利を取ってこれを認めた。', en: 'With Sun Quan’s enthronement, three emperors reign at once — the Three Kingdoms in name as well as fact. Shu, pragmatically, recognized him.' },
    people: ['sun-quan', 'lu-xun', 'zhuge-liang'] },
  { id: 'liaodong', year: 238, type: 'battle', src: 'history',
    title: { ko: '사마의의 요동 정벌', ja: '司馬懿の遼東征伐', en: 'Sima Yi Conquers Liaodong' },
    desc: { ko: '자립을 꾀한 공손연을 사마의가 1년 예고대로 정확히 평정한다. "가는 데 백 일, 치는 데 백 일"의 계산이 그대로 맞았다.', ja: '自立を図った公孫淵を司馬懿が一年の予告どおり正確に平定する。「行くのに百日、攻めるのに百日」の計算がそのまま当たった。', en: 'Sima Yi crushes the separatist Gongsun Yuan exactly on the schedule he announced — a hundred days to march, a hundred to conquer.' },
    people: ['sima-yi'] },
  { id: 'zhuge-ke', year: 253, type: 'battle', src: 'history',
    title: { ko: '제갈각의 몰락', ja: '諸葛恪の没落', en: 'The Fall of Zhuge Ke' },
    desc: { ko: '동흥의 대승으로 오의 권력을 쥔 제갈근의 아들 제갈각이 무리한 합비 원정 실패 후 정변으로 살해된다.', ja: '東興の大勝で呉の権力を握った諸葛瑾の息子・諸葛恪が、無理な合肥遠征の失敗後、政変で殺害される。', en: 'Zhuge Jin’s son Zhuge Ke, master of Wu after his victory at Dongxing, is assassinated in a coup after his reckless Hefei campaign fails.' },
    people: ['zhuge-jin'] },
  { id: 'caomao-death', year: 260, type: 'politics', src: 'history',
    title: { ko: '조모 시해 — 사마씨의 완전 장악', ja: '曹髦弑逆 — 司馬氏の完全掌握', en: 'The Killing of Cao Mao' },
    desc: { ko: '"사마소의 마음은 길 가는 사람도 안다"며 친정에 나선 젊은 황제 조모가 백주에 시해된다. 위 황실의 저항은 여기서 끝났다.', ja: '「司馬昭の心は道行く人も知る」と親征に出た若き皇帝・曹髦が白昼に弑される。魏皇室の抵抗はここで終わった。', en: '"Even the man in the street knows Sima Zhao’s heart" — the young emperor Cao Mao marches out and is cut down in broad daylight. Wei’s imperial resistance ends here.' },
    people: [] },
  { id: 'zhonghui-revolt', year: 264, type: 'politics', src: 'history',
    title: { ko: '종회의 난 — 강유 최후의 계책', ja: '鍾会の乱 — 姜維最後の計', en: 'Zhong Hui’s Revolt — Jiang Wei’s Last Scheme' },
    desc: { ko: '촉 정벌 사령관 종회를 강유가 부추겨 성도에서 반란을 일으키지만 난전 속에 둘 다 목숨을 잃는다. 촉 부흥의 마지막 불씨가 꺼졌다.', ja: '蜀征伐の司令官・鍾会を姜維が唆して成都で反乱を起こさせるが、乱戦の中で二人とも命を落とす。蜀復興の最後の火種が消えた。', en: 'Jiang Wei goads the conquering general Zhong Hui into revolt at Chengdu — and both die in the chaos. The last ember of a Shu restoration goes out.' },
    people: ['jiang-wei', 'liu-shan'] },
  { id: 'sunhao', year: 264, type: 'politics', src: 'history',
    title: { ko: '손호 즉위 — 오의 황혼', ja: '孫皓即位 — 呉の黄昏', en: 'Sun Hao Takes the Wu Throne' },
    desc: { ko: '기대 속에 즉위한 손호가 곧 폭정으로 돌변해 오의 마지막 활력을 소진시킨다. 진의 통일은 시간문제가 되었다.', ja: '期待の中で即位した孫皓がまもなく暴政に豹変し、呉の最後の活力を使い果たす。晋の統一は時間の問題となった。', en: 'Sun Hao, enthroned amid high hopes, turns tyrant and burns through Wu’s last vitality. Jin’s reunification becomes a matter of time.' },
    people: [] },
]
