// 삼국지 퀴즈 — 중급 30 (승인 목록 31–60). c[0]이 정답.
import type { TKQuizQ } from './threeKingdomsQuiz'

const N = (ko: string, ja: string, en: string) => ({ ko, ja, en })

export const QUIZ_MID: TKQuizQ[] = [
  { id: 'm1', q: N('관도대전에서 조조가 기습해 불태운 원소의 군량 기지는?', '官渡の戦いで曹操が奇襲して焼いた袁紹の兵糧基地は？', 'Which grain depot did Cao Cao burn to win Guandu?'),
    c: [N('오소', '烏巣', 'Wuchao'), N('백마', '白馬', 'Baima'), N('연진', '延津', 'Yanjin'), N('업성', '鄴城', 'Yecheng')],
    expl: N('허유의 밀고로 위치를 알아낸 조조가 몸소 5천을 이끌고 야습했어요.', '許攸の密告で位置を知った曹操が自ら五千を率いて夜襲しました。', 'Betrayed by the defector Xu You, it fell to Cao Cao’s personal night raid.'),
    link: { type: 'battle', slug: 'guandu' } },
  { id: 'm2', q: N('손책의 별명은?', '孫策の異名は？', 'What was Sun Ce’s nickname?'),
    c: [N('소패왕', '小覇王', 'The Little Conqueror'), N('강동의 호랑이', '江東の虎', 'Tiger of Jiangdong'), N('백마장군', '白馬将軍', 'The White Horse General'), N('금범적', '錦帆賊', 'The Silk-Sail Pirate')],
    expl: N('항우(패왕)에 비견된 무용에서 나온 별명 — 강동의 호랑이는 아버지 손견이에요.', '項羽（覇王）に比せられた武勇から出た異名 — 江東の虎は父の孫堅です。', 'Compared to the conqueror Xiang Yu; "Tiger of Jiangdong" was his father Sun Jian.'),
    link: { type: 'char', slug: 'sun-ce' } },
  { id: 'm3', q: N('"공명을 얻은 것은 물고기가 물을 만난 것"이라 말한 사람은?', '「孔明を得たのは魚が水を得たようなもの」と言った人は？', 'Who said having Kongming was "like a fish finding water"?'),
    c: [N('유비', '劉備', 'Liu Bei'), N('관우', '関羽', 'Guan Yu'), N('서서', '徐庶', 'Xu Shu'), N('방통', '龐統', 'Pang Tong')],
    expl: N('불평하는 관우·장비를 달랜 말로, 수어지교의 원문이에요.', '不満を漏らす関羽・張飛をなだめた言葉で、水魚の交わりの原文です。', 'Spoken to soothe Guan Yu and Zhang Fei — the origin of the fish-and-water idiom.'),
    link: { type: 'quote', slug: 'liubei-fish-water' } },
  { id: 'm4', q: N('이릉대전에서 오군을 지휘해 유비를 꺾은 사람은?', '夷陵の戦いで呉軍を指揮し劉備を破った人は？', 'Who commanded Wu’s army to victory at Yiling?'),
    c: [N('육손', '陸遜', 'Lu Xun'), N('여몽', '呂蒙', 'Lü Meng'), N('주유', '周瑜', 'Zhou Yu'), N('감녕', '甘寧', 'Gan Ning')],
    expl: N('반 년을 웅크렸다 화공 한 방 — 젊은 대도독의 데뷔전이었어요.', '半年身を潜めて火攻めの一撃 — 若き大都督のデビュー戦でした。', 'Half a year of patience, one fire attack — the young commander’s debut.'),
    link: { type: 'battle', slug: 'yiling' } },
  { id: 'm5', q: N('합비에서 800 결사대로 손권의 대군을 무너뜨린 장수는?', '合肥で八百の決死隊で孫権の大軍を崩した将は？', 'Whose 800 volunteers broke Sun Quan’s host at Hefei?'),
    c: [N('장료', '張遼', 'Zhang Liao'), N('장합', '張郃', 'Zhang He'), N('서황', '徐晃', 'Xu Huang'), N('조인', '曹仁', 'Cao Ren')],
    expl: N('"장료가 온다"는 말이 강동의 우는 아이를 그치게 했다고 전해요.', '「遼来来」の名が江東の泣く子を黙らせたと伝わります。', 'His very name, they said, silenced crying children in the Southland.'),
    link: { type: 'battle', slug: 'hefei' } },
  { id: 'm6', q: N('정군산에서 황충이 벤 위나라 서부 총사령은?', '定軍山で黄忠が斬った魏の西部総帥は？', 'Which Wei commander did Huang Zhong cut down at Mount Dingjun?'),
    c: [N('하후연', '夏侯淵', 'Xiahou Yuan'), N('하후돈', '夏侯惇', 'Xiahou Dun'), N('장합', '張郃', 'Zhang He'), N('우금', '于禁', 'Yu Jin')],
    expl: N('이 일격이 한중 쟁탈전의 승부를 갈랐어요.', 'この一撃が漢中争奪戦の勝敗を分けました。', 'The stroke that decided the war for Hanzhong.'),
    link: { type: 'battle', slug: 'hanzhong' } },
  { id: 'm7', q: N('가정 전투에서 지시를 어기고 산 위에 진을 친 사람은?', '街亭の戦いで指示に背き山上に布陣した人は？', 'Who defied orders and camped on the hilltop at Jieting?'),
    c: [N('마속', '馬謖', 'Ma Su'), N('왕평', '王平', 'Wang Ping'), N('위연', '魏延', 'Wei Yan'), N('강유', '姜維', 'Jiang Wei')],
    expl: N('물길을 끊겨 대패 — 1차 북벌 전체가 무너졌어요.', '水路を断たれ大敗 — 第一次北伐全体が崩れました。', 'His water cut, his army broke — and the whole first campaign with it.'),
    link: { type: 'battle', slug: 'jieting' } },
  { id: 'm8', q: N('유비가 임종 때 "말이 실제보다 앞서니 크게 쓰지 말라"고 경고한 인물은?', '劉備が臨終の際「言葉が実際に過ぎる、重用するな」と警告した人物は？', 'Whom did the dying Liu Bei warn was "all words, no substance"?'),
    c: [N('마속', '馬謖', 'Ma Su'), N('마량', '馬良', 'Ma Liang'), N('위연', '魏延', 'Wei Yan'), N('이엄', '李厳', 'Li Yan')],
    expl: N('언과기실 — 5년 뒤 가정에서 그 경고가 현실이 되었어요.', '言過其実 — 5年後、街亭でその警告が現実になりました。', 'Five years later, at Jieting, the warning came true.'),
    link: { type: 'idiom', slug: 'eongwagisil' } },
  { id: 'm9', q: N('제갈량이 천하삼분지계를 설파한 곳은?', '諸葛亮が天下三分の計を説いた場所は？', 'Where did Zhuge Liang lay out his plan to divide the realm?'),
    c: [N('융중', '隆中', 'Longzhong'), N('신야', '新野', 'Xinye'), N('성도', '成都', 'Chengdu'), N('적벽', '赤壁', 'Red Cliffs')],
    expl: N('초가집에 앉아 천하의 지도를 그린 융중대예요.', '草庵に座して天下の地図を描いた隆中対です。', 'The Longzhong Plan, sketched without leaving his thatched cottage.'),
    link: { type: 'idiom', slug: 'cheonhasambunjigye' } },
  { id: 'm10', q: N('병사들을 상인으로 위장시켜 형주를 무혈 접수한 작전은?', '兵士を商人に偽装させ荊州を無血接収した作戦は？', 'What was Lü Meng’s merchant-disguise operation called?'),
    c: [N('백의도강', '白衣渡江', 'Crossing in white (merchant) garb'), N('연환계', '連環の計', 'The chain scheme'), N('고육지계', '苦肉の策', 'The self-injury ruse'), N('공성계', '空城の計', 'The empty fort')],
    expl: N('여몽의 이 기습으로 관우는 퇴로를 잃었어요.', '呂蒙のこの奇襲で関羽は退路を失いました。', 'Lü Meng’s strike cut Guan Yu’s road home.'),
    link: { type: 'battle', slug: 'fancheng' } },
  { id: 'm11', q: N('손권에게 "한실은 부흥할 수 없다"는 탑상책을 올린 사람은?', '孫権に「漢室は復興できない」という榻上策を献じた人は？', 'Who told Sun Quan the Han could never be restored — the "Couch Plan"?'),
    c: [N('노숙', '魯粛', 'Lu Su'), N('장소', '張昭', 'Zhang Zhao'), N('주유', '周瑜', 'Zhou Yu'), N('제갈근', '諸葛瑾', 'Zhuge Jin')],
    expl: N('제갈량의 융중대보다 7년 앞선 대전략이었어요.', '諸葛亮の隆中対より7年早い大戦略でした。', 'A grand strategy seven years ahead of the more famous Longzhong Plan.'),
    link: { type: 'quote', slug: 'lusu-couch' } },
  { id: 'm12', q: N('관도 결전을 앞두고 십승십패론을 내놓은 참모는?', '官渡の決戦を前に十勝十敗論を出した参謀は？', 'Which adviser produced the "ten victories, ten defeats" analysis?'),
    c: [N('곽가', '郭嘉', 'Guo Jia'), N('순욱', '荀彧', 'Xun Yu'), N('가후', '賈詡', 'Jia Xu'), N('양수', '楊修', 'Yang Xiu')],
    expl: N('병력이 아니라 조직과 리더십의 질을 비교한 분석이었어요.', '兵力ではなく組織とリーダーシップの質を比較した分析でした。', 'It compared not numbers but the quality of organization and leadership.'),
    link: { type: 'quote', slug: 'guojia-ten-wins' } },
  { id: 'm13', q: N('완성 전투에서 조조를 지키다 전사한 호위대장은?', '宛城の戦いで曹操を守って戦死した護衛隊長は？', 'Which bodyguard died covering Cao Cao’s escape at Wancheng?'),
    c: [N('전위', '典韋', 'Dian Wei'), N('허저', '許褚', 'Xu Chu'), N('조홍', '曹洪', 'Cao Hong'), N('악진', '楽進', 'Yue Jin')],
    expl: N('무기를 잃고도 맨몸으로 군문을 막다 쓰러졌어요.', '武器を失っても素手で軍門を塞ぎ、倒れました。', 'Weapons broken, he barred the gate bare-handed until he fell.'),
    link: { type: 'char', slug: 'dian-wei' } },
  { id: 'm14', q: N('150보 밖의 극을 쏘아 맞혀 전쟁을 말린 원문사극의 주인공은?', '150歩先の戟を射抜いて戦を止めた轅門射戟の主人公は？', 'Who stopped a war by shooting the halberd at 150 paces?'),
    c: [N('여포', '呂布', 'Lü Bu'), N('황충', '黄忠', 'Huang Zhong'), N('태사자', '太史慈', 'Taishi Ci'), N('감녕', '甘寧', 'Gan Ning')],
    expl: N('"나는 싸움 말리기를 좋아한다"며 단 한 발로 원술군을 물렸어요.', '「私は戦いを解くのが好きだ」と、ただ一矢で袁術軍を退けました。', '"I only like stopping fights," he said — and one arrow turned back an army.'),
    link: { type: 'quote', slug: 'lvbu-peacemaker' } },
  { id: 'm15', q: N('조조에게 헌제를 허도로 모시라고 진언한 참모는?', '曹操に献帝を許都へ迎えるよう進言した参謀は？', 'Who counseled Cao Cao to take in Emperor Xian?'),
    c: [N('순욱', '荀彧', 'Xun Yu'), N('곽가', '郭嘉', 'Guo Jia'), N('가후', '賈詡', 'Jia Xu'), N('정욱', '程昱', 'Cheng Yu')],
    expl: N('"천자를 받듦이 대순" — 삼국시대 최고의 전략 조언으로 꼽혀요.', '「主上を奉じるは大順」 — 三国時代最高の戦略助言に数えられます。', '"Uphold the sovereign" — arguably the era’s highest-yield advice.'),
    link: { type: 'quote', slug: 'xunyu-emperor' } },
  { id: 'm16', q: N('제갈량이 일곱 번 잡고 일곱 번 놓아준 남중의 지도자는?', '諸葛亮が七度捕らえ七度放った南中の指導者は？', 'Whom did Zhuge Liang capture and release seven times?'),
    c: [N('맹획', '孟獲', 'Meng Huo'), N('축융', '祝融', 'Zhurong'), N('사마가', '沙摩柯', 'Shamoke'), N('올돌골', '兀突骨', 'Wutugu')],
    expl: N('칠종칠금 — 마음을 복속시켜 남방을 안정시켰어요.', '七縦七擒 — 心を服させて南方を安定させました。', 'Seven captures, seven releases — submission of the heart, not the body.'),
    link: { type: 'idiom', slug: 'chiljongchilgeum' } },
  { id: 'm17', q: N('"이곳이 즐거워 촉 생각이 나지 않는다"고 답한 인물은?', '「ここが楽しくて蜀を思い出さない」と答えた人物は？', 'Who said he was "too happy here to miss Shu"?'),
    c: [N('유선', '劉禅', 'Liu Shan'), N('강유', '姜維', 'Jiang Wei'), N('유비', '劉備', 'Liu Bei'), N('제갈첨', '諸葛瞻', 'Zhuge Zhan')],
    expl: N('낙불사촉 — 어리석음인지 생존술인지 지금도 평가가 갈려요.', '楽不思蜀 — 愚かさか生存術か、今も評価が分かれます。', 'Folly or survival craft? The debate has never ended.'),
    link: { type: 'idiom', slug: 'nakbulsachok' } },
  { id: 'm18', q: N('매달 초하루의 인물 품평 "월단평"을 주재한 사람은?', '毎月一日の人物品評「月旦評」を主宰した人は？', 'Who ran the famous first-of-the-month character reviews?'),
    c: [N('허소', '許劭', 'Xu Shao'), N('사마휘', '司馬徽', 'Sima Hui'), N('공융', '孔融', 'Kong Rong'), N('예형', '禰衡', 'Mi Heng')],
    expl: N('조조의 "치세의 능신, 난세의 간웅" 평이 여기서 나왔어요.', '曹操の「治世の能臣、乱世の姦雄」の評はここから生まれました。', 'The source of Cao Cao’s immortal "able minister / cunning hero" verdict.'),
    link: { type: 'idiom', slug: 'woldanpyeong' } },
  { id: 'm19', q: N('일곱 걸음 안에 시를 지어 목숨을 건진 인물은?', '七歩のうちに詩を作って命を繋いだ人物は？', 'Who saved himself with a poem composed within seven paces?'),
    c: [N('조식', '曹植', 'Cao Zhi'), N('조비', '曹丕', 'Cao Pi'), N('공융', '孔融', 'Kong Rong'), N('양수', '楊修', 'Yang Xiu')],
    expl: N('"본래 한 뿌리에서 났거늘" — 세설신어가 전하는 칠보시예요.', '「本是れ同根より生ぜしに」 — 世説新語が伝える七歩詩です。', '"Born of the very same root…" — the seven-pace poem of the Shishuo Xinyu.'),
    link: { type: 'quote', slug: 'caozhi-beans' } },
  { id: 'm20', q: N('사마의가 위나라 실권을 장악한 정변은?', '司馬懿が魏の実権を掌握した政変は？', 'In which coup did Sima Yi seize control of Wei?'),
    c: [N('고평릉 정변', '高平陵の変', 'The Gaopingling coup'), N('종회의 난', '鍾会の乱', 'Zhong Hui’s revolt'), N('십상시의 난', '十常侍の乱', 'The Ten Eunuchs incident'), N('의대조 사건', '衣帯詔事件', 'The girdle edict plot')],
    expl: N('십 년 가까운 은인자중 끝의 단 한 수였어요.', '十年近い雌伏の末の、たった一手でした。', 'One stroke, after nearly a decade of feigned retirement.'),
    link: { type: 'char', slug: 'sima-yi' } },
  { id: 'm21', q: N('촉한이 멸망한 해는?', '蜀漢が滅亡した年は？', 'In what year did Shu-Han fall?'),
    c: [N('263년', '263年', 'AD 263'), N('220년', '220年', 'AD 220'), N('280년', '280年', 'AD 280'), N('234년', '234年', 'AD 234')],
    expl: N('위군이 험로를 넘어 성도를 급습하자 유선이 항복했어요.', '魏軍が険路を越えて成都を急襲し、劉禅が降伏しました。', 'Wei’s columns crossed the mountains and Liu Shan surrendered Chengdu.') },
  { id: 'm22', q: N('"지금 우리 기세는 대나무를 쪼개는 것 같다"고 말한 진의 장수는?', '「今我が軍の勢いは竹を割るがごとし」と言った晋の将は？', 'Which Jin general coined "the force that splits bamboo"?'),
    c: [N('두예', '杜預', 'Du Yu'), N('왕준', '王濬', 'Wang Jun'), N('양호', '羊祜', 'Yang Hu'), N('사마염', '司馬炎', 'Sima Yan')],
    expl: N('오 정벌 중 철군 건의를 물리치며 한 말 — 파죽지세의 어원이에요.', '呉征伐中、撤退の進言を退けて言った言葉 — 破竹の勢いの語源です。', 'Said while overruling calls to pause the conquest of Wu — the idiom’s origin.'),
    link: { type: 'idiom', slug: 'pajukjise' } },
  { id: 'm23', q: N('마초의 아버지는?', '馬超の父は？', 'Who was Ma Chao’s father?'),
    c: [N('마등', '馬騰', 'Ma Teng'), N('마량', '馬良', 'Ma Liang'), N('마대', '馬岱', 'Ma Dai'), N('마원', '馬援', 'Ma Yuan')],
    expl: N('서량의 군벌로, 마초 거병 후 조정에서 처형되었어요.', '西涼の軍閥で、馬超の挙兵後に朝廷で処刑されました。', 'The Xiliang warlord, executed at court after his son’s rising.'),
    link: { type: 'char', slug: 'ma-teng' } },
  { id: 'm24', q: N('조조를 떠나 여포의 참모가 된 책사는?', '曹操のもとを離れ呂布の参謀になった策士は？', 'Which strategist left Cao Cao to advise Lü Bu?'),
    c: [N('진궁', '陳宮', 'Chen Gong'), N('가후', '賈詡', 'Jia Xu'), N('전풍', '田豊', 'Tian Feng'), N('저수', '沮授', 'Ju Shou')],
    expl: N('하비에서 함께 사로잡혀 스스로 형장으로 걸어 나갔어요.', '下邳で共に捕らえられ、自ら刑場へ歩み出ました。', 'Captured with his lord at Xiapi, he walked to the block himself.'),
    link: { type: 'char', slug: 'chen-gong' } },
  { id: 'm25', q: N('손견의 별명은?', '孫堅の異名は？', 'What was Sun Jian called?'),
    c: [N('강동의 호랑이', '江東の虎', 'The Tiger of Jiangdong'), N('소패왕', '小覇王', 'The Little Conqueror'), N('비장', '飛将', 'The Flying General'), N('금마초', '錦馬超', 'Splendid Ma Chao')],
    expl: N('소패왕은 아들 손책, 비장은 여포의 별명이에요.', '小覇王は息子の孫策、飛将は呂布の異名です。', 'The Little Conqueror was his son Sun Ce; the Flying General, Lü Bu.'),
    link: { type: 'char', slug: 'sun-jian' } },
  { id: 'm26', q: N('신정에서 손책과 일기토를 벌인 뒤 그 심복이 된 장수는?', '神亭で孫策と一騎打ちの末、腹心となった将は？', 'Who dueled Sun Ce at Shenting and later became his devoted officer?'),
    c: [N('태사자', '太史慈', 'Taishi Ci'), N('감녕', '甘寧', 'Gan Ning'), N('주태', '周泰', 'Zhou Tai'), N('황개', '黄蓋', 'Huang Gai')],
    expl: N('"약속한 날짜에 돌아오겠다"는 신의의 일화로도 유명해요.', '「約束の日に戻る」という信義の逸話でも有名です。', 'Famed, too, for keeping his promise to return by the appointed day.'),
    link: { type: 'char', slug: 'taishi-ci' } },
  { id: 'm27', q: N('유수구에서 "아들을 낳으려면 손중모 같아야"라고 감탄한 사람은?', '濡須口で「子を持つなら孫仲謀のようであれ」と感嘆した人は？', 'Who sighed "a son should be like Sun Zhongmou" at Ruxukou?'),
    c: [N('조조', '曹操', 'Cao Cao'), N('유비', '劉備', 'Liu Bei'), N('조비', '曹丕', 'Cao Pi'), N('유표', '劉表', 'Liu Biao')],
    expl: N('적장에게 바친 최고의 찬사 — 유표의 아들들과의 대비였어요.', '敵将に捧げた最高の賛辞 — 劉表の息子たちとの対比でした。', 'The finest praise an enemy ever paid — with Liu Biao’s sons as the foil.'),
    link: { type: 'quote', slug: 'caocao-sun-quan' } },
  { id: 'm28', q: N('관우의 수몰칠군 때 통째로 수장된 위군의 지휘관은?', '関羽の水淹七軍で丸ごと水没した魏軍の指揮官は？', 'Whose seven armies did Guan Yu drown at Fancheng?'),
    c: [N('우금', '于禁', 'Yu Jin'), N('조인', '曹仁', 'Cao Ren'), N('서황', '徐晃', 'Xu Huang'), N('장료', '張遼', 'Zhang Liao')],
    expl: N('우금은 항복했고, 조인은 성을 지켰으며, 서황이 포위를 풀었어요.', '于禁は降伏し、曹仁は城を守り、徐晃が包囲を解きました。', 'Yu Jin surrendered; Cao Ren held the walls; Xu Huang broke the siege.'),
    link: { type: 'battle', slug: 'fancheng' } },
  { id: 'm29', q: N('제갈량의 친형으로 오나라를 섬긴 인물은?', '諸葛亮の実兄で呉に仕えた人物は？', 'Which brother of Zhuge Liang served Wu?'),
    c: [N('제갈근', '諸葛瑾', 'Zhuge Jin'), N('제갈각', '諸葛恪', 'Zhuge Ke'), N('제갈탄', '諸葛誕', 'Zhuge Dan'), N('제갈첨', '諸葛瞻', 'Zhuge Zhan')],
    expl: N('형제는 공적인 자리에서만 만나는 원칙을 평생 지켰어요.', '兄弟は公の場でのみ会う原則を生涯守りました。', 'The brothers met only on official business, all their lives.'),
    link: { type: 'char', slug: 'zhuge-jin' } },
  { id: 'm30', q: N('위·촉·오 중 가장 늦게 멸망한 나라는?', '魏・蜀・呉のうち最も遅く滅亡した国は？', 'Which of the three kingdoms fell last?'),
    c: [N('오', '呉', 'Wu'), N('위', '魏', 'Wei'), N('촉', '蜀', 'Shu'), N('셋 다 같은 해', '三国とも同じ年', 'All in the same year')],
    expl: N('촉 263 → 위 265(선양) → 오 280 순이에요.', '蜀263 → 魏265（禅譲） → 呉280の順です。', 'Shu in 263, Wei in 265 (by abdication), Wu in 280.'),
    link: { type: 'battle', slug: 'conquest-of-wu' } },
]
