// 삼국지 공유 사건 데이터 — 인물 사전의 "주요 사건"과 연표(배치3)가 공유한다 (t3 ④ 중복 입력 금지 규칙).
// year는 정사 기준, 연의에만 있는 사건은 src:'novel'. 인물 생몰은 인물 데이터에서 파생하므로 여기 없음.
import type { TKL, TKSrc } from './tkCommon'
import { EVENTS_EXTRA } from './threeKingdomsEventsExtra'

export type TKEventType = 'battle' | 'politics' | 'other'

export interface TKEvent {
  id: string
  year: number
  type: TKEventType
  src: Extract<TKSrc, 'history' | 'novel'>
  title: TKL
  desc: TKL // 1–2문장
  people: string[] // 공통 인물 ID
}

const EVENTS_A: TKEvent[] = [
  { id: 'yellow-turban', year: 184, type: 'battle', src: 'history',
    title: { ko: '황건적의 난', ja: '黄巾の乱', en: 'Yellow Turban Rebellion' },
    desc: { ko: '장각이 이끄는 태평도 신도들이 전국에서 봉기하며 삼국시대의 막이 오른다. 유비·조조·손견이 토벌전에서 처음 이름을 알렸다.', ja: '張角率いる太平道の信徒が全国で蜂起し、三国時代の幕が上がる。劉備・曹操・孫堅が討伐戦で初めて名を上げた。', en: 'Zhang Jiao’s Taiping followers rise across the empire, opening the Three Kingdoms era. Liu Bei, Cao Cao and Sun Jian first made their names in the suppression.' },
    people: ['zhang-jiao', 'liu-bei', 'cao-cao', 'sun-jian', 'guan-yu', 'zhang-fei'] },
  { id: 'peach-oath', year: 184, type: 'other', src: 'novel',
    title: { ko: '도원결의', ja: '桃園の誓い', en: 'The Peach Garden Oath' },
    desc: { ko: '유비·관우·장비가 복숭아밭에서 의형제를 맺는 연의의 첫 장면. 정사에는 "은혜가 형제와 같았다"고만 전한다.', ja: '劉備・関羽・張飛が桃園で義兄弟の契りを結ぶ演義の冒頭場面。正史には「恩は兄弟のごとし」とのみ伝わる。', en: 'Liu Bei, Guan Yu and Zhang Fei swear brotherhood in a peach orchard — the novel’s opening scene; the histories say only their bond was "like brothers".' },
    people: ['liu-bei', 'guan-yu', 'zhang-fei'] },
  { id: 'shishangshi', year: 189, type: 'politics', src: 'history',
    title: { ko: '십상시의 난과 하진의 죽음', ja: '十常侍の乱と何進の死', en: 'The Ten Eunuchs and the Death of He Jin' },
    desc: { ko: '대장군 하진이 환관 세력 제거를 꾀하다 역으로 살해되고, 낙양은 유혈 사태에 빠진다. 이 혼란이 동탁을 불러들였다.', ja: '大将軍・何進が宦官勢力の排除を図って逆に殺害され、洛陽は流血の事態に陥る。この混乱が董卓を呼び込んだ。', en: 'Grand General He Jin plots to purge the eunuchs and is murdered instead, plunging Luoyang into bloodshed — the chaos that invited Dong Zhuo in.' },
    people: ['he-jin', 'dong-zhuo', 'yuan-shao'] },
  { id: 'dongzhuo-seizes', year: 189, type: 'politics', src: 'history',
    title: { ko: '동탁의 집권과 헌제 옹립', ja: '董卓の専横と献帝擁立', en: 'Dong Zhuo Seizes Power' },
    desc: { ko: '낙양에 입성한 동탁이 소제를 폐하고 헌제를 세워 조정을 장악한다. 폭정이 시작되자 천하의 제후들이 등을 돌렸다.', ja: '洛陽に入った董卓が少帝を廃して献帝を立て、朝廷を掌握。暴政が始まると天下の諸侯が背を向けた。', en: 'Entering Luoyang, Dong Zhuo deposes the boy emperor and installs Emperor Xian, seizing the court. His tyranny turned the realm’s lords against him.' },
    people: ['dong-zhuo', 'xian-di', 'lv-bu'] },
  { id: 'coalition', year: 190, type: 'politics', src: 'history',
    title: { ko: '반동탁 연합군 결성', ja: '反董卓連合の結成', en: 'The Coalition Against Dong Zhuo' },
    desc: { ko: '원소를 맹주로 한 관동 제후들이 동탁 토벌의 깃발을 든다. 조조와 손견이 가장 적극적으로 싸웠다.', ja: '袁紹を盟主とする関東の諸侯が董卓討伐の旗を掲げる。曹操と孫堅が最も積極的に戦った。', en: 'The eastern lords raise arms against Dong Zhuo under Yuan Shao. Cao Cao and Sun Jian fought hardest of all.' },
    people: ['yuan-shao', 'cao-cao', 'sun-jian', 'yuan-shu', 'gongsun-zan'] },
  { id: 'hulao', year: 191, type: 'battle', src: 'novel',
    title: { ko: '호로관 전투 (삼영전여포)', ja: '虎牢関の戦い（三英戦呂布）', en: 'Hulao Gate — Three Heroes vs. Lü Bu' },
    desc: { ko: '유비 삼형제가 호로관에서 여포와 맞붙는 연의의 명장면. 정사에서 화웅을 벤 것은 관우가 아니라 손견이다.', ja: '劉備三兄弟が虎牢関で呂布と戦う演義の名場面。正史で華雄を斬ったのは関羽ではなく孫堅である。', en: 'The novel’s famous duel of the three brothers against Lü Bu at Hulao Gate. In the histories it was Sun Jian, not Guan Yu, who slew Hua Xiong.' },
    people: ['lv-bu', 'liu-bei', 'guan-yu', 'zhang-fei', 'sun-jian'] },
  { id: 'dongzhuo-death', year: 192, type: 'politics', src: 'history',
    title: { ko: '왕윤과 여포, 동탁을 주살', ja: '王允と呂布、董卓を誅殺', en: 'Wang Yun and Lü Bu Kill Dong Zhuo' },
    desc: { ko: '사도 왕윤의 계략에 여포가 가담해 동탁을 벤다. 연의는 이 사이에 가공인물 초선의 연환계를 끼워 넣어 극화했다.', ja: '司徒・王允の策に呂布が加わり、董卓を斬る。演義はここに架空の人物・貂蟬の連環の計を挟んで脚色した。', en: 'Minister Wang Yun’s plot wins over Lü Bu, who cuts down Dong Zhuo. The novel dramatizes it with the fictional Diao Chan’s double scheme.' },
    people: ['wang-yun', 'lv-bu', 'dong-zhuo', 'diao-chan'] },
  { id: 'sunjian-death', year: 192, type: 'battle', src: 'history',
    title: { ko: '손견 전사', ja: '孫堅の戦死', en: 'Death of Sun Jian' },
    desc: { ko: '강동의 호랑이 손견이 유표 토벌전에서 복병의 화살에 쓰러진다. 아들 손책이 그 유지를 잇는다.', ja: '江東の虎・孫堅が劉表討伐戦で伏兵の矢に倒れる。息子の孫策がその遺志を継ぐ。', en: 'Sun Jian, Tiger of Jiangdong, falls to an ambush while campaigning against Liu Biao. His son Sun Ce takes up his cause.' },
    people: ['sun-jian', 'liu-biao', 'sun-ce'] },
  { id: 'puyang', year: 194, type: 'battle', src: 'history',
    title: { ko: '조조-여포 연주 쟁탈전', ja: '曹操と呂布の兗州争奪戦', en: 'Cao Cao vs. Lü Bu for Yan Province' },
    desc: { ko: '진궁의 계책으로 여포가 조조의 본거지 연주를 급습, 복양에서 조조와 사투를 벌인다. 조조는 근거지를 겨우 되찾았다.', ja: '陳宮の策で呂布が曹操の本拠・兗州を急襲し、濮陽で死闘を繰り広げる。曹操は根拠地をかろうじて取り戻した。', en: 'On Chen Gong’s counsel, Lü Bu storms Cao Cao’s home province of Yan; savage fighting at Puyang follows before Cao Cao claws it back.' },
    people: ['cao-cao', 'lv-bu', 'chen-gong', 'dian-wei', 'xiahou-dun'] },
  { id: 'taishici-duel', year: 195, type: 'battle', src: 'history',
    title: { ko: '손책의 강동 평정과 태사자', ja: '孫策の江東平定と太史慈', en: 'Sun Ce Conquers the Southland' },
    desc: { ko: '손책이 부친의 옛 부하들을 이끌고 강동 정복에 나선다. 신정에서 일기토를 벌인 태사자를 사로잡아 심복으로 삼은 일화가 유명하다.', ja: '孫策が父の旧臣を率いて江東征服に乗り出す。神亭で一騎打ちした太史慈を捕らえ、腹心にした逸話が有名。', en: 'Sun Ce sets out to conquer the Southland with his father’s veterans. After their famous duel at Shenting, he captured Taishi Ci and won him over.' },
    people: ['sun-ce', 'taishi-ci', 'zhou-yu', 'huang-gai', 'cheng-pu'] },
  { id: 'xiandi-xudu', year: 196, type: 'politics', src: 'history',
    title: { ko: '조조, 헌제를 허도로 모시다', ja: '曹操、献帝を許都に迎える', en: 'Cao Cao Takes Custody of the Emperor' },
    desc: { ko: '순욱의 진언에 따라 조조가 유랑하던 헌제를 허도로 맞아들인다. "천자를 끼고 제후를 호령"하는 위 패권의 초석이 되었다.', ja: '荀彧の進言に従い、曹操が流浪していた献帝を許都に迎える。「天子を擁して諸侯に号令する」魏の覇権の礎となった。', en: 'On Xun Yu’s counsel, Cao Cao brings the wandering Emperor Xian to Xudu — the cornerstone of "commanding the lords in the Son of Heaven’s name."' },
    people: ['cao-cao', 'xian-di', 'xun-yu'] },
  { id: 'wancheng', year: 197, type: 'battle', src: 'history',
    title: { ko: '완성 전투 — 전위의 최후', ja: '宛城の戦い — 典韋の最期', en: 'Battle of Wancheng — Dian Wei’s Last Stand' },
    desc: { ko: '항복했던 장수가 가후의 계책으로 야습을 감행, 조조는 호위장 전위의 결사 항전 덕에 목숨만 건져 달아났다.', ja: '降伏していた張繡が賈詡の策で夜襲を敢行。曹操は護衛の典韋の決死の奮戦でかろうじて逃げ延びた。', en: 'The surrendered Zhang Xiu strikes at night on Jia Xu’s plan; Cao Cao escapes with his life only through bodyguard Dian Wei’s dying stand.' },
    people: ['cao-cao', 'dian-wei', 'jia-xu'] },
  { id: 'yuanshu-emperor', year: 197, type: 'politics', src: 'history',
    title: { ko: '원술의 참칭', ja: '袁術の皇帝僭称', en: 'Yuan Shu Declares Himself Emperor' },
    desc: { ko: '옥새를 손에 넣은 원술이 스스로 황제를 칭하지만, 천하의 공적이 되어 2년 만에 몰락한다.', ja: '玉璽を手にした袁術が自ら皇帝を称するが、天下の公敵となり2年で没落する。', en: 'Holding the Imperial Seal, Yuan Shu proclaims himself emperor — making himself the realm’s common enemy and collapsing within two years.' },
    people: ['yuan-shu'] },
  { id: 'xiapi', year: 198, type: 'battle', src: 'history',
    title: { ko: '하비 전투 — 여포의 최후', ja: '下邳の戦い — 呂布の最期', en: 'Siege of Xiapi — the End of Lü Bu' },
    desc: { ko: '조조와 유비 연합군이 하비성의 여포를 수공으로 몰아붙인다. 부하에게 배신당해 사로잡힌 여포는 처형되고, 진궁도 최후를 함께했다.', ja: '曹操と劉備の連合軍が下邳城の呂布を水攻めで追い詰める。部下に裏切られ捕らえられた呂布は処刑され、陳宮も最期を共にした。', en: 'Cao Cao and Liu Bei flood Lü Bu out of Xiapi. Betrayed by his own men, Lü Bu is captured and executed; Chen Gong dies with him.' },
    people: ['cao-cao', 'lv-bu', 'liu-bei', 'chen-gong', 'zhang-liao'] },
  { id: 'yijing', year: 199, type: 'battle', src: 'history',
    title: { ko: '역경 함락 — 공손찬의 최후', ja: '易京陥落 — 公孫瓚の最期', en: 'Fall of Yijing — Gongsun Zan’s End' },
    desc: { ko: '북방의 백마장군 공손찬이 원소에게 포위된 역경 요새에서 스스로 목숨을 끊는다. 하북은 원소의 천하가 되었다.', ja: '北方の白馬将軍・公孫瓚が袁紹に包囲された易京の要塞で自ら命を絶つ。河北は袁紹の天下となった。', en: 'Gongsun Zan, the White Horse General, dies by his own hand in his besieged fortress of Yijing. The north falls to Yuan Shao.' },
    people: ['gongsun-zan', 'yuan-shao'] },
  { id: 'baima', year: 200, type: 'battle', src: 'history',
    title: { ko: '백마 전투 — 관우, 안량을 베다', ja: '白馬の戦い — 関羽、顔良を斬る', en: 'Battle of Baima — Guan Yu Slays Yan Liang' },
    desc: { ko: '조조에게 일시 몸을 의탁한 관우가 원소군 대장 안량을 대군 한가운데서 베어 은혜를 갚고, 곧 유비에게 돌아간다.', ja: '曹操に一時身を寄せていた関羽が、袁紹軍の大将・顔良を大軍のただ中で斬って恩に報い、まもなく劉備のもとへ帰る。', en: 'Temporarily serving Cao Cao, Guan Yu repays the debt by cutting down Yuan Shao’s general Yan Liang amid his army — then rides back to Liu Bei.' },
    people: ['guan-yu', 'cao-cao', 'yuan-shao'] },
  { id: 'guandu', year: 200, type: 'battle', src: 'history',
    title: { ko: '관도대전', ja: '官渡の戦い', en: 'Battle of Guandu' },
    desc: { ko: '조조가 오소의 군량 기습으로 몇 배 규모의 원소군을 무너뜨린 북방 패권전. 장합이 이때 조조에게 투항했다.', ja: '曹操が烏巣の兵糧急襲で数倍規模の袁紹軍を崩した北方の覇権戦。張郃はこのとき曹操に降った。', en: 'Cao Cao shatters Yuan Shao’s far larger host by burning the Wuchao grain depot — the war for the north. Zhang He defected to Cao Cao here.' },
    people: ['cao-cao', 'yuan-shao', 'xun-yu', 'guo-jia', 'zhang-he', 'xu-huang'] },
  { id: 'sunce-death', year: 200, type: 'politics', src: 'history',
    title: { ko: '손책 급서, 손권 계승', ja: '孫策急死、孫権の継承', en: 'Sun Ce Dies; Sun Quan Succeeds' },
    desc: { ko: '자객의 습격으로 쓰러진 소패왕 손책이 열아홉 아우 손권에게 강동을 맡긴다. 장소와 주유가 어린 주군을 떠받쳤다.', ja: '刺客の襲撃に倒れた小覇王・孫策が、十九歳の弟・孫権に江東を託す。張昭と周瑜が若い主君を支えた。', en: 'Struck down by assassins, Sun Ce entrusts the Southland to his 19-year-old brother Sun Quan, propped up by Zhang Zhao and Zhou Yu.' },
    people: ['sun-ce', 'sun-quan', 'zhang-zhao', 'zhou-yu'] },
  { id: 'guanyu-five-passes', year: 200, type: 'other', src: 'novel',
    title: { ko: '관우 오관참육장', ja: '関羽、五関六将を斬る', en: 'Guan Yu Crosses Five Passes' },
    desc: { ko: '유비를 찾아 떠난 관우가 다섯 관문을 돌파하며 여섯 장수를 벤다는 연의의 창작 여정. 충의의 아이콘이 된 장면이다.', ja: '劉備を求めて旅立った関羽が五つの関所を突破し六将を斬るという演義の創作の道程。忠義の象徴となった場面。', en: 'The novel’s invented journey: Guan Yu breaks through five passes and slays six generals to rejoin Liu Bei — the defining image of loyalty.' },
    people: ['guan-yu', 'liu-bei', 'cao-cao'] },
  { id: 'yuanshao-death', year: 202, type: 'politics', src: 'history',
    title: { ko: '원소 병사', ja: '袁紹病死', en: 'Death of Yuan Shao' },
    desc: { ko: '관도 패전의 화병 속에 하북의 맹주 원소가 세상을 떠난다. 아들들의 내분으로 원가는 급속히 무너졌다.', ja: '官渡の敗戦の失意の中、河北の盟主・袁紹が世を去る。息子たちの内紛で袁家は急速に崩れた。', en: 'Broken by Guandu, Yuan Shao dies; his sons’ infighting brings the great northern house down in short order.' },
    people: ['yuan-shao', 'cao-cao'] },
  { id: 'xushu-leaves', year: 208, type: 'politics', src: 'history',
    title: { ko: '서서, 유비 곁을 떠나다', ja: '徐庶、劉備のもとを去る', en: 'Xu Shu Leaves Liu Bei' },
    desc: { ko: '유비의 참모 서서가 조조군에 억류된 어머니 때문에 눈물로 떠난다. 떠나며 천거한 인재가 제갈량이었다.', ja: '劉備の参謀・徐庶が曹操軍に抑留された母のため、涙ながらに去る。去り際に推挙した人材が諸葛亮だった。', en: 'Liu Bei’s adviser Xu Shu departs in tears for his captive mother’s sake — recommending, as he leaves, a man named Zhuge Liang.' },
    people: ['xu-shu', 'liu-bei', 'zhuge-liang', 'cao-cao'] },
  { id: 'sangu', year: 207, type: 'politics', src: 'history',
    title: { ko: '삼고초려', ja: '三顧の礼', en: 'Three Visits to the Cottage' },
    desc: { ko: '유비가 세 번 찾아간 끝에 제갈량을 얻고, 천하삼분지계를 듣는다. 정사 출사표에 제갈량 스스로 기록한 사건이다.', ja: '劉備が三度訪ねた末に諸葛亮を得て、天下三分の計を聞く。正史の出師表に諸葛亮自身が記した出来事。', en: 'After three visits Liu Bei wins Zhuge Liang — and hears the plan to divide the realm in three. Recorded by Zhuge Liang himself in the Chu Shi Biao.' },
    people: ['liu-bei', 'zhuge-liang', 'guan-yu', 'zhang-fei'] },
  { id: 'guojia-death', year: 207, type: 'battle', src: 'history',
    title: { ko: '백랑산 전투와 곽가의 죽음', ja: '白狼山の戦いと郭嘉の死', en: 'White Wolf Mountain and the Death of Guo Jia' },
    desc: { ko: '"병귀신속"의 진언대로 조조가 오환을 전격 격파해 북방을 평정하지만, 귀환길에 곽가를 잃는다.', ja: '「兵は神速を貴ぶ」の進言どおり曹操が烏丸を電撃撃破して北方を平定するが、帰路で郭嘉を失う。', en: 'Following Guo Jia’s "speed is everything," Cao Cao crushes the Wuhuan at White Wolf Mountain — but loses Guo Jia on the road home.' },
    people: ['cao-cao', 'guo-jia', 'zhang-liao'] },
  { id: 'liubiao-death', year: 208, type: 'politics', src: 'history',
    title: { ko: '유표 병사, 형주의 항복', ja: '劉表病死、荊州の降伏', en: 'Liu Biao Dies; Jing Province Surrenders' },
    desc: { ko: '형주의 주인 유표가 죽자 뒤를 이은 아들이 남하하는 조조에게 싸움 없이 항복한다. 유비는 남쪽으로 쫓기게 되었다.', ja: '荊州の主・劉表が死ぬと、跡を継いだ息子が南下する曹操に戦わずして降伏。劉備は南へ追われることになった。', en: 'When Liu Biao dies, his heir surrenders Jing Province to the advancing Cao Cao without a fight, sending Liu Bei fleeing south.' },
    people: ['liu-biao', 'cao-cao', 'liu-bei'] },
  { id: 'changban', year: 208, type: 'battle', src: 'history',
    title: { ko: '장판파 전투', ja: '長坂の戦い', en: 'Battle of Changban' },
    desc: { ko: '조조의 추격에 궤멸 직전까지 몰린 유비군. 조운이 단기로 유비의 아들을 구출하고, 장비는 다리 위에서 홀로 추격군을 멈춰 세웠다.', ja: '曹操の追撃で壊滅寸前まで追い込まれた劉備軍。趙雲が単騎で劉備の子を救出し、張飛は橋上でただ一人追撃軍を止めた。', en: 'Cao Cao’s pursuit nearly annihilates Liu Bei’s column. Zhao Yun rides alone to rescue Liu Bei’s infant son; Zhang Fei halts the pursuers single-handed at the bridge.' },
    people: ['liu-bei', 'cao-cao', 'zhao-yun', 'zhang-fei'] },
  { id: 'red-cliffs', year: 208, type: 'battle', src: 'history',
    title: { ko: '적벽대전', ja: '赤壁の戦い', en: 'Battle of Red Cliffs' },
    desc: { ko: '주유가 이끄는 손유 연합군이 화공으로 조조의 대함대를 불태워 남진을 좌절시킨다. 천하삼분의 구도가 여기서 굳어졌다.', ja: '周瑜率いる孫劉連合軍が火攻めで曹操の大艦隊を焼き払い、南進を挫く。天下三分の構図がここで固まった。', en: 'Zhou Yu’s Sun–Liu alliance burns Cao Cao’s armada with fire ships, halting his southern conquest. The three-way division of the realm was sealed here.' },
    people: ['zhou-yu', 'cao-cao', 'sun-quan', 'liu-bei', 'zhuge-liang', 'huang-gai', 'lu-su', 'cheng-pu', 'gan-ning'] },
  { id: 'jiangling', year: 209, type: 'battle', src: 'history',
    title: { ko: '강릉 공방전', ja: '江陵攻防戦', en: 'Siege of Jiangling' },
    desc: { ko: '적벽의 여세를 몰아 주유가 조인이 지키는 강릉을 1년여의 격전 끝에 빼앗는다. 주유는 이 싸움에서 화살을 맞았다.', ja: '赤壁の勢いに乗り、周瑜が曹仁の守る江陵を一年余りの激戦の末に奪う。周瑜はこの戦いで矢傷を負った。', en: 'Riding Red Cliffs’ momentum, Zhou Yu wrests Jiangling from Cao Ren after a year of hard fighting — taking an arrow wound himself.' },
    people: ['zhou-yu', 'cao-ren', 'gan-ning'] },
  { id: 'zhouyu-death', year: 210, type: 'politics', src: 'history',
    title: { ko: '주유 병사', ja: '周瑜病死', en: 'Death of Zhou Yu' },
    desc: { ko: '적벽의 명장 주유가 36세로 요절하고, 후임 노숙이 손유 동맹 유지의 축이 된다.', ja: '赤壁の名将・周瑜が36歳で早世し、後任の魯粛が孫劉同盟維持の軸となる。', en: 'Zhou Yu, hero of Red Cliffs, dies at 36; his successor Lu Su becomes the pillar of the Sun–Liu alliance.' },
    people: ['zhou-yu', 'lu-su', 'sun-quan'] },
  { id: 'tongguan', year: 211, type: 'battle', src: 'history',
    title: { ko: '동관 전투 — 마초의 거병', ja: '潼関の戦い — 馬超の挙兵', en: 'Battle of Tong Pass — Ma Chao Rises' },
    desc: { ko: '마초가 서량 연합군을 이끌고 조조와 격돌한다. 수염을 자르며 달아났다는 일화가 남을 만큼 조조를 몰아붙였지만, 가후의 이간계에 무너졌다.', ja: '馬超が西涼連合軍を率いて曹操と激突。髭を切って逃げたという逸話が残るほど曹操を追い詰めたが、賈詡の離間の計に崩れた。', en: 'Ma Chao’s Xiliang coalition slams into Cao Cao — pressing him so hard legend says he cut off his beard to flee — before Jia Xu’s discord scheme broke the alliance.' },
    people: ['ma-chao', 'cao-cao', 'jia-xu', 'xu-chu'] },
  { id: 'xunyu-death', year: 212, type: 'politics', src: 'history',
    title: { ko: '순욱의 죽음', ja: '荀彧の死', en: 'Death of Xun Yu' },
    desc: { ko: '조조의 위공 취임에 반대한 왕좌지재 순욱이 실의 속에 세상을 떠난다. 한실을 향한 신념과 주군 사이에서 갈라진 최후였다.', ja: '曹操の魏公就任に反対した王佐の才・荀彧が失意の中で世を去る。漢室への信念と主君の間で引き裂かれた最期だった。', en: 'Xun Yu, the "talent fit to aid kings," dies in despair after opposing Cao Cao’s elevation — torn between his lord and his loyalty to the Han.' },
    people: ['xun-yu', 'cao-cao'] },
  { id: 'mateng-death', year: 212, type: 'politics', src: 'history',
    title: { ko: '마등 처형', ja: '馬騰処刑', en: 'Execution of Ma Teng' },
    desc: { ko: '아들 마초의 거병에 대한 보복으로 조조가 조정에 있던 마등 일족을 처형한다. 마초의 복수심은 더 깊어졌다.', ja: '息子・馬超の挙兵への報復として、曹操が朝廷にいた馬騰一族を処刑。馬超の復讐心はさらに深まった。', en: 'In reprisal for Ma Chao’s rising, Cao Cao executes Ma Teng and his kin at court — deepening the son’s thirst for vengeance.' },
    people: ['ma-teng', 'ma-chao', 'cao-cao'] },
  { id: 'ruxukou', year: 213, type: 'battle', src: 'history',
    title: { ko: '유수구 전투', ja: '濡須口の戦い', en: 'Battle of Ruxukou' },
    desc: { ko: '조조의 남정을 손권이 유수구에서 막아선다. 감녕의 백기 야습과 주태의 분전, 그리고 "아들을 낳으려면 손중모 같아야"라는 조조의 탄식이 전한다.', ja: '曹操の南征を孫権が濡須口で阻む。甘寧の百騎夜襲と周泰の奮戦、そして「子を持つなら孫仲謀のようであれ」という曹操の嘆息が伝わる。', en: 'Sun Quan blocks Cao Cao at Ruxukou — Gan Ning’s hundred-rider night raid, Zhou Tai’s valor, and Cao Cao’s sigh: "If one must have a son, let him be like Sun Quan."' },
    people: ['sun-quan', 'cao-cao', 'gan-ning', 'zhou-tai'] },
  { id: 'yizhou', year: 214, type: 'battle', src: 'history',
    title: { ko: '유비의 익주 평정', ja: '劉備の益州平定', en: 'Liu Bei Takes Yi Province' },
    desc: { ko: '법정의 내응과 제갈량·장비·조운의 증원으로 유비가 성도에 입성한다. 낙성 공방에서 군사 방통을 잃는 대가를 치렀다.', ja: '法正の内応と諸葛亮・張飛・趙雲の増援で劉備が成都に入城。雒城攻防で軍師・龐統を失う代償を払った。', en: 'With Fa Zheng’s defection and reinforcements under Zhuge Liang, Zhang Fei and Zhao Yun, Liu Bei enters Chengdu — at the cost of his strategist Pang Tong at Luocheng.' },
    people: ['liu-bei', 'fa-zheng', 'pang-tong', 'zhuge-liang', 'zhang-fei', 'zhao-yun', 'ma-chao'] },
  { id: 'xiangshui', year: 215, type: 'politics', src: 'history',
    title: { ko: '익양 대치와 상수 협약', ja: '益陽対峙と湘水の和議', en: 'The Xiang River Accord' },
    desc: { ko: '형주 반환을 둘러싸고 관우와 노숙이 익양에서 대치한다(단도부회). 결국 상수를 경계로 형주를 나누는 선에서 타협했다.', ja: '荊州返還を巡り関羽と魯粛が益陽で対峙（単刀赴会）。結局、湘水を境に荊州を分けることで妥協した。', en: 'Guan Yu and Lu Su face off at Yiyang over Jing Province — the single-blade parley — settling on a split along the Xiang River.' },
    people: ['guan-yu', 'lu-su', 'sun-quan', 'liu-bei', 'zhuge-jin'] },
  { id: 'hefei', year: 215, type: 'battle', src: 'history',
    title: { ko: '합비 전투 — 장료의 800', ja: '合肥の戦い — 張遼の八百', en: 'Battle of Hefei — Zhang Liao’s 800' },
    desc: { ko: '장료가 800 결사대로 손권의 10만 대군을 기습해 무너뜨린다. "장료가 온다"는 말이 강동 아이들 울음을 그치게 했다고 전한다.', ja: '張遼が八百の決死隊で孫権の十万の大軍を奇襲して崩す。「遼来来」の名が江東の子どもの泣き声を止めたと伝わる。', en: 'Zhang Liao’s 800 volunteers shatter Sun Quan’s host of 100,000 in a dawn assault — his very name, it was said, silenced crying children in Wu.' },
    people: ['zhang-liao', 'sun-quan', 'gan-ning', 'taishi-ci'] },
  { id: 'dingjun', year: 219, type: 'battle', src: 'history',
    title: { ko: '정군산 전투', ja: '定軍山の戦い', en: 'Battle of Mount Dingjun' },
    desc: { ko: '법정의 계책 아래 노장 황충이 위의 서부 총사령 하후연을 벤다. 이 승리로 유비는 한중을 손에 넣었다.', ja: '法正の策のもと、老将・黄忠が魏の西部総帥・夏侯淵を斬る。この勝利で劉備は漢中を手にした。', en: 'Under Fa Zheng’s direction, the veteran Huang Zhong cuts down Xiahou Yuan, Wei’s western commander — the stroke that won Hanzhong for Liu Bei.' },
    people: ['huang-zhong', 'xiahou-yuan', 'fa-zheng', 'liu-bei', 'zhao-yun', 'zhang-he'] },
  { id: 'hanzhong-king', year: 219, type: 'politics', src: 'history',
    title: { ko: '유비, 한중왕에 오르다', ja: '劉備、漢中王に', en: 'Liu Bei Becomes King of Hanzhong' },
    desc: { ko: '한중을 확보한 유비가 왕위에 올라 조조와 대등한 격을 갖춘다. 관우·장비·조운·마초·황충이 오호대장군 반열에 들었다(연의의 명칭).', ja: '漢中を確保した劉備が王位に上り、曹操と対等の格を備える。関羽・張飛・趙雲・馬超・黄忠が五虎大将の列に入った（演義の呼称）。', en: 'Master of Hanzhong, Liu Bei takes a royal title to match Cao Cao. Guan Yu, Zhang Fei, Zhao Yun, Ma Chao and Huang Zhong became the Five Tiger Generals (the novel’s term).' },
    people: ['liu-bei', 'guan-yu', 'zhang-fei', 'zhao-yun', 'ma-chao', 'huang-zhong'] },
  { id: 'fancheng', year: 219, type: 'battle', src: 'history',
    title: { ko: '번성 전투 — 수몰칠군', ja: '樊城の戦い — 水淹七軍', en: 'Siege of Fancheng' },
    desc: { ko: '관우가 홍수를 이용해 위의 칠군을 수장시키고 화하를 뒤흔든다. 조인이 번성을 사수하고 서황의 구원군이 포위를 풀었다.', ja: '関羽が洪水を利用して魏の七軍を水没させ、華夏を震撼させる。曹仁が樊城を死守し、徐晃の援軍が包囲を解いた。', en: 'Guan Yu drowns seven Wei armies in the flood and shakes the heartland. Cao Ren holds Fancheng until Xu Huang’s relief breaks the siege.' },
    people: ['guan-yu', 'cao-ren', 'xu-huang', 'cao-cao'] },
  { id: 'jingzhou-fall', year: 219, type: 'battle', src: 'history',
    title: { ko: '여몽의 형주 기습 — 관우의 최후', ja: '呂蒙の荊州奇襲 — 関羽の最期', en: 'Lü Meng Takes Jing Province — the Death of Guan Yu' },
    desc: { ko: '여몽이 상인으로 위장한 병사들로 형주를 무혈 접수한다(백의도강). 퇴로가 끊긴 관우는 맥성에서 사로잡혀 최후를 맞았다.', ja: '呂蒙が商人に偽装した兵で荊州を無血接収（白衣渡江）。退路を断たれた関羽は麦城で捕らえられ、最期を迎えた。', en: 'Lü Meng’s soldiers, disguised as merchants, seize Jing Province without a fight. His retreat cut, Guan Yu is captured at Maicheng and executed.' },
    people: ['lv-meng', 'guan-yu', 'sun-quan', 'lu-xun'] },
  { id: 'yangxiu-death', year: 219, type: 'politics', src: 'history',
    title: { ko: '계륵과 양수의 죽음', ja: '鶏肋と楊修の死', en: '"Chicken Ribs" and the Death of Yang Xiu' },
    desc: { ko: '한중 철수를 앞둔 조조의 암구호 "계륵"을 풀이한 양수가 군심을 어지럽혔다는 죄목으로 처형된다.', ja: '漢中撤退を前にした曹操の合言葉「鶏肋」を読み解いた楊修が、軍心を乱したかどで処刑される。', en: 'Yang Xiu, who decoded Cao Cao’s "chicken ribs" watchword before the Hanzhong withdrawal, is executed for unsettling the army.' },
    people: ['yang-xiu', 'cao-cao'] },
  { id: 'caocao-death', year: 220, type: 'politics', src: 'history',
    title: { ko: '조조 사망, 조비의 찬탈 — 한 멸망', ja: '曹操死去、曹丕の簒奪 — 漢の滅亡', en: 'Cao Cao Dies; Cao Pi Ends the Han' },
    desc: { ko: '난세의 간웅 조조가 66세로 눈을 감고, 아들 조비가 헌제의 선양을 받아 위 황제에 오른다. 400년 한 왕조가 막을 내렸다.', ja: '乱世の姦雄・曹操が66歳で世を去り、息子の曹丕が献帝の禅譲を受けて魏の皇帝に即位。400年の漢王朝が幕を閉じた。', en: 'Cao Cao dies at 66; his son Cao Pi accepts Emperor Xian’s abdication and takes the throne of Wei, ending four centuries of Han rule.' },
    people: ['cao-cao', 'cao-pi', 'xian-di'] },
  { id: 'huatuo-death', year: 208, type: 'politics', src: 'history',
    title: { ko: '신의 화타의 죽음', ja: '神医・華佗の死', en: 'Death of the Physician Hua Tuo' },
    desc: { ko: '조조의 시의 노릇을 거부한 명의 화타가 옥사한다. 관우의 뼈를 긁어 치료했다는 이야기는 연의의 각색이다.', ja: '曹操の侍医となることを拒んだ名医・華佗が獄死する。関羽の骨を削って治療した話は演義の脚色である。', en: 'Hua Tuo, the legendary physician who refused to be Cao Cao’s personal doctor, dies in prison. The tale of scraping Guan Yu’s bone is the novel’s embellishment.' },
    people: ['hua-tuo', 'cao-cao'] },
  { id: 'liubei-emperor', year: 221, type: 'politics', src: 'history',
    title: { ko: '유비 칭제 — 촉한 건국', ja: '劉備即位 — 蜀漢建国', en: 'Liu Bei Proclaims the Shu-Han' },
    desc: { ko: '한의 정통 계승을 내걸고 유비가 성도에서 황제에 오른다. 제갈량이 승상이 되었다.', ja: '漢の正統継承を掲げ、劉備が成都で皇帝に即位。諸葛亮が丞相となった。', en: 'Claiming the Han succession, Liu Bei takes the imperial throne at Chengdu, with Zhuge Liang as his chancellor.' },
    people: ['liu-bei', 'zhuge-liang'] },
  { id: 'zhangfei-death', year: 221, type: 'politics', src: 'history',
    title: { ko: '장비 피살', ja: '張飛暗殺', en: 'Assassination of Zhang Fei' },
    desc: { ko: '관우의 복수전을 준비하던 장비가 부하 장수들에게 살해된다. 평소 아랫사람을 엄히 다룬 것이 화가 되었다.', ja: '関羽の復讐戦を準備していた張飛が部下の将に殺害される。日頃から部下に厳しすぎたことが災いした。', en: 'Preparing to avenge Guan Yu, Zhang Fei is murdered by his own officers — the price, the histories note, of his harshness toward subordinates.' },
    people: ['zhang-fei', 'liu-bei'] },
  { id: 'yiling', year: 222, type: 'battle', src: 'history',
    title: { ko: '이릉대전', ja: '夷陵の戦い', en: 'Battle of Yiling' },
    desc: { ko: '관우의 원수를 갚으러 동정에 나선 유비를 젊은 대도독 육손이 화공 한 방으로 궤멸시킨다. 마량도 이 싸움에서 목숨을 잃었다.', ja: '関羽の仇を討つため東征した劉備を、若き大都督・陸遜が火攻めの一撃で壊滅させる。馬良もこの戦いで命を落とした。', en: 'Marching east to avenge Guan Yu, Liu Bei is annihilated by the young commander Lu Xun’s single fire attack. Ma Liang also perished in the campaign.' },
    people: ['liu-bei', 'lu-xun', 'sun-quan', 'ma-liang', 'zhao-yun'] },
  { id: 'baidicheng', year: 223, type: 'politics', src: 'history',
    title: { ko: '백제성 탁고 — 유비 붕어', ja: '白帝城の託孤 — 劉備崩御', en: 'Liu Bei’s Deathbed Trust at Baidicheng' },
    desc: { ko: '이릉의 패장 유비가 백제성에서 제갈량에게 아들 유선과 나라를 맡기고 눈을 감는다. "마속을 크게 쓰지 말라"는 유언도 이때 남겼다.', ja: '夷陵に敗れた劉備が白帝城で諸葛亮に息子・劉禅と国を託して世を去る。「馬謖を重用するな」という遺言もこのとき残した。', en: 'Defeated at Yiling, the dying Liu Bei entrusts his son Liu Shan and the state to Zhuge Liang at Baidicheng — warning him, too, not to over-promote Ma Su.' },
    people: ['liu-bei', 'zhuge-liang', 'liu-shan', 'ma-su'] },
  { id: 'nanman', year: 225, type: 'battle', src: 'history',
    title: { ko: '남만 정벌 — 칠종칠금', ja: '南蛮平定 — 七縦七擒', en: 'The Southern Campaign — Seven Captures' },
    desc: { ko: '제갈량이 남방의 반란을 평정하며 지도자 맹획을 일곱 번 잡고 일곱 번 놓아주어 마음으로 복속시킨다(한진춘추 기록).', ja: '諸葛亮が南方の反乱を平定し、指導者・孟獲を七度捕らえて七度放ち、心から服属させる（漢晋春秋の記録）。', en: 'Zhuge Liang pacifies the southern revolt, capturing and releasing the chieftain Meng Huo seven times until he submits from the heart (per the Han Jin Chunqiu).' },
    people: ['zhuge-liang', 'ma-su', 'wang-ping'] },
  { id: 'chushibiao', year: 227, type: 'politics', src: 'history',
    title: { ko: '출사표 — 북벌 개시', ja: '出師の表 — 北伐開始', en: 'The Chu Shi Biao — the Northern Campaigns Begin' },
    desc: { ko: '제갈량이 어린 황제 유선에게 출사표를 올리고 한실 부흥의 북벌에 나선다. 강유가 이 무렵 촉에 귀순했다.', ja: '諸葛亮が幼い皇帝・劉禅に出師の表を奉り、漢室復興の北伐に出る。姜維がこの頃、蜀に帰順した。', en: 'Zhuge Liang submits his memorial to the young emperor and marches north to restore the Han. Around this time Jiang Wei came over to Shu.' },
    people: ['zhuge-liang', 'liu-shan', 'jiang-wei'] },
  { id: 'jieting', year: 228, type: 'battle', src: 'history',
    title: { ko: '가정 전투 — 읍참마속', ja: '街亭の戦い — 泣いて馬謖を斬る', en: 'Battle of Jieting' },
    desc: { ko: '마속이 지시를 어기고 산 위에 진을 쳤다가 장합에게 대패, 1차 북벌이 물거품이 된다. 왕평만이 부대를 보전했고, 제갈량은 눈물로 마속을 벤다.', ja: '馬謖が指示に背いて山上に布陣し、張郃に大敗。第一次北伐が水泡に帰す。王平だけが部隊を保全し、諸葛亮は泣いて馬謖を斬った。', en: 'Defying orders, Ma Su camps on the hilltop and is routed by Zhang He, wrecking the first campaign. Only Wang Ping kept his unit intact; Zhuge Liang executed Ma Su in tears.' },
    people: ['ma-su', 'zhang-he', 'wang-ping', 'zhuge-liang'] },
  { id: 'shiting', year: 228, type: 'battle', src: 'history',
    title: { ko: '석정 전투', ja: '石亭の戦い', en: 'Battle of Shiting' },
    desc: { ko: '육손이 위의 대군을 석정에서 대파해 이릉에 이은 두 번째 대승을 거둔다. 이 승리가 손권 칭제의 발판이 되었다.', ja: '陸遜が魏の大軍を石亭で大破し、夷陵に続く二度目の大勝を収める。この勝利が孫権即位の足がかりとなった。', en: 'Lu Xun crushes a Wei host at Shiting — his second great victory after Yiling, paving the way for Sun Quan’s enthronement.' },
    people: ['lu-xun', 'sun-quan'] },
  { id: 'zhanghe-death', year: 231, type: 'battle', src: 'history',
    title: { ko: '4차 북벌 — 장합 전사', ja: '第四次北伐 — 張郃戦死', en: 'Fourth Campaign — Death of Zhang He' },
    desc: { ko: '철군하는 제갈량을 추격하던 위의 명장 장합이 목문도에서 복병의 화살에 전사한다.', ja: '撤退する諸葛亮を追撃していた魏の名将・張郃が、木門道で伏兵の矢に倒れる。', en: 'Pursuing Zhuge Liang’s withdrawal, the veteran Wei general Zhang He is slain by ambush arrows at Mumen Trail.' },
    people: ['zhang-he', 'zhuge-liang', 'sima-yi'] },
  { id: 'wuzhang', year: 234, type: 'battle', src: 'history',
    title: { ko: '오장원 — 제갈량의 죽음', ja: '五丈原 — 諸葛亮の死', en: 'Wuzhang Plains — the Death of Zhuge Liang' },
    desc: { ko: '사마의와 백여 일 대치하던 제갈량이 진중에서 병사한다. 촉군의 정연한 철수에 "죽은 공명이 산 중달을 달아나게 했다"는 말이 남았다.', ja: '司馬懿と百余日対峙していた諸葛亮が陣中で病没。蜀軍の整然たる撤退に「死せる孔明、生ける仲達を走らす」の言葉が残った。', en: 'After a hundred days facing Sima Yi, Zhuge Liang dies in camp. The orderly Shu withdrawal left the saying: "Dead Kongming routed living Zhongda."' },
    people: ['zhuge-liang', 'sima-yi', 'jiang-wei', 'wei-yan', 'liu-shan'] },
  { id: 'weiyan-death', year: 234, type: 'politics', src: 'history',
    title: { ko: '위연의 최후', ja: '魏延の最期', en: 'The End of Wei Yan' },
    desc: { ko: '제갈량 사후 철군 순서를 둘러싼 내분 끝에 위연이 반역자로 몰려 죽는다. 정사는 그의 억울함을 시사하는 기록을 남겼다.', ja: '諸葛亮の死後、撤退順序を巡る内紛の末に魏延が逆賊とされて死ぬ。正史は彼の無念を示唆する記録を残している。', en: 'In the power struggle after Zhuge Liang’s death, Wei Yan is branded a traitor and killed — though the histories hint the charge was unjust.' },
    people: ['wei-yan', 'jiang-wei'] },
  { id: 'xingshi', year: 244, type: 'battle', src: 'history',
    title: { ko: '흥세 방어전', ja: '興勢の戦い', en: 'Battle of Xingshi' },
    desc: { ko: '왕평이 소수의 병력으로 위의 대규모 한중 침공을 지형을 이용해 막아낸다. "왕평의 침착함이 촉을 구했다"는 평가를 받는 방어전이다.', ja: '王平が少数の兵力で魏の大規模な漢中侵攻を地形を活かして防ぎ切る。「王平の冷静さが蜀を救った」と評される防衛戦。', en: 'With a small force and shrewd use of terrain, Wang Ping repels Wei’s massive invasion of Hanzhong — the defense said to have saved Shu.' },
    people: ['wang-ping'] },
  { id: 'gaopingling', year: 249, type: 'politics', src: 'history',
    title: { ko: '고평릉 정변', ja: '高平陵の変', en: 'The Gaopingling Coup' },
    desc: { ko: '십 년 가까이 은인자중하던 사마의가 정변으로 조상 일파를 제거하고 위의 실권을 장악한다. 사마씨 천하의 시작이었다.', ja: '十年近く雌伏していた司馬懿がクーデターで曹爽一派を排除し、魏の実権を掌握。司馬氏の天下の始まりだった。', en: 'After years of feigned retirement, Sima Yi strikes: a coup that destroys Cao Shuang’s faction and seizes real power in Wei — the dawn of the Sima ascendancy.' },
    people: ['sima-yi'] },
  { id: 'sunquan-death', year: 252, type: 'politics', src: 'history',
    title: { ko: '손권 붕어', ja: '孫権崩御', en: 'Death of Sun Quan' },
    desc: { ko: '삼국의 군주 중 가장 오래 자리를 지킨 손권이 71세로 세상을 떠난다. 후계 분쟁의 불씨가 오를 흔들었다.', ja: '三国の君主で最も長く位を守った孫権が71歳で世を去る。後継争いの火種が呉を揺るがした。', en: 'Sun Quan, longest-reigning of the three sovereigns, dies at 71 — leaving a succession quarrel that would shake Wu.' },
    people: ['sun-quan'] },
  { id: 'jiangwei-north', year: 253, type: 'battle', src: 'history',
    title: { ko: '강유의 북벌', ja: '姜維の北伐', en: 'Jiang Wei’s Northern Campaigns' },
    desc: { ko: '제갈량의 유지를 이은 강유가 수차례 북벌을 강행한다. 일진일퇴를 거듭했으나 국력 소모라는 비판도 함께 남았다.', ja: '諸葛亮の遺志を継いだ姜維が数次にわたる北伐を敢行。一進一退を重ねたが、国力消耗という批判も残った。', en: 'Heir to Zhuge Liang’s mission, Jiang Wei launches campaign after campaign north — trading blows with Wei while draining Shu’s strength, critics said.' },
    people: ['jiang-wei', 'liu-shan'] },
  { id: 'shu-falls', year: 263, type: 'politics', src: 'history',
    title: { ko: '촉한 멸망', ja: '蜀漢滅亡', en: 'The Fall of Shu-Han' },
    desc: { ko: '위군이 험로를 넘어 성도를 급습하자 유선이 항복한다. 검각을 지키던 강유는 마지막까지 부흥을 도모하다 쓰러졌다.', ja: '魏軍が険路を越えて成都を急襲し、劉禅が降伏。剣閣を守っていた姜維は最後まで復興を図って倒れた。', en: 'Wei columns cross the mountain trails and descend on Chengdu; Liu Shan surrenders. Jiang Wei, holding Jiange, schemed for a restoration to his dying breath.' },
    people: ['liu-shan', 'jiang-wei'] },
  { id: 'jin-founded', year: 265, type: 'politics', src: 'history',
    title: { ko: '위 멸망, 진 건국', ja: '魏の滅亡、晋の建国', en: 'Wei Ends; Jin Is Founded' },
    desc: { ko: '사마의의 손자 사마염이 위 황제의 선양을 받아 진을 세운다. 조씨가 한을 대신한 지 45년 만에 같은 방식으로 무너졌다.', ja: '司馬懿の孫・司馬炎が魏皇帝の禅譲を受けて晋を建てる。曹氏が漢に取って代わってから45年、同じ方式で倒れた。', en: 'Sima Yi’s grandson Sima Yan accepts the Wei emperor’s abdication and founds the Jin — Wei falling by the very ritual it had used on the Han, 45 years on.' },
    people: ['sima-yi'] },
  { id: 'wu-falls', year: 280, type: 'politics', src: 'history',
    title: { ko: '오 멸망 — 천하통일', ja: '呉の滅亡 — 天下統一', en: 'The Fall of Wu — the Realm Reunited' },
    desc: { ko: '두예 등이 이끄는 진군이 파죽지세로 건업을 함락시키며 오가 항복한다. 황건적의 난으로부터 96년, 삼국시대가 막을 내렸다.', ja: '杜預らの率いる晋軍が破竹の勢いで建業を陥落させ、呉が降伏。黄巾の乱から96年、三国時代が幕を閉じた。', en: 'Jin armies under Du Yu and others take Jianye with bamboo-splitting momentum, and Wu surrenders. Ninety-six years after the Yellow Turbans, the Three Kingdoms era ends.' },
    people: [] },
]

export const TK_EVENTS: TKEvent[] = [...EVENTS_A, ...EVENTS_EXTRA]
export const TK_EVENTS_SORTED = [...TK_EVENTS].sort((a, b) => a.year - b.year)

export function eventsForPerson(id: string, max = 5) {
  return TK_EVENTS_SORTED.filter((e) => e.people.includes(id)).slice(0, max)
}
